### ISSUE TITLE
mup setup error

### ISSUE THREAD

**Issue by SachaG** [arunoda/meteor-up-legacy#10]
Here's the error: 

```
$ mup setup

Meteor-UP : Production Quality Meteor Deployments
--------------------------------------------------


Started TaskList: Setting Up
[162.243.213.202] installing node

buffer.js:552
  if (end > this.length) throw new Error('oob');
                               ^
Error: oob
    at Buffer.slice (buffer.js:552:32)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:124:13)
    at Object.exports.compile (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:224:15)
    at Session._applyTemplate (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:229:27)
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)
```

Any idea what it means?

**Comment by arunoda** [comment]
I think seems like you are usign node 0.8.x. If so upgrading it to 0.10.x
would solve this. Let me if it works. I think I can fix in this side as
well.

On Mon, Dec 23, 2013 at 10:18 AM, Sacha Greif notifications@github.comwrote:

> Here's the error:
> 
> $ mup setup
> 
> ## Meteor-UP : Production Quality Meteor Deployments
> 
> Started TaskList: Setting Up
> [162.243.213.202] installing node
> 
> buffer.js:552
>   if (end > this.length) throw new Error('oob');
>                                ^
> Error: oob
>     at Buffer.slice (buffer.js:552:32)
>     at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:124:13)
>     at Object.exports.compile (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ejs/lib/ejs.js:224:15)
>     at Session._applyTemplate (/usr/local/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:229:27)
>     at fs.readFile (fs.js:176:14)
>     at Object.oncomplete (fs.js:297:15)
> 
> Any idea what it means?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/10
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
Seems like you were right, I updated Node and the error went away. Thanks!
