### ISSUE TITLE
Meteor-up downgrading to xhr instead of using websockets

### ISSUE THREAD

**Issue by geekyme** [arunoda/meteor-up-legacy#100]
Hey there, 

So I compared 2 different setup: 
1. Run meteor create app on the box, then app is launched on remote localhost:3000;
2. Using meteor-up to deploy app to the box and allow meteor-up to manage the upstarts. then app is launched on remote localhost:80;

In setup 1, the meteor app is using websockets. On setup 2, it's not. Why is this occuring?

I am using the DigitalOcean host.

**Comment by arunoda** [comment]
Okay. Now see what's the node version installed with mup in the server. If
that's not 0.10.28 try to change it on mup.json and do mup setup again.

On Sunday, July 27, 2014, Shawn Lim notifications@github.com wrote:

> Hey there,
> 
> So I compared 2 different setup:
> 
>    1.
> 
>    Run meteor create app on the box, then app is launched on remote
>    localhost:3000;
>    2.
> 
>    Using meteor-up to deploy app to the box and allow meteor-up to manage
>    the upstarts. then app is launched on remote localhost:80;
> 
> In setup 1, the meteor app is using websockets. On setup 2, it's not. Why
> is this occuring?
> 
> I am using the DigitalOcean host.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/100.

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by geekyme** [comment]
It is v0.10.28

**Comment by arunoda** [comment]
Can you see any strange logs from your app. Are you using any proxy
firewall.

If possible try check via a Vpn or a socks proxy. ISPs do crazy stuff.

On Sunday, July 27, 2014, Shawn Lim notifications@github.com wrote:

> It is v0.10.28
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/100#issuecomment-50254621.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by geekyme** [comment]
No proxies / firewall. 

The same box is able to fire up a meteor app from `meteor create app` and websockets work. The problem seems to be constrained within the scope of the configurations in meteor-up probably.

Nope no weird errors. The top errors you see below is because I was authenticating wrongly. 

<pre>
s/future.js:326:15)
    at MongoConnection._ensureIndex (packages/mongo-livedata/mongo_driver.js:662)
    at Meteor.Collection._ensureIndex (packages/mongo-livedata/collection.js:512)
    at Accou[104.131.129.195] nts.urls (packages/accounts-base/accounts_server.js:1307)
    at packages/accounts-base.js:1567:4
    at packages/accounts-base.js:1609:3
    at /opt/storyline/app/programs/server/boot.js:155:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/storyline/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/storyline/app/programs/server/boot.js:82:5
    - - - - -
    at Object.toError (/opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/cursor.js:686:54
    at Cursor.close (/opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/cursor.js:969:5)
    at commandHandler (/opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/cursor.js:686:21)
    at /opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at MongoReply.parseBody (/opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/opt/storyline/app/programs/server/npm/mongo-livedata/main/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at EventEmitter.emit (events.js:95:17)
error: Forever detected script exited with code: 8
error: Script restart attempt #123
Failed to load c++ bson extension, using pure JS version
Kadira: completed instrumenting the app
Not migrating, already at version 30
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
Failed to load c++ bson extension, using pure JS version
Kadira: completed instrumenting the app
Not migrating, already at version 30
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
Failed to load c++ bson extension, using pure JS version
Kadira: completed instrumenting the app
Not migrating, already at version 30
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
</pre>

**Comment by geekyme** [comment]
Do I need to install any additional things? 
The only need I manually installed on my server is meteor, which I did so through `curl https://install.meteor.com | /bin/sh`

**Comment by arunoda** [comment]
It's very hard to say since MUP does not do anykind of proxying.
Do this one last test.

Try running a with meteor on port 80 and see.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by geekyme** [comment]
how do I kill mup's processes on port 80 without it restarting?

**Comment by arunoda** [comment]
stop <appname>

appname will be meteor if you've not entered anything.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by geekyme** [comment]
OOHHH! This is interesting. 

the meteor app created by `meteor create` also didn't have websockets on port 80!

**Comment by arunoda** [comment]
Your ISP seems to do http proxying on port 80 and that prevents WS. Only
fix is to use SSL.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by geekyme** [comment]
but i'm able to access my *.meteor.com servers on port 80 with websockets enabled.

**Comment by geekyme** [comment]
At the moment I'm accessing my box's url via IP address only, not domain. Does that affect the WS?

**Comment by arunoda** [comment]
Generally it should not. But not sure.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
WS is working for me :)

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
See meteor.com always use SSL  - view-source:http://errors-dev.meteor.com/

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by geekyme** [comment]
RAWR. Singapore sucks....... Ok anyway thanks so much for your help. 

So basically even though I do not access meteor's url using https://*.meteor.com, it will always use SSL?

And that allowed my websockets to work on my end?

**Comment by arunoda** [comment]
haha. This is happening all over the world :)

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by geekyme** [comment]
Okok well at least things still work in real-time despite the XHR polling. The oplog makes is all very efficient.

**Comment by sclausen** [comment]
A long time ago, I had the same problem and found out, that nginx has to be configured to upgrade the connection.
So, IF you use nginx, here is the additional config to use:

```
location /sockjs/ {
    proxy_pass http://yourapp;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by katopz** [comment]
@arunoda I'm now using PORT 5000 and it work, Is that other way to use port 80 for static file and other port (e.g. 5000) for websocket via mup? or maybe manually way like @sclausen said (mup use nginx?)?

**Comment by arunoda** [comment]
I think it's not possible to do via mup directly.

**Comment by katopz** [comment]
@arunoda `/etc/nginx` is not exist which mean mup didn't use `nginx` am I right?
If someone has an idea how to set this please yell. I'm confusing already.

**Comment by arunoda** [comment]
Yes. Mup does not use nginx.
