### ISSUE TITLE
Where are logs on server?

### ISSUE THREAD

**Issue by boxxa** [arunoda/meteor-up-legacy#1000]
Where are the logs on server that: mupx logs -f would connect to? Looking to download and save locally for parsing.

**Comment by MasterJames** [comment]
It's kind of a three part question.
The Mongo (if used) docker container data is stored outside the docker container on the server so it survives restart.
https://github.com/arunoda/meteor-up/blob/mupx/scripts/linux/install-mongodb.sh#L13
The docker run "volume" attributes point to those locations  or you can connect to any docker container with 'docker exec' with a bash she'll or other command like ls cat tail etc. If SSH to the target machine is not enough.
Then there's meteor.
https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh#L26
This is where you follow the bread crumbs to /opt/appName/current to find other volume folder mounts
If you run SSL option it only mounts certificates.
https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh#L53
So then you have to connect to it with docker exec bash.
Well I hope that helps you find whatever your looking for.
Remember to customize and or as a way forward there is a port at kadirahq/meteor-up that would accept PRs and is better suited to address more complicated needs.
I'll see if I can find what the logs command does still too.
Right also 
https://github.com/arunoda/meteor-up/blob/mupx/lib/actions.js#L217
Here we see most is stderr stdout but also a 'docker logs' command is formulated and executed with options and seems to go to the appName directory.
Here is some reference to it in docker docs
https://docs.docker.com/engine/quickstart/#starting-a-long-running-worker-process
Her is something more useful about it from a package called docker-logs 
https://gist.github.com/afolarin/a2ac14231d9079920864

{Issue #1000 how prestigious}

**Comment by boxxa** [comment]
Thank you for this. Trying to come up with logging alternaltives. It is a great product and just wanted to see if there was any way or new planned methods to allow server debugging if I am not at the PC with MUPX and use the very useful mupx logging -f command.

Go #1000

**Comment by MasterJames** [comment]
Right well digging into that deeper, 
https://github.com/arunoda/meteor-up/blob/mupx/lib/actions.js#L191
you'll see that mupx logs uses 'docker logs'.

**Comment by boxxa** [comment]
@MasterJames I could hug you. Completely forgot it is Docker based.

**Comment by MasterJames** [comment]
[■ Hug accepted and reciprocated ■]
