### ISSUE TITLE
Can't install mup

### ISSUE THREAD

**Issue by yuyangchee98** [arunoda/meteor-up-legacy#1002]
I tried the old version, no error on install but when I try to mup init or mupx init, it'll return command not found. I tried reinstalling node twice and problem still persists.

Then I moved onto the new version, can't install.

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! mup@1.0.0 prepublish: `nofat make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mup@1.0.0 prepublish script 'nofat make'.
npm ERR! This is most likely a problem with the mup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nofat make

**Comment by MasterJames** [comment]
Darwin?  I think only Ubuntu 14+ is supported.
Try a virtual machine maybe but you'll need to setup file system sharing?

**Comment by yuyangchee98** [comment]
I'm on OS X Yosemite. How do I make this work on my OS?

**Comment by MasterJames** [comment]
Might be nodejs conflicts? 
Please try this solution at the bottom and report back.
https://github.com/arunoda/meteor-up/issues/1003

**Comment by yuyangchee98** [comment]
Yang$ meteor npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/Users/Yang/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v0.10.43
npm ERR! npm  v2.14.22
npm ERR! path /Users/Yang/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/Users/Yang/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Yang/MyTravelDay-source/npm-debug.log

**Comment by yuyangchee98** [comment]
npm install mup
mup@0.11.3 ../node_modules/mup
├── underscore@1.7.0
├── colors@0.6.2
├── async@0.9.2
├── uuid@1.4.2
├── rimraf@2.5.2 (glob@7.0.3)
├── cjson@0.3.3 (json-parse-helpfulerror@1.0.3)
├── nodemiral@1.1.1 (debug@0.7.4, async@0.9.0, underscore@1.8.3, progress@1.1.5, ejs@0.8.8, ssh2@0.4.6)
└── archiver@0.14.4 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.34, tar-stream@1.1.5, zip-stream@0.5.2, glob@4.3.5, lodash@3.2.0)
Yangs-MacBook-Air:mytravelday-2 Yang$ mup init
-bash: mup: command not found

Heres how it looks like when i try npm install mup

**Comment by MasterJames** [comment]
If mup is causing problems please try the development branch here called mupx it uses docker and is much better especially since meteor 1.3 and other more recent changes.
Also note both these versions are depreciated in favor of the new version located now at kardirahq/meteor-up

**Comment by yuyangchee98** [comment]
mupx behaves the same as mup for me. meteor-up gives me 

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! mup@1.0.0 prepublish: `nofat make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mup@1.0.0 prepublish script 'nofat make'.
npm ERR! This is most likely a problem with the mup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nofat make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Yang/MyTravelDay-2/meteor-up/npm-debug.log

this error.

**Comment by MasterJames** [comment]
It was through that link a few comments back there's this did you try it.
https://github.com/kadirahq/meteor-up/issues/35#issuecomment-215960661
Delete those folders update everything and try again.
I think it said to use the meteor npm install and not the one on the system.
Are you using Meteor 1.3.2.4+ and mupx with a clean Ubuntu 14+ target, etc.

**Comment by yuyangchee98** [comment]
Tried deleting reinstalling meteor, different versions of node, uninstalling and reinstalling node and npm. No luck :(. 

My project is on Meteor 1.2.1, mup, mupx and Meteor-up all failed.
Tried updating a separate project to the latest meteor, same error.

What do you mean by Ubuntu 14+ target?

**Comment by MasterJames** [comment]
Only Ubuntu 14 is officially supported but 15 works the same. I think it's technically 14.04 or something g like that. I think it's the same for the new version at kadirahq too.
What are you trying to deploy to?

**Comment by yuyangchee98** [comment]
I can't even get `mup/mupx init` working. It doesnt recognise the mup/mupx command.

**Comment by MasterJames** [comment]
Maybe try either of these similar instructions assuming you've got npm (aka nodejs) installed.
Note the global flag then you can't get it in the wrong folder which is what I suspect has happened.
https://github.com/arunoda/meteor-up/tree/mupx
https://www.npmjs.com/package/mupx
I think you can use "meteor npm install -g mupx" or something now too.
http://guide.meteor.com/1.3-migration.html

**Comment by yuyangchee98** [comment]
I got it working finally. Turns out it was some problem with my npm installation, user permissions thats affecting my -g installation.

**Comment by yuyangchee98** [comment]
Thanks :)
