### ISSUE TITLE
Feature request: option for Node garbage collection settings

### ISSUE THREAD

**Issue by derwaldgeist** [arunoda/meteor-up-legacy#1008]
I have the problem that my Meteor app deployed on a t2.micro instance at AWS crashes after some weeks, due to memory overflow. I first thought that it would be caused by a memory leak, but in this thread I've learned that this can happen because Node's garbage collection is not fast enough:

https://forums.meteor.com/t/how-to-find-memory-leaks-in-a-meteor-app/19008

User alveoli recommended to patch the Node config:

https://forums.meteor.com/t/how-to-find-memory-leaks-in-a-meteor-app/19008/16

and later reported that he did not have any memory issues since. However, I'm a bit hesitant about forking mupx for this, as I would prefer to stick to the standard mupx implementation.

So I'd like to suggest to add an option to configure the node settings if required. This would be great!

**Comment by MasterJames** [comment]
These versions are depreciated by kadirahq/meteor-up also note the amazing tools at kadira.io for finding and optimizing the very problems you mentioned.
https://kadira.io/

**Comment by derwaldgeist** [comment]
Hi @MasterJames: Funny thing is that all versions of mup seem to be deprecated and the latest version is "development stage" :-) Nevermind. Yes, I am using Kadira, but I could not find any memory leak with it. I also do not use any self-constructed publications, so I came to the conclusion that the guy who said this behaviour was caused by the garbage collector may be right. And he seemed to have solved his problem by adjusting the GC settings and never had a crash since.

**Comment by MasterJames** [comment]
Right very useful to know thanks for clarity.

**Comment by MasterJames** [comment]
I think you might have to make a custom meteor container/image which is now only possible with the new version. There might be a way to pass the arguments too. I would check with the developers at kadirahq/meteor-up at see what they suggest you do to add the max_old_space_size flag into the new version.
I tracked this to here in the new version.
https://github.com/kadirahq/meteor-up/blob/master/src/modules/meteor/assets/templates/start.sh
But maybe the if there's an environment variable version for this? If so the the evn.list might enable an override?
I'm thinking it should probably go in the settings files somehow.

**Comment by derwaldgeist** [comment]
Thanks for that input!
