### ISSUE TITLE
Issue with Meteor 0.8.3?

### ISSUE THREAD

**Issue by dwinston** [arunoda/meteor-up-legacy#101]
I all of a sudden can't `mup deploy` after doing a `meteor update` to 0.8.3. I can, however, `meteor deploy` to a meteor test server without error.

**Comment by arunoda** [comment]
Can you please give me some logs of both the mup and logs from your app.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by benlavalley** [comment]
dwinston, you may be running into the issue I just ran into -- I had to modify the nodeVersion attribute in my mup.json config file to 0.10.29 from 0.10.28. After I ran a mup setup and a mup deploy all worked well for me.  

I figured this out by checking the node logs in /var/log/upstart/ on my remote app servers and seeing this in the logs - "Meteor requires Node v0.10.29 or later."

First github post for me! 

Have to say you're a hero, Arunoda :+1:

**Comment by arunoda** [comment]
Thanks @nibbl 

That should be the reason. I'll update the default version.

**Comment by dwinston** [comment]
Success! Thanks @nibbl. Your procedure worked for me:
1. Update nodeVersion in mup.json to 0.10.29
2. mup setup
3. mup deploy

And thanks @arunoda for updating the default version!
