### ISSUE TITLE
Mup Deploy kills folder of uploaded files

### ISSUE THREAD

**Issue by msj121** [arunoda/meteor-up-legacy#1022]
Each time I deploy it is successful, but it kills any files that are in a separate ".uploads" folder. Is there a way to exclude a directory from being affected?

I ask because I can't deploy and kill all the files/folders on the server each time, just curious if anyone knows a solution.

**Comment by fckngold** [comment]
+1

**Comment by msj121** [comment]
Is there a way to perhaps save files outside of the docker container higher up in the folder hierarchy?

**Comment by fckngold** [comment]
@msj121 I solved the problem by moving folder with uploaded files in the root of the server.

**Comment by msj121** [comment]
How did you do that? I am not sure I have access to the root of the server since it is in a docker container... you literally put the folders in "/uploads" and that worked?

I am using meteor-uploads package (https://github.com/tomitrescak/meteor-uploads).

**Comment by fckngold** [comment]
I'm using https://github.com/VeliovGroup/Meteor-Files and its allow to do that.

**Comment by msj121** [comment]
I now know that I was actually using a slighter newer version of mup. Which uses docker, which doesn't allow access out of the container unless you mount the volume by changing "start.sh".

**Comment by Tbutnyakov** [comment]
@MeDBejoHok Привет! Не мог бы ты объяснить, какой путь ты описал в "storagePath"?
Я тоже использую Meteor-files, поставил путь '/assets/app/uploads/avatars' и он все равно запихивает файлы в докер. 
Т.е. при редеплое все файлы, само собой, остаются вне поля видимости новой сборки.

**Comment by fckngold** [comment]
@Tbutnyakov Привет. Я использую старую версию мупа, так что вряд ли смогу тебе помочь. Путь указал относительно корня сервера ("storagePath": "/data/photos")

**Comment by Tbutnyakov** [comment]
@MeDBejoHok да, я уже понял это. У тебя версия метеора ниже 1.3?

**Comment by fckngold** [comment]
@Tbutnyakov Да, 1.1.15.
