### ISSUE TITLE
Mupx did not create Meteor database

### ISSUE THREAD

**Issue by timyhou** [arunoda/meteor-up-legacy#1030]
I was able to successfully deploy my App using Mupx the issue is that there is nothing in the mongodb. 

If I open up the mongo shell from the server using `docker exec -it mongodb mongo` I only see the Local database created and no collections at all. I am used to seeing at least a Meteor db which has my collections in it. 

I used the following mup.json which is bone stock. The only thing I changed was the deployCheckWaitTime. 

```
{
  // Server authentication info
  "servers": [
    {
      "host": "timandaliciasweet.life",
      "username": "user",
      "password": "pass",
      "env": {}
    }
  ],

  "setupMongo": true,
  "appName": "weddingApp",
  "app": "E:\\dev\\github\\mysite-meteor13-react-bootstrap-spa",
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://address.com"    
  },

  "deployCheckWaitTime": 120,
  "enableUploadProgressBar": true
}
```

At first I wanted to use a script and run mongo < script.js to populate the DB on the server but when I checked to make sure that the database and collection were there, I couldn't find anything. Can somebody lend me some guidance?

**Comment by MasterJames** [comment]
Did you run mupx setup? 
https://github.com/arunoda/meteor-up/blob/master/README.md#setting-up-a-server

**Comment by timyhou** [comment]
Yeah did that. Otherwise it would not have installed the Mongodb instance correct?

**Comment by MasterJames** [comment]
Oh good I thought from what you said maybe it didn't do that properly. Is it a firewall issue?

**Comment by timyhou** [comment]
No I don't think it is a firewall issue. 

I did a test with the meteor simple-todos project. The database and collections are created immediately so I think it has to do with my app database behavior. 

I created the database and collection manually and inserted some data and it seems to work now. Guess this is my bad. I'll close the issue out.
