### ISSUE TITLE
OpenSSL vulnerability 

### ISSUE THREAD

**Issue by sahanDissanayake** [arunoda/meteor-up-legacy#1056]
https://blog.cloudflare.com/yet-another-padding-oracle-in-openssl-cbc-ciphersuites/
https://www.ssllabs.com/ssltest/analyze.html?d=crater.io

This is a fairly important issue, Not sure if I should report this elsewhere

My server is Digitalocean ubuntu, Seems like the ubnutu servers on EC2 does not have this issue
https://www.ssllabs.com/ssltest/analyze.html?d=atmospherejs.com&latest

**Comment by guilcorp** [comment]
Got the same issue, any fix or news @sahanDissanayake ?

Thanks

**Comment by sahanDissanayake** [comment]
Not yet.. trying to get someone from MDG
or Digital ocean to reply... let's keep looking

**Comment by sahanDissanayake** [comment]
Just login to your ubuntu box

```
apt-get update
apt-get upgrade
```

This worked for me :)

**Comment by sahanDissanayake** [comment]
@guilcorp 

I think I removed SSL from Meteor up and used this Tut https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx

To install SSL and then deployed the Meteor project to the server port 3000

See if it works

**Comment by guilcorp** [comment]
Thanks for your feedback.

Yes, I think the Meteor up openssl is not update with latest version or at least not with the Openssl recommendation:
OpenSSL 1.0.2 users should upgrade to 1.0.2c
OpenSSL 1.0.1 users should upgrade to 1.0.1o
https://www.openssl.org/news/secadv/20160503.txt
