### ISSUE TITLE
Deployment success but site not accessible

### ISSUE THREAD

**Issue by physicsteacher** [arunoda/meteor-up-legacy#1064]
I deployed my app to a digital ocean droplet and while the mupx setup and deploy complete without a problem when I go to the ip address of the droplet Chrome does not connect: 

This site can’t be reached

xxx.xxx.xx.xx refused to connect.
Try:
Reloading the page
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by bielcapanema** [comment]
same here :/

**Comment by ggelango** [comment]
yup same here

chrome for some reason forces an ssl connection. no idea why this happens.

**Comment by ggelango** [comment]
FOUND THE PROBLEM

I removed the 'force-ssl' package from my app and I am now able to access it
