### ISSUE TITLE
Mupx Deploy Verifying deployment: FAILED

### ISSUE THREAD

**Issue by thuraucsy** [arunoda/meteor-up-legacy#1100]
I've a project that was created with meteor 1.3 but now upgraded it and well working in local but when I deploy to AWS server using mupx the error occuring.

I run mupx deploy

```
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

`

My local node js using 4.4.7 and AWS ubuntu 14 node js also 4.4.7 by upgrading it from 0.10.x to 4.4.7. But still getting that error. 

Here is my server node js version check

`ubuntu@ip-172-31-1-138:/opt/dev_popup$ meteor node -v`
`v4.4.7`
`ubuntu@ip-172-31-1-138:/opt/dev_popup$ node -v`
`v4.4.7`

**Comment by jsiig** [comment]
+1

**Comment by thuraucsy** [comment]
I solved it by reading [1091 issues](https://github.com/arunoda/meteor-up/issues/1091).
@humbertocruz said to change mupx's node modules file by manually from meteorhacks/meteord:base to abernix/meteord:base in three places on the file.

Since I'm using windows by running vagrant, I've to change the file from the following location.
C:\Users{UserName}\AppData\Roaming\npm\node_modules\mupx\templates\linux\start.sh

It solved the error. Hope you get it.

**Comment by jsiig** [comment]
Did the same when it happened, rewrote mupx scripts to use that docker image. 

Can confirm that it works brilliantly.

**Comment by nekkon** [comment]
Thank you guys!! Can confirm that I managed to setup/deploy Meteor 1.4.0.1 on Digital Ocean

**Comment by louwers** [comment]
This shouldn't be closed should it? This is still a problem with mupx right?

**Comment by IhsanMujdeci** [comment]
Confirmed working for me
1. Windows navigate to "C:\Users{UserName}\AppData\Roaming\npm\node_modules\mupx\templates\linux\start.sh"
2. Open with text editor or IDE
3. Search document for for "meteorhacks" and replace with "abernix";

**Comment by anas3636** [comment]
Worked for me thanks
