### ISSUE TITLE
The uploaded files disappear every deploy

### ISSUE THREAD

**Issue by Tbutnyakov** [arunoda/meteor-up-legacy#1101]
Hey! I found a lot of issues about dissapearing files after re-deploy...but...i didnt found a decision.
The problem: when we upload files on the own server and call "mupx deploy", mupx create a new folder via docker and new build can't access to previous builds. 

What can we do? I think we need to create a folder in "root" (for example) server directory,  and store files there. But...how can we do that via mupx? @arunoda can we do something, or package need to update?

Sorry for my English:)

**Comment by madushan1000** [comment]
Mupx can't do this, but the new mup version supports docker volumes.

**Comment by Tbutnyakov** [comment]
@madushan1000 thank you for answer!
