### ISSUE TITLE
Horizontal scaling?

### ISSUE THREAD

**Issue by derwaldgeist** [arunoda/meteor-up-legacy#1116]
I would like to scale my Meteor app horizontally, by using multiple cores on the same EC2 instance, as well as additional EC2 instances as necessary.

Maybe I am too dumb, but I don't get whether the `servers` section of mup.json actually supports such horizontal scaling.

Would it configure nginx as a reverse proxy in this case? And if so, does this even work with separate EC2 instances, so one of them can be used as the load-balancer?

If mupx should not support horizontal scaling, is there a way to do it manually, e.g. by installing nginx on your own and let mupx only setup the Meteor apps? Is there any tutorial out there that describes such kind of horizontal scaling?

BTW: It would be great if the setup would also support sticky sessions. :-)

**Comment by elie222** [comment]
Mup is for deploying meteor apps and doesn't take care of the load balancing. You need to install nginx yourself to do this (preferably on another server). Have a look at this guide for more help: 
https://medium.freecodecamp.com/first-experiences-scaling-a-meteor-app-14a48e62a4af#.rimnlc367

**Comment by derwaldgeist** [comment]
@elie222 Thanks for that link!
