### ISSUE TITLE
Errors after updating to Meteor 0.9

### ISSUE THREAD

**Issue by ClaysonIO** [arunoda/meteor-up-legacy#112]
After updating to the latest deployment of meteor, I'm having issues using MUP. It bundles, uploads, and starts to deploy just fine, but then appears to have an issue with the package.json:

```
Started TaskList: Deploying checkup App
[104.131.142.120] uploading bundle
[104.131.142.120] uploading bundle: SUCCESS ✔
[104.131.142.120] setting up env vars
[104.131.142.120] setting up env vars: SUCCESS ✔
[104.131.142.120] invoking deployment process
[104.131.142.120] invoking deployment process: FAILED ✘ 

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '---.---.---.---' (ECDSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/checkup/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    fibers@1.0.1 node_modules/fibers
    checkup stop/waiting
    checkup start/running, process 1781
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    checkup stop/waiting
    checkup start/running, process 1847
    ----------------------------------------------------------------------------
```

**Comment by cristiandley** [comment]
I may ask. Have you tried running 'meteor' on your local enviroment ? any error ?. It seems to be a package

**Comment by arunoda** [comment]
please update meteor-up from github. I make some changes to support 0.9 :)

**Comment by ClaysonIO** [comment]
Running well on my machine and now on meteor.com, I'll try and update meteor-up. Now to learn how to do that without npm... :)

**Comment by ClaysonIO** [comment]
And now appears to be working everywhere. Thanks for being so active with this excellent package!

**Comment by wursttheke** [comment]
@Itinerati How exactly did you get this working? I already tried to `npm install arunoda/meteor` but I still get the exact same error.

**Comment by arunoda** [comment]
@wursttheke You need to run this

```
npm install -g mup
```

**Comment by wursttheke** [comment]
Thanks. It's working now. Must have been something in my app. (Although I successfully updated it to Meteor 0.9.0 an it was running fine on my local machine, it wouldn't deploy.) 

I just tried it with a fresh leaderboard example without any errors. 

Thanks for this great package.

**Comment by TimBroddin** [comment]
Hmm, I'm having an issue with 0.9 (latest release of mup).

```
Bundling Started: /Users/timbroddin/Sites/boost2/

Started TaskList: Deploy app 'meteor' (linux)
[188.226.242.66] - Uploading bundle
[188.226.242.66] ✘ Uploading bundle: FAILED

-----------------------------------STDERR-----------------------------------
Warning: Permanently added '188.226.242.66' (RSA) to the list of known hosts.
/tmp/19fcef02-9d32-4a52-856e-3452165ed492.tar.gz: No such file or directory
Killed by signal 1.
-----------------------------------STDOUT-----------------------------------`
```

With my installed version before it would get passed the uploading bundle stage. The app works locally (and on meteor.com) and is deployed to a clean VPS.

**Comment by arunoda** [comment]
Hey sorry guys.

I got accidentally pushed some testing code changes. Will fix it now.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by TimBroddin** [comment]
Arunoda for president! Works now!

**Comment by arunoda** [comment]
ha ha :)

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by javaknight** [comment]
I am having the same issues described earlier in the thread.

Started TaskList: Deploy app 'myapp' (linux)
[localhost] - Uploading bundle
[localhost] â Uploading bundle: SUCCESS
[localhost] - Setting up Environment Variables
[localhost] â Setting up Environment Variables: SUCCESS
[localhost] - Invoking deployment process
[localhost] â Invoking deployment process: FAILED

```
    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
        stop: Unknown instance:
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------

```
    > fibers@1.0.1 install /opt/myapp/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    semver@2.2.1 node_modules/semver

    source-map-support@0.2.5 node_modules/source-map-support
    âââ source-map@0.1.29 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    myapp start/running, process 3046
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    Waiting for 300 seconds while app is booting up
    Checking is app booted or not?
    myapp start/running, process 3101
    ----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
get the app error logs.

mup logs -n 400

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by javaknight** [comment]
bitnami@ip-172-30-1-110:~/myapp$ mup logs -n 400

## Meteor Up: Production Quality Meteor Deployments

[localhost] Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[localhost] /proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/[localhost] 9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found

**Comment by arunoda** [comment]
have you done mup setup?

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by javaknight** [comment]
yes. it all looks good.

bitnami@ip-172-30-1-110:~/myapp$ mup setup

## Meteor Up: Production Quality Meteor Deployments

Started TaskList: Setup (linux)
[localhost] - Installing Node.js
[localhost] â Installing Node.js: SUCCESS
[localhost] - Installing PhantomJS
[localhost] â Installing PhantomJS: SUCCESS
[localhost] - Setting up Environment
[localhost] â Setting up Environment: SUCCESS
[localhost] - Copying MongoDB configuration
[localhost] â Copying MongoDB configuration: SUCCESS
[localhost] - Installing MongoDB
[localhost] â Installing MongoDB: SUCCESS
[localhost] - Configuring upstart
[localhost] â Configuring upstart: SUCCESS
Completed TaskList: Setup (linux)

**Comment by javaknight** [comment]
Can we please reopen this issue? 

I am using ami-5aa96032 . https://bitnami.com/stack/mean/cloud/amazon

**Comment by arunoda** [comment]
please use a clean ubuntu box without other customizations.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by aldelbal** [comment]
I have same problem. I am using Ubuntu 14.04. Not customized.

**Comment by tnwo** [comment]
Same here - scp: /opt/..../tmp/bundle.tar.gz: No such file or directory
	Killed by signal 1.

**Comment by physicsdude** [comment]
I'm having the same issue.  Ubuntu 14.04 clean launch in amazon EC2. Setup works fine, then I get these errors when I try to do mup deploy.

## Meteor Up: Production Quality Meteor Deployments

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: /Users/dude/Programs/meteor/myapp/myapp

Started TaskList: Deploy app 'myapp' (linux)
[ec2-52-0-163-8.compute-1.amazonaws.com] - Uploading bundle
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Uploading bundle: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Setting up Environment Variables
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Setting up Environment Variables: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Invoking deployment process
[ec2-52-0-163-8.compute-1.amazonaws.com] ✘ Invoking deployment process: FAILED

```
 -----------------------------------STDERR-----------------------------------
 ome/ubuntu/.node-gyp/0.10.31',
 gyp info spawn args   '-Dmodule_root_dir=/opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
 gyp info spawn args   '--depth=.',
 gyp info spawn args   '--no-parallel',
 gyp info spawn args   '--generator-output',
 gyp info spawn args   'build',
 gyp info spawn args   '-Goutput_dir=.' ]
 gyp info spawn make
 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 gyp info ok
 npm WARN package.json meteor-dev-bundle@0.0.0 No description
 npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
 npm WARN package.json meteor-dev-bundle@0.0.0 No README data
 stop: Unknown instance:
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
     App did not pick up! Please check app logs.
     -----------------------------------STDOUT-----------------------------------
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
       COPY Release/bcrypt_lib.node
     make: Leaving directory `/opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
 > fibers@1.0.1 install /opt/myapp/tmp/bundle/programs/server/node_modules/fibers
 > node ./build.js

 `linux-x64-v8-3.14` exists; testing
 Binary is fine; exiting
 underscore@1.5.2 node_modules/underscore

 eachline@2.3.3 node_modules/eachline
 └── type-of@2.0.1

 semver@4.1.0 node_modules/semver

 chalk@0.5.1 node_modules/chalk
 ├── escape-string-regexp@1.0.2
 ├── ansi-styles@1.1.0
 ├── supports-color@0.2.0
 ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
 └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

 source-map-support@0.2.8 node_modules/source-map-support
 └── source-map@0.1.32 (amdefine@0.1.0)

 fibers@1.0.1 node_modules/fibers
 myapp start/running, process 12900
 Waiting for MongoDB to initialize. (5 minutes)
 connected
 Waiting for 15 seconds while app is booting up
 Checking is app booted or not?
 ----------------------------------------------------------------------------
```

mup setup info, ran this right before running the mup deploy command, and I have _no_ customizations on this box.

Started TaskList: Setup (linux)
[ec2-52-0-163-8.compute-1.amazonaws.com] - Installing Node.js
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Installing Node.js: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Installing PhantomJS
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Installing PhantomJS: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Setting up Environment
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Setting up Environment: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Copying MongoDB configuration
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Copying MongoDB configuration: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Installing MongoDB
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Installing MongoDB: SUCCESS
[ec2-52-0-163-8.compute-1.amazonaws.com] - Configuring upstart
[ec2-52-0-163-8.compute-1.amazonaws.com] ✔ Configuring upstart: SUCCESS
Completed TaskList: Setup (linux)

**Comment by davidrinnan** [comment]
This is an old issue so I don't think you have same problem as author of this issue. Or are you also running meteor 0.9? On a version of MUP that not yet support 0.9? :) 
https://github.com/arunoda/meteor-up/issues/112#issuecomment-53504449

I think it might be something else. What does your logs say? 
mup logs -n 400

**Comment by bumbleblym** [comment]
Ran into the same problem "forever not found" with a clean Ubuntu 14.04 box.
SSH-ed in

```
npm install forever -g
```

then

```
mup deploy
```

and it works.

**Comment by nooitaf** [comment]
I just had a similar issue with meteor `1.0.4.1` and solved it by increasing the node version in the `mup.json` from `0.10.33` to `0.10.36` and doing `mup setup` again before deploy.

**Comment by etheleon** [comment]
same issue with @bumbleblym after installing forever manually  on my DO droplet it worked. 
wad's wrong?

**Comment by schankam** [comment]
Same issue here, I fixed it by re-installing forever manually:

```
sudo npm uninstall forever -g
sudo npm cache clean
sudo npm install forever -g
```
