### ISSUE TITLE
Connect using Robomongo

### ISSUE THREAD

**Issue by dyxj** [arunoda/meteor-up-legacy#1122]
Hello,

I've managed to deploy succesfully using mupx, using abernix/meteord:base.
I can access the mongodb using: docker exec -it mongodb mongo Project-A-database,
But I can't seem to connect using robomongo.

Any pointers would be greatly appreciated

Thanks!!!

**Comment by avishaan** [comment]
I think this was asked somewhere else (possibly by me) but basically you won't be able to do it. Maybe in a future version you will

**Comment by dyxj** [comment]
Hey, I've figured it out, I got myself the latest version of robomongo. 
1) Use the SSH function
2) key in localhost for the connection(first tab) 
3) fill in the auth

**Comment by luisreyes** [comment]
You cannot access a mongodb from robomongo if the db is in a docker container...
But you can use a free or paid db from mlab.com.

**MUP.JSON** (part of it at least)

<pre>
"setupMongo": false,
  "appName": "YOURAPP",
  "app": "/YOUR/APP/PATH",
  "env": {
    "ROOT_URL": "https://YOURAPPDOMA.IN/",
    "MONGO_URL": "//mongodb://username:password@xxxx.mlab.com:xxxx/YOURAPP"
  }
</pre>

After this you can setup robomongo to point to the mlab db.

**Comment by avishaan** [comment]
Let me clarify my statement. With some versions of MUP you can't, with other versions you can. What @luisreyes says is correct. If you want more detailed instructions you can check out my blog post which walks you through it using 3T MongoChef. Similar instructions would work for Robo http://blog.codehatcher.com/mongodb-ssh-access-on-remote-meteor-deployment

**Comment by ericmagalhaes** [comment]
I was able to connect to my remote mongodb deployed by mup.
I use windows and I followed this steps.
https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-tunneling-on-a-vps
Windows and PuTTY
-- I created a SSH tunnel to a local port like 3030 then I connected to the database in robomongo using LOCALHOST:3030
