### ISSUE TITLE
how to show current mup version?

### ISSUE THREAD

**Issue by delatorremario** [arunoda/meteor-up-legacy#1129]
Hi, I need install previus version. How to do this?

**Comment by axclever** [comment]
@delatorremario just do
`npm remove -g mup` - remove current version
`npm i -g mup@0.11.1` -install version you need. Here for example I've used **0.11.1**

**Comment by delatorremario** [comment]
thanks!

**Comment by axclever** [comment]
@delatorremario if you wanna check version, try `npm mup -v`

**Comment by delatorremario** [comment]
npm mup -v
1.4.29
