### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by SachaG** [arunoda/meteor-up-legacy#114]
Just got this error on a 0.9.0.1 app with the latest version of mup:

```
72.14.186.212] /opt/meteor/app/programs/server/node_modules/fibers/future.js:173
[72.14.186.212]                         throw(ex);
[72.14.186.212]     [72.14.186.212]             [72.14.186.212]         [72.14.186.212]  [72.14.186.212]      ^
Error: /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
```

I tried running `mup setup` again, but it didn't do anything.

**Comment by arunoda** [comment]
Yep. Known issue.
Working on it.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by SachaG** [comment]
Awesome. Thanks for always being so responsive :)

**Comment by arunoda** [comment]
Done.  https://github.com/arunoda/meteor-up#binary-npm-module-support

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
Actually, I seem to still have the same issue :(

**Comment by arunoda** [comment]
What the telescope version? I will check.

On Friday, August 29, 2014, Sacha Greif notifications@github.com wrote:

> Actually, I seem to still have the same issue :(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/114#issuecomment-53830885.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
That'd be great :) https://github.com/TelescopeJS/Telescope/tree/090

**Comment by arunoda** [comment]
Hey,

I was able to deploy it.
Can you please whether you have done `npm i -g mup`

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
Weird. I made sure I updated and tried again, but still the same problem. I'll try deploying on a new box later.

**Comment by arunoda** [comment]
okay.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by SachaG** [comment]
The issue was actually unrelated, so closing this.
