### ISSUE TITLE
Verifying deployment: FAILED, assert.js:93 throw new assert.AssertionError

### ISSUE THREAD

**Issue by Fred-J** [arunoda/meteor-up-legacy#1140]
Deploying Meteor app onto AWS ubuntu EC2.
From the local development machine:
mupx setup went OK
mupx deploy gave the following output:

Any suggestions?

`
- Uploading bundle
- Uploading bundle: SUCCESS
- Sending environment variables
- Sending environment variables: SUCCESS
- Initializing start script
- Initializing start script: SUCCESS
- Invoking deployment process
- Invoking deployment process: SUCCESS
- Verifying deployment
 x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------

    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
`

//mup.json

> {
  "servers": [
    {
      "host": "aws ip for ec2",
      "username": "ubuntu",
      "pem": "~/keyFile.pem",
      "env": {}
    }
  ],
  "setupMongo": false,
  "appName": "my-name",
  "app": "../app-dir-name",
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://app-domain.com.au",
    "MONGO_URL": "mongodb://link provided by mongodb cloud provider"
  },
  "deployCheckWaitTime": 60,
  "enableUploadProgressBar": true
}

//settings.json
`{
  "env": {
    "MONGO_URL": "mongodb://link provided by mongodb cloud provider"
  }
}`

**Comment by MikeCraig418** [comment]
@Fred-J  How did you resolve this?

**Comment by ashutosh152** [comment]
Did you able to resolve this ?
