### ISSUE TITLE
I am facing this issue, can you help?

### ISSUE THREAD

**Issue by nicolsondsouza** [arunoda/meteor-up-legacy#115]
- Uploading bundle
  ✘ Uploading bundle: FAILED
  
  -----------------------------------STDERR-----------------------------------
  Warning: Permanently added '192.168.1.191' (ECDSA) to the list of known hosts.
  /tmp/c5a8981f-3f42-4972-a3fa-14c8f67b8e79.tar.gz: No such file or directory
  ## -----------------------------------STDOUT-----------------------------------
  
  Completed TaskList: Deploy app 'myapp' (linux)

**Comment by nicolsondsouza** [comment]
I have different mup deployment, never had any issues,
but this is the first time I am having an issue.

meteor version is 0.9.\* version

**Comment by rootedsoftware** [comment]
+1, same issue here

**Comment by rootedsoftware** [comment]
I just removed my mup instance folder and created a new one with the same mup.json and settings.json files and I get the exact same error. Here is what I get after running `mup deploy` and 
`mup logs -f`

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[trashmountain] Warning: Permanently added '[trashmountain]:4444' (ECDSA) to the list of known hosts.
[trashmountain]     at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8
Kadira: completed instrumenting the app
info:  =====> Meteor App restarted Thu Aug 28 2014 13:03:59 GMT-0400 (EDT) <=====
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
```

**Comment by arunoda** [comment]
Just fixed this.
Pushed a new version. 
Please update to that.

**Comment by rootedsoftware** [comment]
Yes, that fixed it. Thanks

**Comment by arunoda** [comment]
Nice.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by nicolsondsouza** [comment]
Thanks, that fixes it.
You are the "hero of meteor"
