### ISSUE TITLE
PhantomJS fails

### ISSUE THREAD

**Issue by tigransloyan** [arunoda/meteor-up-legacy#116]
Even though PhantomJS is installed during mup setup/mup deploy running 

ROOT_URL/?_escaped_fragment_=

after deploying hangs for several seconds and then produces this error in the server logs

spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }

**Comment by tigransloyan** [comment]
@arunoda ping ping :) have you had a chance to look at this?

**Comment by MiroRadenovic** [comment]
:+1:  same problem

**Comment by Batistleman** [comment]
How did you add phantomjs?
I think there are some binaries that need to be installed first. (I think this can be done by installing phantomjs on the server manually first)

**Comment by tigransloyan** [comment]
@Batistleman well according to the meteor-up docs it should automatically take care of installing and configuring Phantomjs for you if you specify this in your mup.json file:

```
  // Install PhantomJS on the server
  "setupPhantom": true,
```

**Comment by Batistleman** [comment]
Ah yes, I missed that...

**Comment by iboxgithub** [comment]
Different points here : 
- I don't know why but never been able to install PhantomJS through MUP so I do it manually and I set up install to false
- I had problems with my proccess killed and I solved it by adding a swap to my server (most of the time it is killed because of a lack od virtual memory, it is not a very excplicit mistake though)

**Comment by tigransloyan** [comment]
ok i figured out the issue, nothing to do with mup. The problem is that if one of your subscriptions doesn't return a cursor or a this.ready() phantomjs will keep on waiting for that subscription and time out after 15 seconds. So go through your subscriptions and make sure that you are either returning a Collection.find() or this.ready().

**Comment by arunoda** [comment]
Oh!  Is that?
