### ISSUE TITLE
"app" in mup.json as ENV variable

### ISSUE THREAD

**Issue by digilord** [arunoda/meteor-up-legacy#119]
Would it be possible to use an environment variable inside of mup.json in place of the absolute path for the app? I work on a team and each of us use `/home/<me>/project/<app>` as the path for projects. Having to have that hardcoded makes it so that we all have to have the same structure for pushing via mup.

Thanks!

With best regards,

D. Allen Morrigan
￼
http://www.digilord.net
https://github.com/digilord

**Comment by arunoda** [comment]
It's not something possible at this moment. May be you can create a simple
shell script to do that.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by digilord** [comment]
A wrapper around mup to fix up the "app" attribute in mup.json?

**Comment by arunoda** [comment]
Not actually. Then you can send me a PR :)
I mean something like mup.sh which generate the mup.json for your users.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
