### ISSUE TITLE
mup deploy fails...

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#124]
## Meteor Up: Production Quality Meteor Deployments

Bundling Started: /Users/sam1/apps/h20140822/app1
Bundling Error: code=1, error:
-------------------STDOUT-------------------

-------------------STDERR-------------------
'/Users/sam1/.meteor' exists, but '/Users/sam1/.meteor/meteor' is not executable.

Remove it and try again

Is it saying to remove the .meteor under /Users/sam1/?

**Comment by arunoda** [comment]
did you got it fixed?

**Comment by ghost** [comment]
Yes… It was on my end. Thanks for follow-up. Very impressive module...

Sridhar
—

**Comment by hamz250** [comment]
How did you fix it please ?
