### ISSUE TITLE
Using mrt with Meteor Up

### ISSUE THREAD

**Issue by SachaG** [arunoda/meteor-up-legacy#129]
Now that Meteor supports packages and `mrt` is on the way out, I assume `mup` uses `meteor` by default. But I'm still supporting older projects (such as Sidebar), and I'm wondering how I can get them to keep using `mrt`, or if that should happen automatically?

I saw the "Custom Meteor Binary" section but I'm not sure where the `mrt` binary is on my server?

I think this could be a pretty common use case, so I'll submit a pull request to update the documentation once I figure it out :)

**Comment by arunoda** [comment]
You don't need to use customBinary at all. mup uses meteor by default from
the beginning. All you have to do is, use mrt update and install packages.

Still if you need to use it. Here's the location: /usr/local/bin/mrt

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by SachaG** [comment]
Oh ok, never mind this comment then. Thanks for the fast reply as always :)
