### ISSUE TITLE
deploy but nor bundle

### ISSUE THREAD

**Issue by pronamc** [arunoda/meteor-up-legacy#131]
Is it possible to skip bundling and just upload and deploy the app. 
A lot of times when changing mup.json I frequently deploy the same code over and over again. 
Could not find a way to do this.

**Comment by arunoda** [comment]
unfortunately, there is no way to do.
BTW: what do you mean by changing mup.json?

If you are only changing env vars, simply run "mup reconfig"

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by pronamc** [comment]
Ah! I missed that one. I am indeed only changing the environment variables.
