### ISSUE TITLE
Bind to multiple urls

### ISSUE THREAD

**Issue by BradRuderman** [arunoda/meteor-up-legacy#133]
Thanks for MUP, its great. How can I bind to multiple root urls, such as http://domain.com and http://www.domain.com.

Thanks!

**Comment by arunoda** [comment]
There is no way to do such in meteor.
You need create a redirect.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by BradRuderman** [comment]
thanks!
