### ISSUE TITLE
Having trouble getting Binary NPM modules installed correctly

### ISSUE THREAD

**Issue by timbrandin** [arunoda/meteor-up-legacy#137]
Hi, I deployed a simple application using Meteor NPM and jsdom.

Everything seams fine, but when running cron (synced-cron) with the jsdom script, I get this error

```
Error: /opt/meteor/app/programs/server/npm/npm-container/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: invalid ELF header\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Module.require (module.js:364:17)\n    at require (module.js:380:17)\n    at bindings (/opt/meteor/app/programs/server/npm/npm-container/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)\n    at Object.<anonymous> (/opt/meteor/app/programs/server/npm/npm-container/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)\n    at Module._compile (module.js:456:26)\n    at Object.Module._extensions..js (module.js:474:10)\n    at Module.load (module.js:356:32)\n    at Function.Module._load (module.js:312:12)\n    at Module.require (module.js:364:17)\n    at require (module.js:380:17)
```

Could this be because of the architecture used or are things not installing correctly?

**Comment by arunoda** [comment]
Yep. You are correct.
Seems like a bug in mup's binary build process.
Let me see.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by timbrandin** [comment]
Can't wait, :)

2014-09-21 9:04 GMT+02:00 Arunoda Susiripala notifications@github.com:

> Yep. You are correct.
> Seems like a bug in mup's binary build process.
> Let me see.
> 
> ---
> 
> Arunoda Susiripala
> I curate Meteor Weekly - Check it out!
> <
> http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly>
> 
> On Sat, Sep 20, 2014 at 12:46 PM, Tim Brandin notifications@github.com
> wrote:
> 
> > Hi, I deployed a simple application using Meteor NPM and jsdom.
> > 
> > Everything seams fine, but when running cron (synced-cron) with the
> > jsdom
> > script, I get this error
> > 
> > Error:
> > /opt/meteor/app/programs/server/npm/npm-container/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node:
> > invalid ELF header\n at Module.load (module.js:356:32)\n at
> > Function.Module._load (module.js:312:12)\n at Module.require
> > (module.js:364:17)\n at require (module.js:380:17)\n at bindings
> > (/opt/meteor/app/programs/server/npm/npm-container/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)\n
> > at Object.<anonymous>
> > (/opt/meteor/app/programs/server/npm/npm-container/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)\n
> > at Module._compile (module.js:456:26)\n at Object.Module._extensions..js
> > (module.js:474:10)\n at Module.load (module.js:356:32)\n at
> > Function.Module._load (module.js:312:12)\n at Module.require
> > (module.js:364:17)\n at require (module.js:380:17)
> > 
> > Could this be because of the architecture used or are things not
> > installing correctly?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/arunoda/meteor-up/issues/137.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/137#issuecomment-56291177.

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com
http://studiointeract.com

**Comment by arunoda** [comment]
Hey, Sorry for taking too long.
Had some network issues.

Fixed the issue and released a new version: `0.6.8`.

Reason: binary module building script didn't work well recursively. see: https://github.com/arunoda/meteor-up/commit/917b53fa2a4f10b16f2e098fdbd1c02b3bb33251

**Comment by timbrandin** [comment]
Awesome, I'll try it out.

**Comment by timbrandin** [comment]
It works! Very well! Great work. :)
