### ISSUE TITLE
'build' is not a Meteor command.

### ISSUE THREAD

**Issue by timbrandin** [arunoda/meteor-up-legacy#143]
Did Meteor just remove the build command in the latest version?

I get this error now when I try to deploy an app I've got:

``` bash
Bundling Error: code=1, error:
-------------------STDOUT-------------------

-------------------STDERR-------------------
'build' is not a Meteor command. See 'meteor --help'.
```

**Comment by arunoda** [comment]
oh! I didn't check that with 0.9.3. Let me check?

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by timbrandin** [comment]
I just realized it might have been caused by an old version of Meteor, METEOR@0.9.0.1

I migrated my app from 0.8.x to 0.9 with the mrt migrate-app command.

And everything seemed fine, but now I noticed iron router was added as cmather:iron-router, which is incompatible with 0.9. I guess this is the underlying reason... causing other issues.

**Comment by timbrandin** [comment]
Yep, It works now when Meteor actually was updated to the latest version. 

Could it be that in 0.9.0.1 something in with build is missing?

**Comment by arunoda** [comment]
mrt migrate-app is quite buggy.
I never used it. I migrated apps manually.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
build was added from 0.9.2

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by timbrandin** [comment]
So yes, migrate-app is something to avoid. Luckily I don't have that many apps on pre 0.9 anymore. :)

**Comment by timbrandin** [comment]
Awesome response time, btw! :)

**Comment by timbrandin** [comment]
I'm closing this.

**Comment by arunoda** [comment]
cool.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by cunneen** [comment]
I get this error too. I haven't migrated my app from 0.8.3 (due to broken soft-dependencies), but I did make the mistake of upgrading my meteor-up to the latest. Now I get this "'build' is not a Meteor command." issue. Do I need to downgrade meteor-up ?

**Comment by arunoda** [comment]
Yes. Use version 0.6.5

On Friday, October 10, 2014, cunneen notifications@github.com wrote:

> I get this error too. I haven't migrated my app from 0.8.3 (due to broken
> soft-dependencies), but I did make the mistake of upgrading my meteor-up to
> the latest. Now I get this "'build' is not a Meteor command." issue. Do I
> need to downgrade meteor-up ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/143#issuecomment-58612873.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by cunneen** [comment]
Wow, that's an all-time record fast response. Thanks arunoda. meteor-up is awesome.

**Comment by timbrandin** [comment]
Quick responses is Arunoda's thing! Love it!

2014-10-10 7:05 GMT+02:00 cunneen notifications@github.com:

> Wow, that's an all-time record fast response. Thanks arunoda. meteor-up is
> awesome.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/143#issuecomment-58612980.

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com
http://studiointeract.com

**Comment by SachaG** [comment]
Is there any way to downgrade mup only for a specific app? I assume probably not?
