### ISSUE TITLE
Strange issue that logs have stopped working

### ISSUE THREAD

**Issue by elie222** [arunoda/meteor-up-legacy#144]
I get the following error message when running the following:
mup logs -f
or
mup logs -n 300:

"tail: cannot open ‘/var/log/upstart/draftapp.log’ for reading: No such file or directory"

It's strange because I haven't made a change to my deployed app in a few weeks now and it's been working fine the last few weeks. Any idea what happened?

**Comment by elie222** [comment]
I do the have the following files in the directory /var/log/upstart/:
draftapp.log.1.gz
draftapp.log.2.gz
draftapp.log.3.gz
draftapp.log.4.gz
draftapp.log.5.gz
draftapp.log.6.gz
draftapp.log.7.gz

**Comment by elie222** [comment]
Now it's working again for some reason. I didn't change anything on the server. I don't know what happened.

**Comment by arunoda** [comment]
This might be the issue.
Time to time, OS compress your log files.

But, when you requested that log file. I was compressed and there was no
new logs to generate a new one.
I suspect, that as the issue.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by elie222** [comment]
Thanks

**Comment by evolross** [comment]
I'm having this same issue... deploy and logging works fine, but then the log stops working after a few days with the `cannot open '/var/log/upstart/appname.log' for reading : No such file or directory`.

My issue is when I list `/var/log/upstart`, I see a ton of log files but none of them are `appname`.  So if the OS compressed my old log file to that point, it's no longer in this folder.  There isn't anything with `appname` on it.  BUT, it was working fine and tailing my log for days before the error message.  Does it move the compressed log files?  I noticed all the other OS log files are all in this folder with the `*.log.#.gz` format.

**Comment by evolross** [comment]
Where would I look into to configure when and why a log gets compressed and archived?  Like how often? What size threshold? Is this an Upstart setting or a general Ubuntu setting?

**Comment by MasterJames** [comment]
Maybe try looking into logrotate 
/etc/logrotate.d and /etc/logrotate.conf

https://github.com/arunoda/meteor-up/wiki/Application-logging-settings

Other such cron like possibilities exist...
https://www.digitalocean.com/community/tutorials/how-to-manage-log-files-with-logrotate-on-ubuntu-12-10
