### ISSUE TITLE
WARNING: Building your app with host: localhost. Pass a -p argument to specify a host URL.

### ISSUE THREAD

**Issue by bayu-aji** [arunoda/meteor-up-legacy#146]
I was able to do deploys before, now with meteor 0.9.3 and the latest version of mup, ran mup update and setup, and getting this error: 

Bundling Error: code=8, error:
-------------------STDOUT-------------------
WARNING: Building your app with host: localhost.
Pass a -p argument to specify a host URL.

-------------------STDERR-------------------
rScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...

```
at execFileSyncOrThrow (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:127:11)
at buildCordova (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:622:3)
at Object.cordova.buildPlatforms (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:661:3)
at main.registerCommand._.extend.name [as func] (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands.js:627:13)
at /root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/main.js:1241:23
```

**Comment by arunoda** [comment]
Can you please send me your mup.json without credentials.

On Thursday, October 2, 2014, bayu-aji notifications@github.com wrote:

> I was able to do deploys before, now with meteor 0.9.3 and the latest
> version of mup, ran mup update and setup, and getting this error:
> 
> Bundling Error: code=8, error:
> -------------------STDOUT-------------------
> WARNING: Building your app with host: localhost.
> Pass a -p argument to specify a host URL.
> 
> -------------------STDERR-------------------
> rScript files...
> [echo] ----------
> [echo] Handling Resources...
> [aapt] Generating resource IDs...
> 
> at execFileSyncOrThrow (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:127:11)
> at buildCordova (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:622:3)
> at Object.cordova.buildPlatforms (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:661:3)
> at main.registerCommand._.extend.name [as func](/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands.js:627:13)
> at /root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/main.js:1241:23
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/146.

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by bayu-aji** [comment]
{
  // Server authentication info
  "servers": [
    {
      "host": "128.199.173.212",
      "username": "myroot",
      "password": "mypass"
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.31 by default. Do not use v, only version number.
  "nodeVersion": "0.10.32",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Application name (No spaces)
  "appName": "sinta",

  // Location of app (local directory)
  "app": "~/meteor-apps/sinta",

  // Configure environment
  "env": {
    "PORT": 3006,
    "ROOT_URL": "http://localhost",
    "MONGO_URL": "mongodb://myuser:mypass@127.0.0.1:27017/rinada"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

**Comment by radiegtya** [comment]
I am getting this error too when deploying using meteor 0.9.3.1

### 1. meteor setup (this is successfully run) but there is some error in logs

[128.199.173.212] Warning: Permanently added '128.199.173.212' (ECDSA) to the list of known hosts.
[128.199.173.212] error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/meteoris/app/main.js does not exist.
error:   Cannot start forever
error:   script [128.199.173.212] /opt/meteoris/app/main.js does not exist.

/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:102
    throw new Error('Could not find package.json up from: ' + dir);
          ^
Error: Could not find package.json up from: /
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:102:11)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.find (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:108:18)
    at Function.pkginfo.read (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:119:17)
    at module.exports (/usr/lib/node_modules/forever/node_modules/pkginfo/lib/pkginfo.js:69:21)
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found
/proc/self/fd/9: 14: /proc/self/fd/9: forever: not found

### 2. Then when i am running "mup deploy", it produce error like @bayu-aji

Bundling Error: code=8, error:
-------------------STDOUT-------------------
WARNING: Building your app with host: localhost.
Pass a -p argument to specify a host URL.

-------------------STDERR-------------------
rScript files...
[echo] ----------
[echo] Handling Resources...
[aapt] Generating resource IDs...

at execFileSyncOrThrow (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:127:11)
at buildCordova (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:622:3)
at Object.cordova.buildPlatforms (/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands-cordova.js:661:3)
at main.registerCommand._.extend.name [as func](/root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/commands.js:627:13)
at /root/.meteor/packages/meteor-tool/.1.0.33.k69mx++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/main.js:1241:23

### 3. But strangely it works in my other aplication with meteor v0.9.3 too. I feel suspicious about my package.

**here my package list (which is producing error):**
accounts-base 1.1.1 A user account system
accounts-facebook 1.0.1 Login service for Facebook accounts
accounts-google 1.0.1 Login service for Google accounts
accounts-password 1.0.2 Password support for accounts
aldeed:collection2 2.1.0 Automatic validation of insert and update o...
cfs:ejson-file 0.0.0 CollectionFS, FS.File as EJSON type
cfs:filesystem 0.0.0 Filesystem storage adapter for CollectionFS
cfs:gridfs 0.0.0 GridFS storage adapter for CollectionFS
cfs:standard-packages 0.0.2 Filesystem for Meteor, collectionFS
francocatena:status 0.9.8 Display the connection status with the server
ground:db 0.0.7 Ground Meteor.Collections offline
iron:router 0.9.4 Routing specifically designed for Meteor
jquery 1.0.0 Manipulate the DOM using CSS selectors
lepozepo:accounting 1.0.0 Accounting.js - number, money and currency...
mdg:geolocation 1.0.2 Provides reactive geolocation on desktop an...
mdg:reload-on-resume 1.0.1 On Cordova, only allow the app to reload wh...
meteor-platform 1.1.1 Include a standard set of Meteor packages i...
meteorhacks:subs-manager 1.1.0 Subscriptions Manager for Meteor
mizzao:timesync 0.2.2 NTP-style time synchronization between serv...
mrt:iron-router-progress 0.9.2 Progressbar for iron:router
mrt:moment 2.8.1 Moment.js, a JavaScript date library for da...
mystor:device-detection 0.2.0 Client-Side Device Type Detection & Templat...
pfafman:font-awesome-4 4.2.0_1 Font awesome packaged for meteor
pinglamb:bootstrap3 3.2.1 Front-end framework from Twitter, version 3
reywood:publish-composite 1.3.0 Publish a set of documents and their child ...
sacha:spin 2.0.4 Simple spinner package for Meteor
service-configuration 1.0.1 Manage the configuration for third-party se...

**here my another package list from another apps (which is success):**
accounts-base              1.1.1  A user account system
accounts-password          1.0.2  Password support for accounts
accounts-ui                1.1.1  Simple templates to add login widgets to an...
aldeed:collection2         2.1.0  Automatic validation of insert and update o...
cunneen:mailgun            0.9.1  Easily send emails using Mailgun as your em...
email                      1.0.3  Send email messages
iron:router                0.9.3\* Routing specifically designed for Meteor
jquery                     1.0.0  Manipulate the DOM using CSS selectors
meteor-platform            1.1.1  Include a standard set of Meteor packages i...
mrt:jquery-masonry         0.1.0  jQuery Masonry repackaged for Meteor
mrt:jquery-ui              1.9.2  jQuery-UI - jQuery user interface
mrt:moment                 2.8.1  Moment.js, a JavaScript date library for da...
natestrauser:font-awesome  4.2.0  Latest version Font-Awesome loaded via CDN
natestrauser:select2       3.4.9  Select2 is a jQuery based replacement for s...
pinglamb:bootstrap3        3.2.1  Front-end framework from Twitter, version 3
reywood:publish-composite  1.3.0  Publish a set of documents and their child ...
sacha:spin                 2.0.4  Simple spinner package for Meteor

Please help @arunoda :)

Regards

**Comment by arunoda** [comment]
I think, you've added either ios or android platform to your app.
Now meteor trying to build them as well. And they require -p argument.

That's why there is an issue. I'm trying to find away to build only for the web. Can anyone have suggestions?

**Comment by arunoda** [comment]
For now, you can remove those ios and android platform and see deploy your app.

```
meteor remove platform ios
meteor remove platform android
```

**Comment by bayu-aji** [comment]
Work perfectly.... Tq Arunoda

**Comment by radiegtya** [comment]
Thanks arunoda for the kind answer. It works now.

I don't have any suggestion right now. But I think you should add some README about this.

Thanks

**Comment by arunoda** [comment]
Started a discussion on meteor-core.
Seems like, there is no way to do it right now other than removing mobile
platforms.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by radiegtya** [comment]
It's ok I think if there is some information in readme. Keep up the great work. :+1:

**Comment by arunoda** [comment]
oh yeah! Can you please send me a PR :)

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by radiegtya** [comment]
Of course @arunoda . I have send you the PR, please check it out.

**Comment by alanning** [comment]
Not a perfect solution but we have a workaround for a similar issue with the [velocity](https://github.com/meteor-velocity/velocity) project that would also seem to be useful in this case.  With velocity the goal is to avoid test-only packages being released to production.  The workaround is a simple, custom bundle script that removes the packages, does the bundle, then puts the packages back in the `.meteor/packages` file.  You can find the script here:  https://gist.github.com/alanning/e9a61744000e177332d1

Someone also did a nodejs version; if you are interested in that, I can track that down.

**Comment by arunoda** [comment]
Guys, I made a fix to deploy without removing mobile platforms.
Something similar to @alanning mentioned solution.
But make sure we will replace the original platforms file even if an error happens.

Install latest mup (0.6.9)
