### ISSUE TITLE
can someone explain this error

### ISSUE THREAD

**Issue by sasikanth513** [arunoda/meteor-up-legacy#151]
when I try to deploy app to DO, it is throwing following error

![mup](https://cloud.githubusercontent.com/assets/6153816/4519019/757e43f0-4caa-11e4-817f-f8f9dee57dbd.png)

**Comment by elie222** [comment]
Exact same error here. I just tried to redeploy having updated a bunch of things, but got that error.

**Comment by elie222** [comment]
I managed to get mine working by using node 10.29. I used to be on 10.28 and the problems started when I upgraded to 10.31. (But it could also have been a lot of other things.)

**Comment by arunoda** [comment]
please check logs by getting mup logs -n 400

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by ChenRoth-old** [comment]
I've just had a similar error message deploying Meteor 1.0.2
by checking the logs, Meteor indicated I need to use a newer node version (0.10.31 -> 0.10.33)
I modified mup.json to have "nodeVersion": "0.10.33",  but the error keeps repeating
so I installed 0.10.33 using nvm on the server, yet the error is still there
I even tried to set "setupNode": false

any thoughts?
