### ISSUE TITLE
mup deploy building error code 137

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#152]
mup setup went fine, but when I try to deploy, I get the following error. Any ideas? Thanks!

root@ts:~/ts-deploy# mup deploy
## Meteor Up: Production Quality Meteor Deployments

Building Started: /root/TS/
Bundling Error: code=137, error:
-------------------STDOUT-------------------

Figuring out the best package versions to use. This may take a moment.

-------------------STDERR-------------------
bash: line 1: 31217 Killed                  meteor build --directory /tmp/dc37af3e-eca0-4a19-bf1a-d6d38bb8f517

**Comment by ghost** [comment]
I'm still banging my head against the wall on this one. Below are the logs. node -v indicates I am using 0.10.31. How do I check which script is exiting with the error? Any other ideas? Thanks!

error: Forever detected script exited with code: 1
error: Script restart attempt #106
Meteor requires Node v0.10.29 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #107
Meteor requires Node v0.10.29 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #108

> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser

**Comment by ghost** [comment]
I've re-run things on a DO Droplet restore and now I get this error (mup logs don't have anything):

root@ts:~/ts-deploy# mup deploy

## Meteor Up: Production Quality Meteor Deployments

Building Started: /root/TS
Bundling Error: code=134, error:
-------------------STDOUT-------------------

Figuring out the best package versions to use. This may take a moment.

-------------------STDERR-------------------
FATAL ERROR: JS Allocation failed - process out of memory
bash: line 1:  1918 Aborted                 (core dumped) meteor build --directory /tmp/5d9d7285-b68f-486b-9233-4a6116913b19

**Comment by ghost** [comment]
I addressed the memory issue by implementing the swap file. Using $5 Droplet and followed instructions at http://stackoverflow.com/questions/26216127/memory-issue-with-meteor-up-mup-on-digital-ocean

**Comment by arunoda** [comment]
BTW: What's cause the memory issue?
Do you have any idea.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by ghost** [comment]
It appears to be a recurring problem when using the $5/mo DigitalOcean Droplet. It has 512 MB of RAM, which I think should be adequate. Do you know how much RAM mup deploy uses when bundling and deploying?

**Comment by arunoda** [comment]
if you are using DO box also building 512 might not be adequate. But 512 is
okay to run a meteor app deployed via Mup.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by ghost** [comment]
Thanks for your input. However, I am not sure I understand your meaning. 512 should be okay for mup, but the problem is that DO Droplets don't function well with 512? 

This would make sense, since I had to implement swap to get it working.

**Comment by arunoda** [comment]
No I mean, in order to run a deployed meteor app. not for bundling and
deploying.

Anyway, it's totally app dependant.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by ghost** [comment]
Got it. Thanks for your input and great work on mup, dude! 

If anyone figures out how to prevent the "JS allocation process out of memory" issue without implementing swap, please comment here.

**Comment by arunoda** [comment]
Nice. :)

On Wednesday, October 8, 2014, artitw notifications@github.com wrote:

> Got it. Thanks for your input and great work on mup, dude!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/152#issuecomment-58297865.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
