### ISSUE TITLE
Having trouble with Mongo configuration

### ISSUE THREAD

**Issue by stephentcannon** [arunoda/meteor-up-legacy#154]
It has been quite sometime since I did a configuration file.  MUP is so awesome I just set it and forget it and deploy.  This morning I found myself having to configure a replicaset on MongoHQ and I cannot get it to work. 

Here is the syntax I am using

```
"MONGO_URL": "mongodb://<username>:<password>@<server1>:<port>,<server2>:<port>/<databasename>?replicaSet=<what is this?>&readPreference=primaryPreferred",

"MONGO_OPLOG_URL": "mongodb://<username>:<password>@<server1>:<port>,<server2>:<port>/local?authSource=<databasename>",
```

Arunoda can you assist?

**Comment by stephentcannon** [comment]
Trying to configure MONGO_URL for replicasets at MongoHQ and I am using the connection string they provided but it is failing on mup deploy with

```
tarted TaskList: Deploy app 'meteor' (linux)
[54.82.228.16] - Uploading bundle
[54.82.228.16] ✔ Uploading bundle: SUCCESS
[54.82.228.16] - Setting up Environment Variables
[54.82.228.16] ✔ Setting up Environment Variables: SUCCESS
[54.82.228.16] - Invoking deployment process
[54.82.228.16] ✘ Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
        /bundle/programs/server/node_modules/node-aes-gcm',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp info spawn make
        gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
        gyp info ok 
        npm http GET https://registry.npmjs.org/fibers
        npm http 304 https://registry.npmjs.org/fibers
        npm http GET https://registry.npmjs.org/bcrypt
        npm http 304 https://registry.npmjs.org/bcrypt
        npm http GET https://registry.npmjs.org/bindings/1.0.0
        npm http GET https://registry.npmjs.org/nan/1.3.0
        npm http 304 https://registry.npmjs.org/bindings/1.0.0
        npm http 304 https://registry.npmjs.org/nan/1.3.0

        /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
            throw err;
                  ^
        Error: TIMEOUTED_WAIT_FOR_MONGO
            at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
            at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
        -----------------------------------STDOUT-----------------------------------
        .1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        wait-for-mongo: failed to connect to [127.0.0.1:27017]
        ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'meteor' (linux)
```

string used was

```
"MONGO_URL": "mongodb://<username>:<password>@<server1>:<port>,<server2>:<port>/<databasename>?replicaSet=<replicasetname>&readPreference=primaryPreferred",

"MONGO_OPLOG_URL": "mongodb://<username>:<password>@<server1>:<port>,<server2>:<port>/local?authSource=<databasename>",

```

any ideas?

**Comment by arunoda** [comment]
This is crazy. Mup detects Mongo URL as 127.0.0.1:27017. And that's
defaults.

Can you please check mup.json whether you put MONGO_URL under env?

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by stephentcannon** [comment]
I just updated mup thinking that might be the problem and now I am getting.

```
Building Started: /home/chronos/user/Downloads/projects/etherpos/etherpos
Bundling Error: code=1, error:
-------------------STDOUT-------------------

-------------------STDERR-------------------
'build' is not a Meteor command. See 'meteor --help'.
```

This project is on meteor Release 0.8.1

**Comment by arunoda** [comment]
Use mup @ 0.6.5 (npm i -g mup@0.6.5)

This is something did for 0.9.x

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by stephentcannon** [comment]
ahh, yes i thought i remembered seeing that on email threads watching this project...i am sooo far behind upgrading into new versions of meteor...they are moving fast...it is hard to keep up...thanks...will go see what is going on now....the mongo url is in env btw

**Comment by stephentcannon** [comment]
This is my env

```
"env": {
    "PORT": 58080,
    "ROOT_URL": "https://staging.etherpos.com",
    "MONGO_URL": "mongodb://<username>:<password>@<domain>:<port>,<domain>:<port>/<databasename>?replicaSet=<set name provided by mongohq>&readPreference=primaryPreferred",
    "MONGO_OPLOG_URL": "mongodb://<username>:<password>@<domain>:<port>,<domain>:<port>/local?authSource=<databasename>"
  }
```

i cannot figure it out for the life of me.  it should be working.  i even had mongohq take a look at the MONGO_URL

**Comment by arunoda** [comment]
Can you please run mup deploy as follow

DEBUG=\* mup deploy

Then send me the logs via email. I'll check what's wrong with that.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by stephentcannon** [comment]
if i change MONGO_URL to

```
 "MONGO_URL": "mongodb://<username>:<password>@<domain>:<port>/<databasename>"
```

it deploys fine, but not via the replicaset conf

**Comment by arunoda** [comment]
Oh! I got the issue.
Can you wrap your replicaUrl with quotes. Like this:

"env":  {
  "MONGO_URL": "\"the-url\""
}

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by stephentcannon** [comment]
so it has to be escaped or something?

what about MONGO_OPLOG_URL when using replicaset?  doesn't appear to need it.

why does this need that?

**Comment by arunoda** [comment]
I think so.
Check the env.sh file located in your server at

/opt/<appName>/config/env.sh

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by stephentcannon** [comment]
it looks like only MONGO_URL needs it

**Comment by mlanett** [comment]
This is really a bug in mup. It should automatically quote values when writing the env file. Putting escaped quotes in the json config file would probably be incorrect for any use other than mup.

**Comment by arunoda** [comment]
Now it does. We fixes it few months a go.
