### ISSUE TITLE
MUP update deployed site

### ISSUE THREAD

**Issue by geekyme** [arunoda/meteor-up-legacy#164]
How do I update my successfully deployed mup app?

After editing my meteor code, I ran mup deploy and got these errors on the console: 

```
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
[128.199.150.165] error: Script restart attempt #48[128.199.150.165]
[128.199.150.165]
[128.199.150.165] events.js:72[128.199.150.165]
        throw er; // Unhandled 'error' event[128.199.150.165]
   [128.199.150.165]   [128.199.150.165]          ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
error: Forever detected script exited with code: 8
[128.199.150.165] error: Script restart attempt #49[128.199.150.165]
```

**Comment by geekyme** [comment]
To get the mup app updated, I had to ssh into the app and run `sudo reboot`

**Comment by arunoda** [comment]
Very strange. Did you manually enter start stop your app, seems like there
was another app running on port 80.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by geekyme** [comment]
Yes there was a failed mup deployment on the same box with bad setup that was taking port 80. 
It's called microscope-1.0 and the correct one is called microscope

After manually stopping microscope-1.0 the problem goes away. 

Is there a quick way to remove all setup files for microscope-1.0? Such as its upstart files / db files etc.

**Comment by arunoda** [comment]
no at this point.
yes. we need one.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by rdewolff** [comment]
Got the same issue here.

**Comment by meonkeys** [comment]
I just started seeing this issue this morning. Repro steps:
- Meteor app deployed and running fine with mup 0.7.4. 
- Run `mup deploy` to update app.
- Old server keeps running, mup tries to start new server.
- Same error shown as original bug report (`Error: listen EADDRINUSE`).

**Comment by rdewolff** [comment]
Seems like we need an expert here :)

**Comment by geekyme** [comment]
the problem only occur for me the other day because I had an erroneous setup that kept running its upstart scripts. 

I had to kill that script, and then redeploy with the correct setup. It should work smoothly afterwards.

**Comment by meonkeys** [comment]
Argh, I think my patch from #209 (adding `kill signal SIGHUP` to the upstart init script) is causing the problem. After reverting that patch the issue goes away for me. Sorry, guys! I'll send a new PR to undo #209.

@arunoda do you use mup on Ubuntu?

**Comment by arunoda** [comment]
I am using ubuntu. I don't get this error.
Anyway now there is a new version `0.7.5` try that :)

**Comment by Ines-K** [comment]
so you just redeploy the app every time you update the app's code? mup reconfig only seems to work for environment files
