### ISSUE TITLE
Avoid running nodejs/forever as root

### ISSUE THREAD

**Issue by timbrandin** [arunoda/meteor-up-legacy#173]
I noticed when using fs.makeDirSync or mkdirp folders are created with user and group root.
And I guess this is because node is running as root, this might not be that perfect.

Here's some ideas for a solution:
http://technosophos.com/2013/03/06/how-use-ubuntus-upstart-control-nodejs-forever.html
http://stackoverflow.com/questions/22923077/run-upstart-with-forever

**Comment by arunoda** [comment]
What's your point?
Just after the app bind to port 80, mup will stepdown your app to a
non-privileged user called meteoruser.
I hope that's fine.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by timbrandin** [comment]
Here's a better explanation of what's happening in my setup.

I have setup mup to step down as **www-data** (I don't think this makes any difference though).

``` js
// Configure environment
"env": {
  "PORT": "8083",
  "USERDOWN_UID": "www-data",
  "USERDOWN_GID": "www-data",
  "ROOT_URL": "http://app.dev"
},
```

I'm using these packages.
cfs:standard-packages
cfs:filesystem

With this code: 

``` js
new FS.Store.FileSystem("medium", {
  path: "/var/www/default/medium",
}),
```

And here's the result:
![image](https://cloud.githubusercontent.com/assets/1715834/5044286/3ec8d636-6bef-11e4-97e8-7471b0979a82.png)

**Comment by arunoda** [comment]
Okay. It seems like CFS does this even before Meteor webapp binds to a port.

Try to wrap following code inside a Meteor.startup() ?
(Why store images on the disk, that's not a good way. Try using S3 if
possible)

new FS.Store.FileSystem("medium", {
  path: "/var/www/default/medium",
}),

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by timbrandin** [comment]
So what you're saying is that node is running as root before startup?
Is that a good solution?

We need to store on disk due to company guidelines, but that's not related to this.

**Comment by arunoda** [comment]
If we need to bind to port 80. We need to have root permission.
Normally, what we do is simply stepdown the permission after we bind to the
port.

There are some other ways, but hard. This is the reasonable one. (easy,
work on anywhere)

Meteor has no way to do this and this is the hack I'm using:
https://github.com/arunoda/node-userdown/blob/master/lib/userdown.js

_Why we need to stepdown_
Normally, we do it to prevent damages done to the system, if someone break
into my app. So, someone can hack into the app(most of the time), if it's
open to the internet.

So, this is a decent solution.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by timbrandin** [comment]
Its a great solution!

I our case we're running multiple meteor on a single machine using nginx and vhosts that proxy to a port running meteor/node apps. And they in turn should not bind to port 80. Maybe in our solution we shouldn't use mup setup to add the upstart scripts, but I like using it and love if I didn't had to use something else.

What if we checked PORT if it's below 1024, and in that case use the userdown solution?

**Comment by arunoda** [comment]
Ah now I got it.
Then we don't need to do use invoke upstart script as root.

We can run upstart script as a non-priviledged users and ignore invoking
user-down at all.
It sounds like a PR to mup :)

What about adding an option like:

{
    upstartUser: "xxx"
}

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by timbrandin** [comment]
Right! Perfect, that works, but maybe uppercase and like userdown (USERDOWN_UID); 
`UPSTART_UID`

**Comment by arunoda** [comment]
If that's an env var uppercase seems great.
But I think we need to change the upstart script dynamically to do this
using ejs templating here:
https://github.com/arunoda/meteor-up/blob/master/templates/linux/meteor.conf

Then we need to pass some argument.

But we might could this without just using a env var. But I'm quite not
sure how to.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by timbrandin** [comment]
Created #174

**Comment by arunoda** [comment]
Hope we can close this.
