### ISSUE TITLE
Multiple Core Support

### ISSUE THREAD

**Issue by ArjunRajJain** [arunoda/meteor-up-legacy#177]
Does Meteor Up support instances with multiple cores?

**Comment by arunoda** [comment]
No. It doesn't

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by joshua1** [comment]
@arunoda , one of your blog posts from 2013 states "Fortunately, I’m working on Meteor-UP to add multi-cpu support automatically. With that, Meteor-Up will do the all the hard work for you." an abrupt NO means that this is discontinued. is that the case? what are the alternatives if any

**Comment by arunoda** [comment]
It's not discontinued. But I had no time to work on this.
Sorry for that. It's on the roadmap, but I have no ETA.
