### ISSUE TITLE
deploy failed

### ISSUE THREAD

**Issue by maxlibin** [arunoda/meteor-up-legacy#180]
Can anyone guide me whats wrong with this deployment?

-----------------------------------STDERR-----------------------------------
    sr/include/nodejs',
    gyp info spawn args   '-Dmodule_root_dir=/opt/watcfy/tmp/bundle/programs/server/npm/vsivsi:file-collection/node_modules/mongodb/node_modules/kerberos',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    stop: Unknown instance:
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    t/watcfy/tmp/bundle/programs/server/npm/vsivsi:file-collection/node_modules/mongodb/node_modules/kerberos/build'
      SOLINK_MODULE(target) Release/obj.target/kerberos.node
      SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
      COPY Release/kerberos.node
    make: Leaving directory `/opt/watcfy/tmp/bundle/programs/server/npm/vsivsi:file-collection/node_modules/mongodb/node_modules/kerberos/build'

```
> fibers@1.0.1 install /opt/watcfy/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@2.2.1 node_modules/semver

source-map-support@0.2.5 node_modules/source-map-support
└── source-map@0.1.29 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
watcfy start/running, process 7442
Waiting for MongoDB to initialize. (5 minutes)
connected
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
watcfy stop/waiting
watcfy start/running, process 7582
```

**Comment by arunoda** [comment]
Can you please get logs via mup logs -n 400.

**Comment by maxlibin** [comment]
sorry my bad, I had some duplicated key in Mongo.

**Comment by arunoda** [comment]
Okay.
