### ISSUE TITLE
Add support for CDN_URL to serve Meteor's CSS/JS from a CDN

### ISSUE THREAD

**Issue by maomorales** [arunoda/meteor-up-legacy#186]
I would like to have a feature that if I have in my settings some parameter like CDN_URL: 'xkjdkjd.cloudfront.net'

The deploy script will change the base URL for the meteor app minified CSS and JS. Would it be possible? I think it'd be very useful for many of us who use meteor-up for production environments and want to optimise page load times.

@arunoda what do you think? - I can help making the changes with your support.

**Comment by arunoda** [comment]
Nope. I don't want to change how meteor works and bundle things.

This should direct goes as a PR to meteor instead MUP.

Anyway, if you need such effect. Use a CDN like Cloudflare. They'll
automatically handle this for you.

**Comment by maomorales** [comment]
Got it! we'll talk to Meteor guys then :)  -  thanks.

**Comment by maomorales** [comment]
Hi @arunoda, this is the reply from Meteor guys:

"@maomorales you can already do it by setting the ROOT_URL_PATH_PREFIX environment variable when you run the meteor server from bundle (if you built if with meteor build command)."

What are your thoughts on integrating this into meteor-up tool?

**Comment by arunoda** [comment]
It's a simple env variable. You can export it with mup.json. No need
special handling.

**Comment by maomorales** [comment]
I see now, support for this is built in. Thanks again!

**Comment by sahanDissanayake** [comment]
@maomorales did you get this to work with CDN ? and notes on what to look out for ?

**Comment by maomorales** [comment]
@sahanDissanayake no, in the end we ended up using CDN for everything else but main meteor files we serve directly from our app server.

**Comment by sahanDissanayake** [comment]
@maomorales  when you say everything else, does it means any file that is not generated or a file that is used to run the Meteor app ??
Thanks for your time

**Comment by maomorales** [comment]
@sahanDissanayake I mean static images, files uploaded by users, etc. (everything that it's either in public/ or in gridFS) - we're using CloudFront for that, or in some other projects we have our own caching distribution layer with Varnish.

The main .js and .css file of the meteor app are served from the application server.
