### ISSUE TITLE
mup deploy breaks DDP

### ISSUE THREAD

**Issue by gargleblaster** [arunoda/meteor-up-legacy#187]
I want to set up DDP from a Groovy app and use Meteor as the console for the app.  I've got a very basic Meteor app that I'm using to get things connected.  The app can be found at https://github.com/advantageous/ddp-client-java/tree/master/examples/meteor-common.

When this simple Meteor app runs on my MacBook, I can connect to it via DDP from my Groovy app on the MacBook, so it seems like everything is good.

However, once I run mup deploy to send the app to a "production" Ubuntu server, I have had no success connecting to the mup'ped app via DDP.  I can access the mup'ped app in the browser, so it looks like the deploy basically works.  But the same Groovy app that can connect via DDP to the Meteor app when running on my MacBook fails to connect via DDP when running on the Ubuntu server.  The DDP connection fails both remotely from my MacBook and locally on the Ubuntu server.  No DDP works at all on the Ubuntu server, as far as I can tell.

To test whether this was an Ubuntu problem or a mup problem, I copied the development sources to the Ubuntu server, effectively making it a meteor development environment.  When I run the meteor app from there, completely unchanged, DDP between Groovy and Meteor works as expected, both locally and remotely.

In addition, I used a Chrome websocket extension and verified that I can connect to the dev version of the Meteor app but not to the mup'ped version.

There is something different between the Meteor app somehow, before and after mup deploy, which interferes with DDP.

BTW, the error I get in Groovy is org.java_websocket.exceptions.WebsocketNotConnectedException.

**Comment by arunoda** [comment]
This is not an issue with MUP. But it's possible such an issue. 
See this: https://github.com/arunoda/meteor-up/issues/100
