### ISSUE TITLE
Cant connect to MongoDB EC2 instance.

### ISSUE THREAD

**Issue by arceduardvincent** [arunoda/meteor-up-legacy#196]
"env": {
    "PORT": 80,
    "ROOT_URL": "http://my.amazon.host.com",
    "Mongo_URL": "mongodb://database.server.ip:27019/mixlinDB"
  },

I tried the details above as my mongo url but i found out in the `mongodb.conf` content was 

```
bind_ip = 127.0.0.1
dbpath=/var/lib/mongodb/
logpath=/var/log/mongodb/mongodb.log
logappend=true
```

It point on the `localhost` but expect it to point what I specified in my Mongo_url or maybe a I am wrong.
Is there any other way that `mup` tool can point my database instance so it will  ensure redundancy and safety in production? 

Thanks

**Comment by arunoda** [comment]
It should be 'MONGO_URL'.
Change that and do `mup reconfig`

**Comment by arceduardvincent** [comment]
Many thanks is figured out that `Mongo_URL` dict is wrong that I define in my `mup.json` the right thing is `MONGO_URL` It is now connecting
I have some error connecting on my database instance but this issue is solved.

**Comment by arceduardvincent** [comment]
I found my answer for the error encounter https://github.com/arunoda/meteor-up/issues/170
