### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by eahefnawy** [arunoda/meteor-up-legacy#197]
I'm using mup for all of my production apps. and it saved me tons of time and energy. I just wanna thank you for this little awesome script that's making our lives much easier, and for all your contributions to the Meteor community. Thank you so much @arunoda and all the awesome contributors :)

You may remove this "issue" now ;)

**Comment by arunoda** [comment]
Ha ha. Thanks for such words.
Without you guys trusting and using these, I won't be not in a situation
like this.

I suggest you to close it :)

**Comment by sclausen** [comment]
:+1: :heart:
