### ISSUE TITLE
mup 2nd deploy of a 2nd instance on same server failed

### ISSUE THREAD

**Issue by riiiiizzzzzohmmmmm** [arunoda/meteor-up-legacy#198]
The info:
- I've got an Ubuntu 12.04 server;
- I have a meteor app developed locally, that I've deployed successfully to this server many times over;
- I have been running that app behind an nginx reverse proxy to handle SSL; has been running fine for quite some time;
- I recently successfully deployed a dev copy of the same app to the same server;
- following the instructions in the meteor-up readme, the dev app has a different mup config with a different appName and is configured to run on a different port;
- once I had successfully deployed the dev, i added another nginx "vhost" to handle SSL for the domain for the dev app;
- both apps are running just fine;
  -however, now i cannot deploy changes to EITHER app.

My guess is that the issue has something to do with fibers. I get some esoteric errors. For example, when running mup logs I get:

node: ../src/coroutine.cc:75: void\* find_thread_id_key(void_): Assertion `thread_data_key' failed.
error: Forever detected script exited with code: null
error: Script restart attempt #1
node: ../src/coroutine.cc:75: void_ find_thread_id_key(void*): Assertion `thread_data_key' failed.
error: Forever detected script exited with code: null
error: Script restart attempt #2 

over and over again.

In the DEBUG output from mup deploy, I see:

stdout: 

> fibers@1.0.3 install /opt/UFCW/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/opt/UFCW/tmp/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
  COPY Release/fibers.node
make: Leaving directory`/opt/UFCW/tmp/bundle/programs/server/node_modules/fibers/build'
Installed in `/opt/UFCW/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
fibers@1.0.3 node_modules/fibers

> bcrypt@0.8.0 install /opt/UFCW/tmp/bundle/programs/server/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/opt/UFCW/tmp/bundle/programs/server/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory`/opt/UFCW/tmp/bundle/programs/server/node_modules/bcrypt/build'
bcrypt@0.8.0 node_modules/bcrypt
├── bindings@1.0.0
└── nan@1.3.0
UFCW stop/waiting
UFCW start/running, process 17949
Waiting for MongoDB to initialize. (5 minutes)
connected
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
UFCW stop/waiting
UFCW start/running, process 18029

Any help appreciated.

**Comment by riiiiizzzzzohmmmmm** [comment]
@arunoda it looks like fibers is failing to build?

**Comment by arunoda** [comment]
Not it's fibers related. But not idea what cause the issue.
But check your node version? We don't support 0.11.x yet!

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by riiiiizzzzzohmmmmm** [comment]
@arunoda when I stopped one of the app instances, I was able to deploy again to the app instance that was still running
