### ISSUE TITLE
Feature Request: Configuration to turn off deploy check

### ISSUE THREAD

**Issue by mccolin** [arunoda/meteor-up-legacy#199]
Having the deploy check in place is excellent, but we're experiencing a handful of apps fail this check intermittently despite successful deploys. It'd be nice to be able to turn it off, either with a separate key in mup.json or perhaps by setting a negative wait time.

**Comment by arunoda** [comment]
It fails means, you app is not bind to the port yet.
You might be doing some migrations like stuff on Meteor.startup
Then increasing the deployWaitTime is the answer.

Unfortunately, I can't accept a feature like this.

**Comment by mccolin** [comment]
Fair enough. I'll close request.

**Comment by arunoda** [comment]
Thanks.
