### ISSUE TITLE
Curl errors

### ISSUE THREAD

**Issue by Tarang** [arunoda/meteor-up-legacy#2]
Originally from http://stackoverflow.com/questions/20585696/performing-mup-deploy-a-second-time-crashes-meteor-js

I'm not too sure if its a meteor-up error or if its from npm

**Comment by dannychua** [comment]
I am also experiencing this error on my first `mup deploy`.

**Comment by arunoda** [comment]
Actually the error is not with fibers. mup check if the site is up after the deploy just waiting 5 secs[0]. Seems like 5 secs is not enough. Specially when database is initializing for the first time. I think I need to come up with a better logic.

Any Ideas?

[0] - https://github.com/arunoda/meteor-up/blob/master/templates/deploy.sh#L44

**Comment by arunoda** [comment]
I can use wait-for-mongo for the first time to wait while db is initializing 
I'll increase the timeout and make it configurable in the `mup.json`

[0] - https://github.com/arunoda/wait-for-mongo

**Comment by arunoda** [comment]
I've added above improvements. Published with version `0.1.7`. Docs for changing wait-time - https://github.com/arunoda/meteor-up#deploy-wait-time

**Comment by arunoda** [comment]
hope this is fixed now : http://goo.gl/ETKMjU

**Comment by miketucker** [comment]
sorry to dig up this issue again, but i'm having this problem with the latest version.

first deploy
30 second delay...

full log:
https://gist.github.com/miketucker/af161995dc479405fb04

**Comment by arunoda** [comment]
Are you doing any special DB initialization which may take more than 30
secs?
Anyway, can you check the logs with *mup logs -n 200 *for any errors

On Tue, Jan 28, 2014 at 1:20 AM, Mike Tucker notifications@github.comwrote:

> sorry to dig up this issue again, but i'm having this problem with the
> latest version.
> 
> first deploy
> 30 second delay...
> 
> full log:
> https://gist.github.com/miketucker/af161995dc479405fb04
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/2#issuecomment-33413436
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by miketucker** [comment]
clearing the local mongo seemed to work, thanks for your reply!

**Comment by arunoda** [comment]
I'm not sure how exactly, it get solved. Anyway, now it works no :)

On Tuesday, January 28, 2014, Mike Tucker notifications@github.com wrote:

> clearing the local mongo seemed to work, thanks for your reply!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/2#issuecomment-33480567
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by ghost** [comment]
Does mup deploy update my existing deployment if I have changed the packages?

**Comment by arunoda** [comment]
Yes. You need to deploy again.

**Comment by applocalizations** [comment]
Does redeployment delete administrative changes in the settings?

2015-02-27 11:34 GMT-08:00 Arunoda Susiripala <notifications@github.com>:

> Yes. You need to deploy again.
>

**Comment by ghost** [comment]
Thanks, it worked like a charm.

2015-02-27 12:18 GMT-08:00 Eric Giannini eric.giannini@fulbrightmail.org:

> Does redeployment delete administrative changes in the settings?
> 
> 2015-02-27 11:34 GMT-08:00 Arunoda Susiripala notifications@github.com:
> 
> Yes. You need to deploy again.
>

**Comment by applocalizations** [comment]
Any ideas on how to make the grid accept 4-5 across?

2015-02-27 12:45 GMT-08:00 Eric Giannini <eric.giannini@fulbrightmail.org>:

> Thanks, it worked like a charm.
>
> 2015-02-27 12:18 GMT-08:00 Eric Giannini <eric.giannini@fulbrightmail.org>
> :
>
> Does redeployment delete administrative changes in the settings?
>>
>> 2015-02-27 11:34 GMT-08:00 Arunoda Susiripala <notifications@github.com>:
>>
>> Yes. You need to deploy again.
>>>
