### ISSUE TITLE
Deployed app reverts to XHR with nginx

### ISSUE THREAD

**Issue by davidrinnan** [arunoda/meteor-up-legacy#200]
I have followed the guideline for proxying traffic via nginx to a mup:d meteor app. To make things simple I have started off with the exact same nginx server settings as in the MUP guide. 

which means I have no root directory or index files declared. apart from logging I only have: 

```
    location / {
    proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
    }
```

nginx version: nginx/1.6.2

I have tried much more elaborate settings for forwarding but without success. 

I get the meteor site working. but with a delay and I always get this warning in the browser console:
    "WebSocket connection to 'ws://xyz/sockjs/131/yb_oya_z/websocket' failed: WebSocket is closed before the connection is established."

and it reverts to xhr. 

Maybe this is not specific to mup but I thought I'd try here first.

**Comment by mmoyles87** [comment]
Do you get the same message: 'WebSocket connection to
'ws://xyz/sockjs/131/yb_oya_z/websocket' failed: WebSocket is closed before
the connection is established.' if you go to the app directly on port 3000
not through nginx?

On Fri, Dec 19, 2014 at 11:27 AM, David Rinnan notifications@github.com
wrote:

> I have followed the guideline for proxying traffic via nginx to a mup:d
> meteor app. To make things simple I have started off with the exact same
> nginx server settings as in the MUP guide.
> 
> which means I have no root directory or index files declared. apart from
> logging I only have:
> 
> ```
> location / {
> proxy_pass http://127.0.0.1:3000;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "Upgrade";
> }
> ```
> 
> nginx version: nginx/1.6.2
> 
> I have tried much more elaborate settings for forwarding but without
> success.
> 
> I get the meteor site working. but with a delay and I always get this
> warning in the browser console:
> WebSocket connection to 'ws://xyz/sockjs/131/yb_oya_z/websocket' failed:
> WebSocket is closed before the connection is established.
> 
> and it reverts to xhr.
> 
> Maybe this is not specific to mup but I thought I'd try here first.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/200.

## 

Matt Moyles
http://mattmoyles.com

**Comment by davidrinnan** [comment]
Only when I proxy pass via nginx. 

I do this all the time but with node+socket.io without issues. 

but I notice that the meteor requst is ws:// so I assume it uses a somewhat different method. 

The proxy pass obviously works, since I can see the site, but it reverts to XHR.

**Comment by strikeout** [comment]
set ENV var `DDP_DEFAULT_CONNECTION_URL` to something like `"ddpi+sockjs://myapp.com:3000/sockjs"`,
to have the websockets not go through the proxy at all (also cool when using cloudflare)

**Comment by davidrinnan** [comment]
We had users who have had problems accessing the meteor app when running on port 3000 due to corporate firewalls. 

This issue must have been related to meteor or sockjs because meteor no longer downgrade to xhr. Websocket is working with the proxying in nginx. I have done nothing but keeping up to the latest upgrades.

**Comment by SantoshSrinivas79** [comment]
@davidrinnan I am having the same problem ... is there a solution that was found for this issue?

**Comment by davidrinnan** [comment]
The thing is that I never did anything. Never changed anything. And suddenly it worked. I assume it is due to sockjs or meteor updates. 

currently I am running the meteor app on app.domain.com and the web on www,domain.com 

in my app.domain.com config I have 

```
    location / {
         proxy_pass http://127.0.0.1:3000;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "Upgrade";
    }
```

**Comment by SantoshSrinivas79** [comment]
Thanks @davidrinnan .. I am not sure what changed but I changed my conf to what you did and my app is now working behind a proxy too!
