### ISSUE TITLE
Problem with Node versions

### ISSUE THREAD

**Issue by micahalcorn** [arunoda/meteor-up-legacy#201]
I upgraded my Meteor app to 1.0.2 today and tried to deploy. The mup logs reveal that `Meteor requires Node v0.10.33 or later`. I ran `npm update mup -g` followed by `DEBUG=* mup setup` and also set `"nodeVersion": "0.10.33"` in my `mup.json`. I can see that `node-v0.10.33-linux-x64.tar.gz.4` is being saved and `Installing Node.js: SUCCESS`. There are _no_ errors thrown by the `setup` command. However the `deploy` still fails with the same output about needing `Node v0.10.33`. I did notice that if I SSH manually and run `node -v` and `which node` I get `v0.10.29` and `/usr/local/bin/node`, neither of which I am expecting. I have had no problems deploying before today. Any suggestions? Thanks!

**Comment by kafechew** [comment]
Unable to mup deploy as well, I think after meteor update to 1.0.2 too. 

```
✘ Invoking deployment process: FAILED

-----------------------------------STDERR-----------------------------------
Dnode_root_dir=/root/.node-gyp/0.10.31',
gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
Latest deployment failed! Reverted back to the previous version.
-----------------------------------STDOUT-----------------------------------
hed
  COPY Release/bcrypt_lib.node
make: Leaving directory `/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

> fibers@1.0.1 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

fibers@1.0.1 node_modules/fibers

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

chalk@0.5.1 node_modules/chalk
├── escape-string-regexp@1.0.2
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)
Waiting for MongoDB to initialize. (5 minutes)
connected
meteor stop/waiting
meteor start/running, process 13354
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
meteor stop/waiting
meteor start/running, process 13480
----------------------------------------------------------------------------
Completed TaskList: Deploy app 'meteor' (linux)
```

**Comment by semikolon** [comment]
Same here. I just got this:

``` bash
[IP address of host removed] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    '-Dnode_root_dir=/root/.node-gyp/0.10.32',
    gyp info spawn args   '-Dmodule_root_dir=/opt/Kaus/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    .node: Finished
      COPY Release/bcrypt_lib.node
```

**Comment by tigransloyan** [comment]
got the same thing

**Comment by tdbs** [comment]
Same issue here

**Comment by benlavalley** [comment]
I was getting this error after updating to 1.0.2 as well. I updated to 0.10.34 on my dev box (I see I may need to downgrade to .33 because of a timers issue), updated the node version in my mup config file to .34, ran npm update -g on my local box and remote boxes, then ran mup setup, and my app deploys OK now.

**Comment by kafechew** [comment]
@nibbl Thanks! Working great :-)

**Comment by arunoda** [comment]
Normally this is the process you've to take.
- update mup.json with the supported nodejs
- then do a `mup setup`

@micahalcorn I assume, your server might have a it's own version of nodejs installed via the packaging system. That may be the issue.

**Comment by tigransloyan** [comment]
@arunoda 's suggestion works for me

**Comment by bitomule** [comment]
I've updated my node version and still get this crash. I've a working version deployed but can deploy the update. Here's my log:

```
-----------------------------------STDERR-----------------------------------
    de_root_dir=/root/.node-gyp/0.10.35',
    gyp info spawn args   '-Dmodule_root_dir=/opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

    > fibers@1.0.1 install /opt/myapp/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── escape-string-regexp@1.0.2
    ├── ansi-styles@1.1.0
    ├── supports-color@0.2.0
    ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
    └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.1 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    myapp stop/waiting
    myapp start/running, process 1971
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    myapp stop/waiting
    myapp start/running, process 1998
    ----------------------------------------------------------------------------
```

**Comment by bitomule** [comment]
Downgraded to Meteor 1.0.1 and deploy is working again.

**Comment by arunoda** [comment]
Check _mup logs -n 400_ also.

**Comment by bitomule** [comment]
Thanks @arunoda,

I've already checked mup logs and I don't see any error (just app logs)

**Comment by arunoda** [comment]
Interesting. Then try to increase deployCheckWaitTime:
https://github.com/arunoda/meteor-up#deploy-wait-time

**Comment by bitomule** [comment]
Fixed! I've increased it to 30 seconds and now I can upload without problems.

**Comment by arunoda** [comment]
Okay great. I hope new Meteor release(or your app) does more things in the
startup.

**Comment by Latnok** [comment]
nmp update and npm update mup
no result

**Comment by Latnok** [comment]
node_root_dir=/root/.node-gyp/0.10.29'

its normal?

**Comment by Dessix** [comment]
It would be nice if the setup-installed node on the servers would be referred to by absolute path rather than just "node" so multiple versions can exist on the same system. I had my system Node version installed (11.x) and the one given by mup setup (10.35 in this case) was not being utilized by the service.

**Comment by PolGuixe** [comment]
@arunoda If I change the nodeVersion in mup.json e.g. from 0.10.31 to 0.10.35, should the node.js version be updated automatically in the server when doing "mup setup"? 

I am deploying to digital ocean and "mup setup" doesn't work on old droplets that had 0.10.31 installed. On a new droplet it actually installed 0.10.35. and "mup deploy" worked no problem.

**Comment by micahalcorn** [comment]
As it turns out I did have a conflicting node version installed in a different location. I didn't understand why the problem only appeared when updating Meteor to 1.0.2+ because I had never had a problem with `mup deploy` on previous versions. I see now that my other node installation's version number was high enough to cover any requirements from previous Meteor versions. It was just confusing because `mup setup` was installing the newer version successfully but `mup deploy` was running the older version from a different location.

I was able to remove the node installation from the location returned by `which node` by following steps similar to [this SO answer](http://stackoverflow.com/questions/5650169/uninstall-node-js-using-linux-command-line). My Meteor app kept running without downtime and I was able to deploy to the updated node version afterward. Thanks so much.

**Comment by MilosStanic** [comment]
ok, I'm deploying to a Ubuntu 14.04 box. 
Tried changing Node version on server, tried changing Node version in mup.json to comply with original version on server. And every time I get this error. 
I also increased waiting time to 60. Same. 
I ran out of ideas.

**Comment by arunoda** [comment]
Try mupx: https://github.com/arunoda/meteor-up/tree/mupx#

**Comment by Clamwinds** [comment]
this problem is killing me, i'll try mupx
