### ISSUE TITLE
bundling error: something's wrong with meteor-tool

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#203]
I have been using Meteor Up for a while now and I would like to thank arunoda and everyone else who contributed for making such an awesome tool! I really love it :+1: 

Recently I just updated an app of mine to Meteor 1.0.2 and also made it open-source (https://github.com/0a-/0a.io). After git cloning it into another directory and adding the file mup.json back with the correct config, I tried to deploy it and encountered this bundling error:

```
eteor-tool/.1.0.37.1v86mkc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:317:26)
  at /Users/archy/.meteor/packages/meteor-tool/.1.0.37.1v86mkc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:536:24
  at runWithEnvironment (/Users/archy/.meteor/packages/meteor-tool/.1.0.37.1v86mkc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:136:21)
  at /Users/archy/.meteor/packages/meteor-tool/.1.0.37.1v86mkc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:143:14
  at /Users/archy/.meteor/packages/meteor-tool/.1.0.37.1v86mkc++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:549:11

/usr/local/lib/node_modules/mup/lib/build.sh: line 42: cd: /tmp/3953cedb-52c8-460a-a521-ef49d5bc6cd1: No such file or directory
tar: bundle: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
```

The app run perfectly fine locally. And I had deployed it to my ec2 successfully a couple of times before. I wonder if I encountered this bundling error because I updated it to 1.0.2, or somehow moving things around caused some misconfiguration.

**Comment by arunoda** [comment]
Seems like a bundling issue.
Could you try one running the meteor app with the upgrade locally and then try to deploy again.

**Comment by ghost** [comment]
I got the same bundling issue.

**Comment by ghost** [comment]
I tried building it locally (instead of running it) and I encountered the same error. It turned out that it was because I used the character ↂ as a variable, which is a valid identifier according to ECMAScript 5.1 (this explains why running it locally is alright) but Meteor threw in an unexpected character error when building it.
