### ISSUE TITLE
Errors while deploying on Centos 7

### ISSUE THREAD

**Issue by qasimzee** [arunoda/meteor-up-legacy#205]
I am getting the following error after entering "mup setup". I am using OSX locally and remote server is on Centos 7

```
Started TaskList: Setup (linux)
[178.79.139.99] - Installing Node.js
[178.79.139.99] ✘ Installing Node.js: FAILED

-----------------------------------STDERR-----------------------------------
Warning: Permanently added '178.79.139.99' (RSA) to the list of known hosts.
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
rm: cannot remove '/var/lib/dpkg/lock': No such file or directory
rm: cannot remove '/var/cache/apt/archives/lock': No such file or directory
sudo: dpkg: command not found
sudo: apt-get: command not found
-----------------------------------STDOUT-----------------------------------
----------------------------------------------------------------------------
Completed TaskList: Setup (linux)
```

**Comment by crapthings** [comment]
mup setup on osx

-----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'xxx.xxx.xxx.xxx' (RSA) to the list of known hosts.
    sudo: sorry, you must have a tty to run sudo
    sudo: sorry, you must have a tty to run sudo
    sudo: sorry, you must have a tty to run sudo
    sudo: sorry, you must have a tty to run sudo
    -----------------------------------STDOUT-----------------------------------
    ----------------------------------------------------------------------------

i've got this on centos 6.6

**Comment by arunoda** [comment]
Sorry. We only support ubuntu atm.

**Comment by aadamsx** [comment]
@crapthings you must remove `Defaults requiretty` as described here: http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password

**Comment by aadamsx** [comment]
@qasimzee I'm having the same issue trying to deploy to Red Hat, did you get this resolved?

**Comment by qasimzee** [comment]
I wrote the details on http://www.qasimzeeshan.com/how-to-deploy-meteor-telescope-on-centos/
