### ISSUE TITLE
Error while deploying `Error: Can't find npm module 'xxx'`

### ISSUE THREAD

**Issue by boulaycote** [arunoda/meteor-up-legacy#206]
Meteor 1.0.2.1

nodeVersion 0.10.33 in mup.json

`mup setup`
`mup deploy`

```
✘ Invoking deployment process: FAILED
```

`mup log`

```
Error: Can't find npm module 'Busboy'. Did you forget to call 'Npm.depends' in package.js within the 'npm-container' package?
    at Object.Npm.require (/opt/xxx/app/programs/server/boot.js:117:17)
    at Object.Meteor.npmRequire (packages/npm-container/index.js:2:1)
    at app/lib/router.js:446:23
    at app/lib/router.js:475:3
    at /opt/xxx/app/programs/server/boot.js:175:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/xxx/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/xxx/app/programs/server/boot.js:86:5
error: Forever detected script exited with code: 8
```

This is the error I get in all 12 attempts.

I had not deployed in a while, since meteor 1.0. I tried deploying again with meteor 1.0 and failed. I moved to 1.0.2.1 in an attempt to update the `npm-container` package, thinking the older version might cause the error. I still cannot deploy.

Any idea what is wrong?

Thanks!

**Comment by boulaycote** [comment]
I also have this error during the deployment process

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 50080: Connection refused
    Latest deployment failed! Reverted back to the previous version.
```

**Comment by boulaycote** [comment]
It was all my fault. Locally, a npm package was named differently. I could deploy perfectly after fixing the name.

**Comment by fooying** [comment]
@boulaycote hi, I have encountered the same problem, but I don't understand your final solution

**Comment by fooying** [comment]
I have find reason, I developed environment is MAC, and then deploy in Ubuntu。
Note that the error tip, can't find Busboy, capital B
I use this in code

```
Busboy = Meteor.npmRequire('Busboy')
```

and try modify to 

```
Busboy = Meteor.npmRequire('busboy')
```

All the problems are solved.

**Comment by pdiniz13** [comment]
Fooying thnx for the post, exactly the issue I was having and that fixed it.
