### ISSUE TITLE
Deployment false failure alert if PORT isn't 80

### ISSUE THREAD

**Issue by mugli** [arunoda/meteor-up-legacy#21]
Hi,
meteor-up deployment gives a false alert that `app didn't pick up` if I use a different port than 80 in env variable, like this:

```
   "env": {
          "PORT": 3000
   } 
```

I have found the source of the problem. It is coming from the last line of `templates/deploy.sh`:

```
  curl localhost || revert_app
```

Maybe you need to check if a different $PORT has been used there and call curl with that complete url. Assigning 80 if nothing is set on $PORT and calling `curl localhost:$PORT || revert_app` would be easier I think.

**Comment by arunoda** [comment]
good one. I'll find a fix.

**Comment by arunoda** [comment]
This is fixed in the never version. (v0.1.10)

**Comment by mugli** [comment]
Great! Thank you!
