### ISSUE TITLE
Escaping issue in env.sh

### ISSUE THREAD

**Issue by msamoylov** [arunoda/meteor-up-legacy#210]
Steps to reproduce:
1. Create a `"MAIL_URL": "smtp://username:(password(@smtp.sendgrid.net:587"` entry with special characters like `()` in mup.json
2. Run `mup deploy`
3. Open `env.sh` and you'll see `export MAIL_URL=smtp://username:(password(@smtp.sendgrid.net:587` throwing `/proc/self/fd/9: 14: config/env.sh: Syntax error: "(" unexpected`

**Comment by arunoda** [comment]
added a fix and released with `v0.7.3`
