### ISSUE TITLE
permission denied error at Configuring upstart

### ISSUE THREAD

**Issue by zevsuld** [arunoda/meteor-up-legacy#211]
After edited mup.json , when running 'mup setup' command having permission denied error.
Running 'mup setup' command as root, or sudo no difference, what is the problem here?
seems like cannot secure copy configuration file, how can I fix this.
Started TaskList: Setup (linux)
[ubuntuserver] - Setting up Environment
[ubuntuserver] ✔ Setting up Environment: SUCCESS
[ubuntuserver] - Configuring upstart
[ubuntuserver] ✘ Configuring upstart: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added 'xxxx.xxxx.xxxx.xxxx' (ECDSA) to the list of known hosts.
scp: /etc/init/myweb.conf: Permission denied
-----------------------------------STDOUT-----------------------------------
----------------------------------------------------------------------------
```

Completed TaskList: Setup (linux)
## mup.json

{
  // Server authentication info
  "servers": [
    {
      "host": "ubuntuserver",
      "username": "user",
      "password": "password"
    }
  ],

  "setupMongo": false,

  "setupNode": false,

  "nodeVersion": "0.10.25",

  "setupPhantom": false,

  "appName": "myweb",

  "app": "/home/user/web",

  // Configure environment
  "env": {
    "ROOT_URL": "http://example.com"

  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 15
}

**Comment by arunoda** [comment]
Log into to the server with the user and try to write to the file location
listed on the logs.

May be it is readonly.

**Comment by boulaycote** [comment]
What user are you deploying with?

`chown` fixes this issue for me as I'm deploying with a user that is not `root` or `su`.

`chown /etc/init/myweb.conf myotheruser`

**Comment by zevsuld** [comment]
Thanks you guys! Manually created folder and files after that changed owner , and successfully deployed. Meteor up rocks :)
