### ISSUE TITLE
Connect to Mongodb on Digital Ocean server after MUP issue

### ISSUE THREAD

**Issue by kafechew** [arunoda/meteor-up-legacy#213]
Deploying to DO using MUP was working great, but I'm having troubles to access the mongodb like normally we did locally (or meteor.com hosted) by using just 

> meteor mongo

According to https://github.com/arunoda/meteor-up/issues/64 , I had tried 

> mongo meteor

But end out

> Failed global initialization: BadValue Invalid or no user locale set. Please ensure LANG and/or LC_\* environment variables are set correctly.

How to solve this?
Thanks!

**Comment by babnik63** [comment]
I'm using digitalocean but no problem now. I have solved something similar by the help of this question on stackoverflow:

[http://stackoverflow.com/questions/26337557/badvalue-invalid-or-no-user-locale-set-please-ensure-lang-and-or-lc-environme](http://stackoverflow.com/questions/26337557/badvalue-invalid-or-no-user-locale-set-please-ensure-lang-and-or-lc-environme)

**Comment by babnik63** [comment]
it may be a better solution
[http://askubuntu.com/questions/536875/error-in-installing-mongo-in-virtual-machine](http://askubuntu.com/questions/536875/error-in-installing-mongo-in-virtual-machine)

**Comment by kafechew** [comment]
Solved! Thanks babnik63 !!!
