### ISSUE TITLE
Failure after install newrelic

### ISSUE THREAD

**Issue by maxlibin** [arunoda/meteor-up-legacy#217]
After I installed newrelic and do mup deploy I get this, any help will be appreciated.

[128.199.211.185] - Uploading bundle
[128.199.211.185] ✔ Uploading bundle: SUCCESS
[128.199.211.185] - Setting up Environment Variables
[128.199.211.185] ✔ Setting up Environment Variables: SUCCESS
[128.199.211.185] - Invoking deployment process
[128.199.211.185] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
.35',
gyp info spawn args   '-Dmodule_root_dir=/opt/watcfy/tmp/bundle/programs/server/npm/vsivsi:file-collection/node_modules/mongodb/node_modules/kerberos',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    make: Leaving directory `/opt/watcfy/tmp/bundle/programs/server/npm/vsivsi:file-collection/node_modules/mongodb/node_modules/kerberos/build'

```
> fibers@1.0.1 install /opt/watcfy/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

fibers@1.0.1 node_modules/fibers

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

chalk@0.5.1 node_modules/chalk
├── escape-string-regexp@1.0.2
├── ansi-styles@1.1.0
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)
```

**Comment by arunoda** [comment]
Get logs from mup logs -n 400 see if there is error.

BTW: try kadira instead of newRelic :) visit https://kadira.io

**Comment by arunoda** [comment]
did you get it fixed?

**Comment by maxlibin** [comment]
problem with package, temporary removed, using kadira instead :+1:

**Comment by arunoda** [comment]
great :)
