### ISSUE TITLE
Feature request: Making nodejs and phantomjs installation optional

### ISSUE THREAD

**Issue by mugli** [arunoda/meteor-up-legacy#22]
Hi,
It would be great if you can make nodejs and phantomjs installation optional, like you already did with mongodb (_I'm curious though, why installing phantomjs mandatory with `mup setup`?_). Some might have node already installed on server or may prefer to use nvm to manage different node versions.

Thanks!

**Comment by arunoda** [comment]
okay, good suggestion. Actually phantomJS is used for spiderable package.
For SEO. Some may might now require it.

On Fri, Jan 31, 2014 at 2:20 AM, Mehdi Hasan Khan
notifications@github.comwrote:

> Hi,
> It would be great if you can make nodejs and phantomjs installation
> optional, like you already did with mongodb (_I'm curious though, why
> installing phantomjs mandatory with mup setup?_). Some might have node
> already installed on server or may prefer to use nvm to manage different
> node versions.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/22
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
Anyway, can you send me a pull request with the change?

**Comment by mugli** [comment]
Sure! I'll make the change on this weekend and send a pull request.

**Comment by arunoda** [comment]
Awesome.

On Fri, Jan 31, 2014 at 4:27 AM, Mehdi Hasan Khan
notifications@github.comwrote:

> Sure! I'll make the change on this weekend and send a pull request.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/22#issuecomment-33744091
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by mugli** [comment]
Do you want me to bump version in package.json or will you do that yourself later (if pull request is accepted)?

**Comment by arunoda** [comment]
I will bump the version.

On Friday, January 31, 2014, Mehdi Hasan Khan notifications@github.com
wrote:

> Do you want me to bump version in package.json or will you do that
> yourself later (if pull request is accepted)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/22#issuecomment-33747042
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by mugli** [comment]
Thanks for accepting the PR. Closing the issue now.
