### ISSUE TITLE
Invoking deployment process: FAILED

### ISSUE THREAD

**Issue by aadamsx** [arunoda/meteor-up-legacy#226]
I'm using Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-3d50120d

When I do a mup deploy I get the following error:

Started TaskList: Deploy app 'formspoint-clients' (linux)
[domain-name.com] - Uploading bundle
[domain-name.com] ✔ Uploading bundle: SUCCESS
[domain-name.com] - Setting up Environment Variables
[domain-name.com] ✔ Setting up Environment Variables: SUCCESS
[domain-name.com] - Invoking deployment process
[domain-name.com] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
//registry.npmjs.org/fibers/-/fibers-1.0.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/source-map-support/-/source-map-support-0.2.8.tgz
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/formspoint-clients/tmp/bundle/programs/server
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/formspoint-clients/tmp/bundle/programs/server/npm-debug.log
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
=> re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
make: Entering directory `/opt/formspoint-clients/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
  COPY Release/bcrypt_lib.node
make: Leaving directory `/opt/formspoint-clients/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
Have you done mup setup?

**Comment by aadamsx** [comment]
yes, I also upgrade to a t2.medium, just to take into account the network error (performance).

Had to do a manual sudo npm install -g node-gyp, and npm config set registry http://registry.npmjs.org

**Comment by arunoda** [comment]
hmm. not sure why node-gyp didn't get installed at the first.

**Comment by aadamsx** [comment]
I just created a new instance, and didn't manually install node-gyp.  Did a mup setup -- it was successful.  then did a mup deploy:

tarted TaskList: Deploy app 'application-name' (linux)
[formspoint.com] - Uploading bundle
[formspoint.com] ✔ Uploading bundle: SUCCESS
[formspoint.com] - Setting up Environment Variables
[formspoint.com] ✔ Setting up Environment Variables: SUCCESS
[formspoint.com] - Invoking deployment process
[formspoint.com] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added 'domain-name.com,ip-address' (RSA) to the list of known hosts.
sudo: node-gyp: command not found
-----------------------------------STDOUT-----------------------------------
=> re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'application-name' (linux)

So should I try to manually install node-gyp with the command sudo npm install -g node-gyp, on the Ubuntu instance manually?

**Comment by arunoda** [comment]
very interesting. What's the ami you've used.

**Comment by arunoda** [comment]
I'll give it a try.

**Comment by aadamsx** [comment]
AMI type:
Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-3d50120d
Ubuntu Server 14.04 LTS (HVM), EBS General Purpose (SSD) Volume Type. Support available from Canonical (http://www.ubuntu.com/cloud/services).

Instance type: t2.small

**Comment by arunoda** [comment]
Ah ah. This might be the issue. We only support Ubuntu at this moment.

**Comment by arunoda** [comment]
But I should give it a try.

**Comment by aadamsx** [comment]
Sorry, I did an edit, I'm using Ubuntu

**Comment by arunoda** [comment]
Okay. Got it.

**Comment by aadamsx** [comment]
Thanks!  I'm kinda stuck without this working... MUP seems to be the defacto deployment option in my situation, is there an alternative way to deploy a Meteor app to a ubuntu-trusty-14.04-amd64-server-20140927 (ami-3d50120d) instance I can use until this gets sorted out?

**Comment by aadamsx** [comment]
mup setup installs node version 0.10.33 (I ssh'd into the server and did a node -v).  my local system (OSX) has node version 0.10.32 (just did a node -v on the command line).  I'm on Meteor 1.0.2.1.  Does this version of Meteor use it's own copy of node?  I thought 1.0.2.1 used node version 0.10.33?

**Comment by cristiandley** [comment]
if you have you own Node version remove it, like:

``` bash
// WARNING: If nodeVersion omitted will setup 0.10.31 by default. Do not use v, only version number.
  "nodeVersion": "0.10.32",
```

I had the same problem, i removed that line then run setup and deploy

**Comment by aadamsx** [comment]
@cristiandley thanks for the help,

You mean remove the reference of it from my mup.json file?  The comment above my "nodeVersion" attribute states:   // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.

So comment out my "nodeVersion": "0.10.33", attribute then?

**Comment by cristiandley** [comment]
@aadamsx  yes, also try using 

``` bash
"setupNode": true,
```

and then run:

``` bash
mup setup && mup deploy
```

**Comment by aadamsx** [comment]
Ok,
(1) created a new Ubuntu instance
(2) assigned the Elastic IP that's linked to my domain
(3) removed "nodeVersion": "0.10.33" attribute from my mup.json file -> made sure "setupMongo": true, "setupNode": true
(4) did a mup setup -> everything installed successfuly
(5) ssh'd into my instanced and did a node -v -> v0.10.33
(6) back on my OSX box -> did a node -v -> v0.10.32
(7) did a mup deploy -> got this error again:

[domain-name.com] - Uploading bundle
[domain-name.com] ✔ Uploading bundle: SUCCESS
[domain-name.com] - Setting up Environment Variables
[domain-name.com] ✔ Setting up Environment Variables: SUCCESS
[domain-name.com] - Invoking deployment process
✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added 'domain-name.com,55.555.5.555' (RSA) to the list of known hosts.
sudo: node-gyp: command not found
-----------------------------------STDOUT-----------------------------------
=> re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
----------------------------------------------------------------------------
```

So, I guess I have node v0.10.32 installed on my OSX box (and node v0.10.33 installed on my amazon instance), but this shouldn't affect my node version for Meteor version 1.2.1, am I right?

My mup.json, where `domain-name.com` is pointing to my Elastic IP assigned to the instance, looks like so:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "domain-name.com",
      "username": "ubuntu",
      // or pem file (ssh based authentication)
      "pem": "/Users/user-name/Meteors/pem-file-name.pem"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Application name (No spaces)
  "appName": "application-name",

  // Location of app (local directory)
  "app": "/Users/user-name/Meteors/application-name",

  // Configure environment
  "env": {
    "ROOT_URL": "http://domain-name.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 30
}
```

**Comment by aadamsx** [comment]
Opened a SO question on this: http://stackoverflow.com/questions/28034984/deploying-meteor-application-with-mup-to-ubuntu-ec2-instance

**Comment by cristiandley** [comment]
Why dont you give a try to DigitalOcean ?... i have 10 vm's with meteor with different Ubuntu versions and no problem at all (production level).

Take a look at my configuration file (im using mongohq):

``` bash
{
  "servers": [
    {
      "host": "111.111.111.111",
      "username": "root",
      "password": "passroot"
    }
  ],
  "setupMongo": false,
  "setupNode": true,
  "setupPhantom": false,
  "appName": "test",
  "app": "/path/for/app",
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://url.com",
    "MONGO_URL": "mongodb://db:dbpass@oceanic.mongohq.com:888/something"
  },
  "deployCheckWaitTime": 15
}
```

**Comment by aadamsx** [comment]
@cristiandley, with Digital Ocean, as far as I know, one cannot install tools on your instance. For example, I need to install PDFtk server (just a command line tool) on my instance.  My Meteor app will call out to this tool to do PDF manipulation.

Am I wrong in thinking this?  Can I install the PDFtk server package on a Digital Ocean Ubuntu 14.\* instance?

$ sudo apt-get install pdftk

Besides, aren't all these VPS providers the same for the most part?  Why would switching over to Digital Ocean help, unless you're implying that AWS somehow is not compatible with Meteor and/or mup?

**Comment by zevsuld** [comment]
I have same issue, asked question here http://stackoverflow.com/questions/28038602/meteor-up-bcrypt-error-on-invoking-deployment-process

**Comment by aadamsx** [comment]
@cristiandley, I contact DigitalOcean support... I will be able to install PDFtk, so I might give them a try now.

What instance did you use?

Did you set up a Nginx server too, if so, do you have a reference I can follow on that?

**Comment by aadamsx** [comment]
I solved this issue.

**Comment by hwrod** [comment]
Fix for me was to set `"setupNode": true`, despite Node already being set up on the server. Also commented out `"nodeVersion"`.

**Comment by robconery** [comment]
@aadamsx Would you be so kind as to share how you solved this? I'm trying each of these solutions with DigitalOcean right now and nothing is working - it's always tripping on the compile of bcrypt. This usually happens when you don't have access to the compile tools but since I'm running as root... that wouldn't make any sense.

I have tried running with no nodeVersion specified, then I tried with the default. Then I tried building another server with Node preinstalled (0.12.3)... nothing. I then tried to `npm install node-gyp` and `bcrypt` - it installed but the deploy still fails.

I've run into this before - where `gyp` causes issues and it almost always has to do with a version clash between Node and the module that's trying to be built.

I'll keep investigating...

**Comment by robconery** [comment]
BTW here's my config:

``` json
{
  "servers": [
    {
      "host": "mymachine.myurl.com",
      "username": "root",
      "pem": "~/.ssh/id_rsa"
    }
  ],
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion" : "0.12.4",
  "setupPhantom": false,
  "enableUploadProgressBar": true,
  "appName": "myapp",
  "app": "/Users/rob/sites/myapp",
  "env": {
    "PORT":"80",
    "ROOT_URL": "http://[my url]"
  },
  "deployCheckWaitTime": 60
}
```

I've tried the above with the node version specified as the default (36), no version specified, `setupNode : false`, etc. 

Here's the error I'm getting on Ubuntu 14.04 running on DigitalOcean:

``` sh
-----------------------------------STDERR-----------------------------------
    R! cwd /opt/myapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
    gyp ERR! node -v v0.12.3
    gyp ERR! node-gyp -v v1.0.3
    gyp ERR! not ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    child_process: customFds option is deprecated, use stdio instead.
    ../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
    ../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (tls == thread_id) {
       ^
    stop: Unknown instance: 
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    src/libcoro/coro.o
      SOLINK_MODULE(target) Release/obj.target/fibers.node
      SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
      COPY Release/fibers.node
    make: Leaving directory `/opt/myapp/tmp/bundle/programs/server/node_modules/fibers/build'
    Installed in `/opt/myapp/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── escape-string-regexp@1.0.3
    ├── ansi-styles@1.1.0
    ├── supports-color@0.2.0
    ├── has-ansi@0.1.0 (ansi-regex@0.2.1)
    └── strip-ansi@0.3.0 (ansi-regex@0.2.1)

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    rocket-shop start/running, process 5053
    Waiting for 60 seconds while app is booting up
    Checking is app booted or not?
    ----------------------------------------------------------------------------
```

**Comment by robconery** [comment]
This is quite confusing :/ - I was running a 1G CPU (the $10/mo machine) and everything failed. I then decided to bump the machine to 2G - I've seen things go south with Node and Rails when resorting to swap files (Discourse comes to mind). 

And it worked.

I don't think this is an issue with mup - it was just trying to compile bcrypt and some other things and (I guess?) ran out of memory or something.

So that's it: use a bigger image (at least 2G).

**Comment by aadamsx** [comment]
I'm glad you got it going.  But in general, no need to install anything on the box extra for mup deployment.

You might also try to changing your nodeVersion setting to this: "nodeVersion": "0.10.36" and do a mup setup/mup deploy again.

**Comment by robconery** [comment]
@aadamsx As mentioned I tried a bunch of different versions of Node - including 36 twice. The solution was a bigger box, for some reason.

**Comment by nickeblewis** [comment]
I had the same issues and like @robconery - I also tried it on a larger instance and it works like a charm via port 3000, though I've yet to try switching it to the main IP but I am sure that will work fine.

**Comment by victorrun** [comment]
@hwrod your solution worked for me as well

**Comment by ennea8** [comment]
@hwrod  it works for me.  Thanks~
I've change several node version 0.12.7/0.12.5/0.10.9, they all don't work.
I found the default node version is 0.10.36

**Comment by mattiLeBlanc** [comment]
I have this issue too, failing deploy with messages about bcrypt. Same as RobConery.
However, I have been deploying successfully (10x maybe) in the last 2 days.
Running free micro instance on AWS, Ubuntu.
Could it be that with every deployment ,temp files are building up and I am running out of diskspace??
I had a demo today...and final deployment ...and then it crashed.
I had to quickly setup new AWS to have demo....sweat was dripping from my spine :) :)

I still have the broken instance, no time for debugging now cause I have a demo in 1 hour. However, I will keep it you want me to look at certain folders for temp data?

**Comment by dospolov** [comment]
Try to update mup.json with Node v0.10.40 
then 
`mup setup`
and 
`mup deploy`

**Comment by sbollampalli** [comment]
Thank you change of Node V0.10.40 worked was struggling with this issue over a day.

**Comment by guillefix** [comment]
Thank you. Change to Node v 0.10.10 worked for me as well! You saved me a day of struggling.

**Comment by dagvonkr** [comment]
Node v 0.10.10 worked here as well, thanks alot!

**Comment by ghost** [comment]
I'm using Digital Ocean, Ubuntu 14.04.4 x64.

! I got it working by resizing the Droplet from 512MB to 1GB ! 

I also:
- updated node and npm to the latest version (1.4.28 npm and v4.4.0 node)
- in my mup.json 
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.40",

**Comment by Deelux** [comment]
w00t! Here it also worked.
Using Digital Ocean, Ubuntu, 14.04.4 x64, 512 MB
Didn't need to resize. All I had to do was change the node version to Node v0.10.40.

Thnk for sharing guys!
