### ISSUE TITLE
NOOB: authentication difficulty deploying to fresh local Vagrant Ubuntu-14.04 machine on Virtualbox

### ISSUE THREAD

**Issue by jononomo** [arunoda/meteor-up-legacy#230]
I am able to deploy to a virtual machine on Digital Ocean without trouble, but when trying to deploy to a Vagrant virtual machine that is running on my MacBook I'm running into SSH authentication issues.

My Vagrantfile has the following:

```
Vagrant.configure(2) do |config|
    config.vm.box = "chef/ubuntu-14.04"
    config.ssh.private_key_path = "~/.ssh/id_rsa"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provider "virtualbox" do |vb|
         vb.memory = "512"
    end
end
```

I am able to bring the Vagrant machine up and I can use `vagrant ssh` to get to its command line, but I can't use Meteor-Up to run the `setup` or `deploy` commands.

I also can't connect to machine with the following command: `ssh root@192.168.33.10` -- it asks me for a password, but won't accept "vagrant" as a password in spite of what I read in these docs: https://docs.vagrantup.com/v2/boxes/base.html

My `mup.json` file is as follows:

``` json
{
  "servers": [
    {
      "host": "192.168.33.10",
      "username": "root",
      "password": "vagrant"
    }
  ],
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.33",
  "setupPhantom": true,
  "appName": "AdVantage",
  "app": "~/dev/sbm/advantage/",
  "env": {
    "ROOT_URL": "http://192.168.33.10"
  },
  "deployCheckWaitTime": 15
}
```

The output I get when I try to do `mup setup` is:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Started TaskList: Setup (linux)
[192.168.33.10] - Installing Node.js
[192.168.33.10] ✘ Installing Node.js: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '192.168.33.10' (RSA) to the list of known hosts.
    Permission denied, please try again.
    -----------------------------------STDOUT-----------------------------------
    ----------------------------------------------------------------------------
Completed TaskList: Setup (linux)
```

I also tried with `mup.json` configured to use `"pem": "~/.ssh/id_rsa"` but it just prompts me for a password when I do that (even though when I generated the SSH I did not add a passphrase) and it won't accept "vagrant".

**Comment by strikeout** [comment]
the new version of vagrant has a command `ssh-config` (outputs OpenSSH valid configuration to connect to the machine) which you give you working credentials to connect

**Comment by redbaron76** [comment]
I just found it yesterday.
In order to use Mup with Vagrant, set your mup.json like this:
(you get the port number and pem path from vagrant ssh-config)

```
// Server authentication info
  "servers": [
    {
      "host": "127.0.0.1",
      "username": "vagrant",
      "pem": <path_where_Vagrantfile_is>/.vagrant/machines/default/virtualbox/private_key",
      "sshOptions": { "Port" : 2200 }
    }
  ],
```
