### ISSUE TITLE
Script to include hidden directories in the deployment bundle

### ISSUE THREAD

**Issue by aadamsx** [arunoda/meteor-up-legacy#232]
I have a hidden folder `/.folder-name` that I use to store pdf files in.  I use a hidden folder so Meteor doesn't restart each time I create a folder or file under it.  

My only issue is that when I deploy using Meteor-up, the bundle never includes the `/.folder-name`.  Not only that, if I manually create the folder structure on my EC2 instance, after I redeploy it actually removes the folder structure.

So I have to find a way to include the folder structure in the Meteor-up deployment bundle.

Is there a script or or some way to include hidden folders (folders that Meteor doesn't watch) in the mup deployment process?

**Comment by arunoda** [comment]
mup uses\* meteor build\* to generate the bundle. It's just like deploying to
meteor.com. So, you can't have that.
It's not a good idea to save data like that.

Use something like slingshot: https://github.com/CulturalMe/meteor-slingshot

**Comment by aadamsx** [comment]
Thanks.
