### ISSUE TITLE
Deploy uncompressed Javascript?

### ISSUE THREAD

**Issue by micahalcorn** [arunoda/meteor-up-legacy#234]
Is there a way to deploy with uncompressed Javascript for client-side debugging? I tried passing `mup deploy --debug` as well as configuring `"meteorBinary": "/usr/local/bin/meteor --debug"` in my mup.json and neither seem to work.

**Comment by maxfriedmann** [comment]
I could also really need this option for debugging on a production like environment, is it planned to support this in the future?

**Comment by arunoda** [comment]
I'm planning for a major upgrade to mup soon. We can have this with that.

**Comment by boustanihani** [comment]
Cool, nice option to have :+1: 

Is this included in **v0.9.2** ??

**Comment by nickjanssen** [comment]
+1, would be really nice to have in order to make deployments to our dev server.

**Comment by joaopiopedreira** [comment]
- 1, really needed!

**Comment by berkaytheunicorn** [comment]
+1

**Comment by micahalcorn** [comment]
Any progress on this? I would pay for this to be solved. :)

**Comment by arunoda** [comment]
Okay. It's here.
It's available on our development version mupx.
See: https://goo.gl/rJn99A

@micahalcorn If you like to pay, purchase a kadira plan or bulletproof meteor :)

**Comment by micahalcorn** [comment]
I can confirm that this now works in mupx.

And yes, I pre-ordered BulletProof last November. :) Thank you!
