### ISSUE TITLE
Error with command sudo npm install -g mup

### ISSUE THREAD

**Issue by leveragepoints** [arunoda/meteor-up-legacy#24]
----------------------- 1: COMMAND ----------------------- 
When I run the command:

sudo npm install -g mup

----------------------- 2: ERROR MESSAGES ----------------------- 
I get the following error messages:

npm ERR! error installing uglify-js@2.3.6
npm ERR! error installing handlebars@1.0.12
npm ERR! error installing nodemiral@0.3.9
npm ERR! error installing mup@0.1.11

----------------------- 3: VERSIONS ----------------------- 
root@droplet1:~#  npm --version
1.1.4

root@droplet1:~#  node --version
v0.6.12

----------------------- 4: FULL OUTPUT ----------------------- 

Here is the full output I get when running the command:

npm http GET http://registry.npmjs.org/mup
npm http 304 http://registry.npmjs.org/mup
npm http GET http://registry.npmjs.org/cjson/0.2.1
npm http GET http://registry.npmjs.org/uuid
npm http GET http://registry.npmjs.org/colors
npm http GET http://registry.npmjs.org/nodemiral
npm http 304 http://registry.npmjs.org/colors
npm http 304 http://registry.npmjs.org/uuid
npm http 304 http://registry.npmjs.org/cjson/0.2.1
npm http 304 http://registry.npmjs.org/nodemiral
npm http GET http://registry.npmjs.org/ejs
npm http GET http://registry.npmjs.org/debug
npm http GET http://registry.npmjs.org/handlebars
npm http 304 http://registry.npmjs.org/handlebars
npm http 304 http://registry.npmjs.org/ejs
npm http 304 http://registry.npmjs.org/debug
npm http GET http://registry.npmjs.org/uglify-js
npm http GET http://registry.npmjs.org/optimist
npm http 304 http://registry.npmjs.org/uglify-js
npm http 304 http://registry.npmjs.org/optimist
npm http GET http://registry.npmjs.org/wordwrap
npm http GET http://registry.npmjs.org/async
npm http GET http://registry.npmjs.org/source-map
npm http 304 http://registry.npmjs.org/wordwrap
npm http 304 http://registry.npmjs.org/async
npm http 304 http://registry.npmjs.org/source-map
npm ERR! error installing uglify-js@2.3.6
npm ERR! error installing handlebars@1.0.12
npm ERR! error installing nodemiral@0.3.9
npm ERR! error installing mup@0.1.11

npm ERR! Error: No compatible version found: source-map@'>=0.1.7- <0.2.0-'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "mup"
npm ERR! cwd /root
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: source-map@'>=0.1.7- <0.2.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm not ok

**Comment by arunoda** [comment]
Seems like you have really old node version. Update to latest.

On Monday, February 3, 2014, paulvieira notifications@github.com wrote:

> ----------------------- 1: COMMAND -----------------------
> When I run the command:
> 
> sudo npm install -g mup
> 
> ----------------------- 2: ERROR MESSAGES -----------------------
> I get the following error messages:
> 
> npm ERR! error installing uglify-js@2.3.6
> npm ERR! error installing handlebars@1.0.12
> npm ERR! error installing nodemiral@0.3.9
> npm ERR! error installing mup@0.1.11
> 
> ----------------------- 3: VERSIONS -----------------------
> root@droplet1:~# npm --version
> 1.1.4
> 
> root@droplet1:~# node --version
> v0.6.12
> 
> ----------------------- 4: FULL OUTPUT -----------------------
> 
> Here is the full output I get when running the command:
> 
> npm http GET http://registry.npmjs.org/mup
> npm http 304 http://registry.npmjs.org/mup
> npm http GET http://registry.npmjs.org/cjson/0.2.1
> npm http GET http://registry.npmjs.org/uuid
> npm http GET http://registry.npmjs.org/colors
> npm http GET http://registry.npmjs.org/nodemiral
> npm http 304 http://registry.npmjs.org/colors
> npm http 304 http://registry.npmjs.org/uuid
> npm http 304 http://registry.npmjs.org/cjson/0.2.1
> npm http 304 http://registry.npmjs.org/nodemiral
> npm http GET http://registry.npmjs.org/ejs
> npm http GET http://registry.npmjs.org/debug
> npm http GET http://registry.npmjs.org/handlebars
> npm http 304 http://registry.npmjs.org/handlebars
> npm http 304 http://registry.npmjs.org/ejs
> npm http 304 http://registry.npmjs.org/debug
> npm http GET http://registry.npmjs.org/uglify-js
> npm http GET http://registry.npmjs.org/optimist
> npm http 304 http://registry.npmjs.org/uglify-js
> npm http 304 http://registry.npmjs.org/optimist
> npm http GET http://registry.npmjs.org/wordwrap
> npm http GET http://registry.npmjs.org/async
> npm http GET http://registry.npmjs.org/source-map
> npm http 304 http://registry.npmjs.org/wordwrap
> npm http 304 http://registry.npmjs.org/async
> npm http 304 http://registry.npmjs.org/source-map
> npm ERR! error installing uglify-js@2.3.6
> npm ERR! error installing handlebars@1.0.12
> npm ERR! error installing nodemiral@0.3.9
> npm ERR! error installing mup@0.1.11
> 
> npm ERR! Error: No compatible version found: source-map@'>=0.1.7- npm
> ERR! Valid install targets:
> npm ERR! ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3"]
> npm ERR! at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
> npm ERR! at next_ (/usr/share/npm/lib/cache.js:438:17)
> npm ERR! at next (/usr/share/npm/lib/cache.js:415:44)
> npm ERR! at /usr/share/npm/lib/cache.js:408:5
> npm ERR! at saved
> (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
> npm ERR! at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
> npm ERR! You may report this log at:
> npm ERR!
> npm ERR! or use
> npm ERR! reportbug --attach /root/npm-debug.log npm
> npm ERR!
> npm ERR! System Linux 3.8.0-29-generic
> npm ERR! command "node" "/usr/bin/npm" "install" "-g" "mup"
> npm ERR! cwd /root
> npm ERR! node -v v0.6.12
> npm ERR! npm -v 1.1.4
> npm ERR! message No compatible version found: source-map@'>=0.1.7-
> <0.2.0-'
> npm ERR! message Valid install targets:
> npm ERR! message ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3"]
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR! /root/npm-debug.log
> npm not ok
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/24
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by leveragepoints** [comment]
Thank you. Worked perfectly!

For future reference here's how updated node.js

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

 Check the running version of Node to verify that it has worked:
node -v

**Comment by arunoda** [comment]
okay. Glad to hear it.

On Tue, Feb 4, 2014 at 1:27 AM, paulvieira notifications@github.com wrote:

> Closed #24 https://github.com/arunoda/meteor-up/issues/24.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/24
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
