### ISSUE TITLE
No ssh agent support?

### ISSUE THREAD

**Issue by danopia** [arunoda/meteor-up-legacy#247]
I just launched an internal app and everyone loves it. But I'm having trouble setting up the deployment on a Jenkins box. Our Jenkins boxes provide the SSH keys for jobs via `ssh-agent` and I don't see any way to tell `mup` to just use the agent.

Am I missing something or is this just not supported yet? I'm content with always using an agent if that's what I have to do, but using the agent key if it's there and otherwise (for development) loading from file is preferable. I just don't want to go against our normal devops practices for an internal app.

**Comment by arunoda** [comment]
Sorry. We don't support that yet!
Frankly, I didn't do any test with that.

**Comment by danopia** [comment]
It's crazy easy to support. You just have to do _nothing_ special when calling SSH.

Adding the key locally: `$ ssh-add ~/.ssh/key.pem` (you'll be password-prompted if there's one)

Then `ssh user@server` just works without any auth steps. I imagine supporting `ssh-agent` shouldn't be hard here.

**Comment by danopia** [comment]
I can PR over the weekend if that's better for you?

**Comment by arunoda** [comment]
Sure. You need to it against our nodemiral npm module. Which does the ssh
logic.

**Comment by danopia** [comment]
Sorry for radio silence. Discovered that as long as the given key file _exists_, meteor up deploys correctly. `ssh` falls back to using the agent by default. I'm not worried about PRing this right now but please keep first-class agent support in mind.

**Comment by queso** [comment]
It looks like something changed here and now ssh keys with passphrases through an error for some reason? What prompted the change? You just broke all my deploys now :)

**Comment by arunoda** [comment]
SSH Agent is back. See: https://goo.gl/SZxCHD

**Comment by queso** [comment]
oh so perfect! Thanks @arunoda!
