### ISSUE TITLE
Uncaught TypeError: Cannot read property 'helpers' of undefined 

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#248]
Deployed Site is displaying Iron-Router Splash page. In the Console there is:
"Uncaught TypeError: Cannot read property 'helpers' of undefined"

The Code (Coffeescript) that throws the Error is not in the App Anymore. I deleted it a few commits ago. It tries to reference a Template that I deleted, too. Yet it is still on the Server.

The Code that throws the Error in the Console starts with this:
!function(){__coffeescriptShare="object"==typeof __coffeescriptShare  ...

The site worked after initial deployment. I don't know what i did wrong.. Maybe the app on the server isn't cleaned sufficently on re-deployment?

Thanks in advance

**Comment by arunoda** [comment]
Could you check logs in the server and see something strange after the
deployment.

Here's the command: _mup logs -n 500_

**Comment by ghost** [comment]
I just deployed again and used the command. This is the output:

"Kadira: completed instrumenting the app"
" >> stepping down to gid: meteoruser"
" >> stepping down to uid: meteoruser"
"Kadira: successfully authenticated"
...

Repeated about 10 Times.

**Comment by arunoda** [comment]
Not sure what's happening.
This is where we store the app:
https://github.com/arunoda/meteor-up#server-setup-details

**Comment by ghost** [comment]
I'll try some more stuff and let you know if it's solved. Thanks for your time.

**Comment by ghost** [comment]
Okay, I reinstalled my server and now it works! Sorry for wasting your time. Cheers!
