### ISSUE TITLE
mup setup error

### ISSUE THREAD

**Issue by rami2929** [arunoda/meteor-up-legacy#253]
Hi,

mup setup is producing error below:
[162.243.141.163] - Installing Node.js
[162.243.141.163] ✘ Installing Node.js: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added '162.243.141.163' (RSA) to the list of known hosts.
Permission denied, please try again.
-----------------------------------STDOUT-----------------------------------
```

Does anyone know how to fix this issue? Your help will be really appreciated.

Thank you

**Comment by davidrinnan** [comment]
Permission denied, the error states. 

I guess MUP is unable to connect to the server properly 
Have you followed the instructions in readme with regards to pre-mup server setup. 

https://github.com/arunoda/meteor-up#ssh-based-authentication

**Comment by rami2929** [comment]
Hi davidrinnan,

Thank you for your reply. It seems like I have correct pre-mup setup...interesting thing is, my other app that is using same server (digital ocean) / different droplet is working well. I can do mup setup & mup deploy on that one, but for some reason, the one I'm trying to setup now is not working...anything I can do here? 

Thank you

**Comment by davidrinnan** [comment]
double check that you can connect the same way as stated in the mup.json, but manually via terminal. Also double check that you when connected via ssh to the server dont have to provide password when you write 
sudo ls

**Comment by rami2929** [comment]
Hi davidrinnan,

Thank you so much for your reply. I completely forgot that I have to authenticate via ssh first time. This article resolved my problem:
https://www.digitalocean.com/community/tutorials/how-to-connect-to-your-droplet-with-ssh

Really appreciated. You saved my day =)
