### ISSUE TITLE
StackOverflow questions

### ISSUE THREAD

**Issue by dandv** [arunoda/meteor-up-legacy#260]
A number of SO questions haven't been answered. Thought I'd bring them to your attention, maybe it's easy to point the users in the right direction:

https://stackoverflow.com/questions/28437442/how-can-i-install-meteor-up-mup-correctly

**Comment by arunoda** [comment]
Let me see.

**Comment by arunoda** [comment]
Hey I tried answering a few questions. Our issue tracker is also very
active.
If there is no solution, ask them to post it on the issue list too.

**Comment by dandv** [comment]
Thanks!
