### ISSUE TITLE
nginx configuration for ssl

### ISSUE THREAD

**Issue by chinna789** [arunoda/meteor-up-legacy#262]
I'm pretty new to these ssl and deployments so my question may be dumb?
Do we need nginx config if you install ssl with mup?

I have this config in my server,what is the path for ssl certificate or we don't need it?

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
  listen 80;
  server_name abc.com www.abc.com;
  rewrite ^ https://$server_name$request_uri? permanent;
}

server {
  listen 443;
  server_name abc.com www.abc.com;

  ssl on;
  ssl_certificate /etc/nginx/ssl/fexfree.crt;
  ssl_certificate_key /etc/nginx/ssl/server.key;

  location = /favicon.ico {
    root /opt/sss/app/programs/web.browser/app;
    access_log off;
    expires 1w;
  }

  location ~* "^/[a-z0-9]{40}\.(css|js)$" {
    root /opt/sss/app/programs/web.browser;
    access_log off;
    expires max;
  }

  location ~ "^/packages" {
    root /opt/sss/app/programs/web.browser;
    access_log off
}
  location / {
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto http;
    proxy_set_header X-Nginx-Proxy true;
    proxy_redirect off;
  }
  ssl_stapling on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 5m;
  ssl_prefer_server_ciphers on;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  add_header Strict-Transport-Security "max-age=31536000;";

}
```

**Comment by arunoda** [comment]
You don't need to use nginx for SSL.
We've our own way of enabling [SSL support](http://goo.gl/FOip8i).

I hope it has the all the info you need.

**Comment by chinna789** [comment]
so setting the url to https://app.com will enable the ssl certificate. If that is it , It is awesome

**Comment by arunoda** [comment]
Oh no. You need to first get a SSL certificate for that URL and do some configurations. For that follow this [guide](http://goo.gl/FOip8i).

**Comment by chinna789** [comment]
yeah I have ssl certificate and built the .pem file using the guide you provided

**Comment by arunoda** [comment]
Okay. Then just set the pem file location as mentioned on guide in
`mup.json` and do a mup setup.
That's all.
You need to have the latest version of  mup.

**Comment by chinna789** [comment]
I'm doing it right now, thanks for the quick replies

**Comment by arunoda** [comment]
Okay. Let me know how it goes.

**Comment by chinna789** [comment]
sure,one more question, no need of `mup deploy` if I'm doing it only for ssl?

**Comment by arunoda** [comment]
If you've already deployed your app with `mup deploy` earlier. No need to
do that again.

**Comment by chinna789** [comment]
Done, it's working fine for me. Thankyou so much for this package. making lot of things easier for the guys like me.

**Comment by arunoda** [comment]
Awesome.

**Comment by ghost** [comment]
I would like to thank you for this package too :)

**Comment by micahalcorn** [comment]
+1 thanks again @arunoda.

I was already running a fairly complicated Nginx proxy, so I have added the standard SSL configuration there. My app is deploying fine and handling https traffic without using a ssl.pem file or making any changes to my mup.config. Is there any reason why I should mess with this?

**Comment by arunoda** [comment]
If you are doing fine with nginx, there is no reason to go with meteor up's
ssl.
