### ISSUE TITLE
CloudFlare and flexible SSL

### ISSUE THREAD

**Issue by timothyarmes** [arunoda/meteor-up-legacy#263]
Hi,

Have you by any chance tested your new SSL support with a combination of a self-signed certificate on the server and cloud flare set up with full (not strict) SSL?

**Comment by arunoda** [comment]
No. I didn't check that. I hope simply changing the SSL config to "full" it'll work.

**Comment by timothyarmes** [comment]
I can confirm that a self-signed certificate uploaded using mup works perfectly well with ClouFlare's "Full SSL" mode.

**Comment by arunoda** [comment]
Awesome.
