### ISSUE TITLE
Revoke http access

### ISSUE THREAD

**Issue by timothyarmes** [arunoda/meteor-up-legacy#267]
Using mup I have now added SSL support to my deployment.

Is it possible to disable non-ssl access? If so, would doing so break cluster?

**Comment by arunoda** [comment]
There is a package on meteor called force-ssl. Add that. It's a core
package.

**Comment by timothyarmes** [comment]
It won't break cluster?

**Comment by arunoda** [comment]
No it simply do a https redirect.
