### ISSUE TITLE
mup deploy hangs without error

### ISSUE THREAD

**Issue by miri-am** [arunoda/meteor-up-legacy#272]
mup deploy stays forever at console output `Building Started: <appPath>`. When I try to check the logs with `mup logs -f` it says `cannot open '/var/log/upstart/<appName>.log' for reading: No such file or directory. 

I can deploy the app to meteor.com. I can deploy other apps on my server: mup setup and mup deploy run fine and the log file can be found in `/var/log/upstart/<appName>.log`.

How can I proceed in this situation?

**Comment by arunoda** [comment]
That means your app is not building locally. Try building your app with
`meteor build <dirnam>`

**Comment by miri-am** [comment]
That is not the reason. It builds successfully when building locally. `meteor build <dirname>` gives me a folder with /android, /ios, and `<appname>.tar.gz`. Sorry, forgot to mention this.

**Comment by miri-am** [comment]
@arunoda any hints how I could debug this situation?

**Comment by miri-am** [comment]
it is working now. I am not sure what caused this: removed platforms and added them again, deleted smart files... cannot say. Closing this.

**Comment by prasanth-cubettech** [comment]
If you changed any settings in mup.json, you need to call mup setup to re initialize configuration and run mup deploy
