### ISSUE TITLE
Is it possible to run a custom script after setup or deployment?

### ISSUE THREAD

**Issue by jakobrosenberg** [arunoda/meteor-up-legacy#274]
This would be very appreciated.

**Comment by arunoda** [comment]
Wait. We will soon move into docker based runtime. Then everything will be
possible.

**Comment by jakobrosenberg** [comment]
That sounds great. Do you have an estimate on when this will happen?

And thank you for your efforts in the Meteor community! :)

**Comment by arunoda** [comment]
End of March.
