### ISSUE TITLE
No explanation when local directory is wrong

### ISSUE THREAD

**Issue by wackazong** [arunoda/meteor-up-legacy#277]
When you have an error in your local meteor directory path, there is no error message. The path is displayed, but well, you know how it is:

```
$ DEBUG=* mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: /this/path/is/wrong
Bundling Error: code=-2, error:spawn bash ENOENT
-------------------STDOUT-------------------

-------------------STDERR-------------------
```

**Comment by arunoda** [comment]
Yes. If we can check it a meteor app or not before loading this command.
That's be awesome.

May we can do some checking here:
https://github.com/arunoda/meteor-up/blob/master/lib/config.js#L61

I'd love to see a PR for this.

**Comment by wackazong** [comment]
https://github.com/arunoda/meteor-up/pull/278
