### ISSUE TITLE
Email address as username - Causes incorrect parsing of MongoDB Connection String

### ISSUE THREAD

**Issue by patrickryan79** [arunoda/meteor-up-legacy#28]
Delete me - my apologies for mucking up the page.

**Comment by arunoda** [comment]
Did you get it solved?

On Wednesday, February 26, 2014, ModestGenius notifications@github.com
wrote:

> Closed #28 https://github.com/arunoda/meteor-up/issues/28.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/28
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by patrickryan79** [comment]
Yes, it was simply a user-error, as me being the user who caused the error. :)

**Comment by arunoda** [comment]
ah okay :)

On Wed, Feb 26, 2014 at 11:00 PM, ModestGenius notifications@github.comwrote:

> Yes, it was simply a user-error, as me being the user who caused the
> error. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/28#issuecomment-36151899
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
