### ISSUE TITLE
Cannot "mup deploy", get: "sudo: node-gyp: command not found"

### ISSUE THREAD

**Issue by chrisco23** [arunoda/meteor-up-legacy#282]
I've tried everything I can think of to deploy to a $5 Digital Ocean droplet running Ubuntu 14.04.  I've installed node-gyp via npm, npm -g, sudo npm -g, and at one point even apt-get.  I've removed node and npm completely and let mup handle installing, 0.10.33.

I get:

mup deploy
## Meteor Up: Production Quality Meteor Deployments

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: ..

Started TaskList: Deploy app 'foo' (linux)
[foo] - Uploading bundle
[foo] ✔ Uploading bundle: SUCCESS
[foo] - Setting up Environment Variables
[foo] ✔ Setting up Environment Variables: SUCCESS
[foo] - Invoking deployment process
[foo] ✘ Invoking deployment process: FAILED

```
    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'foo,xxx.xxx.xxx.xxx' (ECDSA) to the list of known hosts.
    sudo: node-gyp: command not found
    -----------------------------------STDOUT-----------------------------------
    => re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
    ---------------------------------------------------------------------------
```

My mup.json looks like the following (host names, IPs, etc. not shown)

{
  // Server authentication info
  "servers": [
    {
      "host": "foo",
      "username": "foouser",
      //"password": "password",
      // or pem file (ssh based authentication)
      "pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.
  "nodeVersion": "0.10.33",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Application name (No spaces)
  "appName": "foo",

  // Location of app (local directory)
  "app": "..",  // because I am in a foo_staging subdirectory

  // Configure environment
  "env": {
    "PORT": 3001,
    "ROOT_URL": "http://localhost",
    "UPSTART_UID": "foouser" // The user you want to run meteor as.
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 60
}

**Comment by arunoda** [comment]
I hope you have done mup setup too?

**Comment by chrisco23** [comment]
yes I have done mup setup.  Since my earlier post I have tried it out with
a fresh (but same dist) DO droplet and that deploy is successful.  I'm
still trying to figure out now what's different between my fresh droplet
and the other droplet I've kept current and which runs a half dozen LEMP
sites.  I'd rather keep things on the one droplet if at all possible.

**Comment by arunoda** [comment]
Not sure, may be something with your normal nodejs installation.

**Comment by chrisco23** [comment]
I followed this to remove whatever stuff I had leftover from some old node
setup, and I successfully deployed to my original droplet.  At last.
https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by arunoda** [comment]
Ok. Great.
