### ISSUE TITLE
How to include assets?

### ISSUE THREAD

**Issue by jakobrosenberg** [arunoda/meteor-up-legacy#289]
I have three projects which all use mup. They all have identical mup.json files except for appname, env.port and env.root_url.

In the first project, `/opt/myapp1/app/programs/server/assets/app/` includes all non-hidden files from the meteor root folder.

In the second project, `/opt/myapp2/app/programs/server/assets/app/` only includes files from meteor's private folder.

In the third project, `/opt/myapp3/app/programs/server/assets/app/` doesn't even exist.

I can't for the life of me figure the reason behind this inconsistency. Is there anything I can do have mup include the private folder?

**Comment by arunoda** [comment]
I don't think it's a mup issue. May be the third project's might uses a new Meteor version. That might not have that. (not sure BTW).

**Comment by jakobrosenberg** [comment]
They're all on v. 1.0.3.2. Never the less, thanks for the feedback.
