### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by madshargreave** [arunoda/meteor-up-legacy#292]
When deploying to DigitalOcean I get the following error

Started TaskList: Deploy app 'Tabr' (linux)
[104.131.113.12] - Uploading bundle
[104.131.113.12] ✔ Uploading bundle: SUCCESS
[104.131.113.12] - Setting up Environment Variables
[104.131.113.12] ✔ Setting up Environment Variables: SUCCESS
[104.131.113.12] - Invoking deployment process
[104.131.113.12] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ode_root_dir=/root/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/opt/Tabr/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
stop: Unknown instance: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    App did not pick up! Please check app logs.
    -----------------------------------STDOUT-----------------------------------
    /bcrypt_lib.node
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/Tabr/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/Tabr/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

fibers@1.0.1 node_modules/fibers

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)
Waiting for MongoDB to initialize. (5 minutes)
connected
Tabr start/running, process 11414
Waiting for 30 seconds while app is booting up
Checking is app booted or not?
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'Tabr' (linux)

**Comment by arunoda** [comment]
Check logs with `mup logs -n 400`

**Comment by madshargreave** [comment]
Ah it was because my settings file was called config.json, which resultet in Meteor.settings being undefined. It does however work without problems on my local machine on on meteor servers
