### ISSUE TITLE
Issue with bcrypt

### ISSUE THREAD

**Issue by northcoders-chris** [arunoda/meteor-up-legacy#299]
I have an issue with npm bcrypt. I have tried to follow similar issues but seem to be having no luck.

Building Started: /Users/chrishill/dev/tlfbz

Started TaskList: Deploy app 'lf1uk' (linux)
[95.138.190.64] - Uploading bundle
[95.138.190.64] ✔ Uploading bundle: SUCCESS
[95.138.190.64] - Setting up Environment Variables
[95.138.190.64] ✔ Setting up Environment Variables: SUCCESS
[95.138.190.64] - Invoking deployment process
[95.138.190.64] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ypto_lock_cb(int, int, const char*, int)’ defined but not used [-Wunused-function]
 static void crypto_lock_cb(int mode, int n, const char* file, int line) {
             ^
../src/bcrypt_node.cc:105:22: warning: ‘long unsigned int crypto_id_cb()’ defined but not used [-Wunused-function]
 static unsigned long crypto_id_cb(void) {
                      ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/lf1uk/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
-----------------------------------STDOUT-----------------------------------
=> re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
make: Entering directory `/opt/lf1uk/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
make: Leaving directory `/opt/lf1uk/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
----------------------------------------------------------------------------
```

Meteor is at the latest version and I have asked mup to use node version 0.10.33 and also tried 0.10.36 due to the Meteor change logs.

Thanks!

**Comment by revmen** [comment]
Same issue here.

I removed the accounts-password package and the error message changed to:

```
-----------------------------------STDERR-----------------------------------
    r/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /opt/mergers/tmp/bundle/programs/server/node_modules/fibers
    gyp ERR! node -v v0.12.0
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    Build failed
    npm ERR! Linux 3.13.0-43-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! fibers@1.0.1 install: `node ./build.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the fibers@1.0.1 install script 'node ./build.js'.
    npm ERR! This is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /opt/mergers/tmp/bundle/programs/server/npm-debug.log
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/mergers/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    make: Entering directory `/opt/mergers/tmp/bundle/programs/server/node_modules/fibers/build'
      CXX(target) Release/obj.target/fibers/src/fibers.o
    make: Leaving directory `/opt/mergers/tmp/bundle/programs/server/node_modules/fibers/build'
    ----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
This is an issue with node 0.12

Try to use 0.10.x

Configure it in mup.json and setup again.

**Comment by revmen** [comment]
node -v showed me 0.10.36
I removed node completely on the server and allowed mup to install 0.10.33 and the problem seems to be solved now.

**Comment by northcoders-chris** [comment]
I am also using node 0.10.33 and I have tried 0.10.36 My problem is not solved. I have also removed node from the server and allowed mup to install it

**Comment by arunoda** [comment]
@chrishill627 are you still the above error with `0.12.0` issue on it.
May be try to get a fresh servers without installing anything or try to remove node completely.
Seems like 0.12.0 is still there.

**Comment by northcoders-chris** [comment]
Hi arunoda, Ok I will get a fresh one and reply soon.

**Comment by northcoders-chris** [comment]
Hi Arunoda.

I am up and running now in terms of the deploy errors. I have it opening now but I am getting Spacebars is not defined and process is not defined, obviously nothing is showing up in the page.

Is there another issue to reference? I think this one can be closed but I would like to get past the next one!

**Comment by northcoders-chris** [comment]
I am using cron jobs in my app and they are logging to the server when I look with mup logs just have a completely blanc screen and those errors

**Comment by northcoders-chris** [comment]
Just to add I am also getting data in Kadira just cannot see anything but blanc screen.

**Comment by arunoda** [comment]
Seems like something in your client side package. Just try to debug it
locally by running meteor --production

**Comment by northcoders-chris** [comment]
Awesome, thanks. Unsupported package meteor-stubs was not causing an issue locally but did in production.

**Comment by northcoders-chris** [comment]
Been really helpful thanks
