### ISSUE TITLE
Using existing MongoDB database

### ISSUE THREAD

**Issue by wizonesolutions** [arunoda/meteor-up-legacy#3]
I currently deploy with Meteor.sh, so I already have a database I want to use. Do I simply configure the `MONGO_URL` environment variable?

**Comment by arunoda** [comment]
Yes. That's  working.

On Monday, December 16, 2013, Kevin Kaland wrote:

> I currently deploy with Meteor.sh, so I already have a database I want to
> use. Do I simply configure the MONGO_URL environment variable?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/3
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
