### ISSUE TITLE
SSL errors not being reported

### ISSUE THREAD

**Issue by fongandrew** [arunoda/meteor-up-legacy#304]
I had an error where the SSL pem file provided to mup was incorrect. Naturally, HTTPS didn't work. However, `mup setup` reported no errors:

✔ Installing Stud: SUCCESS
✔ Configuring Stud for Upstart: SUCCESS
✔ Configuring SSL: SUCCESS

I was able to confirm the SSL pem file was the issue by SSH-ing into the server and calling `stud --config=/opt/stud/stud.conf` manually. Fixing the PEM file resolved the issue. Would be nice if MUP could have told me that earlier though.

Was using mup version 0.9.2 to set up a Ubuntu 14.04 server.

**Comment by arunoda** [comment]
Okay. That's a good idea.
I can do that.

**Comment by arunoda** [comment]
Done. Landed with the new version: (0.9.3)

**Comment by yanndebelgique** [comment]
Hi I have also no warnings (updated mup to latest version). I did the command:
stud --config=/opt/stud/stud.conf
and got stuck at this ::
{core} Note: no DH parameters found in /opt/stud/ssl.pem

process got stuck here. The process is not terminating. What am I doing wrong ? I got 2 files from comodo ::

-> COMODORSAAddTrustCA.crt
-> COMODORSADomainValidationSecureServerCA.crt

these are the intermediate certificates right? should I add both or just one?
 @fongandrew what magic did you do to fix it manually :) ?

**Comment by arunoda** [comment]
Check this article:
http://alexnj.com/blog/configuring-a-positivessl-certificate-with-stud.html
You need to append both

**Comment by yanndebelgique** [comment]
Thats what I did :( 
I have to go until here right?
cat alexnj_com.crt PositiveSSLCA2.crt AddTrustExternalCARoot.crt alexnj.com.key > bundle.pem

**Comment by arunoda** [comment]
Hmm. weird.

**Comment by yanndebelgique** [comment]
yup weird. I think it has to do with the fact that stud --config=/opt/stud/stud.conf is not terminating...

**Comment by fongandrew** [comment]
@arunoda That was fast! Thanks. The verification is working for me.

**Comment by fongandrew** [comment]
@yanndebelgique You should have gotten four files from COMODO -- the cert for your domain, two intermediate certificates, and a root certificate. You have to concatenate those with your key in this order (so 5 files total):
- Domain certificate
- COMODORSADomainValidationSecureServerCA.crt
- COMODORSAAddTrustCA.crt
- AddTrustExternalCARoot.crt
- Key

The domain I requested a cert for is *.filegraph.com, so in my case, it looks like this:

`cat STAR_filegraph_com.crt COMODORSADomainValidationSecureServerCA.crt COMODORSAAddTrustCA.crt AddTrustExternalCARoot.crt filegraph.com.key > ssl.pem`

**Comment by yanndebelgique** [comment]
Ok thanks I will try that

**Comment by yanndebelgique** [comment]
no luck :(
dum dum questions :

> I changed the file names i.e. adding a_.. b_.. c_.. in order to remember the cat order. Is this an issue?
> what is the expected output from stud --config=/opt/stud/stud.conf? This process doesn't terminate when I try it on my machine. Is this because my ssl file is misconfigured?
> I've deployed my app before without ssl. Is this a pb?
> the domain name is lightnow.co
> what kind of checks can I do to hunt down my bug?

**Comment by madshargreave** [comment]
@yanndebelgique I'm having the same problem with {core} Note: no DH parameters found in /opt/stud/ssl.pem and the process not terminating

**Comment by yanndebelgique** [comment]
Then they were two :)
Still haven't found the issue

**Comment by fongandrew** [comment]
@yanndebelgique @madshargreave Changing the file names shouldn't be an issue.

If calling `stud --config=/opt/stud/stud.conf` doesn't terminate and you don't see any error messages, that might just mean stud is running as a server (e.g. like how calling `meteor` just runs the meteor server until you kill or interrupt it).

You can call `stud --test --config=/opt/stud/stud.conf` to test SSL configuration and then quit (which is what the latest version of mup does).

I get the "no DH parameters" message too. It means (I think) that there are no Diffie Hellman parameters in your PEM file, which are needed for Perfect Forward Secrecy. If you don't care about or need PFS, then you can ignore this message. Just try connecting to the server in your browser via HTTPS. If it connects, then you're done. If it doesn't, there's probably some issue other than the lack of DH parameters you need to deal with (DNS maybe?).

If you do care about PFS, then you'll need to add DH params to your PEM file. You'll probably also need to edit the stud conf file accordingly (I don't think the one Meteor Up provides has PFS enabled).

Some resources regarding how to do that:
http://security.stackexchange.com/questions/38206/can-someone-explain-a-little-better-what-exactly-is-accomplished-by-generation-o
http://vincent.bernat.im/en/blog/2011-ssl-perfect-forward-secrecy.html
http://baudehlo.com/2013/06/24/setting-up-perfect-forward-secrecy-for-nginx-or-stud/

Note that some of these older blog posts suggest using RC4 as a cipher. RC4 is no longer regarded as secure, so don't do that. I'm not a crypto expert, so I'm not quite comfortable suggesting an alternative myself, but see https://wiki.mozilla.org/Security/Server_Side_TLS.

**Comment by fongandrew** [comment]
FYI: I've created an issue for supporting different ciphers for stud (e.g. for PFS) here:  https://github.com/arunoda/meteor-up/issues/307

**Comment by yanndebelgique** [comment]
ok thank you for the extensive answer!

**Comment by yanndebelgique** [comment]
Ok so now it gives me : stud configuration looks ok.
I'll go look at comodoro's configs and see what  I can change.

**Comment by yanndebelgique** [comment]
so my common name is www.lightnow.co
should this be lightnow.co or is that not the problem?

**Comment by yanndebelgique** [comment]
Me again.
What kind of issues can stud detect and which issue can't it detect?
Also in comodo I got the following :
To help reduce domain name mismatch warnings, we have also included the domain name lightnow.co in your certificate.

**Comment by fongandrew** [comment]
Stud just detects whether your pem file is configured correctly (e.g. in the correct order). I guess it also detects the presence of DH params or lack thereof.

It looks your Comodo cert supports both https://www.lightnow.co and https://lightnow.co. Both seem to work when I visit them in my browser, so you're all set for now.

**Comment by yanndebelgique** [comment]
Halleluya!!!!! thanks man you were super helpful!!!! I love the internet

**Comment by ghost** [comment]
@fongandrew How do I troubleshoot to make sure the mup scripts are properly installing and configuring STUD? I am not even getting the output like yours (below). I am running mup 0.9.7

✔ Installing Stud: SUCCESS
✔ Configuring Stud for Upstart: SUCCESS
✔ Configuring SSL: SUCCESS

Referencing (https://github.com/arunoda/meteor-up/issues/352)
