### ISSUE TITLE
Access database from app1 from second app

### ISSUE THREAD

**Issue by benjamin79** [arunoda/meteor-up-legacy#313]
Hi,

i´d like to use the existing database from app1 in app2. As soon as i add:
'''

```
"MONGO_URL": "mongodb://127.0.0.1:27017/app1",
"MONGO_OPLOG_URL": "mongodb://127.0.0.1:27017/local"
```

'''
I get 502 Bad Gateway. What is the right way to do this?

thanks

p.s using latest version, did everything fresh

**Comment by arunoda** [comment]
Remove oplog url. Mup does not support oplog.

**Comment by benjamin79** [comment]
thanks for the fast answer, but it´s not working. mup logs -f gives me:

```
at /opt/board/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/opt/board/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/opt/board/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/opt/board/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at [object Object].emit (events.js:98:17)
```

Seems like a timeout from looking into server.js. But i don´t know how to debug this. If i use `export MONGO_URL ...` i can start the app with node main.js and the connections works.  From local terminal i can connect with `mongo localhost:27017/app1`Any idea?

**Comment by benjamin79** [comment]
it works now. I´m not sure why, but it could be that the server was under a load and did´t response fast enough.

**Comment by CodeLYQ** [comment]
@benjamin79 
I try to do the similar things, but don't work. I get this : 
Error: failed to connect to [127.0.0.1:27017] . 

Part of my mup.json :  

 // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": false,

 "nodeVersion": "0.10.36",

  // Application name (no spaces).
  "appName": "test",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": "~/webroot/test",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 3002,
    "ROOT_URL": "http://t.mydomain.com",
    "MONGO_URL": "mongodb://127.0.0.1:27017/otherapp"
  },

Any help will be appreciated
