### ISSUE TITLE
Codeship does not fail when `mup deploy` fails

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#324]
In Codeship I have configured deployment via a custom script with the content `mup deploy`. I use mup 0.9.6.

Here is the log of a failing deploy where Codeship still reports success: https://gist.github.com/Sanjo/6c702cd17db1ab5422e7.

How can I make Codeship fail when this happens?

**Comment by arunoda** [comment]
May be we are not sending proper exit codes when deploy failed. Need to
check.

**Comment by arunoda** [comment]
Glad, if you can look at it.
