### ISSUE TITLE
Faster updates if we use git to upload changes

### ISSUE THREAD

**Issue by jaredtmartin** [arunoda/meteor-up-legacy#327]
Right now, it takes along time to deploy an existing project because it is uploading all the files, not just changed files.  Wouldn't it be faster if mup used git and set up a git repo on the server? That way when you deploy, mup would just commit, push the changes to the server, which is very fast, and then rebuild as normal. Wouldn't that speed things up quite a bit?  Using git is always a good idea anyway.

**Comment by arunoda** [comment]
Check this: https://github.com/arunoda/meteor-up/issues/185
