### ISSUE TITLE
Do you have to use the "root" user?

### ISSUE THREAD

**Issue by davidcittadini** [arunoda/meteor-up-legacy#330]
Newbie:  Good security practices say when using ssh we should:
1. Setup a new user with "super user" or root privileges.
2. Add the new user to the "sudo" group
3. Change the ssh config and set PermitRootLogin no
4. Change mup.json for the new user.

Having done this I found that I could not use MUP to deploy/start etc.  However, once I changed the user name in mup.json to "root" (and changed the password) then it worked perfectly (apart from having to enter my password in every step).  So, is there any special reason why MUP must use the "root" user or is there a problem in my configuration/understanding..

Thanks :)

**Comment by arunoda** [comment]
Check here:https://github.com/arunoda/meteor-up/issues/173
