### ISSUE TITLE
meteor up and iron router issue

### ISSUE THREAD

**Issue by nick-preda** [arunoda/meteor-up-legacy#333]
Hi guys,
I'm experimenting some issues deploying the meteor application on my server.
I'm using the iron-router package to create all the pages inside the app.
While the application works perfectly on the local machine in development, after the 'mup deploy' all I see on the webpage is the iron:router error message: 

```
Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});
```

this is happening since yesterday. before everything worked wonderfully.

meteor 1.0.4.2
iron:router 1.0.7

any suggestions?

P.S.: checked the node version inside the mup.json and tried mup setup several times

thanks guys,
cheers

**Comment by MaazAli** [comment]
Have you tried running meteor in production mode on your local machine to see if the error message comes up?

**Comment by jakobloekke** [comment]
I see the same issue. Running `meteor --production` locally works fine.

**Comment by nick-preda** [comment]
in meteor --production iron router gives me the same problem...
any suggestions?

**Comment by MaazAli** [comment]
This becomes more of an iron-router / meteor issue than a meteor-up issue.

**Comment by Flavien-Pensato** [comment]
Someone have a solution? I have the same problem :(

**Comment by ofthewood** [comment]
Same pb. what is the workaround ?

**Comment by Domiserver** [comment]
I have been trying to deploy using "mup setup && mup deploy" for
20 hours without success and many Failed Messages, blogging,
searching. I tried MUPX the beta version by Arunoda /GiTHUB. I
installed manually Node.js and MongoDB- and still MUP does not deploy from my local server.

My VPS Server is a Centos and locally I have a Windows 7.

When I try to send environment variables, installing Docker or any other the action fails.

I also continuosly get the message STDIN: is not a TTY

Any options? Thanks.

**Comment by arunoda** [comment]
Hey, Meteor up only works with Ubuntu.
I think it's on top of the README.

Is it possible for you to get a Ubuntu VM?
Use mupx. It's much stable than this version.

**Comment by Domiserver** [comment]
Arunoda, my apologies. I read it  and somehow it did not hit me until now that you said it.  Thanks so much for replying.

**Comment by ofthewood** [comment]
ok mupx solve the pb.
