### ISSUE TITLE
Problem in Deployment process

### ISSUE THREAD

**Issue by jonxduo** [arunoda/meteor-up-legacy#334]
Hi, sorry for my english.
Your work is very amazing.
But i receive this report:

[178.62.195.14] - Uploading bundle
[178.62.195.14] ✔ Uploading bundle: SUCCESS
[178.62.195.14] - Setting up Environment Variables
[178.62.195.14] ✔ Setting up Environment Variables: SUCCESS
[178.62.195.14] - Invoking deployment process
[178.62.195.14] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
de_root_dir=/root/.node-gyp/0.10.36',
gyp info spawn args   '-Dmodule_root_dir=/opt/MY_APP_NAME/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    se/bcrypt_lib.node
    make: Leaving directory `/opt/MY_APP_NAME/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/MY_APP_NAME/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
MY_APP_NAME stop/waiting
MY_APP_NAME start/running, process 5538
Waiting for 30 seconds while app is booting up
Checking is app booted or not?
MY_APP_NAME stop/waiting
MY_APP_NAME start/running, process 5714
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'MY_APP_NAME' (linux)

why? can you help me?

**Comment by arunoda** [comment]
Check logs. Do this: `mup logs -n 300`

**Comment by jonxduo** [comment]
wow, you have been fast...

Error: FS.Store.FileSystem unable to resolve "~" in path
    at new FS.Store.FileSystem (packages/cfs:filesystem/filesystem.server.js:29:1)
    at app/lib/upload_collection.js:2:14
    at app/lib/upload_collection.js:20:3
    at /opt/territorg/app/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/territorg/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/territorg/app/programs/server/boot.js:116:5
error: Forever detected script exited with code: 8
error: Script restart attempt #188

**Comment by arunoda** [comment]
Try to look into that. May be something with CFS.
Meteor UP may not compatible with CFS for the local filesystem usage.

**Comment by jonxduo** [comment]
can i use cfs:s3 ???

**Comment by arunoda** [comment]
Of course. That won't have any issues. I guess.

**Comment by ddresch** [comment]
Just to confirm meteor-up is compatible with CFS local filesystem, at least I got it working. You need to set the write/read rights accordingly to your meteor-up user settings manually. '~' in your error means it tries to access a user folder which in case of the default mup settings would be the folder of meteoruser. Didn't check it but my guess, it's just a user rights problem.

**Comment by mmoyles87** [comment]
I've always had to chown -R meteoruser:meteoruser /opt/APP_NAME/cfs after deploying to get cfs working correctly.

If you run your app under a different user you'll need to replace meteoruser with that username accordingly.

I have to do this after re-running mup setup but not after re-running mup deploy

**Comment by jonxduo** [comment]
tnx
For this project, I can remove CFS.
but your ways worked (@ddresch @dubvfan87)

**Comment by isAlmogK** [comment]
I'm running into the same issues, But I went ahead and removed the CF File System and added CF Grid but I'm still getting this error any ideas how to fix this 

 @ddresch  what did you do to get this working

**Comment by ddresch** [comment]
@almogdesign as written by @dubvfan87 a simple 'chown -R meteoruser:meteoruser /opt/APP_NAME/cfs' helps in the case of a filesystem rights problem. Your issue seems to be of another nature I guess.
