### ISSUE TITLE
'sudo: no tty present and no askpass program specified'

### ISSUE THREAD

**Issue by victorbstan** [arunoda/meteor-up-legacy#335]
Thanks for the great tool, but I'm stuck at this part of the documentation:

```
When this process is not working you might encounter the following error:

'sudo: no tty present and no askpass program specified'
```

What IS the next step if `this process is not working`? I have followed the previous instructions...

**Comment by mmoyles87** [comment]
Login to your server with the username you are using for mup and try "sudo
-s" Does it dump you into a root prompt without asking for a password?

On Tue, Mar 24, 2015 at 11:28 PM, Victor Stan notifications@github.com
wrote:

> Thanks for the great tool, but I'm stuck at this part of the documentation:
> 
> When this process is not working you might encounter the following error:
> 
> 'sudo: no tty present and no askpass program specified'
> 
> What IS the next step if this process is not working? I have follows the
> previous instructions...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/335.

## 

Matt Moyles
http://mattmoyles.com

**Comment by victorbstan** [comment]
It does ask me for password... 
I thought my user was added to sudoers list, but it wasn't, I added it and now sudo -s doesn't ask for a login. However I still the same error.

**Comment by mmoyles87** [comment]
I think your problem is the sudoers file. Make sure you have replaced the
line, not just added a new line.

# replace this line

%sudo  ALL=(ALL) ALL

# by this line

%sudo ALL=(ALL) NOPASSWD:ALL

On Wed, Mar 25, 2015 at 9:53 AM, Victor Stan notifications@github.com
wrote:

> It does ask me for password...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/335#issuecomment-86037182.

## 

Matt Moyles
http://mattmoyles.com

**Comment by victorbstan** [comment]
Ah, yes it was the file, I edited the %admin group not %sudo. Doh! Thanks, I'll close this.
