### ISSUE TITLE
Deployment failing since recent mup update

### ISSUE THREAD

**Issue by serenitus** [arunoda/meteor-up-legacy#339]
A tail of my remote logs says:

```
ReferenceError: require is not defined
    at app/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/strategies/ping_strategy.js:1:49
    at app/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/strategies/ping_strategy.js:368:3
    at /opt/efs/app/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/efs/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/efs/app/programs/server/boot.js:117:5
error: Forever detected script exited with code: 8
error: Script restart attempt #77
```

wait-for-mongo works just fine on the command line if I ssh into the box.

**Comment by mmoyles87** [comment]
Have you updated  to "nodeVersion": "0.10.36" in your  mup.json file and
re-run mup setup before deploying?

On Thu, Mar 26, 2015 at 5:59 PM, Simon Turvey notifications@github.com
wrote:

> A tail of my remote logs says:
> 
> ReferenceError: require is not defined
>     at app/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/strategies/ping_strategy.js:1:49
>     at app/node_modules/wait-for-mongo/node_modules/mongodb/lib/mongodb/connection/repl_set/strategies/ping_strategy.js:368:3
>     at /opt/efs/app/programs/server/boot.js:222:10
>     at Array.forEach (native)
>     at Function._.each._.forEach (/opt/efs/app/programs/server/node_modules/underscore/underscore.js:79:11)
>     at /opt/efs/app/programs/server/boot.js:117:5
> error: Forever detected script exited with code: 8
> error: Script restart attempt #77
> 
> wait-for-mongo works just fine on the command line if I ssh into the box.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/339.

## 

Matt Moyles
http://mattmoyles.com

**Comment by serenitus** [comment]
Nope! Somehow I'd managed to run `npm install wait-for-mongo` in my local app folder while debugging a connection string issue!

Closing issue. Reason: chronic user error revealing the truth behind the maxim _"The solution to a 2-hour problem will always present itself 30 seconds after posting a github issue and will do so in a such a way as to unmask the poster as a ham-fisted clown."_
