### ISSUE TITLE
Meteor 1.1

### ISSUE THREAD

**Issue by vunguyentuan** [arunoda/meteor-up-legacy#345]
/opt/meteor/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: ENOENT, no such file or directory '/opt/meteor/app/programs/server/npm/meteorhacks_kadira/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/types.js'
    at Object.fs.lstatSync (fs.js:691:18)
    at Object.realpathSync (fs.js:1279:21)
    at tryFile (module.js:142:15)
    at tryExtensions (module.js:150:20)
    at Function.Module._findPath (module.js:185:20)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/meteor/app/programs/server/npm/meteorhacks_kadira/node_modules/request/node_modules/http-signature/node_modules/asn1/lib/ber/index.js:4:13)
error: Forever detected script exited with code: 8
error: Script restart attempt #1

module.js:340
    throw err;
          ^
Error: Cannot find module './programs/server/boot.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/meteor/app/main.js:9:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
error: Forever detected script exited with code: 8

**I'm running node 0.10.36

**Comment by vunguyentuan** [comment]
Look like Kadira package cause that error, but after I remove kadira and deploy again

/opt/meteor/app/programs/server/node_modules/fibers/future.js:245
                        throw(ex);
                              ^
Error: Can't find npm module 'mailgun-js'. Did you forget to call 'Npm.depends' in package.js within the 'gfk_mailgun-api' package?
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:155:17)
    at new constructor (packages/gfk:mailgun-api/mailgun-api.js:14:1)
    at app/server/helpers/email.js:7:27
    at app/server/helpers/email.js:22:3
    at app/server/helpers/email.js:24:3
    at /opt/meteor/app/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:117:5

Also mailgun-js, I'm using meteorhacks/npm

**Comment by elie222** [comment]
Also having problems with Meteor 1.1.1 and the latest mup version.

I get this from mup logs:
error: Script restart attempt #50
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1

I set node to version 0.10.36, but it looks like it didn't update.

✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
_dir=/home/draft/.node-gyp/0.10.33',
gyp info spawn args   '-Dmodule_root_dir=/opt/draftapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 8080: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    elease/bcrypt_lib.node
    make: Leaving directory `/opt/draftapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.5 install /opt/draftapp/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

semver@4.1.0 node_modules/semver

fibers@1.0.5 node_modules/fibers

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)
Waiting for MongoDB to initialize. (5 minutes)
connected
draftapp stop/waiting
draftapp start/running, process 11387
Waiting for 60 seconds while app is booting up
Checking is app booted or not?
draftapp stop/waiting
draftapp start/running, process 11560
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'draftapp' (linux)

**Comment by teknologist** [comment]
Just ssh into your meteor server and install nodejs-0.10.36 manually into /opt/nodejs

That did the trick for me! Hope it helps.

**Comment by elie222** [comment]
thanks. i got it working by running meteor setup, followed my meteor deploy

**Comment by jm4r7in** [comment]
You mean "mup setup" and "mup deploy" ?
