### ISSUE TITLE
Problems with installing Mup on Ubuntu (14.10 64bit)

### ISSUE THREAD

**Issue by thijssmudde** [arunoda/meteor-up-legacy#346]
My meteor app runs smoothly on my localhost. Now I want to use the mup command and push the app to production on a VPS server (running ubuntu).

Running the default command npm install -g mup, returns the following errorcodes:

<pre>
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/bin/mup'
npm ERR! error rolling back  mup@0.9.7 { [Error: EACCES, unlink '/usr/local/bin/mup'] errno: 3, code: 'EACCES', path: '/usr/local/bin/mup' }
npm ERR! Error: EACCES, unlink '/usr/local/bin/mup'
npm ERR!  { [Error: EACCES, unlink '/usr/local/bin/mup'] errno: 3, code: 'EACCES', path: '/usr/local/bin/mup' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mup"
npm ERR! cwd /home/thijs/projects/gridpay
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path /usr/local/bin/mup
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/bin/mup'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/thijs/projects/gridpay/npm-debug.log
npm ERR! not ok code 0
</pre>

Of course, I should run it as sudo:

sudo npm install -g mup gives me the following:

<pre>
/usr/local/bin/mup -> /usr/local/lib/node_modules/mup/bin/mup
mup@0.9.7 /usr/local/lib/node_modules/mup
├── colors@0.6.2
├── underscore@1.7.0
├── async@0.9.0
├── uuid@1.4.2
├── rimraf@2.3.2 (glob@4.5.3)
├── nodemiral@0.3.11 (debug@0.7.4, ejs@0.8.8, handlebars@1.0.12)
└── cjson@0.3.0 (jsonlint@1.6.0)
</pre>

Mup seems to be installed. However, when I try to run any of the mup commands, no result seems to be returned, not even an error message.

I tried the following commands: mup init, mup setup, mup deploy, mup logs, mup -help, mup reconfig.
None seem to work.

Then I tried adding the mup.json & settings.json manually. This didn't help either. I followed the youtube video by sacha and followed the exact same procedure.

**Comment by fullhdpixel** [comment]
Here is the full debug log: http://pastebin.com/4Lnmm4fZ

**Comment by thijssmudde** [comment]
Had an outdated version of node installed:

this thread helped me: http://stackoverflow.com/questions/27727234/sudo-mup-deploy-error
