### ISSUE TITLE
WebSocket connection to 'ws://x.x.x.x/sockjs/383/gzez2mj3/websocket' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by geekyme** [arunoda/meteor-up-legacy#350]
After deploying my meteor app to Digital Ocean using MUP, that console error cropped up. 

Any ideas?

**Comment by geekyme** [comment]
never mind. I realized its just my ISP that is blocking insecure websockets. The solution is to use SSL, or connect to a different ISP (like tethering my phone internet, lol)

**Comment by Dielz98** [comment]
@geekyme how do you know it is your ISP?

**Comment by aa21** [comment]
@geekyme How did you figure out that it's your ISP? I'm using Digital Ocean also. 
@Dielz98 Are you using Digital Ocean?

**Comment by geekyme** [comment]
I forgot. I believe it's just a matter of testing different cases for me
