### ISSUE TITLE
Using meteor up with StartSSL

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#351]
I am trying to install SSL on my existing configuration (mup+DigitalOcean+Ubuntu). I have signed up for a free class 1 SSL certificate from https://www.startssl.com/?app=11&action=regform

How do I proceed? From the documentation here (https://github.com/arunoda/meteor-up#ssl-support), I presume that I can jump straight to the step "Now you need combine SSL certificate(s) with the private key and save it in the mup config directory as ssl.pem. Check this guide to do that."

Is my understanding correct? Thanks!

**Comment by arunoda** [comment]
Yes it is.

**Comment by ghost** [comment]
Cool, one more quick question -- I don't currently have `stud` on my Ubuntu server. How do you recommend I install it? A quick Google search reveals no such `sudo apt-get install stud`

Your recommendation is appreciated. Thanks, dude!

**Comment by arunoda** [comment]
You don't need to install it.
Just configure the mup.json as stated on the docs.

Then call `mup setup`. Then it'll do the trick.

**Comment by ghost** [comment]
I just did 

`cat ssl.crt sub.class1.server.ca.pem ca.pem ssl_decrypted.key > ssl.pem`

and added to mup.json

`"ssl": { "pem": "./ssl.pem" }`

I called `mup setup` and also `mup deploy`, but my site still has no https

I also installed `force-ssl`. The logs showed no errors. Any ideas?

**Comment by ghost** [comment]
Also, when running `mup setup`, I don't see anything about `STUD` or `SSL`:
    - Installing Node.js
    ✔ Installing Node.js: SUCCESS
    - Installing PhantomJS
    ✔ Installing PhantomJS: SUCCESS
    - Setting up Environment
    ✔ Setting up Environment: SUCCESS
    - Copying MongoDB configuration
    ✔ Copying MongoDB configuration: SUCCESS
    - Installing MongoDB
    ✔ Installing MongoDB: SUCCESS
    - Configuring upstart
    ✔ Configuring upstart: SUCCESS

What am I doing wrong?
