### ISSUE TITLE
Error when deploying to EC2

### ISSUE THREAD

**Issue by iwoork** [arunoda/meteor-up-legacy#36]
Not sure what I'm missing here but getting this error when running on our EC2 instance.

```
[54.255.153.149] invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '54.255.153.149' (RSA) to the list of known hosts.
    npm http GET https://registry.npmjs.org/fibers
    npm http 304 https://registry.npmjs.org/fibers
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:80; Connection refused
    reverted back to the previous version due to the latest version didn't pick up!
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.1 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    fibers@1.0.1 node_modules/fibers
    meteor stop/waiting
    meteor start/running, process 13906
    wait for mongo(5 minutes) to initiaze
    connected
    waiting for 15 secs while app is booting up
    checking for app is booted or not?
    meteor stop/waiting
    meteor start/running, process 13939
    ----------------------------------------------------------------------------
Completed TaskList: Deploying App
```

**Comment by arunoda** [comment]
Invoke mup logs and see app logs. You will find something there.

On Friday, April 4, 2014, Efren Macasaet notifications@github.com wrote:

> Not sure what I'm missing here but getting this error when running on our
> EC2 instance.
> 
> [54.255.153.149] invoking deployment process: FAILED
> 
> ```
> -----------------------------------STDERR-----------------------------------
> Warning: Permanently added '54.255.153.149' (RSA) to the list of known hosts.
> npm http GET https://registry.npmjs.org/fibers
> npm http 304 https://registry.npmjs.org/fibers
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> ```
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:80; Connection refused
>     reverted back to the previous version due to the latest version didn't pick up!
>     -----------------------------------STDOUT-----------------------------------
> 
> ```
> > fibers@1.0.1 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
> > node ./build.js
> 
> `linux-x64-v8-3.14` exists; testing
> Binary is fine; exiting
> fibers@1.0.1 node_modules/fibers
> meteor stop/waiting
> meteor start/running, process 13906
> wait for mongo(5 minutes) to initiaze
> connected
> waiting for 15 secs while app is booting up
> checking for app is booted or not?
> meteor stop/waiting
> meteor start/running, process 13939
> ----------------------------------------------------------------------------
> ```
> 
> Completed TaskList: Deploying App
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/36
> .

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by iwoork** [comment]
Didn't see any problem on logs

```
[54.255.153.149] Warning: Permanently added '54.255.153.149' (RSA) to the list of known hosts.
[54.255.153.149] --> schools index mapping completed
--> users index mapping completed
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
--> schools index mapping completed
--> users index mapping completed
--> schools index mapping completed
--> users index mapping completed
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

Any idea why the error it complains earlier saying connection to localhost:80 is refused? Why is it connecting to localhost:80?

**Comment by arunoda** [comment]
If you are doing some initialisation before starting up. Please make sure
they are getting complete before 15 secs.
Or else increase deployCheckWaitTime
https://github.com/arunoda/meteor-up#example-file

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by iwoork** [comment]
This worked! Increased it to 35. Thanks @arunoda

**Comment by ccorcos** [comment]
Hmm. I'm not having the same luck :(
