### ISSUE TITLE
Using external variables or commands in mup.json

### ISSUE THREAD

**Issue by jeroengijsman** [arunoda/meteor-up-legacy#376]
Hi @arunoda,

Im currently working on a meteor app and using meteor up to deploy it to a google compute engine vm.

Mongodb is hosted on Compose so in my mup.json i have the following MONGO_URL...

  `"env": {
    "MONGO_URL": "mongodb://<username>:<password>@somurl",
  }`

The thing is, i don't want to insert the username and password directly in the mup.json and push it to github.

With Compute Engine it is possible to store things in custom metadata and retrieve them using:
`curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/mongourl -H \
"Metadata-Flavor: Google\"`

Is it possible to use a command as MONGO_URL value that wil be executed when running meteor deploy? Somthing like this..

`"MONGO_URL": "curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/mongourl -H \"Metadata-Flavor: Google\""`

**Comment by arunoda** [comment]
Sorry. This the current way.
We have no plans to change how mup.json works.

mup.json is a private file and should not be shared.
Seems like you need to something specific to Google Cloud.
May be you can env. variables directly from it rather than depending with
mup.json.

**Comment by jeroengijsman** [comment]
@arunoda thanks for the quick response!

I already found a different solution :)
Travis automatically deploys the app using mup so thats why i needed the mup.json file in the repo.

With Travis you can encrypt files and let Travis decrypt it when its running the .yml file.
I added the encrypted mup.json file to the repo and my problem is solved!
http://docs.travis-ci.com/user/encrypting-files/

Btw meteor-up is awesome dude :)

**Comment by arunoda** [comment]
Okay. That's good solution.
