### ISSUE TITLE
Can I run multiple mup deploy operations in parallel on one machine?

### ISSUE THREAD

**Issue by meonkeys** [arunoda/meteor-up-legacy#381]
I want to simultaneously deploy 3 different apps from the same machine. Should that work?

The apps deploy to the same remote server, but they're all separate, independent apps. Well, they do share one MongoDB.

Currently, I'm doing:

```
cd app1 && mup deploy > app1-deploy.log 
cd -
cd app2 && mup deploy > app2-deploy.log 
cd -
cd app3 && mup deploy > app3-deploy.log 
cd -
```

I'd like to do this:

```
cd app1 && mup deploy > app1-deploy.log &
cd -
cd app2 && mup deploy > app2-deploy.log &
cd -
cd app3 && mup deploy > app3-deploy.log &
cd -
```

I'll test it regardless, I'm just wondering if `mup` was intended to be used in parallel like this.

**Comment by arunoda** [comment]
Yes. It can do that.

**Comment by meonkeys** [comment]
Cool, thank you!
