### ISSUE TITLE
NOt minify when deploying 

### ISSUE THREAD

**Issue by yanndebelgique** [arunoda/meteor-up-legacy#382]
Hi is it possible to use the --debug flag with mup? if not what can I do to prevent my js file from minifying?
I have a bug that is caused by the minification process.

**Comment by smeijer** [comment]
An option to deploy a unbundled version, would indeed be very much welcome.

**Comment by arunoda** [comment]
It's there. Try mupx.
It's on the mupx branch.

**Comment by smeijer** [comment]
@arunoda nice one. Works great. Thanks!

Guess you can close this issue. _(Even though mupx does not yet ran flawlessly.)_
