### ISSUE TITLE
Error when invoking deployment process 

### ISSUE THREAD

**Issue by AlbinHolmlund** [arunoda/meteor-up-legacy#389]
I get this error while trying to deploy to my server. Deploying worked a few days ago but now it doesn't work anymore.

```
-----------------------------------STDERR-----------------------------------
work_t* req) {
                                   ^
../src/bcrypt_node.cc:429:30: error: expected ‘}’ at end of input
 NODE_MODULE(bcrypt_lib, init);
                              ^
../src/bcrypt_node.cc:80:6: warning: ‘bool {anonymous}::ValidateSalt(const char*)’ defined but not used [-Wunused-function]
 bool ValidateSalt(const char* salt) {
      ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-23-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /opt/buildit/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
-----------------------------------STDOUT-----------------------------------
=> re-installing binary npm module 'bcrypt' of package 'npm-bcrypt'
make: Entering directory '/opt/buildit/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
bcrypt_lib.target.mk:84: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
make: Leaving directory '/opt/buildit/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
```

**Comment by AlbinHolmlund** [comment]
I updated Mup, and now i get another error instead.

```
-----------------------------------STDERR-----------------------------------
"
gyp ERR! cwd /opt/buildit/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
child_process: customFds option is deprecated, use stdio instead.
../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (tls == thread_id) {
   ^
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    node
      SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
      COPY Release/fibers.node
    make: Leaving directory '/opt/buildit/tmp/bundle/programs/server/node_modules/fibers/build'
    Installed in `/opt/buildit/tmp/bundle/programs/server/node_modules/fibers/bin/linux-ia32-v8-3.28/fibers.node`
    underscore@1.5.2 node_modules/underscore

```
semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

fibers@1.0.5 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
buildit stop/waiting
buildit start/running, process 12732
Waiting for 30 seconds while app is booting up
Checking is app booted or not?
buildit stop/waiting
buildit start/running, process 12977
```

**Comment by jaredpalmer** [comment]
Same. Mup no longer works. Just tried on a fresh Digital Ocean instance.

```
 ✘ Invoking deployment process: FAILED

-----------------------------------STDERR-----------------------------------
Dnode_root_dir=/root/.node-gyp/0.10.36',
gyp info spawn args   '-Dmodule_root_dir=/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    hed
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/meteor/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.5 install /opt/meteor/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

fibers@1.0.5 node_modules/fibers

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)
Waiting for MongoDB to initialize. (5 minutes)
connected
meteor stop/waiting
meteor start/running, process 12347
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
meteor stop/waiting
meteor start/running, process 12416
----------------------------------------------------------------------------
```

**Comment by AlbinHolmlund** [comment]
I have now tracked down where the error comes from. It's the accounts-password package that includes npm-bcrypt that causes the error, without it the deployment works. I don't know how to fix it yet tho.

**Comment by arunoda** [comment]
Try to use node version 0.10.36.
Your server has 0.12.x

Change it on the mup.json and do `mup setup`

**Comment by AlbinHolmlund** [comment]
I tried changing the node version now. I still get the same error.

**Comment by AlbinHolmlund** [comment]
Even after i changed the node version i still get the same error, including this line:
gyp ERR! node -v v0.12.2
Is mup for some reason maybe still using the wrong node version?

**Comment by AlbinHolmlund** [comment]
I GOT IT TO WORK!!! FINALLY!!
I apparently had a node version running on the server. By uninstalling that one, and rerunning mup setup i got it to use the correct version of node.

You can uninstall node by following these steps: 
(source: http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x)

To recap, the best way (I've found) to completely uninstall node + npm is to do the following:
1. go to /usr/local/lib and delete any node and node_modules
2. go to /usr/local/include and delete any node and node_modules directory
3. if you installed with brew install node, then run brew uninstall node in your terminal
4. check your Home directory for any local or lib or include folders, and delete any node or node_modules from there
5. go to /usr/local/bin and delete any node executable

You may need to do the additional instructions as well:

sudo rm /usr/local/bin/npm
sudo rm /usr/local/share/man/man1/node.1
sudo rm /usr/local/lib/dtrace/node.d
sudo rm -rf ~/.npm
sudo rm -rf ~/.node-gyp
sudo rm /opt/local/bin/node
sudo rm /opt/local/include/node
sudo rm -rf /opt/local/lib/node_modules
