### ISSUE TITLE
If Mongo fails to start mup still reports success

### ISSUE THREAD

**Issue by yauh** [arunoda/meteor-up-legacy#392]
I had a missing `/etc/mongod.conf`file and therefore mongo would fail to start properly.

in my `mup.json` I have 

```
 "setupMongo": true
```

therefore `mup setup` reports 

```
[192.168.2.69] ✔ Installing MongoDB: SUCCESS
```

However, when performing a `mup deploy` it would pause forever when invoking the deployment.

Steps to reproduce: Deploy to a machine with a local mongo installation. Delete the `/etc/mongod.conf` file and perform another deploy. The deploy will never finish.

Todo: Add a sanity check that mongo can connect as part of the setup/deployment

**Comment by arunoda** [comment]
Actually, we've that check. That's where it's waiting.
It's being set to 5 minutes.
Hope we don't need to have that much.

**Comment by yauh** [comment]
Ah, perhaps I was just too impatient. Anyway, if such a check exists I doubt there is a need for this ticket. It's quite the edge-case afterall ;)

**Comment by arunoda** [comment]
I put 5 minutes because, sometime it's take time to mongo to come alive,
after the initial setup.
Not sure, how to change it.

Anyway, I'm releasing Windows support on monday.
Hope that's a good news for you (for the book actually)

**Comment by yauh** [comment]
I am telling people to use mup. Period. I never said it only exists for linux, so I have virtually no work with that new release of yours :)
Or do you mean it can deploy to Windows now? I though it means deploying from Windows to Solaris and Debian-ish systems.

**Comment by arunoda** [comment]
Yeah! It's from deploying from Windows.
In this weekend, I'm moving the meteor runtime into Docker. So, I don't
need to worry about upstart/systemd stuff.
And it'll reduce a large number of issues we are receiving.
