### ISSUE TITLE
All Mup Commands Cause Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by stolinski** [arunoda/meteor-up-legacy#396]
Even running mup logs gives the same error

```
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)
```

**Comment by arunoda** [comment]
That means the current PORT is utilized. Have you change the name of your
app. If so, try to stop the app before deploying the app with the new name.

**Comment by stolinski** [comment]
What's odd is that this is happening on all Meteor sites I have on several servers. I just did a restart, so no sites are even running.

**Comment by stolinski** [comment]
I can't seem to solve this. I've uninstalled and reinstalled Node & Mup. Absolutely nothing is running. I've tried mup commands on several apps on different servers, ones that have been working just a day ago, nothing. I have no idea how to troubleshoot this any further.

**Comment by stolinski** [comment]
This has been resolved by removing Mup and installing v.0.7.7 I have no idea why v.0.10.5 suddenly stopped working for me.

**Comment by gooderist** [comment]
Experiencing the same issue with v0.10.7. Reverting back to v0.7.7 fixed it for me too.

**Comment by arunoda** [comment]
Are you using some configurations with ssh config file at ~/.ssh/config

**Comment by gooderist** [comment]
This is what I have in my ~/.ssh/config

StrictHostKeyChecking no 
UserKnownHostsFile /dev/null
LogLevel QUIET

Host bitbucket.org
 IdentityFile ~/.ssh/id_rsa

**Comment by rhyslbw** [comment]
Also having the same problem with an old mup deployment running 0.10.7, and can confirm downgrading to 0.7.7 works. @arunoda I've not got anything in ~/.ssh/config

**Comment by arunoda** [comment]
Hmm. How about your internet connection? Is it good?
We use SSH2 and it has a 30 timeout?

**Comment by rhyslbw** [comment]
Connection is fine, I've got 3 other mup setups that are communicating with their servers. I did just change the name of the app, but have since restarted the ubuntu 14.04 server, and removed the old app directory, and tried changing the port env variable in mup.json to 81. It immediately fails on any mup command

I'd blow away the VM and start with a fresh one, but I'm needing this instance as it has a batch of test files I don't want to replace due to upload bandwidth limitations on my end. Is there something I've missed on the server to remove the first installation?

**Comment by arunoda** [comment]
Hmm. Anyway, are you using custom SSH ports other than 22? If so try to
change "Port" to "port".

**Comment by rhyslbw** [comment]
Yep that solved it, thanks for the prompt support @arunoda

**Comment by arunoda** [comment]
No problem. That was an issue from my end :)

**Comment by gooderist** [comment]
That worked for me too, thanks!

**Comment by scsirdx** [comment]
Changed Port to port in .ssh/config, but still got an error (mup 0.10.7)
Tried different versions, and fond that 0.9.7 still works, but 0.10.0 don't. Maybe 'pureJs' commit broke something?

**Comment by elie222** [comment]
Just had the same issue. Changing "Port" to "port" fixed it.

**Comment by mcoenca** [comment]
mup version '0.11.3'. Using mupx.

I have "port 443" in my ~/ssh/.config to get behind my proxy blocking port 22
So, I can `ssh` to my ec2 instance by using regular ssh commands (e.g without `-p 443`).

But still can't use `mupx logs` without getting this error... Any idea ?

**Comment by mcoenca** [comment]
Oops sorry my bad didn't see the "sshOptions": { "port" : 443 }, you can provide in the servers list in mup.json.
