### ISSUE TITLE
Deploy to specific server

### ISSUE THREAD

**Issue by wizonesolutions** [arunoda/meteor-up-legacy#4]
It looks like `mup.json` supports multiple servers, but is it possible to tell it only to deploy to, say, `staging` or `production` somehow? Or will it deploy to all the servers listed?

**Comment by arunoda** [comment]
Use seperate mup projects in diff folders.

On Monday, December 16, 2013, Kevin Kaland wrote:

> It looks like mup.json supports multiple servers, but is it possible to
> tell it only to deploy to, say, staging or production somehow? Or will it
> deploy to all the servers listed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/4
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
If multiple servers provided, it will deploy to all.

**Comment by wizonesolutions** [comment]
Ah, I see. I could use two with the same path to app but different servers. Thanks for the explanation.

**Comment by arunoda** [comment]
exactly.

On Mon, Dec 16, 2013 at 4:45 PM, Kevin Kaland notifications@github.comwrote:

> Closed #4 https://github.com/arunoda/meteor-up/issues/4.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/4
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
