### ISSUE TITLE
mup deploy with shippable 

### ISSUE THREAD

**Issue by ericallard** [arunoda/meteor-up-legacy#402]
Hi! I'm new to this.. on meteor but I like what I see so far!

I'm trying to deploy with Shippable and I have the the foolowing error on the node-progress.js:168!
Seems related to the type of stream used by the docker or the redirection of that stream for the CLOUD admin page.

Any Idea?

INFO From Shippable:
npm install -g mup
/usr/bin/mup -> /usr/lib/node_modules/mup/bin/mup
mup@0.10.6 /usr/lib/node_modules/mup
├── colors@0.6.2
├── underscore@1.7.0
├── async@0.9.0
├── uuid@1.4.2
├── rimraf@2.3.3 (glob@4.5.3)
├── nodemiral@1.0.1 (debug@0.7.4, progress@1.1.5, underscore@1.8.3, ejs@0.8.8, ssh2@0.4.6, handlebars@1.0.12)
├── archiver@0.14.3 (buffer-crc32@0.2.5, lazystream@0.1.0, readable-stream@1.0.33, tar-stream@1.1.4, zip-stream@0.5.1, glob@4.3.5, lodash@3.2.0)
└── cjson@0.3.1 (jsonlint@1.6.0)

[45.55.205.132] - Uploading bundle

/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168
    this.stream.clearLine();
                ^
TypeError: Object #<Socket> has no method 'clearLine'
    at ProgressBar.terminate (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:168:17)
    at ProgressBar.tick (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:91:10)
    at ProgressBar.update (/usr/lib/node_modules/mup/node_modules/nodemiral/node_modules/progress/lib/node-progress.js:157:8)

**Comment by SamuelBolduc** [comment]
+1 for this. Meteor up is a great tool, and using it in a continuous deployment workflow would be great

**Comment by ericallard** [comment]
Thanks Sam!

**Comment by manuel-schoebel** [comment]
+1

**Comment by enaros** [comment]
experiencing the same problem in my dev machine!

**Comment by SamuelBolduc** [comment]
I submitted a pull request (https://github.com/arunoda/meteor-up/pull/407) to Meteor Up to add an option `enableUploadProgressBar` which, when set to `false`, fixes this problem.

**Comment by arunoda** [comment]
PR merged and released a new version.

**Comment by enaros** [comment]
yey! fixed my problem! thanks a lot :)

**Comment by kfatehi** [comment]
I'm getting the same error as OP. `mup` version 0.10.7

**Comment by kfatehi** [comment]
Ah I just noticed the mup.json setting -- thanks!

**Comment by gazzer82** [comment]
Could anyone share there shippable config for this, I'm having some issues getting this to work.

**Comment by SamuelBolduc** [comment]
Here is mine : 

```
build_image: shippableimages/ubuntu1404_nodejs
language: node_js
node_js:
  - 0.10.38
services:
  - openjdk7
before_install:
  - npm install -g mup
install:
  - curl https://install.meteor.com/ | sh
after_success:
  - if [ "$BRANCH" == "qa" ]; then mup setup && mup deploy; fi
```

**Comment by mbabauer** [comment]
This worked great with my Jenkins install.  Thanks for the pull request!
