### ISSUE TITLE
Deploy with mup - get error: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by nathanschacherer** [arunoda/meteor-up-legacy#405]
Tried to deploy Telescope app with mup but get this error:

`Building Started: ,
events.js:85
     throw er; // Unhandled 'error' event
           ^
Error: spawn meteor ENOENT
   at exports._errnoException (util.js:746:11)
   at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
   at child_process.js:1144:20
   at process._tickCallback (node.js:355:11)
   at Function.Module.runMain (module.js:503:11)
   at startup (node.js:129:16)
   at node.js:814:3`

Checked out: `mup logs -f` and got this:

 `[45.55.198.184] tail: [45.55.198.184] cannot open ‘/var/log/upstart/VEG52.log’ for reading[45.55.198.184] : No such file or directory[45.55.198.184]`

Any ideas?

**Comment by arunoda** [comment]
Do you have meteor installed on your system?
If so, what's the OS.

**Comment by nathanschacherer** [comment]
Yes I have meteor installed on my system OS X (10.10.3) - the site loads correct locally and on the demo site.meteor.com

**Comment by arunoda** [comment]
That's why I fear. Seems like meteor command is not available in the path.
May be I need to give absolute path of the meteor command.

If possible, try to edit the lib/build.js file of the repo. I will try to
do some fix.

**Comment by nathanschacherer** [comment]
oops - seems like the only issue was the incorrect app location path - didn't have /Users/name/AppFolder correct - it just deployed correctly now.

**Comment by arunoda** [comment]
Ah okay. We need to check the path and do a proper error message.

**Comment by RRiccio** [comment]
Same issue here. I had the wrong app location path as well. Thanks.

**Comment by KristerV** [comment]
omg shit.. spent hours on this and turns out i had a capital letter where it should not have been.. god damn :D an error message would be uber nice.

**Comment by hems** [comment]
relative path would also be super nice ( :

**Comment by tbbooher** [comment]
ok -- for others looking at this -- make sure your

```
// Location of app (local directory)
  "app": "/Users/foo/Sites/happy",
```

is correct

**Comment by tbbooher** [comment]
would recommend an error if local directory can't be found . . . !

**Comment by hems** [comment]
also relative path would be essential for this, since most of people will find this error when using the project repository in another computer or after moving files around

**Comment by doctoroakin** [comment]
This thread saved me!! Was dealing with this error for days!

**Comment by hems** [comment]
If the string from "path" is going directly to bash, maybe we could hack it using $(PWD) instead of the full path ?

unfortunately i didn't test that, and i'm saying out of my imagination.

**Comment by lakeshorelabs** [comment]
Just to chime in for someone coming here from Meteor on Windows, as tbbooher pointed out, you must specify the path to your app differently than a typical windows path:

i.e. **_C:\Users\foo\Sites\happy**_

Needs to be written in the mup.json file as: 

// Location of app (local directory)
  "app": **_"/Users/foo/Sites/happy"**_,

**Comment by psyfreak** [comment]
actually you can use "." if your mup.json is in your root folder of your app and generally any other relative path...
