### ISSUE TITLE
Copying  Mongodb configuration : failed

### ISSUE THREAD

**Issue by splex7** [arunoda/meteor-up-legacy#411]
Hello. 
Very appreciate to start read it.
I am a guy who want to really want to install small meteor project on AWS EC2. So what i've do ne first is cloning microscope(dicover meteor) from gitHub. And it works well in my Mac local server.
Secondly i signed up AWS and get new EC2 linux instance. 

mup setup 

Node.js installed ! Panthom.js as well. 
It looks working well until
 "copying mongoDB configuration:failed"

But suddenly it failed. 
I googled several times but can not find any soultion. Please just let me know small hint? 
Which part i need to inspect? I dont know at all.

![2015-05-07 12 17 01](https://cloud.githubusercontent.com/assets/12082436/7507966/4abbbd30-f4b3-11e4-8f9c-944c863e5d80.png)

 Thanks for read.

**Comment by CTimmerman** [comment]
Why did you close this issue? Do you have a solution? If so, please post it.

**Comment by superandrew213** [comment]
Change username to "ubuntu" in mup.json fixed it for me.

**Comment by akshaykmr** [comment]
yes use "ubuntu" as username instead of "root"

**Comment by PatrickOfRubiconRealm** [comment]
Still fails for me.

**Comment by MasterJames** [comment]
I believe mupx doesn't have this problem. Maybe try it. If it does then it might reveal something about the problem your having.

I've also submitted a PR with Mongo backup caabilities and various useful tools (but I fear it and 25+ other ones will never be merged). [Maybe there's an albeit difficult way for people to built it for themselves from my branch.]
