### ISSUE TITLE
How is it possible to add a custom Data Volume to docker container

### ISSUE THREAD

**Issue by ddresch** [arunoda/meteor-up-legacy#433]
I'm using the new mupx version of mup, which is working and seems to be way more stable then mup itself cause of the container approach. My question is how to integrate custom Data Volumes parameters to the `config/start.sh` script which is also uploaded on each deploy. I'm pretty new to Docker so maybe I miss another option which makes it easier to add custom parameters to the run command or anything else. 

If this is really the only option it would probably be great to have a kind of additional run parameters  option within the `mup.json` file.

**Comment by arunoda** [comment]
You don't need to add a data volume to meteor container normally, because
it's stateless.
If you are try to save locally, I strongly against that.

Basically, there won't be such api in mup.

**Comment by ddresch** [comment]
OK I also already thought about this :) but at the moment I'm using cfs:filesystem as file storage. So your approach is to use gridfs in general or totally relay on e.g. S3 which is not a option for my current client ;(

**Comment by arunoda** [comment]
You can use gridfs or something like couchdb for store blobs.

**Comment by ddresch** [comment]
Hmm will need to change that, so thanks for your quick response!
