### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by Subha** [arunoda/meteor-up-legacy#437]
I have been trying to use npm install but no luck.

 Any input or suggestions are greatly appreciated

 c:\Program Files npm install oracledb
 npm ERR! tar.unpack untar error C:\Users\user\AppData\Roaming\npm-cache\oracledb\0.2.4\package.tgz
 npm ERR! Windows_NT 6.1.7601
 npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "oracledb"
 npm ERR! node v0.12.2
 npm ERR! npm v2.7.4
 npm ERR! path c:\Program Files\node_modules
 npm ERR! code EPERM
 npm ERR! errno -4048

 npm ERR! Error: EPERM, mkdir 'c:\Program Files\node_modules'
 npm ERR! at Error (native)
 npm ERR! { [Error: EPERM, mkdir 'c:\Program Files\node_modules']
 npm ERR! errno: -4048,
 npm ERR! code: 'EPERM',
 npm ERR! path: 'c:\Program Files\node_modules',
 npm ERR! fstream_type: 'Directory',
 npm ERR! fstream_path: 'c:\Program Files\node_modules\oracledb',
 npm ERR! fstream_class: 'DirWriter',
 npm ERR! fstream_stack:
 npm ERR! [ 'C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:171:23',
 npm ERR! 'C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:46:53',
 npm ERR! 'FSReqWrap.oncomplete (fs.js:95:15)' ] }
 npm ERR!
 npm ERR! Please try running this command again as root/Administrator.
 npm ERR! Windows_NT 6.1.7601
 npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "oracledb"
 npm ERR! node v0.12.2
 npm ERR! npm v2.7.4

 npm ERR! Uncaught, unspecified "error" event.
 npm ERR!
 npm ERR! If you need help, you may report this error at:
 npm ERR! <https://github.com/npm/npm/issues

 npm ERR! Please include the following file with any support request:
 npm ERR! c:\Program Files\npm-debug.log

 c:\Program Files

 I tried the steps from this site:
 https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

 Still could not fix the issue.

 Thank you.

**Comment by arunoda** [comment]
Hi,

This is not a direct meteor up question. You should try to ask this question on stackoverlfow or on meteor forums.
