### ISSUE TITLE
Deploy error on DO Ubuntu 14.04

### ISSUE THREAD

**Issue by dyyce** [arunoda/meteor-up-legacy#438]
Hey,

I have just started to use _mup_ and I am getting this error while trying to deploy my app:

Started TaskList: Deploy app 'cnt' (linux)
[46.101.182.59] - Uploading bundle
[46.101.182.59] - Uploading bundle: SUCCESS
[46.101.182.59] - Setting up Environment Variables
[46.101.182.59] - Setting up Environment Variables: SUCCESS
[46.101.182.59] - Invoking deployment process
[46.101.182.59] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------

npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/type-of
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/type-of
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.32.tgz
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------

> fibers@1.0.5 install /opt/cnt/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

----------------------------------------------------------------------------
```

**Comment by x5engine** [comment]
no, not the same error, seems you have an outdated nodejs version.
i think you should reinstall nodejs to a newer version

**Comment by arunoda** [comment]
You need to use a Ubuntu box which does not have node.
Ubuntu 14.04 is the best choice.

**Comment by arunoda** [comment]
Otherwise choose Mupx with ubuntu 14.04 https://github.com/arunoda/meteor-up/tree/mupx#
It does not have any of these issues.

**Comment by dyyce** [comment]
thx for the reply!
going to check mupx

When I deploy on Ubuntu 14.04 without node on it, I am getting this error:

Started TaskList: Deploy app 'cnt' (linux)
[46.101.182.59] - Uploading bundle
[46.101.182.59] - Uploading bundle: SUCCESS
[46.101.182.59] - Setting up Environment Variables
[46.101.182.59] - Setting up Environment Variables: SUCCESS
[46.101.182.59] - Invoking deployment process
[46.101.182.59] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
sudo: npm: command not found
-----------------------------------STDOUT-----------------------------------
----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
Have you done mup setup?

**Comment by dyyce** [comment]
yes I did `mup setup`.

I have tried _mupx_ now and it works!
