### ISSUE TITLE
Cannot deploy on EC2 Ubntu 14

### ISSUE THREAD

**Issue by x5engine** [arunoda/meteor-up-legacy#439]
Hi, I am trying to deploy to an AWS EC2 Instance running Ubuntu 14.04 64-bit. But I'm getting this error : (yes i'm using mupx)
## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /home/ubuntu/Telescope
Using buildOptions : {}
execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

thanks

**Comment by x5engine** [comment]
same thing goes for mup
same error ? is this a bug from mup or the meteor app ??

**Comment by tonyaom** [comment]
I also have the same problem.

**Comment by arunoda** [comment]
Check you appPath pointing to the correct folder/directory of the local
meteor app.

**Comment by tonyaom** [comment]
Thank you arunoda. appPath is correct

mup setup works well but mup deploy got errorBuilding Started: /todos

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by tonyaom** [comment]
silly me, appPath just miss ~ in the beginning
mup deploy does work now

**Comment by x5engine** [comment]
it's working my bad I just updated the mup and it's working :) thanks
