### ISSUE TITLE
Deploy Error - Ubuntu 14.04 on Azure

### ISSUE THREAD

**Issue by simongroll** [arunoda/meteor-up-legacy#441]
Hi,

I'm using mupx to deploy to Ubuntu 14.04 VM running on Azure.
I'm having the following error: 

```
        gyp ERR! System Linux 3.16.0-37-generic
        gyp ERR! command "node" "/opt/nodejs/lib/node_modules/npm/node_modules/n
ode-gyp/bin/node-gyp.js" "rebuild" "--release"
        gyp ERR! cwd /bundle/bundle/programs/server/node_modules/fibers
        gyp ERR! node -v v0.10.36
        gyp ERR! node-gyp -v v1.0.1
        gyp ERR! not ok
        Build failed
        npm ERR! fibers@1.0.5 install: `node ./build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the fibers@1.0.5 install script.
        npm ERR! This is most likely a problem with the fibers package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./build.js
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls fibers
        npm ERR! There is likely additional logging output above.
        npm ERR! System Linux 3.16.0-37-generic
        npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
        npm ERR! cwd /bundle/bundle/programs/server
        npm ERR! node -v v0.10.36
        npm ERR! npm -v 1.4.28
        npm ERR! code ELIFECYCLE
        npm ERR! not ok code 0
```

mupx logs --tail=50 gives:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[xxx.cloudapp.net] npm ERR!     npm owner ls fibers
[xxx.cloudapp.net] npm ERR! There is likely additional logging output a
bove.
[xxx.cloudapp.net] npm ERR! System Linux 3.16.0-37-generic
[xxx.cloudapp.net] npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
[xxx.cloudapp.net] npm ERR! cwd /bundle/bundle/programs/server
[xxx.cloudapp.net] npm ERR! node -v v0.10.36
[xxx.cloudapp.net] npm ERR! npm -v 1.4.28
[xxx.cloudapp.net] npm ERR! code ELIFECYCLE
[xxx.cloudapp.net] npm ERR! not ok code 0
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No des
cription
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No rep
ository field.
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No REA
DME data
[xxx.cloudapp.net]
[xxx.cloudapp.net] > fibers@1.0.5 install /bundle/bundle/programs/serve
r/node_modules/fibers
[xxx.cloudapp.net] > node ./build.js
[xxx.cloudapp.net]
[xxx.cloudapp.net] gyp ERR! configure error
[xxx.cloudapp.net] gyp ERR! stack Error: Can't find Python executable "
python", you can set the PYTHON env variable.
[xxx.cloudapp.net] gyp ERR! stack     at failNoPython (/opt/nodejs/lib/
node_modules/npm/node_modules/node-gyp/lib/configure.js:103:14)
[xxx.cloudapp.net] gyp ERR! stack     at /opt/nodejs/lib/node_modules/n
pm/node_modules/node-gyp/lib/configure.js:42:11
[xxx.cloudapp.net] gyp ERR! stack     at F (/opt/nodejs/lib/node_module
s/npm/node_modules/which/which.js:43:25)
[xxx.cloudapp.net] gyp ERR! stack     at E (/opt/nodejs/lib/node_module
s/npm/node_modules/which/which.js:46:29)
[xxx.cloudapp.net] gyp ERR! stack     at /opt/nodejs/lib/node_modules/n
pm/node_modules/which/which.js:57:16
[xxx.cloudapp.net] gyp ERR! stack     at Object.oncomplete (evalmachine
.<anonymous>:108:15)
[xxx.cloudapp.net] gyp ERR! System Linux 3.16.0-37-generic
[xxx.cloudapp.net] gyp ERR! command "node" "/opt/nodejs/lib/node_module
s/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
[xxx.cloudapp.net] gyp ERR! cwd /bundle/bundle/programs/server/node_mod
ules/fibers
[xxx.cloudapp.net] gyp ERR! node -v v0.10.36
[xxx.cloudapp.net] gyp ERR! node-gyp -v v1.0.1
[xxx.cloudapp.net] gyp ERR! not ok
[xxx.cloudapp.net] Build failed
[xxx.cloudapp.net]
[xxx.cloudapp.net] npm ERR! fibers@1.0.5 install: `node ./build.js`
[xxx.cloudapp.net] npm ERR! Exit status 1
[xxx.cloudapp.net] npm ERR!
[xxx.cloudapp.net] npm ERR! Failed at the fibers@1.0.5 install script.
[xxx.cloudapp.net] npm ERR! This is most likely a problem with the fibe
rs package,
[xxx.cloudapp.net] npm ERR! not with npm itself.
[xxx.cloudapp.net] npm ERR! Tell the author that this fails on your sys
tem:
[xxx.cloudapp.net] npm ERR!     node ./build.js
[xxx.cloudapp.net] npm ERR! You can get their info via:
[xxx.cloudapp.net] npm ERR!     npm owner ls fibers
[xxx.cloudapp.net] npm ERR! There is likely additional logging output a
bove.
[xxx.cloudapp.net] npm ERR! System Linux 3.16.0-37-generic
[xxx.cloudapp.net] npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
[xxx.cloudapp.net] npm ERR! cwd /bundle/bundle/programs/server
[xxx.cloudapp.net] npm ERR! node -v v0.10.36
[xxx.cloudapp.net] npm ERR! npm -v 1.4.28
[xxx.cloudapp.net] npm ERR! code ELIFECYCLE
[xxx.cloudapp.net] npm ERR! not ok code 0
```

Anything I'm missing?

**Comment by arunoda** [comment]
I'm on it. Will fix this today.

**Comment by psyfreak** [comment]
super :+1:

**Comment by simongroll** [comment]
Great, thanks!

**Comment by arunoda** [comment]
Try deploying via mupx now?

**Comment by simongroll** [comment]
Retried:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Updating configurations (linux)
[xxx.cloudapp.net] - Sending environment variables
[xxx.cloudapp.net] - Sending environment variables: SUCCESS
[xxx.cloudapp.net] - Starting app
[xxx.cloudapp.net] - Starting app: SUCCESS
[xxx.cloudapp.net] - Verifying deployment
[xxx.cloudapp.net] x Verifying deployment: FAILED

        -----------------------------------STDERR-----------------------------------
         from server
          % Total    % Received % Xferd  Average Speed   Time    Time     Time Current
                                         Dload  Upload   Total   Spent    Left Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        curl: (52) Empty reply from server
          % Total    % Received % Xferd  Average Speed   Time    Time     Time Current
                                         Dload  Upload   Total   Spent    Left Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
        curl: (52) Empty reply from server
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data

        > fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
        > node ./build.js

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------
```

mupx logs --tail=50 gives:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[xxx.cloudapp.net]           ^
[xxx.cloudapp.net] Error: `/bundle/bundle/programs/server/node_modules/
fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fib
ers`?
[xxx.cloudapp.net]     at Object.<anonymous> (/bundle/bundle/programs/s
erver/node_modules/fibers/fibers.js:16:8)
[xxx.cloudapp.net]     at Module._compile (module.js:456:26)
[xxx.cloudapp.net]     at Object.Module._extensions..js (module.js:474:
10)
[xxx.cloudapp.net]     at Module.load (module.js:356:32)
[xxx.cloudapp.net]     at Function.Module._load (module.js:312:12)
[xxx.cloudapp.net]     at Module.require (module.js:364:17)
[xxx.cloudapp.net]     at require (module.js:380:17)
[xxx.cloudapp.net]     at Object.<anonymous> (/bundle/bundle/programs/s
erver/boot.js:1:75)
[xxx.cloudapp.net]     at Module._compile (module.js:456:26)
[xxx.cloudapp.net]     at Object.Module._extensions..js (module.js:474:
10)
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No des
cription
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No rep
ository field.
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No REA
DME data
[xxx.cloudapp.net] => Starting meteor app on port:80
[xxx.cloudapp.net]
[xxx.cloudapp.net] /bundle/bundle/programs/server/node_modules/fibers/f
ibers.js:16
[xxx.cloudapp.net]     throw new Error('`'+ modPath+ '.node` is missing
. Try reinstalling `node-fibe
[xxx.cloudapp.net]           ^
[xxx.cloudapp.net] Error: `/bundle/bundle/programs/server/node_modules/
fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fib
ers`?
[xxx.cloudapp.net]     at Object.<anonymous> (/bundle/bundle/programs/s
erver/node_modules/fibers/fibers.js:16:8)
[xxx.cloudapp.net]     at Module._compile (module.js:456:26)
[xxx.cloudapp.net]     at Object.Module._extensions..js (module.js:474:
10)
[xxx.cloudapp.net]     at Module.load (module.js:356:32)
[xxx.cloudapp.net]     at Function.Module._load (module.js:312:12)
[xxx.cloudapp.net]     at Module.require (module.js:364:17)
[xxx.cloudapp.net]     at require (module.js:380:17)
[xxx.cloudapp.net]     at Object.<anonymous> (/bundle/bundle/programs/s
erver/boot.js:1:75)
[xxx.cloudapp.net]     at Module._compile (module.js:456:26)
[xxx.cloudapp.net]     at Object.Module._extensions..js (module.js:474:
10)
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No des
cription
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No rep
ository field.
[xxx.cloudapp.net] npm WARN package.json meteor-dev-bundle@0.0.0 No REA
DME data
[xxx.cloudapp.net] => Starting meteor app on port:80
[xxx.cloudapp.net]
[xxx.cloudapp.net] /bundle/bundle/programs/server/node_modules/fibers/f
ibers.js:16
[xxx.cloudapp.net]     throw new Error('`'+ modPath+ '.node` is missing
. Try reinstalling `node-fibe
[xxx.cloudapp.net]           ^
[xxx.cloudapp.net] Error: `/bundle/bundle/programs/server/node_modules/
fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fib
ers`?
[xxx.cloudapp.net]     at Object.<anonymous> (/bundle/bundle/programs/s
erver/node_modules/fibers/fibers.js:16:8)
[xxx.cloudapp.net]     at Module._compile (module.js:456:26)
[xxx.cloudapp.net]     at Object.Module._extensions..js (module.js:474:
10)
[xxx.cloudapp.net]     at Module.load (module.js:356:32)
[xxx.cloudapp.net]     at Function.Module._load (module.js:312:12)
[xxx.cloudapp.net]     at Module.require (module.js:364:17)
[xxx.cloudapp.net]     at require (module.js:380:17)
[xxx.cloudapp.net]     at Object.<anonymous> (/bundle/bundle/programs/s
erver/boot.js:1:75)
[xxx.cloudapp.net]     at Module._compile (module.js:456:26)
[xxx.cloudapp.net]     at Object.Module._extensions..js (module.js:474:
10)
```

**Comment by arunoda** [comment]
That's pretty weird. Can I know your meteor app's version?

**Comment by arunoda** [comment]
If possible give me a way to reproduce this myown. Then I can work on this closely.

**Comment by simongroll** [comment]
Meteor 1.1.0.2.
Developing on Windows. Could that be an issue?

I can't give you access to VM but I can share source code.

**Comment by arunoda** [comment]
Okay. Share the source code with me.
I'll try to do a mup deploy and find out the case.

**Comment by simongroll** [comment]
As it stands, @arunoda sees this as a Windows issue.
I will attempt the deploy from a local Ubuntu VM and give feedback.

**Comment by psyfreak** [comment]
any update on this issue?

**Comment by simongroll** [comment]
Hi @psyfreak 

I successfully deployed the same source code to the same target Azure VM from Ubuntu.
I can't give technical proof but this confirms suspicion that the issue lies with building Meteor app in Windows.

@arunoda, do you plan to address or should I close?

**Comment by arunoda** [comment]
I think, I need to see try to deploy from Windows. Haven't done that. We
can keep this open until then.

**Comment by psyfreak** [comment]
@simongroll thank you for pointing this out, I will give it a try as well in the next couple of days.
@arunoda I can test your upates if you want, cause winX is my primary dev OS ...

**Comment by arunoda** [comment]
Sure. I'll try to find the bug.

**Comment by simongroll** [comment]
Probably worth noting I _do_ experience an error on deploy, even though it is successul:

```
[x.cloudapp.net] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    regex@0.2.1)

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)

    fibers@1.0.5 node_modules/fibers
    => Starting meteor app on port:80
```

**Comment by arunoda** [comment]
Even with using Ubuntu?

**Comment by simongroll** [comment]
Yes.
Other than that error, the app is deployed correctly.

**Comment by iandfox** [comment]
For whatever it's worth, I have been trying to normal Azure, not even using meteor up, and have not been able to crack this issue. Strangely I get the same errors, even though I'm not doing it on top of an ubuntu VM. Perhaps it's an azure issue?

**Comment by simongroll** [comment]
This is no longer an issue for me.
I am using Mupx 1.4.1 on Ubuntu to build and deploy to my Azure server.

**Comment by mistriel** [comment]
Still a big issue for me, getting the same error on windows .

[178.62.192.37] x Invoking deployment process: FAILED

```
    -----------------------------------STDERR-----------------------------------
    R! System Linux 3.13.0-37-generic
    gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    gyp ERR! cwd /opt/todos-app/tmp/bundle/programs/server/node_modules/fibers
    gyp ERR! node -v v0.10.40
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok
    Build failed

    npm ERR! fibers@1.0.5 install: `node ./build.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the fibers@1.0.5 install script.
    npm ERR! This is most likely a problem with the fibers package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./build.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls fibers
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-37-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! cwd /opt/todos-app/tmp/bundle/programs/server
    npm ERR! node -v v0.10.40
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.5 install /opt/todos-app/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    ----------------------------------------------------------------------------
```

Please assist ASAP .

**Comment by simongroll** [comment]
Hi @mistriel 

Please note I didn't find success in deploying from Windows.
I suggest deploying from an Ubuntu VM on VirtualBox until Windows deployments are 100%.

**Comment by CodeLYQ** [comment]
The same issue even with using Ubuntu! I'm using mupx.

**Comment by simongroll** [comment]
@phoue, can you paste the error logs?

**Comment by CodeLYQ** [comment]
Started TaskList: Deploy app 'yizhema' (linux)
[120.62.112.151] - Uploading bundle
[120.62.112.151] - Uploading bundle: SUCCESS
[120.62.112.151] - Sending environment variables
[120.62.112.151] - Sending environment variables: SUCCESS
[120.62.112.151] - Initializing start script
[120.62.112.151] - Initializing start script: SUCCESS
[120.62.112.151] - Invoking deployment process
[120.62.112.151] - Invoking deployment process: SUCCESS
[120.62.112.151] - Verifying deployment
[120.62.112.151] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
url: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
bash: line 28: curl: command not found
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

lyq@ubuntu:~/webroot/yizhema$ mupx logs

## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No README data

---

Also, a question, when I redeploy the app, do I need to "mupx stop " first ?

**Comment by simongroll** [comment]
It looks like you don't have _curl_ installed.

Try (in your terminal):
`sudo apt-get install curl`

**Comment by phoue** [comment]
@simongroll , Thanks for your help. Maybe it's my network issue, I'm from China. I just tried: sudo apt-get install curl . and this time I get:
[120.62.112.151] x Verifying deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	 --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------

lyq@ubuntu:~/webroot/yizhema$ mupx logs

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[120.62.112.151] npm ERR! registry error parsing json

**Comment by phoue** [comment]
I try: mupx start, there is the same issue, but then I try: mupx logs, get this: Starting meteor app on port:80.

[120.62.112.151] - Starting app
[120.62.112.151] - Starting app: SUCCESS
[120.62.112.151] - Verifying deployment
[120.62.112.151] x Verifying deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	 0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------
lyq@ubuntu:~/webroot/yizhema$ mupx logs

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[120.62.112.151] npm ERR! cb() never called!
[120.62.112.151] npm ERR! not ok code 0
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[120.62.112.151] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[120.62.112.151] 
[120.62.112.151] > fibers@1.0.5 install /bundle/bundle/programs/server/node_modules/fibers
[120.62.112.151] > node ./build.js
[120.62.112.151] 
[120.62.112.151] `linux-x64-v8-3.14` exists; testing
[120.62.112.151] Binary is fine; exiting
[120.62.112.151] underscore@1.5.2 node_modules/underscore
[120.62.112.151] 
[120.62.112.151] semver@4.1.0 node_modules/semver
[120.62.112.151] 
[120.62.112.151] fibers@1.0.5 node_modules/fibers
[120.62.112.151] 
[120.62.112.151] eachline@2.3.3 node_modules/eachline
[120.62.112.151] └── type-of@2.0.1
[120.62.112.151] 
[120.62.112.151] source-map-support@0.2.8 node_modules/source-map-support
[120.62.112.151] └── source-map@0.1.32 (amdefine@0.1.0)
[120.62.112.151] 
[120.62.112.151] chalk@0.5.1 node_modules/chalk
[120.62.112.151] ├── ansi-styles@1.1.0
[120.62.112.151] ├── escape-string-regexp@1.0.3
[120.62.112.151] ├── supports-color@0.2.0
[120.62.112.151] ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
[120.62.112.151] └── has-ansi@0.1.0 (ansi-regex@0.2.1)
[120.62.112.151] => Starting meteor app on port:80

**Comment by CodeLYQ** [comment]
@simongroll, Great! Thanks for your help, it works fine now.
