### ISSUE TITLE
mup no longer works with encrypted keys

### ISSUE THREAD

**Issue by mlanett** [arunoda/meteor-up-legacy#451]
mup 0.10.0 introduced a regression wherein it no longer works with encrypted keys.
`Error: Encrypted private key detected, but no passphrase given`

0.9.7 was totally fine with encrypted keys loaded with `ssh-add`

Based on some cursory poking about, it looks like the problem is that mup now uses nodemiral, and nodemiral is trying to build connections by mucking with keys itself instead of using a local ssh-agent. There is some stuff in the code suggesting a passphrase can be passed around in a config, but there is no release notes describing this, and copying the passphrase around (say, into a config file) is exactly what you DON'T want to do, compared to using an ssh-agent.

So this looks like a regression.
Is ssh-agent support planned?

**Comment by nicksergeant** [comment]
Yeah just ran into this myself. This is pretty bonkers, I'm not sure why the change.

**Comment by mccolin** [comment]
Another ping on this. This is a critical part of our workflow that is not working and is keeping us locked to a prior version of mup.

**Comment by arunoda** [comment]
I get it. This is something blocking after we have added ssh2 support which
is specially for windows.

It also gives us more other advantages as well. Since now ssh is fully
implemented using js,that's why this is not working.

I will look at ways to do it. But I am quite not sure.

**Comment by lowi** [comment]
Same issue for me.

**Comment by flowen** [comment]
can't add much more except that I have the same problem either using a SSH key or password

**Comment by meteorjs3000** [comment]
How can we rollback to a previous version where encrypted SSH keys can be use? I updated using `sudo npm -g update mup`

**Comment by mlanett** [comment]
Try `sudo npm -g install mup@0.9.7`

**Comment by asidiali** [comment]
Had the same error, downgraded to 0.9.7 like @mlanett said and obv worked fine again.

**Comment by pechitook** [comment]
Thanks @mlanett

**Comment by queso** [comment]
Guess it is time to fork mup at 0.9.7 and continue porting for those that love security more than windows?

**Comment by slobatch** [comment]
@queso +1

**Comment by arunoda** [comment]
Add paraphrase support via ssh-agent. See: https://goo.gl/SZxCHD

About forking. It's better to fork and PR rather doing +1 or similar.
Project authors has a lot in their hands and do many things. 
Doing `+1` in this way is the least helpful thing you can do.

**Comment by mlanett** [comment]
Thanks Arunoda! Problem solved.

**Comment by bkuri** [comment]
@arunoda your solution did not work for me using `mup@0.11.2`, unfortunately. I commented the `pem` option inside `mup.json`, ran a new ssh-agent, added my passphrase with `ssh-add ~/.ssh/id...`, and finally `mup setup`. Error message below:

```
$ mup setup

[...]

Started TaskList: Setup (linux)
[162.243.105.172] - Installing Node.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/usr/lib/node_modules/mup/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/lib/node_modules/mup/node_modules/ssh2/lib/client.js:469:5)
    at emitTwo (events.js:87:13)
    at SSH2Stream.emit (events.js:172:7)
    at parsePacket (/usr/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:3652:10)
    at SSH2Stream._transform (/usr/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:555:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/usr/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
```

EDIT: I just repeated the process without removing the `pem` option and I got the following error instead:

```
$ mup setup

[...]

Started TaskList: Setup (linux)
[162.243.105.172] - Installing Node.js
/usr/lib/node_modules/mup/node_modules/ssh2/lib/client.js:161
        throw new Error('Encrypted private key detected, but no passphrase given');
        ^

Error: Encrypted private key detected, but no passphrase given
    at Client.connect (/usr/lib/node_modules/mup/node_modules/ssh2/lib/client.js:161:15)
    at SSH.connect (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/ssh.js:12:16)
    at Session._withSshClient (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:52:29)
    at Session.execute (/usr/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:140:8)
    at /usr/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:168:12
    at /usr/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:183:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by ryparty** [comment]
@arunoda ssh-agent was clutch, worked great thanks!

**Comment by seanmavley** [comment]
Can't get it to work

Started TaskList: Setup (linux)
[178.62.3.120] - Installing Node.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/home/khophi/npm-global/lib/node_modules/mup/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/khophi/npm-global/lib/node_modules/mup/node_modules/ssh2/lib/client.js:469:5)
    at emitTwo (events.js:87:13)
    at SSH2Stream.emit (events.js:172:7)
    at parsePacket (/home/khophi/npm-global/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:3652:10)
    at SSH2Stream._transform (/home/khophi/npm-global/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:557:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/khophi/npm-global/lib/node_modules/mup/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)


This is my server setup:

"servers": [
    {
      "host": "xx.xx.xx.xx",
      "username": "root"
      // "password": "password"
      // or pem file (ssh based authentication)
      // "pem": "~/.ssh/id_rsa"
    }
  ],

**Comment by seanmavley** [comment]
@mlanett I'm having same error.

**Comment by marshyon** [comment]
I have had the same issues as described above when trying to run mup over ssh with keys and ssh-add

```
sudo npm -g install mup@0.9.7
```

for the time being seems to be a work around for me

**Comment by seanmavley** [comment]
I used mupx instead. Worked nicely. Mupx is kinda the dev version of mup. Give it a try

**Comment by onedr0p** [comment]
mupx seems nice, but from the readme it doesn't support keys with passphrases

```
{
  // Server authentication info
  "servers": [
    {
      "host": "hostname",
      "username": "root",
      "password": "password",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      //"pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],
...
```

**Comment by granda** [comment]
I can confirm it works with encrypted keys as long as you have `ssh-agent` running with:

``` bash
$ eval "$(ssh-agent -s)"
```

and adding encrypted key with:

``` bash
$ ssh-add ~/.ssh/id_rsa
```

Afterwards I removed this line from my `mup.json`:

``` json
"pem": "~/.ssh/id_rsa"
```

So my `mup.json` looks like this:

``` json
{
  "servers": [
    {
      "host": "beta.appdomain.com",
      "username": "root"
    }
  ],
  "setupMongo": true,
  "appName": "AppProject",
  "app": "~/Development/AppProjectFolder",
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://beta.appdomain.com"
  },
  "deployCheckWaitTime": 15,
  "enableUploadProgressBar": true
}
```

Then I ran the command to deploy `mupx` on a fresh DigitalOcean droplet with:

``` bash
$ mupx deploy
```

EDIT: I see I missed it in the `README.md``[0]` 😅

`[0]` https://github.com/arunoda/meteor-up#ssh-keys-with-passphrase-or-ssh-agent-support

**Comment by abaumer** [comment]
Confirm this works for me as well, just as @granda stated and with mupx as documented in the github readme https://github.com/arunoda/meteor-up/tree/mupx#ssh-keys-with-paraphrase-or-ssh-agent-support

Thanks @arunoda
