### ISSUE TITLE
Failed to connect to localhost port 80: Connection refused

### ISSUE THREAD

**Issue by scottmcpherson** [arunoda/meteor-up-legacy#47]
Hey @arunoda, I'm not really to sure what to make of this error and was hoping you could help me out. I'm trying to deploy to ec2 and I'm getting the following STDERR error after running mup deploy:

```
Failed to connect to localhost port 80: Connection refused
```

and when I run mup logs:

```
[184.72.179.106]     at new Server (packages/livedata/livedata_server.js:1068)
    at Package (packages/livedata/server_convenience.js:10)
    at packages/livedata.js:3971:4
    at packages/livedata.js:3982:3
    at /opt/meteor/app/programs/server/boot.js:155:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/meteor/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #111
```

I set up an ec2 instance with ubuntu 14.04 LTS and and added an incoming security group for for ssh on port 22. Other than that I haven't modified the server at all. Do you have any ideas as to what might be causing this?

**Comment by arunoda** [comment]
Hey log output is not enough. Deploy again. Get a log output with

mup logs -n 300

To see the real issue.

On Friday, April 25, 2014, Scott McPherson notifications@github.com wrote:

> Hey @arunoda https://github.com/arunoda, I'm not really to sure what to
> make of this error and was hoping you could help me out. I'm trying to
> deploy to ec2 and I'm getting the following STDERR error after running mup
> deploy:
> 
> Failed to connect to localhost port 80: Connection refused
> 
> and when I run mup logs:
> 
> [184.72.179.106]     at new Server (packages/livedata/livedata_server.js:1068)
>     at Package (packages/livedata/server_convenience.js:10)
>     at packages/livedata.js:3971:4
>     at packages/livedata.js:3982:3
>     at /opt/meteor/app/programs/server/boot.js:155:10
>     at Array.forEach (native)
>     at Function._.each._.forEach (/opt/meteor/app/programs/server/node_modules/underscore/underscore.js:79:11)
>     at /opt/meteor/app/programs/server/boot.js:82:5
> error: Forever detected script exited with code: 8
> error: Script restart attempt #111
> 
> I set up an ec2 instance with ubuntu 14.04 LTS and and added an incoming
> security group for for ssh on port 22. Other than that I haven't modified
> the server at all. Do you have any ideas as to what might be causing this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/47
> .

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by scottmcpherson** [comment]
Yep, that revealed the problem. I totally forgot to configure the settings.json file and my app was looking for a settings name/value pair that didn't exist.

**Comment by jamiewilson** [comment]
Hey @scott-mcpherson, I'm running into this same issue now. Any chance you remember what you did to resolve it?

**Comment by scottmcpherson** [comment]
For me, my app was looking for settings that didn't exist. In your mup's project folder, there is a file called settings.json. If you have the same problem, then you just have to set your settings there.

**Comment by jamiewilson** [comment]
@scott-mcpherson cool. thanks for the help!

**Comment by brylie** [comment]
I am getting the same error, and my log repeats the following:

```
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
```

On my system, Ubuntu 14.04, I have the following node version available:

```
$ node -v
v0.10.33
```

I manually changed the node version setting to `0.10.36` in mup.json and ran `mup setup` again.

**Comment by brylie** [comment]
OK, now I am getting a different error:

```
Error: `/opt/pym-2015/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
```

**Comment by mmoyles87** [comment]
Change your nodeVersion to 0.10.36 in and re-run mup setup and then deploy.

On Wed, Apr 1, 2015 at 3:06 PM, Brylie Christopher Oxley <
notifications@github.com> wrote:

> OK, now I am getting a different error:
> 
> Error: `/opt/pym-2015/app/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node` is missing. Try reinstalling `node-fibers`?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/47#issuecomment-88596958.

## 

Matt Moyles
http://mattmoyles.com

**Comment by mathiasburton** [comment]
I'm still getting this issue though I have nothing in my settings.json except:

```
{
  "public": {

  }
}

```

mup logs -n 300 say: 

```
Error: $ROOT_URL, if specified, must be an URL
    at Error (<anonymous>)
    at Meteor.absoluteUrl.options (packages/meteor/url_server.js:8:1)
    at /opt/localbrainstorm/app/programs/server/packages/meteor.js:1132:4
    at /opt/localbrainstorm/app/programs/server/packages/meteor.js:1274:3
    at /opt/localbrainstorm/app/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/localbrainstorm/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/localbrainstorm/app/programs/server/boot.js:137:5
error: Forever detected script exited with code: 8
```

**Comment by MasterJames** [comment]
Maybe you should try with the default settings and default meteor app first? Then simply adjust as needed.
