### ISSUE TITLE
Stud version / Support for TLS 1.2

### ISSUE THREAD

**Issue by thomasf1** [arunoda/meteor-up-legacy#474]
It seems the version of stud currently seems to not have updated in the last 3-4 years. Maybe it´s a good idea to switch to a fork under active development.

The key issue is Support for TLS 1.2 (the only SSL currently considered safe) without supporting SSLv3 (unsafe, should not be supported as it opens the door for attacks that try to have the connection fall back to SSLv3)

What do you guys think?

**Comment by thomasf1** [comment]
PS: That´s the issue discussion on stud: https://github.com/bumptech/stud/issues/150

**Comment by arunoda** [comment]
Yes it is.
Use mupx. Now we are using nginx.

**Comment by thomasf1** [comment]
PS: Current SSL issues that got flagged for our mup deployment...
![screen shot 2015-06-12 at 13 46 18](https://cloud.githubusercontent.com/assets/937467/8129444/836c3b60-1109-11e5-9927-6a8fefc5374e.png)

**Comment by arunoda** [comment]
Yes it is.
That's why we fixed this with mupx. We are no longer maintaining mup.

**Comment by thomasf1** [comment]
Thanks, @arunoda  :)

**Comment by avishaan** [comment]
@arunoda can you confirm mupx has TLS 1.2 support. I'm on this other thread https://github.com/arunoda/meteor-up/issues/819 and trying to get a definitive answer.
