### ISSUE TITLE
mup deploy sucessful to EC2, but web page is not available

### ISSUE THREAD

**Issue by vandretti** [arunoda/meteor-up-legacy#487]
I was got mup deploy successfully to EC2, but I failed to see the web page. I keep getting ERR_CONNECTION_TIMED_OUT. Am I missing any steps to start the app after running mup deploy?

**Comment by MasterJames** [comment]
Starting with DNS we move through the debug problem and isolate where the fault lies. 
This sounds like a DNS problem?

**Comment by vandretti** [comment]
I use the same EC2 instance public DNS as specified in the ROOT_URL of mup.json file. ie. http://ec2-52-27-24-168.us-west-2.compute.amazonaws.com

EC2 shows the instance is running.

Also, mup log file does not show any error: 
[ec2-52-27-24-168.us-west-2.compute.amazonaws.com]  >> stepping down to gid: meteoruser

> > stepping down to uid: meteoruser
> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser
> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser
> > stepping down to gid: meteoruser
> > stepping down to uid: meteoruser

**Comment by vandretti** [comment]
As suggested in the Sever Setup Details section, I tried to start the app with upstart: 
- start hello

I got the error message: 
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.32" (uid=1000 pid=12624 comm="start hello ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")

**Comment by MasterJames** [comment]
SSH looks available seems there's nothing at port 80?

Starting Nmap 6.00 ( http://nmap.org ) at 2015-06-19 09:55 EEST 
Initiating SYN Stealth Scan at 09:55 
Scanning ec2-52-27-24-168.us-west-2.compute.amazonaws.com (52.27.24.168) [22 ports] 
Discovered open port 22/tcp on 52.27.24.168 
Completed SYN Stealth Scan at 09:55, 1.84s elapsed (22 total ports) 

Nmap scan report for ec2-52-27-24-168.us-west-2.compute.amazonaws.com (52.27.24.168) 
Host is up (0.14s latency). 

PORT STATE SERVICE 
21/tcp filtered ftp 
22/tcp open ssh 
23/tcp filtered telnet 
25/tcp filtered smtp 
80/tcp filtered http 
110/tcp filtered pop3 
143/tcp filtered imap 
179/tcp filtered bgp 
443/tcp filtered https 
465/tcp filtered smtps 
993/tcp filtered imaps 
995/tcp filtered pop3s 
1433/tcp filtered ms-sql-s 
1720/tcp filtered H.323/Q.931 
1723/tcp filtered pptp 
3306/tcp filtered mysql 
3389/tcp filtered ms-wbt-server 
5060/tcp filtered sip 
5900/tcp filtered vnc 
8000/tcp filtered http-alt 
8080/tcp filtered http-proxy 
8443/tcp filtered https-alt 

Nmap done: 1 IP address (1 host up) scanned in 2.06 seconds 
Raw packets sent: 44 (1.936KB) | Rcvd: 4 (256B) 

Job finished [2015-06-19 06:55:44]

**Comment by vandretti** [comment]
Thanks! Open port 80 for http connection on EC2 was the missing step for me.
