### ISSUE TITLE
MUP with Jenkins, is it possible to parametrize "host": ?

### ISSUE THREAD

**Issue by allandequeiroz** [arunoda/meteor-up-legacy#492]
Hello guys, I'm using mup with jenkins and it works well except for a single point.

I have two environments, prod and homol but just a single mup.json, when I want to deploy on homol I have to vary the host property, commit it and start the deployment process, so sometimes:
"host": "jolie.me"

Sometimes
"host": "joliehomolog.portaltecsinapse.com.br"

So, is there a way to parametrize this? Like
"host": "$HOST"

**Comment by SierraGolf** [comment]
I am currently thinking of how to integrate mup with jenkins as well. I my scenario I want the whole server configuration(s) to be configurable from the jenkins job. As long as nobody goes the distance to create a meteor-up jenkins plugin, you could probably use something like bash or the groovy plugin to dynamically generate the mup.json in the workspace of the job before running `mup deploy`.

imho server configuration should not be part of the project itself.

**Comment by JuusoV** [comment]
Hi @allandequeiroz 
Not sure if this helps but...

We used a Jenkins task to parameterize the mup.json and the settings.json files.
Create build with parameters and give it string parameters where you define your $HOST. Then in the build steps execute shell with something like this: 

rm -rf mup.json

cat <<EOT > mup.json
{
  // Server authentication info
  "servers": [
    {
      "host": "$host_name",
      "username": "$user_name",
      "password": "$pass_word"
    }
  ],

  "setupMongo": true,

  "setupNode": true,

  //"nodeVersion": "0.10.36",

  "setupPhantom": false,

  "enableUploadProgressBar": true,

  "appName": "$app_name",

  "app": "$app_path",

  "env": {
    "ROOT_URL": "$root_url"
  },

  "deployCheckWaitTime": 30
}

EOT

**Comment by ilfrich** [comment]
In regards to the original question (having 2 or more environments), I think it is acceptable to maintain a mup.json file for each environment. What I do is having a single GIT repository with sub-folders for each environment. Inside each folder I put the settings.json, mup.json (and for test servers the ssl.pem).
