### ISSUE TITLE
Passing an option to build command

### ISSUE THREAD

**Issue by sungwoncho** [arunoda/meteor-up-legacy#500]
I would like to pass an option when the application is building. After consulting the documentation, I could not find a way to do so. Perhaps this feature will be useful.

e.g.

I am having an issue with bcrypt and would like to pass `--architecture os.linux.x86_64` option when building.

**Comment by arunoda** [comment]
Use mupx, we've fixed this issue.
(You can also use custom options)

**Comment by sungwoncho** [comment]
Thanks. See [Build options](https://github.com/arunoda/meteor-up/tree/mupx#build-options) in mupx branch if anyone has the similar issue. Closing.
