### ISSUE TITLE
Page refresh with nginx load balancer

### ISSUE THREAD

**Issue by cbwheadon** [arunoda/meteor-up-legacy#505]
I'm using mupx with aws, and all is fine if I work with a single instance. If I place the instance behind an elastic load balancer, however, the site reloads two or three times before settling down. It looks like a similiar issue to this: https://groups.google.com/forum/#!topic/meteor-core/yuIR-p3fXck which required some changes to the nginx configuration to fix. Do you think this is the same issue, and is it possible to fix using changes in the mupx configuration?

**Comment by arunoda** [comment]
I hope that's a routing issue. I don't think it's nginx issue as you don't
use it.

I am not quite remember. These is a way to enable sticky seasons in elb.
Then you can't use websocket.

**Comment by cbwheadon** [comment]
Turning off web sockets worked, thank you!
