### ISSUE TITLE
Google Cloud deployment SSH not working

### ISSUE THREAD

**Issue by dkmooers** [arunoda/meteor-up-legacy#507]
Sorry if this is an obvious question - I'm new to gcloud and am pretty baffled by it.

I've got SSH set up on my computer (OSX), using gcloud tool. Now I can SSH into my instance from Terminal just fine. But the mupx deployment script can't get SSH access to the Google Cloud instance.

The gcloud auto-generated SSH key is stored here:

`~/.ssh/google_compute_engine`

So in my mup.json config file, I've done this:

```
"servers": [
  {
    "host": "XXX.XXX.XXX.XXX",
    "username": "email@domain.com",
    "pem": "~/.ssh/google_compute_engine",
    "env": {}
  }
],
```

But can't deploy. I get this error:

```
Error: All configured authentication methods failed
at tryNextAuth (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:290:17)
at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:469:5)
at SSH2Stream.EventEmitter.emit (events.js:98:17)
at parsePacket (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3649:10)
at SSH2Stream._transform (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
at SSH2Stream.Transform._read [as __read] (_stream_transform.js:179:10)
at SSH2Stream._read (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
at SSH2Stream.Transform._write (_stream_transform.js:167:12)
at doWrite (_stream_writable.js:226:10)
at writeOrBuffer (_stream_writable.js:216:5)
```

Is there some other configuration I need to do with mupx or with Google Cloud? I should be using my Google email address that I use to login to Google Cloud, right?

**Comment by arunoda** [comment]
With gcloud, you need to put the IP address, pem file since we don't
support OS level hostfile config.

For the username, you need to set the server's username. Not your gcloud
login.

**Comment by dkmooers** [comment]
Got it, thanks! Changed the username to my local computer username, as per this article:

https://cloud.google.com/compute/docs/instances/

> USER
> [Required] The username to log in that instance. Typically, this is the username of the local user running gcloud compute.

**Comment by arunoda** [comment]
In other case, you can also add SSH keys directly to the instance via
metadata.
Then, server's username is the username.

**Comment by dkmooers** [comment]
You mean then the server's username is my Google Cloud account login? (I'm not aware of any other username attached to the server)

**Comment by ivanthemeh** [comment]
Hey Im very new to google cloud and I was wondering if I could get some help with the authentication so I can use meteor-up? I see the issue is closed so sorry If Im violating some protocol. Thanks.

I am getting the same authentication error.

**Comment by MasterJames** [comment]
Hmm. .. the link above is good. Leads to this one too.
https://cloud.google.com/compute/docs/instances/managing-ssh-keys

It has a getting started guide...
https://cloud.google.com/compute/docs/quickstart

Are you using gcloud or ssh?
By default you should be able to SSH.
Try to get it so you can SSH from the local dev machine to your target instance. Report back with progress or potential issues and/or questions, thanks.

We also like to know more about your situation to be able to provide help.
Everything from your mup settings to "DEBUG =\* mupx deploy" logs, OS type & versions for node, etc.

Also I like ti ask if you're having trouble with mup to try mupx but at this point we are only concerned with you SSH and less about mup(x). That's next let's just clarify your SSH connection.

**Comment by ivanthemeh** [comment]
I tried using both, I was able to use ssh locally from cloud console but not from my machine or through gcloud. Gonna work on this again today for now I was able to deploy to a linode and host the db on compose.
