### ISSUE TITLE
invoking deployment process:failed.. ec2 

### ISSUE THREAD

**Issue by richpowell** [arunoda/meteor-up-legacy#509]
Hi 
Im on ec2 using a t2.micro instance, with the ami Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-5189a661.
My deploy is failing at the invoking deployment process stage...   any hints how to fix this?
Thanks!

my mup.json looks like this.

{
  // Server authentication info
  "servers": [
    {
      "host": "52.26.238.231",
      "username": "ubuntu",
      //"password": "password"
      // or pem file (ssh based authentication)
      "pem": "/Users/rich/.ssh/ec2pairname.pem"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server.
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "koma",

  "app": "/Users/rich/Documents/koma",

  "env": {
    "ROOT_URL": "http://ec2-52-26-238-231.us-west-2.compute.amazonaws.com"
  },
  "deployCheckWaitTime": 15
}

---

Heres the error..

Started TaskList: Deploy app 'koma' (linux)
[52.26.238.231] - Uploading bundle
  nodemiral:sess:52.26.238.231 copy file - src: /tmp/a5e49cf7-840b-4f74-8501-6dc575a664d8/bundle.tar.gz, dest: /opt/koma/tmp/bundle.tar.gz, vars: undefined +0ms
[52.26.238.231] - Uploading bundle: SUCCESS
[52.26.238.231] - Setting up Environment Variables
  nodemiral:sess:52.26.238.231 copy file - src: /usr/local/lib/node_modules/mup/templates/linux/env.sh, dest: /opt/koma/config/env.sh, vars: {"env":{"ROOT_URL":"http://ec2-52-26-238-231.us-west-2.compute.amazonaws.com","METEOR_SETTINGS":"{\"public\":{}}","CLUSTER_ENDPOINT_URL":"http://52.26.238.231:80"},"appName":"koma"} +9s
[52.26.238.231] - Setting up Environment Variables: SUCCESS
[52.26.238.231] - Invoking deployment process
[52.26.238.231] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
44c8fffea8a21da
npm ERR! fetch failed https://registry.npmjs.org/fibers/-/fibers-1.0.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/underscore/-/underscore-1.5.2.tgz
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/koma/tmp/bundle/programs/server
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/koma/tmp/bundle/programs/server/npm-debug.log
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
----------------------------------------------------------------------------
```

And heres my log when i log into the server...

ubuntu@ip-172-31-21-58:~$ ls
npm-debug.log
ubuntu@ip-172-31-21-58:~$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'forever',
1 verbose cli   'userdown',
1 verbose cli   'wait-for-mongo',
1 verbose cli   'node-gyp' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink /usr/bin/node
5 verbose cache add [ 'forever', null ]
6 verbose cache add name=undefined spec="forever" args=["forever",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'forever',
7 verbose parsed url   path: 'forever',
7 verbose parsed url   href: 'forever' }
8 verbose cache add [ 'userdown', null ]
9 verbose cache add name=undefined spec="userdown" args=["userdown",null]
10 verbose parsed url { protocol: null,
10 verbose parsed url   slashes: null,
10 verbose parsed url   auth: null,
10 verbose parsed url   host: null,
10 verbose parsed url   port: null,
10 verbose parsed url   hostname: null,
10 verbose parsed url   hash: null,
10 verbose parsed url   search: null,
10 verbose parsed url   query: null,
10 verbose parsed url   pathname: 'userdown',
10 verbose parsed url   path: 'userdown',
10 verbose parsed url   href: 'userdown' }
11 verbose cache add [ 'wait-for-mongo', null ]
12 verbose cache add name=undefined spec="wait-for-mongo" args=["wait-for-mongo",null]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: 'wait-for-mongo',
13 verbose parsed url   path: 'wait-for-mongo',
13 verbose parsed url   href: 'wait-for-mongo' }
14 verbose cache add [ 'node-gyp', null ]
15 verbose cache add name=undefined spec="node-gyp" args=["node-gyp",null]
16 verbose parsed url { protocol: null,
16 verbose parsed url   slashes: null,
16 verbose parsed url   auth: null,
16 verbose parsed url   host: null,
16 verbose parsed url   port: null,
16 verbose parsed url   hostname: null,
16 verbose parsed url   hash: null,
16 verbose parsed url   search: null,
16 verbose parsed url   query: null,
16 verbose parsed url   pathname: 'node-gyp',
16 verbose parsed url   path: 'node-gyp',
16 verbose parsed url   href: 'node-gyp' }
17 silly lockFile e07f8c4a-forever forever
18 verbose lock forever /home/ubuntu/.npm/e07f8c4a-forever.lock
19 silly lockFile 8428d6f7-userdown userdown
20 verbose lock userdown /home/ubuntu/.npm/8428d6f7-userdown.lock
21 silly lockFile 1385fa64-wait-for-mongo wait-for-mongo
22 verbose lock wait-for-mongo /home/ubuntu/.npm/1385fa64-wait-for-mongo.lock
23 silly lockFile 54062583-node-gyp node-gyp
24 verbose lock node-gyp /home/ubuntu/.npm/54062583-node-gyp.lock
25 silly lockFile e07f8c4a-forever forever
26 silly lockFile e07f8c4a-forever forever
27 silly lockFile 8428d6f7-userdown userdown
28 silly lockFile 8428d6f7-userdown userdown
29 silly lockFile 1385fa64-wait-for-mongo wait-for-mongo
30 silly lockFile 1385fa64-wait-for-mongo wait-for-mongo
31 silly lockFile 54062583-node-gyp node-gyp
32 silly lockFile 54062583-node-gyp node-gyp
33 verbose addNamed [ 'forever', '' ]
34 verbose addNamed [ null, '_' ]
35 silly lockFile 28ef027b-forever forever@
36 verbose lock forever@ /home/ubuntu/.npm/28ef027b-forever.lock
37 verbose addNamed [ 'userdown', '' ]
38 verbose addNamed [ null, '_' ]
39 silly lockFile 0d622e2c-userdown userdown@
40 verbose lock userdown@ /home/ubuntu/.npm/0d622e2c-userdown.lock
41 verbose addNamed [ 'wait-for-mongo', '' ]
42 verbose addNamed [ null, '_' ]
43 silly lockFile da03bc7e-wait-for-mongo wait-for-mongo@
44 verbose lock wait-for-mongo@ /home/ubuntu/.npm/da03bc7e-wait-for-mongo.lock
45 verbose addNamed [ 'node-gyp', '' ]
46 verbose addNamed [ null, '_' ]
47 silly lockFile c0cd6589-node-gyp node-gyp@
48 verbose lock node-gyp@ /home/ubuntu/.npm/c0cd6589-node-gyp.lock
49 silly addNameRange { name: 'forever', range: '_', hasData: false }
50 silly addNameRange { name: 'userdown', range: '_', hasData: false }
51 silly addNameRange { name: 'wait-for-mongo', range: '_', hasData: false }
52 silly addNameRange { name: 'node-gyp', range: '_', hasData: false }
53 verbose request where is /forever
54 verbose request registry https://registry.npmjs.org/
55 verbose request id d65e055a5c49bce7
56 verbose url raw /forever
57 verbose url resolving [ 'https://registry.npmjs.org/', './forever' ]
58 verbose url resolved https://registry.npmjs.org/forever
59 verbose request where is https://registry.npmjs.org/forever
60 info trying registry request attempt 1 at 04:09:02
61 http GET https://registry.npmjs.org/forever
62 verbose request where is /userdown
63 verbose request registry https://registry.npmjs.org/
64 verbose url raw /userdown
65 verbose url resolving [ 'https://registry.npmjs.org/', './userdown' ]
66 verbose url resolved https://registry.npmjs.org/userdown
67 verbose request where is https://registry.npmjs.org/userdown
68 info trying registry request attempt 1 at 04:09:02
69 http GET https://registry.npmjs.org/userdown
70 verbose request where is /wait-for-mongo
71 verbose request registry https://registry.npmjs.org/
72 verbose url raw /wait-for-mongo
73 verbose url resolving [ 'https://registry.npmjs.org/', './wait-for-mongo' ]
74 verbose url resolved https://registry.npmjs.org/wait-for-mongo
75 verbose request where is https://registry.npmjs.org/wait-for-mongo
76 info trying registry request attempt 1 at 04:09:02
77 http GET https://registry.npmjs.org/wait-for-mongo
78 verbose request where is /node-gyp
79 verbose request registry https://registry.npmjs.org/
80 verbose url raw /node-gyp
81 verbose url resolving [ 'https://registry.npmjs.org/', './node-gyp' ]
82 verbose url resolved https://registry.npmjs.org/node-gyp
83 verbose request where is https://registry.npmjs.org/node-gyp
84 info trying registry request attempt 1 at 04:09:02
85 http GET https://registry.npmjs.org/node-gyp
86 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
87 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
88 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
89 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
90 info trying registry request attempt 2 at 04:11:19
91 http GET https://registry.npmjs.org/forever
92 info trying registry request attempt 2 at 04:11:19
93 http GET https://registry.npmjs.org/userdown
94 info trying registry request attempt 2 at 04:11:19
95 http GET https://registry.npmjs.org/wait-for-mongo
96 info trying registry request attempt 2 at 04:11:19
97 http GET https://registry.npmjs.org/node-gyp
98 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
99 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
100 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
101 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
102 info trying registry request attempt 3 at 04:14:26
103 http GET https://registry.npmjs.org/forever
104 info trying registry request attempt 3 at 04:14:26
105 http GET https://registry.npmjs.org/userdown
106 info trying registry request attempt 3 at 04:14:26
107 http GET https://registry.npmjs.org/node-gyp
108 info trying registry request attempt 3 at 04:14:26
109 http GET https://registry.npmjs.org/wait-for-mongo
110 silly lockFile 28ef027b-forever forever@
111 silly lockFile 28ef027b-forever forever@
112 silly lockFile 0d622e2c-userdown userdown@
113 silly lockFile 0d622e2c-userdown userdown@
114 silly lockFile c0cd6589-node-gyp node-gyp@
115 silly lockFile c0cd6589-node-gyp node-gyp@
116 silly lockFile da03bc7e-wait-for-mongo wait-for-mongo@
117 silly lockFile da03bc7e-wait-for-mongo wait-for-mongo@
118 error network connect ETIMEDOUT
118 error network This is most likely not a problem with npm itself
118 error network and is related to network connectivity.
118 error network In most cases you are behind a proxy or have bad network settings.
118 error network
118 error network If you are behind a proxy, please make sure that the
118 error network 'proxy' config is set properly.  See: 'npm help config'
119 error System Linux 3.13.0-48-generic
120 error command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "forever" "userdown" "wait-for-mongo" "node-gyp"
121 error cwd /home/ubuntu
122 error node -v v0.10.36
123 error npm -v 1.4.28
124 error syscall connect
125 error code ETIMEDOUT
126 error errno ETIMEDOUT
127 verbose exit [ 1, true ]

**Comment by MasterJames** [comment]
I think people reported having problems with micro instance being too small try the next larger RAM instance available to help confirm that.

If so, maybe there's a way to check for that in MupX and error (with an override option).

Also I'm wondering if are you using and or have tried mupx?

**Comment by richpowell** [comment]
Im using mup. I just tried installing mupx and got an error.. Im wondering is there a recommended size for ram on ec2? or a best practices / or even a way to monitor ram. I believe on nitrous.io and modulus ram monitoring was a built in feature, I believe both run on aws.  is there a spot on aws to watch for this?
thanks

**Comment by MasterJames** [comment]
Let's just determine if the next bigger sized instance helps, but those are all good questions i dont have the answers to off hand. I believe 2GB will work if your deployment is just a simple test.
their are commands like df (disk free space) that you could check via ssh etc to maybe check that, but either way just avoid mini and see if that makes a difference thanks.

**Comment by richpowell** [comment]
mupx i get these errors
i will try the larger ec2 instance now.
Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
config/start.sh: line 11: docker: command not found
config/start.sh: line 14: docker: command not found
config/start.sh: line 17: docker: command not found
```

**Comment by MasterJames** [comment]
Okay so it's not the instance size this time.
If you can SSH into the instance can you ping or reach
registry.npmjs.org
Also consider this...
http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

Maybe try something beyond this basic starter idea if you see problems with it...
npm config set registry "http://registry.npmjs.org/"

**Comment by richpowell** [comment]
I couldnt ping.  I added a security rule to allow icmp (which ec2 uses for ping).  and got a fresh instance. this seemed to do the trick with mupx on both a micro instance and a larger instance.  I think it could be possibly due to this security rule.

**Comment by MasterJames** [comment]
If you could test if removing the rule causes the problem then maybe we are looking at a pull request before this gets closed.

**Comment by richpowell** [comment]
yikes, having trouble reproducing this now.  When i find it I will repost.
