### ISSUE TITLE
mupx not installing on osx, npm or node v issue?

### ISSUE THREAD

**Issue by richpowell** [arunoda/meteor-up-legacy#511]
Hi Im trying to test a deployment with mupx, but im getting this error on install. Is this a npm or node v issue?
Richs-MacBook-Air-2:~ rich$ npm install -g mupx
npm WARN locking Error: EACCES, open '/Users/rich/.npm/_locks/mupx-84ac75d4c3f80c3a.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/rich/.npm/_locks/mupx-84ac75d4c3f80c3a.lock failed { [Error: EACCES, open '/Users/rich/.npm/_locks/mupx-84ac75d4c3f80c3a.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/rich/.npm/_locks/mupx-84ac75d4c3f80c3a.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "mupx"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! Attempt to unlock /usr/local/lib/node_modules/mupx, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rich/npm-debug.log
Richs-MacBook-Air-2:~ rich$

**Comment by jaaaco** [comment]
try:
sudo npm install -g mupx

**Comment by richpowell** [comment]
yeah that worked
