### ISSUE TITLE
mupx mongo error

### ISSUE THREAD

**Issue by richpowell** [arunoda/meteor-up-legacy#514]
Any thoughts on this mongo error? Do i need an Mongo_URL in my mup.json?

Richs-MacBook-Air-2:koma rich$ mupx setup
## Meteor Up: Production Quality Meteor Deployments

Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Started TaskList: Setup (linux)
[52.10.9.141] - Installing Docker
[52.10.9.141] - Installing Docker: SUCCESS
[52.10.9.141] - Setting up Environment
[52.10.9.141] - Setting up Environment: SUCCESS
[52.10.9.141] - Copying MongoDB configuration
[52.10.9.141] - Copying MongoDB configuration: SUCCESS
[52.10.9.141] - Installing MongoDB
[52.10.9.141] x Installing MongoDB: FAILED

```
-----------------------------------STDERR-----------------------------------
Error response from daemon: Cannot start container 807501983b36153536afda102ebb08d826a5e211b882c1c97100998c0fe5ecf0: Error starting userland proxy: listen tcp 127.0.0.1:27017: bind: address already in use
-----------------------------------STDOUT-----------------------------------
latest: Pulling from mongo
104de4492b99: Already exists
065218d54d7d: Already exists
bb2fbb9da757: Already exists
2ee3edbbf31e: Already exists
7fbceb4b229f: Already exists
2f065532662e: Already exists
31178773394d: Already exists
ae45372c5cf0: Already exists
36a241da2aab: Already exists
0346de63a225: Already exists
40ad445e4b1f: Already exists
125046cfae70: Already exists
60c57e35a69a: Already exists
8a84609c8ec5: Already exists
a96eed4f7c82: Already exists
a2f0a3c2052e: Already exists
a7b01f71af86: Already exists
a7b01f71af86: Already exists
Digest: sha256:1f8d904a64cd547bf445fa3d435112760ac0b59724c227f595f84875de16bab0
Status: Image is up to date for mongo:latest
mongodb
807501983b36153536afda102ebb08d826a5e211b882c1c97100998c0fe5ecf0
----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
It seems like mongodb is already installed on your system.
Read this: https://www.npmjs.com/package/mupx#migration-guide

**Comment by richpowell** [comment]
a new instance did the trick.
