### ISSUE TITLE
Mup error out of nowhere  

### ISSUE THREAD

**Issue by aadamsx** [arunoda/meteor-up-legacy#521]
I've have a standard AWS Ubuntu instance.  I've been using MUP for months now without issues.  Even last night when I deployed everything worked fine.  This morning I deploy to my staging environment and the the following errors. 

```
Invoking deployment process: FAILED

-----------------------------------STDERR-----------------------------------
ttps://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da
npm ERR! fetch failed https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da
npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/application_name/tmp/bundle/programs/server
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ECONNRESET
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/application_name/tmp/bundle/programs/server/npm-debug.log
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
 > ./bcrypt: npm install due to binary npm modules
bindings@1.0.0 node_modules/bindings

nodeunit@0.9.1 node_modules/nodeunit
└── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.1, slide@1.1.6, deep-equal@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, runforcover@0.0.2, glob@4.5.3)
make: Entering directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
make: Leaving directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
----------------------------------------------------------------------------
```

I tried node version v0.10.26
    Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ailed https://github.com/meteor/node-eachline/tarball/ff89722ff94e6b6a08652bf5f44c8fffea8a21da
npm ERR! Error: 502 Bad Gateway
npm ERR!     at WriteStream.<anonymous> (/opt/nodejs/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1598:14
npm ERR!     at /opt/nodejs/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/application_name/tmp/bundle/programs/server
npm ERR! node -v v0.10.26 < -- [I had v0.10.36 before and it didn't work either!!]
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/application_name/tmp/bundle/programs/server/npm-debug.log
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
 > ./bcrypt: npm install due to binary npm modules
bindings@1.0.0 node_modules/bindings

nodeunit@0.9.1 node_modules/nodeunit
└── tap@0.7.1 (inherits@2.0.1, buffer-equal@0.0.1, slide@1.1.6, deep-equal@1.0.0, yamlish@0.0.7, nopt@3.0.3, mkdirp@0.5.1, difflet@0.2.6, runforcover@0.0.2, glob@4.5.3)
make: Entering directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
make: Leaving directory `/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'
----------------------------------------------------------------------------
```

My configuration file I've always used:

```
{
  "servers": [
    {
      "host": "staging.my-application.com",
      "username": "ubuntu",
      "pem": "/Users/username/Meteors/pem_file.pem"
    }
  ],
  "setupMongo": true,
  "setupNode": true,
  "nodeVersion": "0.10.36", 
  "setupPhantom": false,
  "appName": "application-name",
  "app": "/Users/username/Meteors/application_name",
  "env": {
    "ROOT_URL": "https://staging.my-site.com" // change to https
  },
  "ssl": {
    "pem": "./ssl.pem"
  },
  "deployCheckWaitTime": 30
}
```

I ran the command mup setup again, and it installs fine.

**Comment by aadamsx** [comment]
After doing a meteor update, mup setup, and mup deploy the error changed a bit for node v0.10.36:

```
Invoking deployment process: FAILED

-----------------------------------STDERR-----------------------------------
e/ubuntu/.node-gyp/0.10.36',
gyp info spawn args   '-Dmodule_root_dir=/opt/application_name/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    int-clients/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.5 install /opt/application_name/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

fibers@1.0.5 node_modules/fibers

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)
Waiting for MongoDB to initialize. (5 minutes)
connected
application-name stop/waiting
application-name start/running, process 16427
Waiting for 30 seconds while app is booting up
Checking is app booted or not?
application-name stop/waiting
application-name start/running, process 16655
----------------------------------------------------------------------------
```

**Comment by arunoda** [comment]
GitHub is down right now. That's the issue. There are some npm packages
getting from npm. That's the issue.

Not something related to mup.

**Comment by aadamsx** [comment]
great thanks.  I see you guys are moving on to Docker with mupx, do you recommend trying this out for small and informal production environments on AWS EC2 Ubuntu instances?  If so, is there a good how to on getting this up and running on my mac?  Also, for one of my processes in Meteor in need to install a linux package named pdftk and need to create a few local directories outside of the Meteor project for temporary files, is this supported in Docker?

**Comment by aadamsx** [comment]
I checked github status just now here: https://status.github.com/messages, and it says everything is operational.  I did a mup setup, mup deploy again and get the following error.  Could it be something else?

  Invoking deployment process: FAILED

	-----------------------------------STDERR-----------------------------------
	e/ubuntu/.node-gyp/0.10.36',
	gyp info spawn args   '-Dmodule_root_dir=/opt/formspoint-clients/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp info spawn make
	gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
	gyp info ok
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	int-clients/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

	> fibers@1.0.5 install /opt/formspoint-clients/tmp/bundle/programs/server/node_modules/fibers
	> node ./build.js

	`linux-x64-v8-3.14` exists; testing
	Binary is fine; exiting
	underscore@1.5.2 node_modules/underscore

	semver@4.1.0 node_modules/semver

	fibers@1.0.5 node_modules/fibers

	chalk@0.5.1 node_modules/chalk
	├── ansi-styles@1.1.0
	├── escape-string-regexp@1.0.3
	├── supports-color@0.2.0
	├── has-ansi@0.1.0 (ansi-regex@0.2.1)
	└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

	eachline@2.3.3 node_modules/eachline
	└── type-of@2.0.1

	source-map-support@0.2.8 node_modules/source-map-support
	└── source-map@0.1.32 (amdefine@0.1.0)
	Waiting for MongoDB to initialize. (5 minutes)
	connected
	formspoint-clients stop/waiting
	formspoint-clients start/running, process 17998
	Waiting for 30 seconds while app is booting up
	Checking is app booted or not?
	formspoint-clients stop/waiting
	formspoint-clients start/running, process 18226
	----------------------------------------------------------------------------
