### ISSUE TITLE
Setting up Environment: FAILED

### ISSUE THREAD

**Issue by toutoclic** [arunoda/meteor-up-legacy#522]
Hi,
I try to deploy my project from mac to Amazon server. I got an error "Setting up Environment: FAILED" when I execute mupx setup.
Where this error can leave? I doesn't have any setting environnement.

Thanks,
Yoann

**Comment by Ethaan** [comment]
Could you please type 

```
mup logs -n1000
```

and paste the error?

Btw, check #521

**Comment by Ethaan** [comment]
reffer also to  #521

**Comment by toutoclic** [comment]
I get the error: "sorry, you must have a tty to run sudo"

**Comment by toutoclic** [comment]
Hi,
I try to deploy with mup. I don't have the same errors. 
When I want deploy (after my setup ok), I have this error : 'Uploading bundle: FAILED No such file'

I try modified my sudoers file with 

```
root    ALL=(ALL:ALL)   ALL
%admin  ALL=(ALL)       NOPASSWD:ALL
%sudo   ALL=(ALL)       NOPASSWD:ALL
myUser       ALL=(ALL)       NOPASSWD:ALL
```

But I have always the same errors ... I don't know what I can do :/

Yoann

**Comment by aadamsx** [comment]
Thanks @Ethaan , using mup logs -n1000 worked for me!

**Comment by toutoclic** [comment]
I spent a great night! Upon awakening I just commented "requiretty Defaults" in my sudoers file.

and everything is OK!

Thanks,
Yoann
