### ISSUE TITLE
Error on mup setup

### ISSUE THREAD

**Issue by wentjun** [arunoda/meteor-up-legacy#530]
Hi,

While following the instructions over here (https://github.com/arunoda/meteor-up#ssh-keys-with-passphrase-or-ssh-agent-support), I received the following the following error:

/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:221
        throw err;
              ^
Error: Parse error on line 6:
...                 }  ],    "setupM
--------------------^
Expecting 'STRING', got '}'
File: "/Users/WenTjun/workspace/Meteor-chatapp/mup.json"
    at Object.parseError (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.parse (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:88:28)
    at Object.load (/usr/local/lib/node_modules/mup/node_modules/cjson/index.js:218:24)
    at Object.exports.read (/usr/local/lib/node_modules/mup/lib/config.js:12:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:20:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

If you are wondering, this is what i did which led to the error message:
1) "eval $(ssh-agent)"
2) "ssh-add <path-to-key>"
3) enter passphrase as per requested
4) "mup setup"

I understand that this issue is similar to #312, but so far i can't find a satisfactory solution on it. Thanks for reading!

**Comment by arunoda** [comment]
Your mup.json is formatted incorrectly. Fix it.

**Comment by wentjun** [comment]
I've checked my mup.json. It seems correct; Can't figure out whats wrong though.

{
  // Server authentication info
  "servers": [
    {
      "host": "128.199.123.114",
      "username": "root",
      // "password": "password"
      // or pem file (ssh based authentication)
      // "pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server.
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "NUSChat",

  // Location of app (local directory)
  "app": "~/workspace/Meteor-chatapp",

  // Configure environment
  "env": {
    "ROOT_URL": "http://128.199.123.114"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

**Comment by MasterJames** [comment]
You have no password and so then your last line has a comma .
uncomment password or remove the comma from the last line in the {} block.
testing for this can be done by removing lines or blocks one at a time a process of elimination. Once you have the line go words or letters different from the example.

**Comment by wentjun** [comment]
Oh gosh.. How could i miss out that comma! Thanks for pointing out! Really appreciate your help guys @arunoda and @MasterJames
