### ISSUE TITLE
Deploy error can't connect to mongo db

### ISSUE THREAD

**Issue by bitspook** [arunoda/meteor-up-legacy#54]
So I had to move from meteor.sh to mup as meteor.sh is no longer working for latest meteor version. 

I have set up mup, everything goes fine on deployment but in the end it gives me the error that it can't connect to mongo. Any ideas about what might be going wrong here?

The Error:
[54.215.253.100] ✘ Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
Warning: Permanently added '54.215.253.100' (RSA) to the list of known hosts.
npm http GET https://registry.npmjs.org/fibers
npm http 200 https://registry.npmjs.org/fibers

/usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
    throw err;
          ^
Error: TIMEOUTED_WAIT_FOR_MONGO
    at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
-----------------------------------STDOUT-----------------------------------
st:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
wait-for-mongo: failed to connect to [localhost:27017]
----------------------------------------------------------------------------
```

This is what I am using for mongo_url:

``` sh
    "env": {
        "ROOT_URL": "http://my_app.com",
        "MONGO_URL": "mongodb://localhost:27017/app_name"
    },
```

**Comment by arunoda** [comment]
Seems like your local MongoDB server is down. Check that a bit.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it
out!http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by bitspook** [comment]
Checked. It was running. I was able to log in to the mongo shell and all the data. I gonna bring down that ec2 instance and try fresh as the last resort. 

---

Charanjit Singh
Github || Twitter || +91-7696166158

**Comment by bitspook** [comment]
Okay. Got it to working without swaping the OS. The only difference this time was that I had the mongo shell open via ssh. Even for like last 3 tries, I was manually starting the mongo from console and getting that message. This time it worked. Might be some fuck up in my instance.

@arunoda Thanks for replying by the way. Big fan of meteor hacks and rest of your work. Great work.

**Comment by arunoda** [comment]
Cool. Thanks.

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
 http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
