### ISSUE TITLE
error: app is not compatible with architecture 'os.linux.x86_64'

### ISSUE THREAD

**Issue by zimt28** [arunoda/meteor-up-legacy#541]
I just tried to update a project using MUPX, but now get this error:

> Errors prevented bundling:
> While linking the program:
> error: app is not compatible with architecture 'os.linux.x86_64'
> => Build Error. Check the logs printed above.

The logs are not very helpful here, any idea how I could find a fix?

**Comment by MasterJames** [comment]
You have followed the "update migration guide" instructions to make a clean deployment?

**Comment by zimt28** [comment]
Turns out it wasn't a MUP problem but a npm dependency wouldn't work for some reason.

**Comment by ChenLi0830** [comment]
Hi @zimt28, do you still remember what did you do to fix the problem? I am having the exact same error after upgrading to meteor 1.3.

**Comment by crapthings** [comment]
we have exact same error too

**Comment by zimt28** [comment]
Hey @ChenLi0830 and @crapthings, unfortunately I don't remember that; I think it was a package from NPM which caused the problems and I ended up using another one.

However, I "installed the problem into my app", and it's possible that your problem is actually caused by packages Meteor uses internally. You might just have a look at https://github.com/meteor/meteor/issues/6537, good luck :)

**Comment by MadeInMoon** [comment]
I had the same problem. 

I deleted `node_modules/` & `.meteor/local` and run `$ npm install`& `$ meteor`, and it worked..
