### ISSUE TITLE
mupx deploy error response from daemon: no such id

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#544]
On a fresh DO droplet, I did

```
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install npm
sudo ln -s /usr/bin/nodejs /usr/bin/node
npm install -g mupx
```

and `mupx init`, `mupx setup` and `mup deploy` gave me this

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /root/myApp
Using buildOptions : {}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

`mupx logs --tail=50` gave me
`Error response from daemon: no such id: myApp`

Can anyone help point me in the right direction for debugging? Thanks all!

**Comment by ghost** [comment]
what was the issue?

**Comment by markudevelop** [comment]
Same issue here any fix for this? Fresh droplet.
UPDATE: ah of course! Install meteor! curl https://install.meteor.com/ | sh

**Comment by MasterJames** [comment]
I wondered if the thread creator thought to edit his mup.json after mupx init.  His comments of process skipped the obvious step but there is no settings file posted. The default myApp suggests the same. 
He would have had to set a valid host username password etc.It's the only conclusion one can derive at this point.
Was there a meteor app at /root/myApp ? Probably not.

**Comment by ghost** [comment]
This error is due to not having meteor installed as indicated by @voidale
