### ISSUE TITLE
Meteor Deploy to EC2 successful but does not work

### ISSUE THREAD

**Issue by lancygoyal** [arunoda/meteor-up-legacy#547]
I have successfully deployed a meteor app to an aws ec2 server via meteor-up.but it does not work, i am using ami - ami-5189a661for Amazon EC2.

ERR_CONNECTION_TIMED_OUT

PING 52.26.202.242 (52.26.202.242): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6

Public DNS
ec2-52-26-202-242.us-west-2.compute.amazonaws.com

Can you please help.

**Comment by namsouth** [comment]
You may need to open the port 80 to access your meteor application

**Comment by lancygoyal** [comment]
Thank you, its working fine now. Added http rule in security group.

**Comment by lancygoyal** [comment]
@arunoda Please close this issue. Thank u for your time and MUP.
