### ISSUE TITLE
Bundling Error: code=-1, error:spawn ENOENT

### ISSUE THREAD

**Issue by cramhead** [arunoda/meteor-up-legacy#56]
Hi Aronuda,

I'm getting this error on deploying. I've run mup init and mup setup with no errors. It seems to have a problem bundling, but I can call meteor bundle bundle.tgz and it seems to work fine. 
I fired up node-inspector with export NODE_OPTIONS='--debug-brk'; node-inspector & and message that states that it's listen pops up, but when I run mup deploy the message following outputs without node-inspector breaking. 
Is there a good way to debug this?
Any thoughts on the error?

Thanks Marc

```
Lava:app cram$ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Bundling Started: /Users/marc/Projects/METEOR/Sqwrl/app
Bundling Error: code=-1, error:spawn ENOENT
-------------------STDOUT-------------------

-------------------STDERR-------------------
```

**Comment by cramhead** [comment]
I resolved the error condition.
The problem was that I was deploying from a different machine, and as such, have a different username and home directory path. I changed the location of the app parameter and all worked well. 

I'm aim still wondering how to debug, but I'll close the open issue.

**Comment by crapthings** [comment]
@cramhead

hey @cramhead how do u solve your error?

**Comment by cramhead** [comment]
The path to the project was wrong. When I moved from machine to machine the locations of the checkout were different. The mup.json file app value needs to point the correct location. Using a symbolic link or relative path is my approach to allowing variation in path while still keeping the mup.json the same.

**Comment by brylie** [comment]
I just had this issue as well. I had moved my local development folder to a new location and failed to update the mup.json settings.

**Comment by papayaah** [comment]
can we make so that mup look up for current directory?
