### ISSUE TITLE
Add support for MongoDB SSL

### ISSUE THREAD

**Issue by lorensr** [arunoda/meteor-up-legacy#563]
For instance, through Compose:

https://www.compose.io/articles/going-ssl-with-compose-mongodb-plus/

Currently doesn't appear to support SSL URIs: 

```
TypeError: Cannot read property 'master' of undefined
  ...
  at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
  ...
```

**Comment by arunoda** [comment]
May be you need to ask this on Meteor issue list.
We may need some core changes.

**Comment by lorensr** [comment]
Got it, thanks. https://github.com/meteor/meteor/issues/4812
