### ISSUE TITLE
Where does mupx deploy write files?

### ISSUE THREAD

**Issue by daslicht** [arunoda/meteor-up-legacy#564]
Do I understand it correct that mupx deploy will create a prepared copy of my meteor app?
Where does it create those files?

How to remove a deployed app?

**Comment by MasterJames** [comment]
I think it's /opt/appName 
stop it first remove it
maybe stop mongo
typically the kubernettes container can be destroyed as easily as its created and removal is a meaningless question as I understood it.
personally I'd rather see a shared folder AWS EFS and have a remove option.
just waiting on EFS for now myself.

**Comment by daslicht** [comment]
Thank you !
