### ISSUE TITLE
It gets stuck on 'Invoking Deployment Process'

### ISSUE THREAD

**Issue by Netherdrake** [arunoda/meteor-up-legacy#567]
```
Started TaskList: Deploy app 'meteor' (linux)
[domain] - Uploading bundle
  nodemiral:sess:domain copy file - src: /tmp/e5185b8e-0395-4440-98f5-dac5f4c3cc46/bundle.tar.gz, dest: /opt/meteor/tmp/bundle.tar.gz, vars: undefined +0ms
[domain] - Uploading bundle: SUCCESS
[domain] - Setting up Environment Variables
  nodemiral:sess:domain copy file - src: /usr/local/lib/node_modules/mup/templates/linux/env.sh, dest: /opt/meteor/config/env.sh, vars: {...} +41s
[domain] - Setting up Environment Variables: SUCCESS
[domain] - Invoking deployment process
```

It worked the first time, but not anymore.

**Comment by MasterJames** [comment]
Seems like a networking error.

**Comment by Netherdrake** [comment]
But it happens every time. It hangs for a few hours, then deploys.

**Comment by tjflaagan** [comment]
+1 Haven't got it to actually deploy yet, it just hangs. mup setup works remotely.

**Comment by MasterJames** [comment]
Maybe open the ports of the firewall?

**Comment by elie222** [comment]
There's a problem with mup 0.11.1

Revert back to 0.11.0 and it should work:
`sudo npm install mup@0.11.0 -g`

**Comment by Netherdrake** [comment]
@MasterJames I have allowed the connection.
@elie222 doesn't seem to work either.

The problem persists, the DEPLOY step is stuck for a few hours, and then it goes thru. Why the delay?

**Comment by MasterJames** [comment]
It's probably something to do with the service providers and not mup or meteor related.
You need to test each steps support ssh and file transfer etc I guess. Maybe you have more logs to post where it hangs.

**Comment by d-i-b** [comment]
+1 @MasterJames I have the same issue but mupx logs provides nothing, how can I trace what happened?

**Comment by MasterJames** [comment]
Well dib elie's problem seems to be the connection.
One should always try to confirm manually at each step at a low level things are working and how well. 
Confirming with a different provider or computer that there's a networking performance problem and then move on with comparisons and find the differences. You could just compare to FTP on a few medium sized files, time taken, success, etc.
http://www.cyberciti.biz/faq/check-network-connection-linux/
Maybe a monitor would help too http://www.aboutlinux.info/2006/04/iptraf-reliable-network-monitoring.html
http://www.firewall.cx/networking-topics/general-networking/970-network-performance-testing.html

First use this below (for extra log info) ...

```
DEBUG =* mupx deploy
```

Search the repository for the last thing before it fails that can be found.
Put an exit() or comment out or delete revert_app
https://github.com/arunoda/meteor-up/blob/456bd5913b3867243b8844f311f756bcea765a73/templates/linux/deploy.sh#L138

Then you can SSH into the target host check what worked or failed or see with your own eyes as you try each command manually from the break/exit point.

**Comment by Netherdrake** [comment]
My problem has been resolved.

The issue was that the NTP service didn't run properly, so time on server was several hours off and thats why the `mup deploy` would just hang for hours.

**Comment by MasterJames** [comment]
Wow that's odd, I'll have to think about how that caused it to wait? Any deeper thoughts why NTP affected what?
Glad you got the networking sorted!

**Comment by d-i-b** [comment]
@MasterJames Thank you for the detailed answer! I found that my client had banned quite a lot stuff and ports on their azure server..
