### ISSUE TITLE
Error: read ETIMEDOUT  -  Unhandled 'error' event

### ISSUE THREAD

**Issue by harlyluyar** [arunoda/meteor-up-legacy#568]
I am hitting this error again and again, when deploying to AWS Ubuntu server:

"Started TaskList: Deploy app 'myapp' (linux)
[5.7.9.210] - Uploading bundle
[========                               ] 23% 0.9sevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:550:26)
"

It was working stably. The same code failed now. Can ssh to this server.
This is blocking our team. Any suggestion is appreciated.

**Comment by harlyluyar** [comment]
Arunoda, any idea? Hope to get your feedback soon, coz it is blocking our whole team now :(

Thanks a lot and really appreciate

**Comment by arunoda** [comment]
This seems like normally a internet / ISp issue.

Try to proxy via another server or use it in a service like codeship.

**Comment by harlyluyar** [comment]
Thanks for the quick reply, Arunoda!
I do not understand: I can ssh to that AWS server on the same MAC, so this means there is not connection issue, am I right?

**Comment by arunoda** [comment]
It's different. Here you could connect. But error throws after some times.
Some ISPs kill these kind of long connections.

**Comment by harlyluyar** [comment]
BTW: I can run 'mup stop; mup start' on that server now (for last deployment, which was successful)

**Comment by harlyluyar** [comment]
OK, I will try from a different network later. Thanks~

**Comment by harlyluyar** [comment]
It works now! after changing to a better network.
Thanks a lot, Arunoda!

**Comment by arunoda** [comment]
Hope we can close this issue.
