### ISSUE TITLE
mup deploy Error: spawn ENOENT events.js:72

### ISSUE THREAD

**Issue by Jayuda** [arunoda/meteor-up-legacy#570]
Hello,
I am Tried to deploy my meteor app with mup but get this error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

Please help me.
Thanks

I was use this recommendation :
https://github.com/arunoda/meteor-up/issues/405

And 

https://github.com/arunoda/meteor-up/issues/556

But not solved.

**Comment by digz6666** [comment]
I Have a same problem.

**Comment by pmuens** [comment]
Same here

**Comment by elie222** [comment]
There's a problem with mup 0.11.1

Revert back to 0.11.0 and it should work:
`sudo npm install mup@0.11.0 -g`

**Comment by sonicviz** [comment]
I was using mup 0.11.1 just fine, now I'm getting the same error as above.
Reverting to 0.11.0 just results in the same error.

Any clues? It doesn't give much to go on.

**Comment by elie222** [comment]
Yeah. I was wrong. For me it works 1 in 2 times approximately. There were
some other people posting about it. Someone said he updated node on the
server to 0.12 and that helped

**Comment by sonicviz** [comment]
I was wrong too;-) I was just about to delete this but you answered.
I'd renamed the directories and though the mup.json had the right name but apparently not.

The error is not really informative though.

Solution for me was:
tbbooher commented on Jun 29
ok -- for others looking at this -- make sure your

// Location of app (local directory)
  "app": "/Users/foo/Sites/happy",
is correct

from https://github.com/arunoda/meteor-up/issues/405

**Comment by Jayuda** [comment]
Hello Mr @sonicviz ,
I've checked the location of the app. But it did not work for me. 
Can you explain order of settings you did. Please.
Thank you verry much

**Comment by elie222** [comment]
The order of the settings doesn't matter. Go to the folder of your app in
the command line and write pwd and you'll get the path of the folder you
need. Use that for the app location

**Comment by sonicviz** [comment]
I just put the full location
eg:

**Comment by sonicviz** [comment]
I just put the full path, ie:
  // Location of app (local directory)
  "app": "G:/Meteor Projects/MyMeteorProject/",

So far it's working ok _touch wood_ deploying to EC2 Ubuntu with SSL

**Comment by Jayuda** [comment]
Still does not work, may God dont bless my code. wkwkwkw,... :+1:

**Comment by elie222** [comment]
Try mupx

**Comment by MasterJames** [comment]
I'm wondering if the drive letter G would be problematic.

**Comment by sonicviz** [comment]
no

**Comment by MasterJames** [comment]
So the trailing slash neither to then I guess.

**Comment by sonicviz** [comment]
Seems to work fine with or without

**Comment by digz6666** [comment]
I had specified server path on app, changed to my local project path and issue resolved.

**Comment by MasterJames** [comment]
Exactly well done! So app is where to put it not where to find it? It finds in in the working directory. Correct?

**Comment by digz6666** [comment]
My folder structure is like following.

```
meteor_deploy/mup.json
meteor_deploy/settings.json
meteor_app/.meteor
meteor_app/client
meteor_app/public
meteor_app/server
```

My mup.json is like following:

``` javascript
{
  // Server authentication info
  "servers": [
    {
      "host": "99.99.99.92",
      "username": "root",
      "password": "blabla"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "blabla",

  // Location of app (local directory)
  //"app": "/home/astvision/autoland", // server path which caused the issue
  "app": "../meteor_app",

  // Configure environment
  "env": {
    "ROOT_URL": "http://blabla.mn",
    "PORT": 3000
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}
```

**Comment by MasterJames** [comment]
I see thank you I hope it helps the other guy with the G folder issue.

**Comment by sonicviz** [comment]
I don't have a "G folder issue".
My mup is currently in a different folder for a reason.

**Comment by MasterJames** [comment]
Right sorry.
Maybe post your settings files and logs to see clearer what other ideas might lead to a solution for you.

**Comment by sonicviz** [comment]
I don't have a problem at all. It works just fine.-> https://github.com/arunoda/meteor-up/issues/570#issuecomment-127023983

**Comment by MasterJames** [comment]
Oh sorry it's jayuda that still had a problem I thought it was you.
I was away and had 400+ emails so my sincerist apologies.

**Comment by ClarenceL** [comment]
I have this problem since 0.10.8, I've reverted back to 0.10.7 and it works, so my directories are named correctly.

## Meteor Up: Production Quality Meteor Deployments

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: /Users/zzzzzzzz/workspace/zzzzz-mobile/mobile

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

---

| ~/workspace/zzzzz-mobile/mobile @ Clarences-MacBook-Pro (zzzzzzzz) 
| => sudo npm install -g mup@0.10.7
| ~/workspace/zzzzz-mobile/mobile @ Clarences-MacBook-Pro (zzzzzzzz) 
| => mup deploy

## Meteor Up: Production Quality Meteor Deployments

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: /Users/zzzzzzzz/workspace/zzzzz-mobile/mobile
The Android platform is not installed; skipping build for it.

Started TaskList: Deploy app 'zzzzz-mobile' (linux)
[xxx.xxx.xxx.xxx] - Uploading bundle
[xxx.xxx.xxx.xxx] - Uploading bundle: SUCCESS
[xxx.xxx.xxx.xxx] - Setting up Environment Variables
[xxx.xxx.xxx.xxx] - Setting up Environment Variables: SUCCESS
[xxx.xxx.xxx.xxx] - Invoking deployment process
[xxx.xxx.xxx.xxx] - Invoking deployment process: SUCCESS

**Comment by suchipi** [comment]
Make sure meteor is installed and up-to-date on the system you are trying to deploy from; that was my problem.

**Comment by ClarenceL** [comment]
Updated Meteor to 1.2, this issue is back again, I really want to track down this path issue!

**Comment by ClarenceL** [comment]
Ok for now I can at least deploy with an ugly hack 

[https://github.com/arunoda/meteor-up/issues/609#issuecomment-143689075](https://github.com/arunoda/meteor-up/issues/609#issuecomment-143689075)

**Comment by natewallis** [comment]
Hi all - if you are using PEM authentication make sure you are able to SSH to your server.  I only allow SSH from a single IP on my EC2 instance and I had forgotten to change the IP back in the AWS console after returning home.  mup makes it look like there is an error with your javascript when there may not be - it looks like this happens when it can't access the server

**Comment by MPJHorner** [comment]
Did you have Meteor install on the local machine? This fixed the error for me.

**Comment by delueg** [comment]
for me it was also false directory.

i said "./myapp" // the directory where .meteor lives 

but he couldn't recognize it

then "/Users/mymacusername/Development/myapp"

was solving this issue for me
