### ISSUE TITLE
Oplog issue 

### ISSUE THREAD

**Issue by isAlmogK** [arunoda/meteor-up-legacy#575]
I just added the mongo oplog url and when I deploy everything is fine but my app is not loading any ideas 

this is the url 

"MONGO_OPLOG_URL": "mongodb://myusername:mypassword@c290.capital.3.mongolayer.com:10290,capital.2.mongolayer.com:10290/local?authSource=linkly"

**Comment by isAlmogK** [comment]
This is what I get in the logs 
linkly start/running, process 18943

**Comment by TimFletcher** [comment]
A code search of mup doesn't seem to return any results for `MONGO_OPLOG_URL`, only `MONGO_URL`. My guess is that the oplog is supported via `MONGO_URL`.

**Comment by TimFletcher** [comment]
Although [this](https://github.com/arunoda/meteor-up/issues/245#issuecomment-108378662) recent comment would indicate it's still valid.

**Comment by MasterJames** [comment]
What happens if you put only one domain:port ?

**Comment by isAlmogK** [comment]
I finally was able to get to the bottom of this, in your username or password you can't have any special characters like "@#$" that was causing the issue

**Comment by TimFletcher** [comment]
@almogdesign Argh. I've had that in the past. Thanks for updating the issue with your solution.
