### ISSUE TITLE
Setup failing on Ubuntu 15.04 x64

### ISSUE THREAD

**Issue by hassanasad** [arunoda/meteor-up-legacy#591]
Hi

I am trying to setup meteor to run on a newly created droplet on digital ocean with OS Ubuntu 15.04 x64

This is the error i am getting:

```
Started TaskList: Setup (linux)
[trialsmap.com] - Installing Node.js
[trialsmap.com] - Installing Node.js: SUCCESS
[trialsmap.com] - Installing PhantomJS
[trialsmap.com] - Installing PhantomJS: SUCCESS
[trialsmap.com] - Setting up Environment
[trialsmap.com] - Setting up Environment: SUCCESS
[trialsmap.com] - Copying MongoDB configuration
[trialsmap.com] - Copying MongoDB configuration: SUCCESS
[trialsmap.com] - Installing MongoDB
[trialsmap.com] x Installing MongoDB: FAILED

        -----------------------------------STDERR-----------------------------------
        rm: cannot remove ‘/var/cache/apt/archives/lock’: No such file or directory
        gpg: requesting key 7F0CEB10 from hkp server keyserver.ubuntu.com
        gpg: key 7F0CEB10: "Richard Kreuter <richard@10gen.com>" not changed
        gpg: Total number processed: 1
        gpg:              unchanged: 1
        sudo: stop: command not found
        sudo: start: command not found
        -----------------------------------STDOUT-----------------------------------
        nslation-en
        Ign http://downloads-distro.mongodb.org dist/10gen Translation-en
        Hit http://mirrors.digitalocean.com vivid-updates/main Sources
        Hit http://mirrors.digitalocean.com vivid-updates/universe Sources
        Hit http://mirrors.digitalocean.com vivid-updates/main amd64 Packages
        Hit http://mirrors.digitalocean.com vivid-updates/universe amd64 Packages
        Hit http://mirrors.digitalocean.com vivid-updates/main i386 Packages
        Hit http://mirrors.digitalocean.com vivid-updates/universe i386 Packages
        Hit http://mirrors.digitalocean.com vivid-updates/main Translation-en
        Hit http://mirrors.digitalocean.com vivid-updates/universe Translation-en
        Reading package lists...
        Reading package lists...
        Building dependency tree...
        Reading state information...
        mongodb-org is already the newest version.
        mongodb-org-server is already the newest version.
        mongodb-org-shell is already the newest version.
        mongodb-org-tools is already the newest version.
        0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
        ----------------------------------------------------------------------------
```

Can you please help me out.

P.S: 
I had to install python on my server first ( `apt-get install python-minimal` )
Then it gave error trying to setup mongoDB. I researched online and used this command `sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10` after which that particular error disappeared but now the above is showing.

**Comment by MasterJames** [comment]
Maybe see if the non minimal version of python makes a difference. So uninstall python-minimal and do just
 apt-get install python
Next try mupx if you have mup follow upgrade instructions.
Also try a larger RAM instance (once working by other means potentially see how small you can still run it).
Also extend the deployCheckWaitTime to 120 (similarly to ram size bring it back later to something that is optimized).

**Comment by hassanasad** [comment]
Ok - have reinstalled python. The installed Python is version `2.7.9`

I have a droplet with 2GB ram and its clean. So that shouldn't be a problem. I have tried extending the `deployCheckWaitTime` to 120. Still the same issue :(

Can it be a firewall issue by any chance ?

**Comment by MasterJames** [comment]
If you can build/use a new (apparently) undamaged Ubuntu image!?
Try repairing the fault with something like this..
http://serverfault.com/questions/109970/debian-ubuntu-how-to-restore-var-cache-apt-structure-after-deleting-it

Clean the get-apt package tool cache

**Comment by hassanasad** [comment]
Thanks, i have tried creating a lock file and do it that way.

The thing i have noticed is when it says `Installing MongoDB` on mup application, it removes the lock file on server.

Can i install mongoDB on my own and skip this step?

**Comment by hassanasad** [comment]
Yeah i think i might have discovered the problem. There is no official distribution of MongoDB for Ubuntu 15.04 released so far ( https://www.mongodb.org/downloads#development )

**Comment by MasterJames** [comment]
You can try in the settings
"setupMongo": false,
I think you can use in env something like...
 "env": {
...
    "MONGO_URL": "mongodb://user:password@hanso.mongohq.com:10023/MyApp",
...
  },
Maybe close this when your satisfied. Thank you and happy computing.

**Comment by hassanasad** [comment]
Yeah i will close this issue. Its an issue with MongoDB and Ubuntu version. Nothing meteor up can do about it :)
