### ISSUE TITLE
When I finish deploy my app on server,dose it started?

### ISSUE THREAD

**Issue by Silence-wzy** [arunoda/meteor-up-legacy#595]
When I finish deploy my app on server,dose it started?

And how can I visit my app?

I‘m a newcomer...

Thank you!

**Comment by MasterJames** [comment]
You can check your logs out via 
mupx logs -f 
for error messages
mupx deploy will
mupx is the dev branch for mup but has improvements and is seemingly better to use.
see migration instructions if needed...
https://www.npmjs.com/package/mupx#migrating-from-meteor-up-0-x

This might help you get started
https://www.youtube.com/watch?v=WLGdXtZMmiI

To access the running server look in the settings file. There you have
"env": {
    "PORT": 80,
    "ROOT_URL": "http://myapp.com"
  },

hit the webserver with the correct IP or routed URL and port number.

**Comment by MasterJames** [comment]
There is also
mupx start
and
mupx stop
https://github.com/arunoda/meteor-up/tree/mupx#other-utility-commands

**Comment by Silence-wzy** [comment]
thank you for your vidio,but I still can not deploy successfully,can you give me some suggestion?

![Uploading QQ截图20150813165318.png…]()

**Comment by Silence-wzy** [comment]
thank you for your help.I access my app with IP.
