### ISSUE TITLE
Digital Ocean+Meteor Image and meteor-up

### ISSUE THREAD

**Issue by katopz** [arunoda/meteor-up-legacy#604]
I saw Digital Ocean provide 1 click to install Meteor is that same as meteor-up?
Or do I need to choose that image anyway and also need meteor-up?

Yes! I'm confuse! Thanks!

**Comment by arunoda** [comment]
That's meteor development version. It's not for production deployment.

You don't need that and you shouldn't use that. Use a plain Ubuntu VM.

**Comment by katopz** [comment]
@arunoda Cool Thanks! What a quick reply! :rabbit:
