### ISSUE TITLE
"mupx deploy" failed due to error "Can't find npm module 'double-ended-queue"

### ISSUE THREAD

**Issue by andyxueyuan** [arunoda/meteor-up-legacy#614]
The following error occurred when I tried to run the command **mupx deploy**. 

I have tried two PaaS: **Windows Azure** and **AWS** both running _Ubuntu 14.04_.
I have tried to deploy both my app and the template app "simple-todos".

<img width="676" alt="screen shot 2015-08-21 at 12 56 22 pm" src="https://cloud.githubusercontent.com/assets/4667716/9400374/12737928-4804-11e5-80a2-812b904dc216.png">

Any solutions? Thank you.

**Comment by arunoda** [comment]
We've seen these issues when deploying with windows. I'm not sure you are deploying from Windows. 
If not try using something other than Azure.

**Comment by andyxueyuan** [comment]
Appreciate your prompt reply. I’m deploying from Mac. 

What alternative service providers are you recommending? Thank you in advance.

**Comment by arunoda** [comment]
Digital Ocean, Google Cloud, AWS.

We haven't tested on Azure.

**Comment by arunoda** [comment]
If this is still happening, could you send me a reproducible app. Then we can work on it.

**Comment by andyxueyuan** [comment]
Thank you.

**Comment by arunoda** [comment]
Did it work?

**Comment by andyxueyuan** [comment]
Will try on other providers. Will let you know.

**Comment by arunoda** [comment]
Okay.

**Comment by MasterJames** [comment]
Try 
meteor reset

**Comment by andyxueyuan** [comment]
Thanks MasterJames for the comment. Tried ""meteor reset", and still got the same error.

**Comment by andyxueyuan** [comment]
Hi:

I switched to AWS, but the same error occurred. I also tried to deploy the template "simple-todos" app, and the same error occurred. Any fixes? Really appreciate it.

**Comment by MasterJames** [comment]
I guess you should post your settings and logs at this point not much to go on.
There is an option explained for DEBUG logs if you find that try ito to maybe.
Any version numbers for node, Ubuntu, meteor etc may also lead to an understanding of this problem you're having.

**Comment by MasterJames** [comment]
Maybe this will help
https://github.com/meteor/meteor/issues/3432

Reinstall meteor is what it says.
The meteor reset only fixes Mongo.

**Comment by andyxueyuan** [comment]
@MasterJames The problem is finally solved after I followed your instruction to completely uninstall Meteor from my local machine. Appreciate your help.

For a reference, this is what I did:

``` bash
# completely delete meteor on my local machine
sudo rm /usr/local/bin/meteor
rm -fr ~/.meteor

# reinstall Meteor
curl https://install.meteor.com/ | sh

# update Meteor project
cd myMeteorApp
meteor reset
meteor update

# deploy
mupx init
mupx setup
mupx deploy
```
