### ISSUE TITLE
 Invoking deployment process failed [one more problem]

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [arunoda/meteor-up-legacy#625]
Hi, there,
I'm trying to deploy my meteor in an amazon ec2 instance using ubuntu 14.04 using `mup` .

`mup setup` ran successfully but Here is the error I got in the last step of `mup deploy` :

```
x Invoking deployment process: FAILED:
-----------------------------------STDERR-----------------------------------
npm ERR! network connect ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/annuaire/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/annuaire/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/npm-debug.log
npm ERR! not ok code 0
-----------------------------------STDOUT-----------------------------------
 > ./bcrypt: npm install due to binary npm modules
----------------------------------------------------------------------------
```

What am I doing wrong?
Thanks in advance and thank you for this great package
HR

**Comment by MasterJames** [comment]
Is this Ubuntu 14 you're deploying too? 
I think you need a compatible instance.

**Comment by MasterJames** [comment]
Sorry I see you said that.
It says you have a network problem.
Are your settings installing node?

**Comment by RanaivosonHerimanitra** [comment]
I'm deploying on Ubuntu 14.04 ec2 micro instance on aws...
My local node version is : v0.11.14-pre 
My meteor packages are: 

```
accounts-facebook      1.0.4  Login service for Facebook accounts
accounts-google        1.0.4  Login service for Google accounts
accounts-password      1.1.1  Password support for accounts
accounts-ui            1.1.5  Simple templates to add login widgets to an app
bootstrap              1.0.1  Front-end framework from Twitter
cfs:standard-packages  0.5.9  Filesystem for Meteor, collectionFS
dsyko:meteor-node-csv  0.3.7  node-csv npm packaged for meteor.
insecure               1.0.3  Allow all database writes by default
iron:router            1.0.9  Routing specifically designed for Meteor
jquery                 1.11.3_2  Manipulate the DOM using CSS selectors
meteor-platform        1.2.2  Include a standard set of Meteor packages in y...
meteorhacks:npm        1.4.0  Use npm modules with your Meteor App
mizzao:bootstrap-3     3.3.1_1  HTML, CSS, and JS framework for developing r...
mrt:bootstrap-select   1.5.4  A custom select/multiselect for @twitter boots...
npm-container          1.1.0+ Contains all your npm dependencies

```

My `mup.json` settings are:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "xx.xx.xxx.xx",
      "username": "ubuntu",
      //"password": "password"
      // or pem file (ssh based authentication)
      "pem": "/home/herimanitra/Téléchargements/meteor.pem"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  //"nodeVersion": "0.10.36",
  "nodeVersion": "0.12.7",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "annuaire",

  // Location of app (local directory)
  "app": "/home/herimanitra/annuaire",

  // Configure environment
  "env": {

    "ROOT_URL": "http://xxxxxxxxx.us-west-2.compute.amazonaws.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

```

Should I remove `npm-container` ? [No, I guess]

Are my security group correct ?:
inbound type: ssh
inbound protocol: TCP
inbound Port range: 22
inbound Source: my IP

Outbound type: htttp
Outbound protocol: TCP
Outbound port range: 80
Outbound destination: anywhere

**Comment by semikolon** [comment]
Same problem here! :(

**Comment by semikolon** [comment]
Solved my problem upgrading node (http://davidwalsh.name/upgrade-nodejs) on the server to 0.10.36 from 0.10.34 (mup didn't upgrade despite several runs of "mup setup"...)

**Comment by MasterJames** [comment]
To use NPM to update nodeJS 

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

Or you can n version
Current stable is 0.12.7 noted in your settings.
There is one locally and one being pushed to the instance when deploying.
Maybe keep both the same. It looks like some version causes problems so you may try upgraging or downgrading helps for compatibilités with mupx etc.

You could double check (try) if you need inbound http too. I don't know off hand it's in various walk throughs. (Minor typo htttp 2 Ts in http of course)

**Comment by RanaivosonHerimanitra** [comment]
I both tried downgrading to 0.10.36 and upgrading to the latest stable version (0.12.7) using your advices. Still getting an error:

```
x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    npm ERR! network connect ETIMEDOUT
    npm ERR! network This is most likely not a problem with npm itself
    npm ERR! network and is related to network connectivity.
    npm ERR! network In most cases you are behind a proxy or have bad network settings.
    npm ERR! network 
    npm ERR! network If you are behind a proxy, please make sure that the
    npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

    npm ERR! System Linux 3.13.0-48-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! cwd /opt/annuaire/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! syscall connect
    npm ERR! code ETIMEDOUT
    npm ERR! errno ETIMEDOUT
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /opt/annuaire/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/npm-debug.log
    npm ERR! not ok code 0
    -----------------------------------STDOUT-----------------------------------
     > ./bcrypt: npm install due to binary npm modules

```

I also tried to export proxy `export HTTP_PROXY=http://xx.xx.xx.xxx` without chance.

**Comment by MasterJames** [comment]
Did you put ingres for http yet? 
I think you need to check your network firewall rules etc. are working too.
It also says in the log...
"Additional logging details can be found in npm-debug.log"
Anyway it says the network is most likely at fault.
Maybe try to SSH in and test the network setup via ping and curl etc.

**Comment by RanaivosonHerimanitra** [comment]
Can you elaborate more on this. I'm not very good at networking stuff. What steps should I follow ?

**Comment by MasterJames** [comment]
First off it looked like you did not setup Ingress for HTTP port 80
This might be a bit of a higher level then you want to see but there are online interfaces provided by AWS for all this stuff too.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html

Also see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html

**Comment by MasterJames** [comment]
So you wanna use SSH (at Amazon) start here...
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-connect-to-instance-linux.html
eventually you put on the command line 
ssh user@hostnameOrIP
and enter a password (if not using PEM {these options are also set in mup.json of course}).
Then you can easily access what's happening and test things on the deployment server.
'curl' is a command to get a webpage. if it works locally from the SSH {Secure SHell} and you test it (via curl or browser) remotely too with the IP/hostname you SSHed to and you don't get the page then it's something in the network routing (possibly ingress rules, etc.).
This is really beyond the scope of this forum and you should maybe look or ask on stackoverflow.
You can view process and logs via typical unix commands (ps, ls, cat, etc.)

Take sometime maybe a week or whatever it takes to get more familiar with the puzzle pieces and how they fit together. Walk through each logical step confirming it's working before moving on to the next (basic debugging skills = lots of orderly patients), then if it hasn't revealed itself to you maybe report what you think is working and what maybe isn't, with your logs and useful information you've gathered.

I think maybe your just missing some networking setup.

**Comment by RanaivosonHerimanitra** [comment]
Thank you for all of your advice. Actually the problem was in the security group. I got it worked allowing "All traffic" from inbound

**Comment by MasterJames** [comment]
I see. Excellent work and thanks for the heads up on where else the ingress can be effected. We can close this now.

**Comment by RanaivosonHerimanitra** [comment]
Thank you for your help.

**Comment by RanaivosonHerimanitra** [comment]
Thank you for your help.
