### ISSUE TITLE
Mupx Setup failed in AWS t2.micro

### ISSUE THREAD

**Issue by felipesmendes** [arunoda/meteor-up-legacy#627]
Hi,

I'm trying to deploy one application in AWS and when I run mupx setup is getting this error:

Started TaskList: Setup (linux)
[54.94.224.19] - Installing Docker
[54.94.224.19] x Installing Docker: FAILED

```
    -----------------------------------STDERR-----------------------------------
    bash: line 4: docker: command not found
    sudo: no tty present and no askpass program specified
    sudo: no tty present and no askpass program specified
    sudo: no tty present and no askpass program specified
    sudo: no tty present and no askpass program specified
    -----------------------------------STDOUT-----------------------------------
    ----------------------------------------------------------------------------
```

**Comment by MasterJames** [comment]
First thought is did you try the NOPASSWD in sudoers stuff described in here...
https://github.com/arunoda/meteor-up/blob/master/README.md
Second though does that t2.micro have docker installed or is that a dependency needed still. Double check with ssh if docker is installed in tye instance and in the users env path as well as permission to use/execute it.

**Comment by felipesmendes** [comment]
@MasterJames I did the steps but still not working with same problem,

**Comment by MasterJames** [comment]
There is a scripts/linux shell called install-docker.sh
That checks on the instance if it has docker and attempts to install it if not found.
If that process is blocked etc you get an error there I suspect.
so if you SSH into the instance and type "docker version" you'll now to call this or not.
    wget -qO- https://get.docker.com/ | sudo sh
and then you should get a clearer understanding of a problem in there or not.

```
#!/bin/bash

# Is docker already installed?
set +e
haveDocker=$(docker version | grep "version")
set -e

if [ ! "$haveDocker" ]; then

  # Remove the lock
  set +e
  sudo rm /var/lib/dpkg/lock > /dev/null
  sudo rm /var/cache/apt/archives/lock > /dev/null
  sudo dpkg --configure -a
  set -e

  # Required to update system
  sudo apt-get update

  # Install docker
  wget -qO- https://get.docker.com/ | sudo sh
fi
```

Update: I suspect a permissions problem possibly wrong username when it was executing in the mupx call.

**Comment by felipesmendes** [comment]
It works with this script! Thank you so much!
