### ISSUE TITLE
Migration of mongo from MUP to MUPX

### ISSUE THREAD

**Issue by jm4r7in** [arunoda/meteor-up-legacy#637]
I set a new server using mupx (the old server was using mup). 
I did on old server: 
**mongodump -> tar -> wput (ftp)**

On new server: 
**wget (ftp) -> tar -> mongorestore**

And I got the error:

```
connected to: 127.0.0.1
assertion: 17370 Restoring users and roles is only supported for clusters with auth schema versions 1 or 3, found: 5
```

How am I supposed to migrate the mongodb database ?

**Comment by sferoze** [comment]
@jm4r7in did you figure out how to restore your database in mupx. Do you have steps for me? I have a dump folder and I want to restore it into my mupx deployment which uses docker.
