### ISSUE TITLE
MUPX and OpLog

### ISSUE THREAD

**Issue by jm4r7in** [arunoda/meteor-up-legacy#639]
Is there an easy way to set OpLog with mupx ?
Thanks!

**Comment by TimFletcher** [comment]
To my knowledge it's the same as with mup. I'm using compose.io for my database. This is my env:

```
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://myapp.com",
    "MONGO_URL": "mongodb://username:password@capital.5.mongolayer.com:10040/myapp?replicaSet=set-55ca0e3e518351653f000a0e",
    "MONGO_OPLOG_URL": "mongodb://username:password@capital.5.mongolayer.com:10040/local?authSource=myapp"
  },
```

**Comment by jm4r7in** [comment]
Thanks @TimFletcher 
I'm thinking about it. And what about doing it locally ?

**Comment by TimFletcher** [comment]
I've not experience with a local install of Mongo. I'd way rather give that task to a 3rd party expert. Depends on your situation, of course. If I could afford a sysadmin then I'd likely have them manage all my infrastructure. Until then I try to steer clear of devops as much as possible. :) Perhaps someone else better suited you your question can chime in.

**Comment by jm4r7in** [comment]
I created a database on compose.io, created a user w/ oplogAccess, modified the mup.json to have similar env as yours, and ran **mupx reconfig**, **mupx deploy**...
But the app still uses the old (and local) mongo.
What am I missing ?

**Comment by jm4r7in** [comment]
After some time, and without any particular reason, it was working.
Thanks @TimFletcher
