### ISSUE TITLE
Error: Could not load the bindings file with bcrypt

### ISSUE THREAD

**Issue by KrishnaPG** [arunoda/meteor-up-legacy#641]
This message keeps occurring with the latest version, and installing the bcrypt manually resolve the problems (temporarily). But redeployment are failing .

Installing the `brcypt` globally is not also helping either. The `require` for whatever reason is just looking in the relative folders and not considering the global one.

**Comment by MasterJames** [comment]
Is your Ubuntu image supported? 14.0.4 I think.
Did you try mupx? 
Please post verbose DEBUG logs and both settings files for assistance thanks.
