### ISSUE TITLE
Deploy without Nginx

### ISSUE THREAD

**Issue by mbabauer** [arunoda/meteor-up-legacy#648]
Is it possible to deploy a Meteor app with mupx but without the Nginx docker piece?  I just need MongoDB and the app setup, but I need to be able to handle the Nginx config outside of mupx.

**Comment by MasterJames** [comment]
If you read the Readme for meteorhacks cluster meteor plug in. 
https://github.com/meteorhacks/cluster
If says no need for nginx so maybe you should try to reassess your situation.

**Comment by MasterJames** [comment]
There's a page about using nginx vhosts here that might be of help
https://github.com/arunoda/meteor-up/wiki/Using-Meteor-Up-with-NginX-vhosts
It looks like removal of SSL setting in mup.json might disable it?

**Comment by mbabauer** [comment]
@MasterJames: Thanks, I'll read up.  I am not sure if the clustering will work in my case, but the other posting looks like it has great potential.  What I am trying to do is use Nginx to service some static web content on http but have one URL redirect to HTTPS, which will be the Meteor app.  My other option was to use a custom Nginx docker image.  I think this was the approach that @stephentcannon did for one of his projects.
