### ISSUE TITLE
deploy to server and run on iOS-device

### ISSUE THREAD

**Issue by devdudeio** [arunoda/meteor-up-legacy#656]
whats the common way to run the app on a mobile device with an native app (cordova)? I have successfully deployed the app with `mup deploy` to my server but when I try to `meteor run ios-device --mobile-server=myserver:port` it always give me an error in the log so my mobile build can´t connect to my server:

`2015-09-14 18:22:13.443 yourapp[4431:1720140] network`

if I try it to run the meteor server on my local server and run it on my iOS device its working like a charm.

any clue whats wrong?

**Comment by MasterJames** [comment]
Could it be a cross domain policy?

**Comment by devdudeio** [comment]
looks like its not working with my domain (A Record). I used my IPs and now its working.
