### ISSUE TITLE
Uploading bundle: FAILED 	No such file

### ISSUE THREAD

**Issue by mattlinares** [arunoda/meteor-up-legacy#666]
I'm not sure how to debug this. The app runs well locally and with meteor deploy (to meteor.com). Can you help? Thanks!

Here's the console log and package list below:

```
➜  ssc git:(master) ✗ mup setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[46.101.21.215] - Installing Node.js
[46.101.21.215] - Installing Node.js: SUCCESS
[46.101.21.215] - Installing PhantomJS
[46.101.21.215] - Installing PhantomJS: SUCCESS
[46.101.21.215] - Setting up Environment
[46.101.21.215] - Setting up Environment: SUCCESS
[46.101.21.215] - Configuring upstart
[46.101.21.215] - Configuring upstart: SUCCESS
➜  ssc git:(master) ✗ mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: .

Started TaskList: Deploy app 'ssc' (linux)
[46.101.21.215] - Uploading bundle
[46.101.21.215] x Uploading bundle: FAILED
    No such file
➜  ssc git:(master) ✗
```

package list:

```
accounts-facebook                  1.0.4* Login service for Facebook accounts
accounts-google                    1.0.4* Login service for Google accounts
accounts-twitter                   1.0.4* Login service for Twitter accounts
aldeed:autoform                    5.4.1* Easily create forms with automatic ...
aldeed:autoform-bs-datetimepicker  1.0.6  Custom bootstrap-datetimepicker inp...
aldeed:collection2                 2.4.0* Automatic validation of insert and ...
autopublish                        1.0.3* Publish the entire database to all ...
blaze                              2.1.2* Meteor Reactive Templating library
cmather:handlebars-server          2.0.0  Allows handlebars templates to be d...
email                              1.0.6* Send email messages
insecure                           1.0.3* Allow all database writes by default
iron:router                        1.0.9  Routing specifically designed for M...
meteor-platform                    1.2.2* Include a standard set of Meteor pa...
momentjs:moment                    2.10.6  Moment.js (official): parse, valid...
mquandalle:jade                    0.4.3_1  Jade template language
msavin:mongol                      1.1.5  The insanely handy development pack...
orphan:synced-cron                 1.2.0  Orphan release of percolate:synced-...
service-configuration              1.0.4* Manage the configuration for third-...
stevezhu:fbgraph                   1.2.0* Node.js module to access the Facebo...
todda00:friendly-slugs             0.3.4  Generate URL friendly slugs from a ...
tsega:bootstrap3-datetimepicker    3.1.3_3* Bootstrap 3 DateTime picker from ...
twbs:bootstrap                     3.3.5  The most popular front-end framewor...
useraccounts:bootstrap             1.12.3  Accounts Templates styled for Twit...
useraccounts:iron-routing          1.12.3  UserAccounts package providing rou...

```

**Comment by MasterJames** [comment]
Does this mean anything to you?
https://www.npmjs.com/package/ssc

**Comment by MasterJames** [comment]
Oh it's the App name, sorry I got confused.
Try to manually step through...
Line 57 in lib/taskLists/linux.js aka deploy()
... no wait please try the dev branch mupx first and see if that helps, thanks.
https://github.com/arunoda/meteor-up/tree/mupx#

**Comment by mattlinares** [comment]
Thanks, I have tried mupx, same issue, output very similar. Btw, even the app isn't actually called ssc, I changed that for this post, although almost no chance of a conflict there.

**Comment by MasterJames** [comment]
Okay well in mup the deploy function points to this nodemiral dependency from what I can tell. (That's why it's hard to debug somewhat I guess.)

https://github.com/arunoda/nodemiral/blob/master/lib/session.js#L67

So your into SSH issues maybe post your settings files but trying a password instead of a PEM comes to mind, to mention off hand.

If you Run DEBUG *= mup you would get better logging like from Line 82 there I believe...
https://github.com/arunoda/nodemiral/blob/master/lib/session.js#L82

**Comment by mattlinares** [comment]
Stupid error, I'd given the app a name with spaces in spite of the comment not too. Now I just have a new error.
Thanks for your attention.

**Comment by ghost** [comment]
Ahhh - I just did the same thing - thoughtlessly added a space to the App name
Pleased to have got the hint from Matt's comment
but would still like the last 30 minutes back!

**Comment by makstr** [comment]
I keep getting this with mupx:

Started TaskList: Deploy app 'myapp' (linux)
[42.203.172.542] - Uploading bundle
[42.203.172.542] x Uploading bundle: FAILED
    No such file

**Comment by makstr** [comment]
I ran it again with debug on: DEBUG=\* mupx deploy

Started TaskList: Deploy app 'myapp' (linux)
[42.203.172.542 - Uploading bundle
  nodemiral:sess:42.203.172.542 copy file - src: /tmp/5d71e350-ddd0-4cb6-8a58-1e75f7e53404/bundle.tar.gz, dest: /opt/myapp/tmp/bundle.tar.gz, vars: undefined +0ms
[42.203.172.542] x Uploading bundle: FAILED
    No such file

**Comment by MasterJames** [comment]
Can you sudo su or something before building and see if it might be permission related?

**Comment by gmochid** [comment]
I got an issue exactly like what @Makstr wrote.

**Comment by MasterJames** [comment]
Is it the source or destination that's missing?

**Comment by gmochid** [comment]
it is the source

**Comment by MasterJames** [comment]
Must be a permissions problem. Maybe check access to the tmp folder or again 'sudo su' before running deploy and if it works there was a permissions problem with the other account or the tmp folder.

**Comment by MasterJames** [comment]
Anyway consider trying the new port over at kadirahq ! You'll get better help for everyone as this is pretty much depreciated now.
