### ISSUE TITLE
error: No plugin known to handle file '../../packages.json'.

### ISSUE THREAD

**Issue by mattlinares** [arunoda/meteor-up-legacy#670]
Here's an error for which I have searched and puzzled to no avail. The packages file was made automatically and is just one pair of empty parentheses: `{}`

Can you help? 

```
➜  ssc git:(master) ✗ DEBUG=* mup deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: .
=> Errors while initializing project:

While building package npm-container:
error: No plugin known to handle file '../../packages.json'. If you want this
file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('../../packages.json', 'client').


=> Build Error. Check the logs printed above.
➜  ssc git:(master) ✗
```

**Comment by arunoda** [comment]
Update `meteorhacks:npm` for Meteor 1.2
See: https://github.com/meteorhacks/npm#use-npm-modules-with-your-meteor-app

**Comment by mattlinares** [comment]
Thank you! Very responsive. mup didn't work, but mupx did. To the future.. :)

**Comment by brylie** [comment]
I have the same error. When I run `meteor update meteorhacks:npm`, I get the following message:

```
The specified packages are at their latest compatible versions.
```

My versions file shows `meteorhacks:npm@1.5.0`

**Comment by shahidkarimi** [comment]
Still can't solve this issue. @arunoda

**Comment by interfaith** [comment]
simply remove all the packages not needed for meteor 1.3 such as npm:container
and mrt arunoda packages
