### ISSUE TITLE
How to backup mongodb deployed with MUPX?

### ISSUE THREAD

**Issue by sferoze** [arunoda/meteor-up-legacy#674]
I deployed my app to a digital ocean droplet and setup mongodb with it as well. 

I used MUPX

Now I want to get the contents of mongodump onto my local computer from the server. 

I can ssh into the server. Then what? What command do I run?

I ran the command `docker exec -it mongodb mongodump`

and it looked like it did a dump. but when I type ls I dont see any files.

How can I access the dump files on my server? And then transfer them to my local computer?

**Comment by sferoze** [comment]
I figured it out. I had to learn more about how to use docker. 

So first after running the command `docker exec -it mongodb mongodump`

The dump was inside the docker container. 

To see running docker container type

`docker ps`

Check out the files in the container with name mongodb by using command

`docker exec -it mongodb ls`

You will see the dump directory. To copy it over to outside the container, to your server use

`docker cp mongodb:dump .`

that will copy the dump directory into your current directory. Then just use scp to copy from to your local computer

**Comment by rdewolff** [comment]
Thanks for sharing your solution @sferoze - this helped me.

**Comment by wdhif** [comment]
I've made a little script to help with the backup of meteor. Here is the tree for MupX : https://github.com/wdhif/meteor-script-backup/tree/mupx

**Comment by emminnn** [comment]
Sorry, newbie here :) Can you please explain how you do this step @sferoze ?

> Then just use scp to copy from to your local computer

Thx.

**Comment by wdhif** [comment]
To SCP your files, you just have to do this command where you want your backup on your local computer.

`scp login@serverIP:/path/to/files .`

Just enter the ssh password when ask to and your done.

For more information : https://en.wikipedia.org/wiki/Secure_copy

**Comment by emminnn** [comment]
Great thx @wdhif ! Though I get this cause, I guess, I don't know what is the path to the directory where the mongodump is located.

> No such file or directory

so what is `/path/to/files` in this case?

**Comment by emminnn** [comment]
When I run `docker exec -it mongodb ls`, I get this:

```
bin   data  entrypoint.sh  home  lib64  mnt           opt   root  sbin  sys  usr
boot  dev   etc        lib   media  mongodb.conf  proc  run   srv   tmp  var
```

**Comment by wdhif** [comment]
You are doing a backup of all the content of the container, you actually just need your database. I would recommend doing the backup that way : 

`docker exec mongodb mongodump -d myDB -o /myDB-dump`

Then you do a docker cp to get the data out of the container.

`docker cp mongodb:/myDB-dump .`

And then you can get the dump to your local computer using SCP.

To simplify, we dump the database in the container with `docker exec mongodump`, we extract the dump from the container to the server with `docker cp`and then we transfer the dump with `scp`.

I would recommend you checking out the script I use to backup my databases : https://github.com/wdhif/meteor-script-backup/tree/mupx

**Comment by emminnn** [comment]
But I can not find where the dump is located in the server :/

**Comment by wdhif** [comment]
It should be where you entered the docker cp command.

To make sure to find it, do : `docker cp mongodb:/myDB-dump /myDump`

**Comment by emminnn** [comment]
Oops. I did something, like what you recommended not to -> to copy the folder to my desktop. It was a lot of terminal processing, but I do not see anything on my Desktop. How does that happen?

I'll try to run yours now... Thx meanwhile...

**Comment by emminnn** [comment]
Alright actually it was, by default copied in a folder called `dump`, in the server.

Then actually just installed Cyberduck and connected via SSH. It was a blessing to do it with a GUI.
