### ISSUE TITLE
mup deploy error with meteor 1.2.0.1

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [arunoda/meteor-up-legacy#677]
Hi there,
Like many others, I'm experiencing problems with my development app after upgrading to the latest version of meteor.
Before,  deployment ( `mup deploy`) worked perfectly, now, I'm getting this error:

```
Errors prevented bundling:
While minifying app code:

/home/herimanitra/.meteor/packages/standard-minifiers/.1.0.0.1x69nbw++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token punc «:», expected punc «,»
at new JS_Parse_Error
```

Notice that I already have the latest version of `npm` and `mup` running and changed to `node:0.10.40`
Do you have any clues on how to solve it?
thanks in advance,

**Comment by RanaivosonHerimanitra** [comment]
Oops, sorry all,
One of my js file had a syntax error so that's why It refused to compile. solve it!

**Comment by malsher** [comment]
Hi RanaivosonHerimanitra,

Are you able to share which file please? Is it one of your packages, or one belonging to Meteor?

I have the same issue and suspect others may too. However, I don't have any console errors and none are obvious in my code. The app is perfect when run locally. It simply fails on minification during mup deploy.

**Comment by RanaivosonHerimanitra** [comment]
Hi malsher,
The file I mentioned belongs to my application then had nothing related to mup package 
. I had a js syntax error with it that's why I got this issue. Check carefully whether  you forget to remove some commas or dot before deploying

**Comment by malsher** [comment]
Thank you for coming back so quickly. It helps to confirm the error is likely my own.

**Comment by joaobarcia** [comment]
Hi, it seems it might not even be due to errors in the code. It's an issue with meteor's bundling:
https://github.com/meteor/meteor/issues/5643

**Comment by davidnathanael** [comment]
Im having the same issue, did you figure out how to make it work guys?

I don't think i have any syntax error.

```
Errors prevented bundling:
While minifying app code:


/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token punc «(», expected punc «:»
at new JS_Parse_Error
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:196:18)
at js_error
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:204:11)
at croak
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:675:9)
at token_error
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:683:9)
at expect_token
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:696:9)
at expect
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:699:36)
at
/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:1252:13
at
/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:722:24
at expr_atom
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:1182:35)
at maybe_unary
(/Users/daviddelacruz/.meteor/packages/standard-minifiers/.1.0.2.recna8++os+web.browser+web.cordova/plugin.minifyStd.os/npm/minifiers/node_modules/uglify-js/lib/parse.js:1358:19
```

**Comment by MasterJames** [comment]
Maybe try updating meteor to 1.3.2.4 and use mupx or the new port at kadirahq/meteor-up ?
Oh and meteor remove-plateform ios android

**Comment by davidnathanael** [comment]
Yes updating meteor worked for me. Thanks

**Comment by ghost** [comment]
hi RanaivosonHerimanitra and ddela-cr, i think you add ecmascript package to package.js in your packages folder. It will run good with es5+ syntax. I spent one day for solve it.
