### ISSUE TITLE
Where to see detailed mup failure logs?

### ISSUE THREAD

**Issue by ffxsam** [arunoda/meteor-up-legacy#679]
Where can I find detailed logs for mup? Not the actual process on the server, but `mup setup` is failing and I need to figure out why:

```
[xx] - Configuring upstart
[xx] x Configuring upstart: FAILED
    Permission denied
```

**Comment by babnik63** [comment]
MUP should be more powerful for showing deployments errors. Now most of errors are not so clear for trouble shooting.

**Comment by MasterJames** [comment]
There's stuff in the Readme about this...

   DEBUG *= mupx deploy

Is that sufficient for your case?

**Comment by ffxsam** [comment]
I'm using mup, not mupx. BTW, it's `DEBUG=* mupx deploy`.

I'll have to see if this works for mup too.

**Comment by digz6666** [comment]
Where to use DEBUG=\* mup deploy?
Run in command line or?

**Comment by ffxsam** [comment]
@digz6666 Correct, on the command line. Basically, you're just setting an environment variable in your shell.

**Comment by arrutneo** [comment]
Hi, I'm getting the same error. 

```
x Uploading bundle: FAILED
    Received exit code 0 while establishing SFTP session
```

With Debug activated I also see this 
`nodemiral:sess:52.27.154.183 copy file - src: /var/folders/w5/tgb6xp8d0xj_c1tsfzx6pb7h0000gp/T/2993602d-e8da-4c3f-b08a-ecb945fcf10a/bundle.tar.gz, dest: /opt/Piqued/tmp/bundle.tar.gz, vars: undefined +0ms`

Any Idea what can it be?

Thanks!

**Comment by ffxsam** [comment]
Not sure, but I've moved on to using mupx now. I recommend it.
