### ISSUE TITLE
Debug/verbose mode?

### ISSUE THREAD

**Issue by wizonesolutions** [arunoda/meteor-up-legacy#68]
Is it possible to see the full output of Meteor Up?

**Comment by arunoda** [comment]
set DEBUG=\* as the env variables.

eg: `DEBUG=* mup deploy`

**Comment by wizonesolutions** [comment]
Thanks! Opened a follow-up.

**Comment by wizonesolutions** [comment]
Oh, whoops. In my PR I wrote `DEBUG=1`. Will that work or should I amend it to `*`?

**Comment by arunoda** [comment]
No need. I just fixed it. :)

On Sunday, May 25, 2014, Kevin Kaland notifications@github.com wrote:

> Closed #68 https://github.com/arunoda/meteor-up/issues/68.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-up/issues/68#event-124590819
> .

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
