### ISSUE TITLE
Mobile servers and Cordova build( two different hashes)

### ISSUE THREAD

**Issue by sasikanth513** [arunoda/meteor-up-legacy#688]
I'm using mupx to deploy my mobile app server

there is no issue there, everything worked fine.

(here when we deploy to servers, meteor generates one file hash)
But to generate `apk/ipa` files we need to do build in local, like

```
meteor build ../build --server=https://mysite.com
```

as this is a seperate build meteor generates new hash

so when users open the app they are again downloading new files of same code from server.

Is there any solution for this?

I tried to go through the scripts and saw that you're saving the build in `os.temp()` directory

I checked temporary directory using `echo $TEMP_DIR` and didn't find anything related to mupx in that  directory.

I can think of one solution right now,

*. If we know where build files stored in local then we can create apk/ipa from those files so files hash will be same.

Thx

**Comment by sasikanth513** [comment]
Looks like in this line

https://github.com/arunoda/meteor-up/blob/22590ba75791958adbd78d71d2c82e7b6b0e2436/lib/actions.js#L254

build location directory is removed

**Comment by MasterJames** [comment]
You could exit there (step and debug manually) or comment it out if you want to see what's happening or available there after it completes.
I'm not fully grasping you problem but maybe you can slot in your build code before there and see what happens.

**Comment by guilhermedecampo** [comment]
hey @sasikanth513 maybe you could use your own version with the environment variable `AUTOUPDATE_VERSION` when you build and deploy with mup. Here a readme of [autoupdate](https://github.com/meteor/meteor/blob/devel/packages/autoupdate/QA.md)  package.

Hope it helps.

**Comment by sasikanth513** [comment]
@guilhermedecampo even using `AUTOUPDATE_VERSION` is not fixing the issue, may be it is because I'm using `settings.json` file in my project.

Anyway I forked this package, and made few changes to display the build directory and not to delete the build directory after building completed, so I can use the same build to create `apk/ipa` files.
