### ISSUE TITLE
can't save files to filesystem with collectionfs on mup deployed server

### ISSUE THREAD

**Issue by bgrayburn** [arunoda/meteor-up-legacy#689]
Hey! Thanks for this awesome project!

I'm trying to deploy a server for a meteor cordova app (using mup) that uses collection:fs to transfer videos from the mobile app to the server and then backs them with the filesystem. Currently all my transfers are failing and no files are showing up on the server. Could I be missing some security settings in mup, or is it possible that write access from node is somehow blocked by mup? I've set the permissions on that folder to make sure it wasn't a filesystems permissions problem (chmod a+rw) but that didn't seem to change anything.

**Comment by bgrayburn** [comment]
obviously I need to RTFM, found answer [here](https://github.com/arunoda/meteor-up/wiki/Change-Ownership-of-Additional-Directories)

**Comment by jakelacey2012** [comment]
Hi I'm having a similar problem, 

I've set permissions like the previous commenter and I've also changed the user to 'meteoruser'. However no luck
