### ISSUE TITLE
Unable to Deploy using mup deploy

### ISSUE THREAD

**Issue by ftkendrakuhl** [arunoda/meteor-up-legacy#694]
I'm super new to the whole meteor thing, so it might be something simple... but here's what I have.

Local Machine:
OS: Ubuntu 14.04
Meteor Version: 1.0.1
Node Version: 0.10.36
MUP Version: Latest. Just installed yesterday.

Server:
OS: Ubuntu 12.04.5
Meteor Version: ?? meteor --version is returning a command not found error
Node Version: 0.10.33

mup setup did not receive any errors.
mup deploy received the following error:

Started TaskList: Deploy app 'myApplication' (linux)
[255.255.255.255] - Uploading bundle
[255.255.255.255] - Uploading bundle: SUCCESS
[255.255.255.255] - Setting up Environment Variables
[255.255.255.255] - Setting up Environment Variables: SUCCESS
[255.255.255.255] - Invoking deployment process
[255.255.255.255] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ver/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Warning: File `../binding.gyp' has modification time 4.2e+02 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) couldn't connect to host
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    arget) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      COPY Release/bcrypt_lib.node
    make: Leaving directory `/opt/myApplication/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.1 install /opt/myApplication/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@2.2.1 node_modules/semver

source-map-support@0.2.5 node_modules/source-map-support
??? source-map@0.1.29 (amdefine@0.1.0)

fibers@1.0.1 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
myApplication stop/waiting
myApplication start/running, process 27870
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
myApplication stop/waiting
myApplication start/running, process 27936
----------------------------------------------------------------------------
```

These errors show up in the mup logs -n 400

/opt/myApplication/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: Can't find npm module 'body-parser'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/opt/myApplication/app/programs/server/boot.js:113:17)
    at assert (packages/iron:router/lib/body_parser_server.js:1)
    at /opt/myApplication/app/programs/server/packages/iron_router.js:1255:4
    at /opt/myApplication/app/programs/server/packages/iron_router.js:1441:3
    at /opt/myApplication/app/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/myApplication/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/myApplication/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
error: Script restart attempt #6

/opt/myApplication/app/programs/server/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: ENOENT, no such file or directory '/opt/myApplication/app/programs/server/packages/accounts-base.js'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at /opt/myApplication/app/programs/server/boot.js:83:19
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/myApplication/app/programs/server/node_modules/underscore/underscore.js:79:11)
    at /opt/myApplication/app/programs/server/boot.js:82:5
error: Forever detected script exited with code: 8
Kadira: completed instrumenting the app

**Comment by MasterJames** [comment]
I think you want your server version to be Ubuntu 14 as well. Also consider trying mupx (the dev branch version) to resolve problems like this.

**Comment by mattiLeBlanc** [comment]
I am having the same issue:

Started TaskList: Deploy app 'superApp' (linux)
[xx.xx.xxx.xxx] - Uploading bundle
[xx.xx.xxx.xxx] - Uploading bundle: SUCCESS
[xx.xx.xxx.xxx] - Setting up Environment Variables
[xx.xx.xxx.xxx] - Setting up Environment Variables: SUCCESS
[xx.xx.xxx.xxx] - Invoking deployment process
[xx.xx.xxx.xxx] x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/superApp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    nsi-regex

```
ansi-styles@1.1.0 node_modules/ansi-styles

chalk@0.5.1 node_modules/chalk

escape-string-regexp@1.0.3 node_modules/escape-string-regexp

strip-ansi@0.3.0 node_modules/strip-ansi

supports-color@0.2.0 node_modules/supports-color

has-ansi@0.1.0 node_modules/has-ansi

eachline@2.3.3 node_modules/eachline

type-of@2.0.1 node_modules/type-of

amdefine@1.0.0 node_modules/amdefine

asap@2.0.3 node_modules/asap

underscore@1.5.2 node_modules/underscore

meteor-promise@0.5.0 node_modules/meteor-promise

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.5 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
superApp stop/waiting
superApp start/running, process 532
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
superApp stop/waiting
superApp start/running, process 597
----------------------------------------------------------------------------
```

Completed TaskList: Deploy app 'superApp' (linux)

This happened to me before, just when I had an important meeting. I don't know what the cause is.

I am running om Amazon with Ubuntu 14.04.
I will try mupx right now.

**Comment by MasterJames** [comment]
Excellent well also consider extending the deploy wait time via deployCheckWaitTime to 120+ to be sure about that as well. Please post your mup settings if you're still having a problem with mupx too.

**Comment by mattiLeBlanc** [comment]
Hi the fix was actually going on the server in the /opt folder and remove the node 0.10.36 and the app.
Then I update mup config to Node 0.10.40 and ran mup setup again and deploy after.
That seemed to fix it for now

**Comment by ftkendrakuhl** [comment]
@mattiLeBlanc - Sorry for the needed hand holding. How do you remove the node from just the opt folder (or did you mean uninstalling it completely)? I tried just deleting the myApplication and the nodejs folder from under /opt. Ran mup setup with 0.10.40 in the mup config file... and it still didn't deploy properly. If that wasn't what you did, can you point me in the right direction?

**Comment by louwers** [comment]
Had the same issue. @mattiLeBlanc his solution solved it for me too.

@ftkendrakuhl delete /opt/nodejs (`rm -r /opt/nodejs`) and /opt/appname. Then `mup setup && mup deploy`.

**Comment by ftkendrakuhl** [comment]
@louwers - Thanks! That's what I tried... and it didn't fix my issue, so I'll keep plugging away.

**Comment by louwers** [comment]
Bummer! Perhaps try mupx. Also, have you seen this:

`Error: Can't find npm module 'body-parser'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?`

Try creating a fresh meteor app with `meteor create`, see if you can deploy that. If so, it must be something with your app.

**Comment by mattiLeBlanc** [comment]
@ftkendrakuhl  Don't apologise buddy, I know how annoying it is to experience these difficulties.
Any way, as @louwers said, I did exactly that PLUS a reboot of the server (not sure if that is necessary but I thought it might clear up memory or processes that were stuck).

Did you do a `mup logs -f` while running the mup deploy (in another terminal). It did give me a good indication what was wrong while running the deployment process (it screamed about needing node 0.10.40).
Also, make sure that you are not running another version of node on your server (the one you would nstall with apt-get). I am not sure if it makes a difference but if I remove the node from /opt I want to have no node at all on the server in case that might cause an issue.

Oh and one final thing you probably already changed: " Make sure you have node version 0.10.40 in your mup file.

**Comment by ftkendrakuhl** [comment]
@mattiLeBlanc - Thanks, I will give that a try! (I did change my mup file already...)

**Comment by MasterJames** [comment]
I'd be interested to know if you have to delete /opt/nodejs because **setup** & deploy should replace it? If it doesn't it must be a bug and then something should do that for you as part of deploy?

**Comment by mattiLeBlanc** [comment]
I imagine when you delete node from your opt folder MUP replaces it. If you
don't delete it, it skips the node installation.
When I changed my mup file to a newer node version but did not delete node
from the opt folder, it did not resolve the issue for me. Only after
removing node manually did it resolve

**Comment by MasterJames** [comment]
Okay is see now. This is a big difference in mup vs mupx. so if mupx works it's preferable.
IMAOO The Docker route seems a better approach for many reasons, but not all. (You can control various settings well, and if necessary build a custom image BTW).
mupx launches a base image https://github.com/meteorhacks/meteord
from https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh
for various prepackaged Container targets (mongo, meteor, etc.).
But with mup the install node shell script...
https://github.com/arunoda/meteor-up/blob/master/scripts/linux/install-node.sh
extracts a specific '.tar'  NodeJS Distribution from nodejs.org/dist

Where it looks to my eye at a quick glance like it should be removing that there?!
https://github.com/arunoda/meteor-up/blob/master/scripts/linux/install-node.sh#L34
I suppose it doesn't get there for some reason. Looks like a bug at first glance, it needs looking into.
I would say the simplest fix is to set the defaults (& docs) to the .40 for the node version.
Maybe a way to use "latest" is a better default and easy to override?
https://nodejs.org/dist/latest/
As a quick patch for mup at least. I think getting the mupx branch to work is a better route for the person deploying.
Then there's mup2 for large scale production deployment. (I've not even noticed until now!)
https://github.com/arunoda/meteor-up/tree/mup2
**Anyway thanks for the feedback, thoughts or pull requests on this I'm sure are welcome.**
