### ISSUE TITLE
Deploy fails after updating to Meteor 1.2.0.2

### ISSUE THREAD

**Issue by eeiswerth** [arunoda/meteor-up-legacy#696]
I've been using mup for about a year without issue.  Tonight I updated to the latest version of Meteor and tried to deploy my app to a Digital Ocean machine.  I see this:

```
-----------------------------------STDERR-----------------------------------
c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing initializer for field ‘isName2’ of ‘const struct normal_encoding’ [-Wmissing-field-initializers]
 };
 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused

Any ideas?  I bumped the node version to 0.10.40 as part of this process as well.

**Comment by eeiswerth** [comment]
I can't recall if I was supposed to do this step or if mup setup was supposed to do it for me, but manually ssh'ing into the machine and running 'n 0.10.40', followed by yet another deploy seems to have fixed the issue for me.

**Comment by MasterJames** [comment]
I've noted https://github.com/arunoda/meteor-up#updating
says....

```
if you need to update your Node version, you'll have to run "mup setup" again before deploying
```

Maybe that had something to do with it? **I'm glad you got it mup!**

**Comment by eeiswerth** [comment]
Thanks @MasterJames. I did run "mup setup". It didn't work.  Or I should say, mup setup appeared to work, but deploy continued to fail after running setup.  I had to manually login to the machine and update node myself.

**Comment by MasterJames** [comment]
Okay great! I imagined a "mup deploy" would have pushed the changes done by "mup setup".  Thanks for the report back.
