### ISSUE TITLE
Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by bala2excel** [arunoda/meteor-up-legacy#707]
HI,

I am using MUP from windows PC to deploy meteor App on my Ubuntu 14.4 server.

I am able to connect to the Ubuntu by using putty with username & password. When I provided the same in Mup.Json, I am getting the below error. 

I am a newbie to Ubuntu & Node. Please direct me in right direction.

Started TaskList: Deploy app 'IMBU' (linux)
[10.175.96.50] - Uploading bundle

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: All configured authentication methods failed
    at tryNextAuth (C:\Users\balamurugan.a\AppData\Roaming\npm\node_modules\mup\
node_modules\nodemiral\node_modules\ssh2\lib\client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\balamurugan.a\AppData\Roaming\npm
\node_modules\mup\node_modules\nodemiral\node_modules\ssh2\lib\client.js:469:5)
    at SSH2Stream.emit (events.js:98:17)
    at parsePacket (C:\Users\balamurugan.a\AppData\Roaming\npm\node_modules\mup\
node_modules\nodemiral\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:36
49:10)
    at SSH2Stream._transform (C:\Users\balamurugan.a\AppData\Roaming\npm\node_mo
dules\mup\node_modules\nodemiral\node_modules\ssh2\node_modules\ssh2-streams\lib
\ssh.js:555:13)
    at SSH2Stream.Transform._read [as __read](_stream_transform.js:179:10)
    at SSH2Stream._read (C:\Users\balamurugan.a\AppData\Roaming\npm\node_modules
\mup\node_modules\nodemiral\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.
js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)

My Mup.JSON

{
  // Server authentication info
  "servers": [
    {
      "host": "10.175.96.50",
      "username": "username", 
      "password": "password"

```
}
```

  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  //"nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": false,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "IMBU",

  // Location of app (local directory)
  "app": "~/IMBU",

  // Configure environment
  "env": {
    //"ROOT_URL": "http://ec2-52-88-154-226.us-west-2.compute.amazonaws.com"
    "ROOT_URL": "http://10.175.96.50"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

**Comment by MasterJames** [comment]
It appears it didn't like your username password.
Can you double check your login. [Maybe test without special characters if possible.]

Please try mupx and see if that helps.
https://github.com/arunoda/meteor-up/tree/mupx

**Comment by bala2excel** [comment]
both my username & password doesn't have any special characters. 

Is some port needs to be open @ my Ubuntu server?

I will try with MUPX later today and post the results.

**Comment by MasterJames** [comment]
Yes maybe these will help. If your using AWS.
http://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html

**Comment by bala2excel** [comment]
Sorry! there was a special character which I didn't notice and it took me time to get it changed. After changing the node version to 0.10.40, I was able to deploy

**Comment by arvi** [comment]
I had the same issue and was able to resolve it by doing the ff:

1.Make sure servers object is setup with only host and username details:

```
  // Server authentication info
  "servers": [
    {
      "host": "123.456.789.01",
      "username": "root"
    }
```

2.Configure the ssh-agent to use your private SSH key

```
//make sure ssh-agent is enabled; it should output something like Agent pid 12344
eval "$(ssh-agent -s)"
```

3.Add your private SSH key to your ssh-agent

```
ssh-add ~/.ssh/sample_project_rsa
```

4.Run `mup setup`

5.Run `mup deploy`

Hope it helps! :)
