### ISSUE TITLE
mupx fs.createWriteStream on server throws error every time

### ISSUE THREAD

**Issue by rkstar** [arunoda/meteor-up-legacy#710]
i was using this same code when deploying with `mup` but now with `mupx` (on a new droplet @ digital ocean) it throws errors EVERY time.

``` javascript
{ [Error: ENOENT, open '/opt/crate-staging/download/zxtfg7JEn7KTbD75k.png']
  errno: 34,
  code: 'ENOENT',
  path: '/opt/crate-staging/download/zxtfg7JEn7KTbD75k.png' }
```

i've tried changing permissions on the download directory to 777 but it still fails.  i am out of ideas of how to fix this!  anyone else know what's happening?  is this something to do with docker?

``` javascript
Meteor.methods({
  'image/download': function( opts ){
    check(opts, Object)

    var fs = Npm.require('fs'),
      Future = Npm.require('fibers/future'),
      future = new Future(),
      filepath = process.env.IMAGE_DOWNLOAD_DIR+"/"+Random.id()+'.png',
      fp = fs.createWriteStream(filepath)
    fp.on('error', function(err){
      console.warn(err)
    })
    fp.on('open', function(fd){
      request.get(opts.url, opts)
        .on('data', function(chunk){
          console.log(chunk)
          fp.write(chunk)
        })
        .on('end', function(){
          fp.end()
          future.return({filepath: filepath})
        })
    })

    return future.wait()
  }
})
```

**Comment by MasterJames** [comment]
First off I would do put the semicolons in.
Second
ENOENT = "no such file or directory"
So you should see what happens trying to 'touch' the same filename from the same user running the process on the host via ssh or 
Docker exec <containerID> bash 
Or something like that.
Maybe check the permissions in all the paths directories just to be sure. Still I would restore that if not the problem after checking.
I wondered further about the on open having the argument fd but it's not used.
Maybe there's another path you could try like tmp to isolate the problem?

**Comment by MasterJames** [comment]
Also thinking you might need to make the path first instead via something like mkdirp
https://github.com/substack/node-mkdirp

**Comment by rkstar** [comment]
the problem turned out to be that i was trying to write to a directory outside of the app bundle.  i changed the write dir to be `process.env.PWD+"/server/"+Random.id()+'.png'` and it works as expected.

from where i'm sitting, this seems to be a difference with `mup` vs `mupx` and docker or nginx specifically.  i would love a comment from @arunoda on this.

**Comment by arunoda** [comment]
In mupx(also in mup, we don't recommend) , we don't support storing data
directly into the file system.
You may need to use S3 or something else.
That's the root for this.
