### ISSUE TITLE
Weird deployment error but app still deploys 

### ISSUE THREAD

**Issue by isAlmogK** [arunoda/meteor-up-legacy#725]
I'm trying to deploy Azure Linux VM, Ubuntu the app is deploying and working with no issues. But I'm getting the following deployment error  

[40.114.80.110] x Invoking deployment process: FAILED

-----------------------------------STDERR-----------------------------------
        '-Dnode_lib_file=node.lib',
        gyp info spawn args   '-Dmodule_root_dir=/opt/spoiler-alert-app/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp info spawn make
        gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
        gyp info ok 
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
        Latest deployment failed! Reverted back to the previous version.
        -----------------------------------STDOUT-----------------------------------
        x

```
    ansi-styles@1.1.0 node_modules/ansi-styles

    chalk@0.5.1 node_modules/chalk

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    strip-ansi@0.3.0 node_modules/strip-ansi

    has-ansi@0.1.0 node_modules/has-ansi

    supports-color@0.2.0 node_modules/supports-color

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    spoiler-alert-app stop/waiting
    spoiler-alert-app start/running, process 56612
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    spoiler-alert-app stop/waiting
    spoiler-alert-app start/running, process 56643
    ----------------------------------------------------------------------------
```

When I check the logs no errors, any ideas what's casing this

**Comment by MasterJames** [comment]
How about your 

   "deployCheckWaitTime": 15

?

**Comment by isAlmogK** [comment]
I had it set to 15 and then tried it also with 30 didn't change anything

**Comment by MasterJames** [comment]
Try 120 just to be sure that's not it.
In a new shell if you type 
docker attach mongodb
Or the dockerId instead of the image name mongodb you can sometimes see feedback if there's a lock enabled from improper shutdown etc. or some other problem.
I've noticed using
docker exec -it containerNameID bash
will not work in this case as docker tries to restart it but via attach you'll get the errors logged as it cycles.
You're using mupx instead of mup right? Try it instead if you're not.

**Comment by bryanlimy** [comment]
I am having the same problem, but it doesnt even deploy it

**Comment by isAlmogK** [comment]
Just tried setting it to 120 and it was good thanks 
I'm not using docker and I'm using mup up not mupx
