### ISSUE TITLE
Is it possible to use MUP with MongoHQ elastic deployment?

### ISSUE THREAD

**Issue by elie222** [arunoda/meteor-up-legacy#73]
Are there any special settings I need to set to get it working? I had mongo working with a free MongoHQ account, but when I created a new db with elastic deployment I couldn't get it to work.

**Comment by arunoda** [comment]
It works pretty well. Please give me more info, why it's not working and so
on?

On Friday, June 6, 2014, Eliezer notifications@github.com wrote:

> Are there any special settings I need to set to get it working? I had
> mongo working with a free MongoHQ account, but when I created a new db with
> elastic deployment I couldn't get it to work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/73.

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by elie222** [comment]
I had it working with my free mongohq db using the Mongo URI provided in the admin section with my username and password. I've now switched that line with the Replica Set URI provided for my elastic deployment, but now mongo has stopped working. (Log in doesn't work on my site and pretty sure mongodb in general doesn't)

**Comment by arunoda** [comment]
For the MongoHQ oplog URL, you need to prefix something different. Simply
ask their support staff on how to generate a oplog URL or follow this blog
http://blog.mongohq.com/meteor-the-oplog-and-elastic-deployment/

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by elie222** [comment]
thanks. i did that. it didnt solve my problems, but somehow now my site is working again and I have no idea what i did to fix it. i hope it continues to work. somehow somebody managed to sign up to the site last during the period it "wasn't" working

**Comment by stephentcannon** [comment]
@elie222 Make sure you create a mongodb user from the mongohq control panel and make sure you give that user oplog access.  This little point isn't well documented even in their blog posts.

http://blog.mongohq.com/meteor-the-oplog-and-elastic-deployment/

Then in my experience I need 2 entries for mongo url in my mup.json.

Here is an example that worked for me, AFTER I properly setup the mongohq/mongodb user (not Meteor User).

```
MONGO_URL": "mongodb://mongohq_db_user:mongo_users_password@candidate.12.mongolayer.com:10081/database_name",
    "MONGO_OPLOG_URL": "mongodb://mongohq_db_user:mongo_users_password@candidate.11.mongolayer.com:10081,candidate.12.mongolayer.com:10081/local?authSource=database_name",
```

Then you can check via the facts package.

Good luck.

**Comment by elie222** [comment]
Thanks. I made that change and things sometimes work now. It seems my
problem is somewhere else.
