### ISSUE TITLE
How to delete project?

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#732]
Hi All,

There is no information how to delete an existing project.

I deployed to the server having in `mup.json`:

```
"appName": "meteor",
  // Location of app (local directory)
  "app": "app",
```

Finally, I found that it was deployed by default to `/opt/meteor/app`. I deleted this folder on the server - even the whole opt folder and stopped meteor process.

Now, when I try to deploy a different project. I receive the following message after invoking `mup init`:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

A Project Already Exists

```

What should I do?
Thank you ;)

**Comment by MasterJames** [comment]
Init only creates both mup.json and settings.json in the current working folder these can be deleted or repurposed.

**Comment by ghost** [comment]
Ahh, ok I now understand. Thank you ;)

However, it is strange situation, because I have X project on the server and want to upload there Y project. I just changed `appName` and `app` fileds in mup.json. Unfortunately, I receive the following error:

```
Building Started: ydevs
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3

```

@MasterJames or anyone, do you know maybe what can be a reason?

**Comment by ghost** [comment]
I made a stupid mistake and I did not notice that there is written `(local directory)`:

```
// Location of app (local directory)
  "app": "app",
```

Thank you for the help.
