### ISSUE TITLE
How does binaryNpmModules work?

### ISSUE THREAD

**Issue by elie222** [arunoda/meteor-up-legacy#74]
"binaryNpmModules": {
    "meteor-package-name": ["npm-module1", "npm-module2"]
  } 

I use the npm modules: 
{
  "cron": "1.0.4",
  "time": "0.10.0",
  "cheerio": "0.15.0"
}

And some of my packages also have npm dependencies. e.g. fast-render and iron-router depend on connect.

What needs to go in "binaryNpmModules"?
Also, is there an easy way to find all my npm dependencies?

**Comment by arunoda** [comment]
Actually,

binaryNpmModules are not modules like connect and so on. Those are pure JS
modules.
Sometimes we have binary NPM modules which has been written in C. They
needs to be compiled on the target platform if there is no special handling.
All the modules you've mentioned are not binary modules.

This is an experimental feature for this. (Works well on Digital Ocean, but
found issues with EC2)

Generally, you don't need to use this.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by elie222** [comment]
Thanks
