### ISSUE TITLE
mup deploy error when using external modules.

### ISSUE THREAD

**Issue by mariobaldini** [arunoda/meteor-up-legacy#767]
Hi all, 

If I use the the npm module 'pg' (PostgreSQL) in my project, the 'mup deploy' process fails. 

My code works fine locally, with or without the module. 
It also deploys fine when not using the module (related code commented; but module still installed). 

The related code that uses the module is: 

```
pg = Npm.require('pg');
var sql_client = new pg.Client(sql_conString);
etc.. 
```

The module was installed locally by: (dev machine)
`meteor add austinrivas:postgresql`
and 

```
sudo npm install pg -g
sudo npm install pg
```

(installing just globally didn't work at first) 

I installed the npm module globally in the remote machine (-g), but it didn't solve the issue. I'm not sure how could I install it "in the local scope of the the mup user" in the remote machine. (without -g, in which folder?)

When I installed the module in my current user of the local machine (without -g) it created the folder node_modules/pg (in the same path as client, server, private, etc...). 

It appears that the issue is regarding the missing npm 'pg' package in the remote machine. How could I force Meteor to use the globally installed package? Or bundle it so mup deploy already uploads all the code? 

```
 x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    pawn args   '-Dnode_lib_file=node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/opt/logview/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ng
    ansi-regex@0.2.1 node_modules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    chalk@0.5.1 node_modules/chalk

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    has-ansi@0.1.0 node_modules/has-ansi

    strip-ansi@0.3.0 node_modules/strip-ansi

    supports-color@0.2.0 node_modules/supports-color

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    logview stop/waiting
    logview start/running, process 4842
    Waiting for 15 seconds while app is booting up
    Checking is app booted or not?
    logview stop/waiting
    logview start/running, process 4966
    ----------------------------------------------------------------------------
```

mup logs -f when deploying: 

```
[logview-dev.logview.com.br] Error: Cannot find module 'pg'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.Npm.require (/opt/logview/app/programs/server/boot.js:150:18)
    at server/api.js:2:1
    at server/api.js:241:1
    at /opt/logview/app/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/opt/logview/app/programs/server/node_modules/underscore/underscore.js:79:11)
[logview-dev.logview.com.br] error: Forever detected script exited with code: 8
[logview-dev.logview.com.br] Kadira: completed instrumenting the app
[logview-dev.logview.com.br]  >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

**Comment by MasterJames** [comment]
I'm going to recommend trying mupx in this situation too.
It uses docker and rebuilds the package on the container which hopefully adresses it.
It appears it couldn't download pg when building... maybe the connection is blocked by your target machines security group etc. SSH into the machine and check it can install pg etc manually.
Using the DEBUG logging option may also reveal details.

**Comment by gibex** [comment]
Had a similar issue and installing the npm package on DO by hand solve it.

**Comment by mariobaldini** [comment]
MasterJames, I could install the package manually (globally, with -g). So I think it's not blocked. 

gibex, how did you installed the package? Installing with -g did work? 

In my local machine it only worked when I installed without -g (within my project root folder and it created the node_modules folder in it). But I'm not sure in which path I should do it in the server. 

But I will try using mupx and let you know. 

Thanks

**Comment by MasterJames** [comment]
Interesting doing it manually I thought was just to test the connection to the repository was accessible.

```
 stepping down to uid: meteoruser
```

Maybe this part of your error suggest trying npm install as user meteoruser.  
To do that you can use "sudo su -" and ctrl-c or something like that. Either the prompt or whoami should clarify the user account and then test npm again maybe that user lacks permissions etc.

**Comment by gibex** [comment]
I used as root:  npm -g install package@version (DO - Ubuntu)

**Comment by mariobaldini** [comment]
MUPX gives the same error: `cannot find module pg`

```
mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /atto/logview-webapp
Using buildOptions : {}

Started TaskList: Deploy app 'meteor' (linux)
[devdo.logview.com.br] - Uploading bundle
[devdo.logview.com.br] - Uploading bundle: SUCCESS
[devdo.logview.com.br] - Sending environment variables
[devdo.logview.com.br] - Sending environment variables: SUCCESS
[devdo.logview.com.br] - Initializing start script
[devdo.logview.com.br] - Initializing start script: SUCCESS
[devdo.logview.com.br] - Invoking deployment process
[devdo.logview.com.br] - Invoking deployment process: SUCCESS
[devdo.logview.com.br] - Verifying deployment
[devdo.logview.com.br] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    /amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.0 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    => Starting meteor app on port:80

    /bundle/bundle/programs/server/node_modules/fibers/future.js:245
                            throw(ex);
                                  ^
    Error: Cannot find module 'pg'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.Npm.require (/bundle/bundle/programs/server/boot.js:150:18)
        at server/api.js:2:1
        at server/api.js:241:1
        at /bundle/bundle/programs/server/boot.js:242:10
        at Array.forEach (native)
        at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
mario@ideapad:/atto/logview-webapp/private/mupx-devdo$ 
```

For the record (and maybe help future users) I found some issues specific to the Server Mania provider. ServerMania uses a 'minimal' ubuntu image. I think that mupx has some target dependency not addressed by mupx setup. 

MUPX SETUP fails in ServerMania (Ubunut 14.04). 

```
$ mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Setup (linux)
[dev.logview.com.br] - Installing Docker
[dev.logview.com.br] - Installing Docker: SUCCESS
[dev.logview.com.br] - Setting up Environment
[dev.logview.com.br] - Setting up Environment: SUCCESS
[dev.logview.com.br] - Copying MongoDB configuration
[dev.logview.com.br] - Copying MongoDB configuration: SUCCESS
[dev.logview.com.br] - Installing MongoDB
[dev.logview.com.br] x Installing MongoDB: FAILED

    -----------------------------------STDERR-----------------------------------
    Cannot connect to the Docker daemon. Is the docker daemon running on this host?
    -----------------------------------STDOUT-----------------------------------
    ----------------------------------------------------------------------------
```

```
$ mupx logs -f

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

[dev.logview.com.br] Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

But I instantiated a VM with same specs and OS at Digital Ocean, and at least the mupx setup worked fine. 

```
mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Setup (linux)
[devdo.logview.com.br] - Installing Docker
[devdo.logview.com.br] - Installing Docker: SUCCESS
[devdo.logview.com.br] - Setting up Environment
[devdo.logview.com.br] - Setting up Environment: SUCCESS
[devdo.logview.com.br] - Copying MongoDB configuration
[devdo.logview.com.br] - Copying MongoDB configuration: SUCCESS
[devdo.logview.com.br] - Installing MongoDB
[devdo.logview.com.br] - Installing MongoDB: SUCCESS
```

Although mupx deploy didn't work. (first log in this message). 

After installing the package manually in the remote (sudo npm install pg -g), the error persisted in the mupx setup (as expected I think, since it was installed in the host OS, and not within the docker image?).

When using mupx I couldn't install the dependency in the meteoruser context, since there's no such user in the host OS. (`sudo su meteoruser --> No passwd entry for user 'meteoruser').

And couldn't properly install in the meteoruser of regular mup. I can switch to its context (sudo su meteoruser), but it doesn't have a home folder so it appears pointless to install in a random folder. 
But I did installed with global scope (-g) as was mentioned. 

```
npm list -g --depth=0
/usr/lib
├── forever@0.15.1
├── node-gyp@3.1.0
├── pg@4.4.3
├── userdown@0.2.1
└── wait-for-mongo@0.2.0
```

As you can see pg is installed in the remote machine, but mup deploy/init/meteoruser "can't find it".

I'm not sharing any images between mup and mupx (rebuilding the VM images from provider's default). 

And with the `pg = Npm.require('pg');` and related function commented, everything works fine. 

I'll keep trying and post here any update.

**Comment by mariobaldini** [comment]
The tests bellow are local and not related to mup/mupx:
- Removed the package locallly/globally. 
- Installing the package globally doesn't solve the dependency. 
- Only installing without the -g, in the project root, solved the 'pg' dependency. (created the node_modules folder...). Tried to install it in the subfolder lib, but it doesn't work. I need to install it locally, in the project root. 

```
drwxrwxr-x 1 mario mario  124 Nov 23 11:52 ./
drwxr-xr-x 1 mario mario  246 Out 27 11:58 ../
drwxrwxr-x 1 mario mario  740 Out 29 12:59 client/
drwxrwxr-x 1 mario mario   28 Out 27 11:13 collections/
drwxrwxr-x 1 mario mario  204 Nov 23 11:54 .git/
drwxrwxr-x 1 mario mario   58 Nov 23 11:52 lib/
drwxrwxr-x 1 mario mario  138 Nov 21 15:32 .meteor/
drwxr-xr-x 1 mario mario    4 Nov 23 11:52 node_modules/
drwxrwxr-x 1 mario mario  382 Nov 23 10:10 private/
drwxrwxr-x 1 mario mario 1,1K Out 27 19:57 public/
drwxrwxr-x 1 mario mario  288 Nov 21 15:33 server/
```

In which folder of the remote server I should install the package 'locally'? (without -g). 

I tried at /opt/logview/app (created the node_modules/pg folder there) but the error persists.

**Comment by MasterJames** [comment]
Sometimes one can add stuff in their deploy shell. 
https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh
There you can call 
Docker exec with you npm install needs etc.

**Comment by semeano** [comment]
@mariobaldini how did you solved the issue? I'm facing the same problem with a different package.

Edit: nevermind. This fixed my issue: https://github.com/arunoda/meteor-up/issues/938#issuecomment-208225940
