### ISSUE TITLE
Supporting AWS Beanstalk

### ISSUE THREAD

**Issue by isAlmogK** [arunoda/meteor-up-legacy#77]
Hi, 
Does this support AWS Beanstalk?

**Comment by arunoda** [comment]
Nope. That's a different story.

**Comment by adamgins** [comment]
HI, just wondering if folk have Meteor 1.0 working with Beanstalk? I am about to extrapolate from this pre 1.0 example... https://www.youtube.com/watch?v=RPLThdFgztg 

@almogdesign  just wondering if you got it working and any issues with AWS EB?

**Comment by isAlmogK** [comment]
@adamgins I'm using modulus.io really happy with them they also have very easy to use CLI for deployments

**Comment by adamgins** [comment]
@almogdesign  thanks. Still looking for AWS beanstalk solution as I am planning ot use AWS for storage and image/video processing and I understand that data transfer etc is probably faster/cheaper. Phew been struggling with using the native "meteor build" together with beanstalk today... I have been using MUP for a while with AWS and it works great (thanks @arunoda )... would love to have it work with beanstalk :-)

**Comment by isAlmogK** [comment]
I don't think the data transfer is a big I plan on using AWS S3

**Comment by adamgins** [comment]
anyway , still keen to get it running on Beanstalk. Perhaps I need to try demeteorizer. Where I have run into issues with the "meteor build" is things like bcrypt are platform specific... so I need to rip them out of the bundle and then send instructions to Beanstalk to re-install the. Anyway, will keep trying for now before I jump ship.
