### ISSUE TITLE
Question: Does mup setup work on Windows Server?

### ISSUE THREAD

**Issue by jase88** [arunoda/meteor-up-legacy#771]
Hi,
Just a short question: Can mup also be used on a Windows system (serverside)?

Thanks in advance!

//edit: Just read it now: It supports only Debian/Ubuntu flavours and Open Solaris

**Comment by MasterJames** [comment]
It requires Ubuntu 14 on the server (only one supported). Mupx is targeted more to docker which means any kind of os can run inside the containers. Still it might be possible to customize it somehow, but no I don't think in its current state you can deploy to a windows server. I doubt there's a reason windows is a better option. One it's not as cheaply scalable etc.
