### ISSUE TITLE
Capturing node server output to logfile

### ISSUE THREAD

**Issue by zenmatt** [arunoda/meteor-up-legacy#78]
Hi is it possible to specify something in mup.json that captures the output of the `node /usr/bin/userdown /opt/whatever/app/main.js` command? When debugging locally I often bundle the app and run node in the foreground in order to debug issues, would be great to do this in deployed instances as well.

**Comment by arunoda** [comment]
You can access it with [`mup logs -t`](https://github.com/arunoda/meteor-up#access-logs)

And it's located at `/var/log/upstart/meteor.log` in your server.
