### ISSUE TITLE
Port mapping problem.

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#793]
even I didn't include ssl object in my mup.json file. that whole build process is still assume I use ssl and redirect all the traffic into 433 port even if listen at 80 only.

here is my config: 

``` json
{
  // Server authentication info
  "servers": [
    {
      "host": "myhost",
      "username": "myuser",
      "password": "mypassword",
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
      "env": {
        "PORT": 3000,
        "NODE_ENV": "production"
      }
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // Application name (No spaces)
  "appName": "myapp",

  // Location of app (local directory)
  "app": "../../",

  // Configure environment
  "env": {
    "PORT": 3000,
    "ROOT_URL": "http://myurl.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15,

  // show a progress bar while uploading.
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}
```

when I run this inside my remote server:
`root@localhost:/# curl -L http://localhost:3000`
`curl: (7) Failed to connect to myurl port 443: Connection refused`

**Comment by MasterJames** [comment]
Do you have force-ssl package installed. Make a visual confirmation in the packages file, since sometime add remove misses something.

**Comment by ghost** [comment]
in meteor app? no, there is no force-ssl, the apache server is currently serve a wordpress and it's fine without ssl, so I think on apache level, there are no force-ssl installed.

**Comment by MasterJames** [comment]
Not sure why it says myurl? Maybe there's a redirect to a url with httpS somewhere?

**Comment by ghost** [comment]
I double checked the settings, they all are http uri s, I still think it's the app that redirected it self.

**Comment by MasterJames** [comment]
Well maybe if you can make a default meteor app to test in its place.

**Comment by MasterJames** [comment]
A possibly final thought is that maybe it could be environment variables that are causing that too. If you could view all your environment variables maybe there's something revealing there. That is if a default meteor app is still misbehaving.

**Comment by ghost** [comment]
@MasterJames  thanks for the help, I think it's docker it self now, when we run mupx and it runs in docker deamon mode, so according to the doc, it will be protected from client access by using ssl. https://docs.docker.com/engine/articles/https/#daemon-modes because inside the container, when I do curl -i http://localhost:3000, it returns the page correctly.

**Comment by ghost** [comment]
@MasterJames  problem solved by change how I locally config the docker setup. @MasterJames thanks for help!
