### ISSUE TITLE
Installing MongoDB: FAILED

### ISSUE THREAD

**Issue by dmitrika** [arunoda/meteor-up-legacy#799]
Cant deploy my app to DigitalOcean server:

Started TaskList: Setup (linux)
[178.62.195.250] - Installing Docker
[178.62.195.250] - Installing Docker: SUCCESS
[178.62.195.250] - Setting up Environment
[178.62.195.250] - Setting up Environment: SUCCESS
[178.62.195.250] - Copying MongoDB configuration
[178.62.195.250] - Copying MongoDB configuration: SUCCESS
[178.62.195.250] - Installing MongoDB
[178.62.195.250] x Installing MongoDB: FAILED

-----------------------------------STDERR-----------------------------------
    Error response from daemon: Cannot start container 821b4cb8af14586b9928814e0f0eb37b08e3467f92c2206598d306b60d258728: failed to create endpoint mongodb on network bridge: Error starting userland proxy: listen tcp 127.0.0.1:27017: bind: address already in use
    -----------------------------------STDOUT-----------------------------------
    latest: Pulling from library/mongo
    Digest: sha256:8453d81cfe34363285a203720bf08b37dcbd622023ea2fe54c0de97d2e257281
    Status: Image is up to date for mongo:latest
    mongodb
    821b4cb8af14586b9928814e0f0eb37b08e3467f92c2206598d306b60d258728

---

**Comment by MasterJames** [comment]
It says something (probably mongodb) is already using the port 27017
Make sure it's a fresh instance. SSH into it before you deploy and then telnet to the port or whatever means to assert what's already running there.

**Comment by dmitrika** [comment]
Thanks for support. Solved.

**Comment by matthlavacka** [comment]
how? I have the same problem
