### ISSUE TITLE
meteor 0.8.2 deploy fails - Invalid ELF Header

### ISSUE THREAD

**Issue by nooitaf** [arunoda/meteor-up-legacy#80]
As stated in [meteor-talks comments](https://groups.google.com/d/msg/meteor-talk/rux3C-xykgU/89QCMbxmFGkJ), the 0.8.2 release is the first where the binary npm module dependency issue stops allowing the app to run 'as is'.

bcrypt has binaries in it so if you build the package on one architecture and deploy on another the application won't start with the error "Invalid ELF Header"

**Comment by arunoda** [comment]
There is already a fix. Please update meteor up from npm and deploy again.
It works.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

On Tue, Jun 24, 2014 at 4:51 PM, Ralf Brandenstein <notifications@github.com

**Comment by nooitaf** [comment]
Did the update, works, Awsome!! :)

**Comment by arunoda** [comment]
Nice.

On Tuesday, June 24, 2014, Ralf Brandenstein notifications@github.com
wrote:

> Closed #80 https://github.com/arunoda/meteor-up/issues/80.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/80#event-134509744.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
