### ISSUE TITLE
Setup, reconfig, deploy fails with no error

### ISSUE THREAD

**Issue by ksendra** [arunoda/meteor-up-legacy#800]
Hello, 

All commands that are related to moving stuff to the server stopped working for me (were working before).
mupx reconfig returns "Sending environment variables: FAILED Failure"
mupx setup returns "Copying MongoDB configuration: FAILED Failure"
mupx deploy returns "Uploading bundle: FAILED Failure"

Reason of failure is not specified. I'm using close-to default mup.json file from the mupx example. Also, as mentioned before, deployment worked at first (first couple of days actually) and now suddenly stopped.

Any suggestions on what would fix this?

**Comment by MasterJames** [comment]
Sounds like maybe you need to double check all versions are updated and supported etc.
update meteor to 1.2.1 and use node 0.10.40 and make sure your target is an instance of Ubuntu 14.
Also try mupx if you not using that one already and having problems with mup

**Comment by ksendra** [comment]
Meteor is at 1.2.1, node is at 10.40 and ubuntu is at 14.04.

As I said before: I deployed a version to the server just fine. Then after like 10min. tried to deploy it again and started getting previously mentioned errors.

Only thing that got my attention is that currently my system is using 97% of 7.74GB. Is it possible that the problem is that the system does not have enough space to push the version i'm trying to deploy?

**Comment by MasterJames** [comment]
Oh it can fill up with logs and docker stuff potentially. Maybe that's the problem. There was a thread in here about that somewhere?

**Comment by MasterJames** [comment]
I think this was the one ...
https://github.com/arunoda/meteor-up/issues/762
which might help?

**Comment by ksendra** [comment]
Thanks for the thread link. I tried what was suggested there but with no success. Still i'm sure that was a memory-related problem. We moved to a bigger server instance - everything works there.
