### ISSUE TITLE
deploy to unequal "."

### ISSUE THREAD

**Issue by sakulstra** [arunoda/meteor-up-legacy#805]
When deploying the app via mupx deploy everything works as expected as long as I am using:

``` js
"app":"."
```

When using anything else, I get:

``` sh
Invalid configuration file mup.json: There is no meteor app in the current app path.
```

What am I doing wrong?

**Comment by sakulstra** [comment]
sry missunderstanding the docs :/

**Comment by sarkistlt** [comment]
i have the same problem, what was ur solution?

**Comment by bevinhex** [comment]
same here , keep getting 
`Invalid configuration file mup.json: There is no meteor app in the current app path.`

**Comment by bevinhex** [comment]
Got rid of the problem, looks like I put the wrong path for "app", changed it to:`"app": ".",
`, then solved the error.
