### ISSUE TITLE
bcrypt_lib.node: wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by skarborg** [arunoda/meteor-up-legacy#83]
I doubt this is a bug per se with meteor-up but just in case anyone else stumbles upon it...

After upgrading to 0.8.2 (which includes changing accounts-password from SRP -> bcrypt) I started receiving this error (in server logs) after deploying:

```
Error: /opt/teamhub/app/programs/server/node_modules/bcrypt/build/Release/bcrypt_lib.node: wrong ELF class: ELFCLASS32
    at Module.load (module.js:356:32)
```

Turns out I was trying to deploy from a 32bit VM to a 64bit server. I guess during the bundling process it must include a 32bit binary. This used to work pre Meteor 0.8.2.

Deploying from a 64bit OS solved this for me. 

Not so obvious to the less experienced perhaps :)

**Comment by arunoda** [comment]
Update Meteor UP from NPM.
See this thread too: https://github.com/arunoda/meteor-up/issues/79
