### ISSUE TITLE
mup hangs on build at mup deploy after recent upgrade to El Capitain

### ISSUE THREAD

**Issue by reduxdj** [arunoda/meteor-up-legacy#833]
After a recent El Capitan Upgrade, mup stopped working.

DEBUG=\* mup deploy
## Meteor Up: Production Quality Meteor Deployments

Building Started: /Users/me/thing

(nothing happens)

**Comment by reduxdj** [comment]
but then it works

**Comment by MasterJames** [comment]
I just realized there can be no space between DEBUG and the =\* part. You can do only DEBUG*= ___.
I know you typed that here but it's a good thing to point out to others and I thought maybe that's what happen there.
