### ISSUE TITLE
MUP deployment fails with with meteor + redis (no mongo)

### ISSUE THREAD

**Issue by pranny** [arunoda/meteor-up-legacy#834]
I have a meteor app which uses redis instead of mongodb. My `mup.json` file is as follows

```
{
  "servers": [
    {
      "host": "xxx.xxx.xxx.xxx",
      "username": "ubuntu",
      "pem": "~/.ssh/octo.pem"
    }
  ],
  "setupMongo": false,
  "setupNode": true,
  "nodeVersion": "0.10.40",
  "setupPhantom": true,
  "enableUploadProgressBar": true,
  "appName": "octo",
  "app": "/Users/pranav/workspace/octo/octo.nerve/",
  "env": {
    "ROOT_URL": "http://somethinghere.ap-southeast-1.compute.amazonaws.com",
    "PORT": 4000,
    "REDIS_URL":"redis://127.0.0.1:6379",
    "REDIS_CONFIGURE_KEYSPACE_NOTIFICATIONS": 1
  },
  "deployCheckWaitTime": 15
}
```

As can be seen, I am using redis and no mongo. However, whenever I do `mup deploy` I get the following error

```
[xxx.xxx.xxx.xxx] - Uploading bundle
  nodemiral:sess:xxx.xxx.xxx.xxx copy file - src: /var/folders/jn/1xhkgc6x5h39kptrbcs7z18m0000gn/T/250b5cba-002b-4599-9fa2-987c8ace0574/bundle.tar.gz, dest: /opt/octo/tmp/bundle.tar.gz, vars: undefined +0ms
[xxx.xxx.xxx.xxx] - Uploading bundle: SUCCESS
[xxx.xxx.xxx.xxx] - Setting up Environment Variables
  nodemiral:sess:xxx.xxx.xxx.xxx copy file - src: /Users/pranav/.nvm/versions/node/v5.0.0/lib/node_modules/mup/templates/linux/env.sh, dest: /opt/octo/config/env.sh, vars: {"env":{"ROOT_URL":"http://somethinghere.ap-southeast-1.compute.amazonaws.com","PORT":4000,"REDIS_URL":"redis://127.0.0.1:6379","REDIS_CONFIGURE_KEYSPACE_NOTIFICATIONS":1,"METEOR_SETTINGS":"{\"public\":{}}","CLUSTER_ENDPOINT_URL":"http://xxx.xxx.xxx.xxx"},"appName":"octo"} +13s
[xxx.xxx.xxx.xxx] - Setting up Environment Variables: SUCCESS
[xxx.xxx.xxx.xxx] - Invoking deployment process
[xxx.xxx.xxx.xxx] x Invoking deployment process: FAILED
    -----------------------------------STDERR-----------------------------------
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
        throw err;
              ^
    Error: TIMEOUTED_WAIT_FOR_MONGO
        at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
        at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
    -----------------------------------STDOUT-----------------------------------
    .1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
    wait-for-mongo: failed to connect to [127.0.0.1:27017]
```

Why does it wait for mongo to start? Even though mongo is not present anywhere in the scene. However, when I do `mup start`, I can see the log which says app started. Even though I am unable to access my app at xxx.xxx.xxx.xxx:4000

```
[xxx.xxx.xxx.xxx] - Starting app
[xxx.xxx.xxx.xxx] - Starting app: SUCCESS
```

The logs are not useful either. When i do `mup logs` I just see the following, which is not too useful.

```
 >> stepping down to uid: meteoruser
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
```

Any reason what could be happening?

**Comment by MasterJames** [comment]
Redis instead of mongo? ! Is there a link you suggest to learn more about that? 
I think if you set in the settings useMongo to off it should work? 

```
"setupMongo": false,
```

Is that already false? Maybe post you settings otherwise. It's not designed for redis clearly. How to alter a new version/PR is not easy. 
Certainly it's possible somehow.
Are you using dev branch version mupx or  the older mup? Mupx is typically prefered as it solves many problems people have with mup but maybe in your case it's different.

**Comment by pranny** [comment]
I'm using this package https://atmospherejs.com/slava/redis-livedata and have completely removed mongodb from my meteor app. My `setupMongo` is set to `false` in mup.json. My `settings.json` is mostly empty. It's as follows

```
{
  "public": {
  }
}
```

Also, I am using _older_  mup and _not_ mupx. I saw the source and it looks like mup/x are tightly coupled with mongodb. I will try to fork/pr to make a redis version if that's what it takes.

**Comment by MasterJames** [comment]
Okay that's great! 
Experiment with mupx just to see if it helps.
Next consider a test with default meteor app using mongo and make sure your target is deployable to in a normal situation. If not it should be easier to fix with mupx and then it should deploy with your redis project or then it's time to PR. Tracing manually step by step until the problem presents itself.

**Comment by MasterJames** [comment]
Those can't be proper settings?  It's totally empty?

**Comment by pranny** [comment]
Yes, as weird it may look. The `settings.json` is totally empty. Not found enough things to put in there. Mostly it is ENV variables which are inside `mup.json`. Let me try with mupx and will update then. Till then, maybe this block [linux/deploy.sh:125](https://github.com/arunoda/meteor-up/blob/master/templates/linux/deploy.sh#L125) should be inside a block that checks for `setupMongo` or if we add `redis` support, then should check for redis availability.

**Comment by MasterJames** [comment]
Try putting more of the mupx init default settings back and set deployCheckWaitTime to 120 seconds just to be sure it's not that.
Anyway the deploy.sh is different in mupx and that's the one I use. it's docker-centric and (for now) a/the preferred way forward in the future.

**Comment by pranny** [comment]
mupx seems to do better job. At least now I have error connecting to redis server

```
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
        at RedisClient.on_error (/bundle/bundle/programs/server/npm/slava_redis-livedata/node_modules/redis/index.js:185:24)
        at Socket.<anonymous> (/bundle/bundle/programs/server/npm/slava_redis-livedata/node_modules/redis/index.js:95:14)
        at Socket.emit (events.js:95:17)
        at net.js:441:14
        at process._tickCallback (node.js:448:13)
```

But I have redis server running, as I can open redis-cli and connect. Neverthless, that does not belong to this project's scope.
