### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by derwaldgeist** [arunoda/meteor-up-legacy#839]
Once in a while, mupx deploy breaks with this error message in the log:

```
/usr/local/lib/node_modules/mup/lib/config.js:91
    return location.replace('~', process.env.HOME);
                   ^

TypeError: Cannot read property 'replace' of undefined
    at rewriteHome (/usr/local/lib/node_modules/mup/lib/config.js:91:20)
    at Object.exports.read (/usr/local/lib/node_modules/mup/lib/config.js:73:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:20:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

mupx deploy itself reports this in this case:

```
- Uploading bundle
- Uploading bundle: SUCCESS
- Sending environment variables
- Sending environment variables: SUCCESS
- Initializing start script
- Initializing start script: SUCCESS
- Invoking deployment process
- Invoking deployment process: SUCCESS
- Verifying deployment
x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
     to the latest stable version, run:
    npm WARN deprecated 
    npm WARN deprecated   npm -g install npm@latest
    npm WARN deprecated 
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated 
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

Typically, all of these errors magically disappeared and the deployment just worked fine if I simply repeated it or if I stopped the app before deploying, so I didn't care too much about it.

But today, it came up more than once, so I decided to report this issue, maybe it can be solved somehow, or I am doing something wrong here.

BTW: Does the latter message mean that I should update npm? Is it recommended to do so?

PS: I am running this on a fresh Amazon EC2 Ubuntu instance, without any additions.

**Comment by derwaldgeist** [comment]
Sorry, it was my fault that the deploy broke. I found another error in the logs now. I am closing this, but would be still curious where this "Cannot read property" error comes from.

**Comment by ChenLi0830** [comment]
Hey @derwaldgeist , I have the same error can can't figure out why. Do you still remember what you did to fix this problem? Thanks!

**Comment by SatishGandham** [comment]
Same error. How did you fix it?

**Comment by MasterJames** [comment]
I'll suggest you extend the wait time in the settings to maybe 120 just to see if it's that.
Why "location" is undefined would take some looking at if repeatable. Chances are the new port at kadirahq is going to handle this better. It would be important to know if it's still randomly happening on the newer port.

**Comment by ChenLi0830** [comment]
Thanks for your reply @MasterJames , but extending the wait time to 120 doesn't remove the error message. BTW, although I get the error message everytime I run 'mupx deploy', the deployed app actually works as far as I can see.

**Comment by MasterJames** [comment]
240?

**Comment by ChenLi0830** [comment]
Changed it to 300 and it is still the same. 

Here is the error message from mupx

```
x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    alled in `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
    ansi-regex@0.2.1 node_modules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    escape-string-regexp@1.0.4 node_modules/escape-string-regexp

    chalk@0.5.1 node_modules/chalk

    supports-color@0.2.0 node_modules/supports-color

    strip-ansi@0.3.0 node_modules/strip-ansi

    has-ansi@0.1.0 node_modules/has-ansi

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.1 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.8 node_modules/fibers
    => Starting meteor app on port:80
    Kadira: completed instrumenting the app
    Kadira: successfully authenticated

    => Redeploying previous version of the app
```

And here is the error message from the log

```
/usr/local/lib/node_modules/mup/lib/config.js:91
    return location.replace('~', process.env.HOME);
                   ^

TypeError: Cannot read property 'replace' of undefined
    at rewriteHome (/usr/local/lib/node_modules/mup/lib/config.js:91:20)
    at Object.exports.read (/usr/local/lib/node_modules/mup/lib/config.js:73:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/mup/bin/mup:20:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

```

**Comment by MasterJames** [comment]
Okay thanks for trying that.
You're using mupx and have a fresh Ubuntu 14+ target. Maybe post you settings too. Why 'location' is undefined is not obvious but maybe there's a value missing from a typical default settings file.

**Comment by joncursi** [comment]
@derwaldgeist what was your solution? same error here

**Comment by derwaldgeist** [comment]
To fix the

```
 Cannot read property 'replace' of undefined
```

error, it was enough to try again. I still haven't found out what triggers this error.

The only time I was not able to resolve the problem by trying again was when there was another problem on the server that I found out using mupx logs --tail 50. But this problem wasn't related to the error message above.

**Comment by joncursi** [comment]
I was able to get past this error by downgrading MongoDB from 3.2 to 3.0.7. Seems like Meteor support for MongoDB 3.2 is spotty at best right now, especially with replica sets

**Comment by ChenLi0830** [comment]
Hi @joncursi could you be more specific? Are you using mupx? If so, did you downgrade MongoDB in the docker container? Thanks!

**Comment by ChenLi0830** [comment]
Hi @MasterJames , you are right, I am using mupx and a Ubuntu 14.04 64bit server. 
Here is my configuration file. 

```
{
  // Server authentication info
  "servers": [
    {
      "host": "101.200.130.***",
      "username": "******",
      "password": "******",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      //"pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": true,

  // Application name (no spaces).
  "appName": "myAppName",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": ".",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://101.200.130.***"
    },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 300,

  // show a progress bar while uploading.
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true,

  "ssl": {
    "certificate": "./ssl/edf4bc5d27a15377.crt", // this is a bundle of certificates
    "key": "./ssl/ssl.key", // this is the private key of the certificate
    "port": 443 // 443 is the default value and it's the standard HTTPS port
  }
}
```

**Comment by ChenLi0830** [comment]
@MasterJames I don't know if this is relevant my project uses meteor force-ssl package.

**Comment by MasterJames** [comment]
Oh well if you temporarily disable it does the problem go away? 
Consider also setting the path to be absolute not ".", it should be okay if run in the correct location? Still it's just to make sure. 
Otherwise one way is to hack a exit () break point into the code where the problem is and try to understand why the location is undefined.
Maybe update everything or do a test with a blank default meteor project and see if that deploys then add in your packages and see if those are at fault.

**Comment by ChenLi0830** [comment]
I've been using the path '.' since a while ago and it has been working fine. But I will give the absolute path a try. Also, I've been trying to use https://github.com/kadirahq/meteor-up, and I can deploy the app successfully when using an external MongoDB, but not a local one. 

I created a issue [here](https://github.com/kadirahq/meteor-up/issues/107) for that.

**Comment by micktaiwan** [comment]
I was directed here while searching for this error.
I had this in my mup config file
"ssl": {
//    "pem": "../bundle.pem",
//    "backendPort": 80
},

Commenting ENTIRELY the ssl thing got rid of the error.
Just in case...
