### ISSUE TITLE
mupx won't deploy due to an outdated version

### ISSUE THREAD

**Issue by fschaeffler** [arunoda/meteor-up-legacy#847]
We had a running setup, where we did a deployment about 3 hours ago and everything went as expected. However, we now are not able to do deployments via mupx anymore. I'm not sure if the error is due to an update in meteor or the docker image for the mupx-deployment. My questions is now, how can I solve that situation?

Meteor version
METEOR@1.2.0.2

The log we're getting is as follows.
Started TaskList: Deploy app '**_' (linux)
[**_] - Uploading bundle
[**_] - Uploading bundle: SUCCESS
[**_] - Sending environment variables
[**_] - Sending environment variables: SUCCESS
[**_] - Initializing start script
[**_] - Initializing start script: SUCCESS
[**_] - Invoking deployment process
[**_] - Invoking deployment process: SUCCESS
[**_] - Verifying deployment
[***] x Verifying deployment: FAILED
    -----------------------------------STDERR-----------------------------------
     to the latest stable version, run:
    npm WARN deprecated 
    npm WARN deprecated   npm -g install npm@latest
    npm WARN deprecated 
    npm WARN deprecated (Depending on how Node.js was installed on your system, you
    npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
    npm WARN deprecated on Windows, run them from an Administrator prompt.)
    npm WARN deprecated 
    npm WARN deprecated If you're running the version of npm bundled with
    npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
    npm WARN deprecated will be bundled with a version of npm@2, which has some small
    npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    => Starting meteor app on port:80

```
=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------
To see more logs type 'mup logs --tail=50'
----------------------------------------------------------------------------
```

Our versions file looks as follows.
4commerce:pubsettings-template-helper@1.0.0
accounts-base@1.2.1
accounts-password@1.1.3
alamont:chartjs@0.0.9
alanning:roles@1.2.14
aldeed:collection2@2.8.0
aldeed:collection2-core@1.0.0
aldeed:schema-deny@1.0.1
aldeed:schema-index@1.0.1
aldeed:simple-schema@1.5.3
angular@1.0.1
angular:angular@1.4.7
anti:i18n@0.4.3
aslagle:reactive-table@0.8.21
autoupdate@1.2.3
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:filesystem@0.1.2
cfs:http-methods@0.0.30
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.3
cfs:tempstore@0.1.5
cfs:ui@0.1.3
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.0.6
coffeescript@1.0.10
d3js:d3@3.5.8
dburles:google-maps@1.1.5
dburles:mongo-collection-instances@0.3.4
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.1
ddp-rate-limiter@1.0.0
ddp-server@1.2.1
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.5
ecmascript-collections@0.1.6
ejson@1.0.7
email@1.0.7
fastclick@1.0.7
geojson-utils@1.0.4
harrison:papa-parse@1.1.1
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
iron:controller@1.0.8
iron:core@1.0.8
iron:dynamic-template@1.0.8
iron:layout@1.0.8
iron:location@1.0.9
iron:middleware-stack@1.0.9
iron:router@1.0.9
iron:url@1.0.9
jquery@1.11.4
jspdf:autotable@1.3.0
jspdf:core@1.1.135
lai:collection-extensions@0.1.4
launch-screen@1.0.4
less@2.5.0_3
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
mdg:geolocation@1.1.0
mdg:validation-error@0.2.0
meteor@1.1.9
meteor-base@1.0.1
meteorhacks:aggregate@1.2.1
meteorhacks:collection-utils@1.2.0
meteorhacks:ssr@2.2.0
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
momentjs:moment@2.10.6
monbro:mongodb-mapreduce-aggregation@1.0.1
mongo@1.1.2
mongo-id@1.0.1
mongo-livedata@1.0.9
mrt:moment@2.8.1
mrt:moment-timezone@0.2.1
mrt:nprogress@0.2.0
nemo64:bootstrap@3.3.5_2
nemo64:bootstrap-data@3.3.5
npm-bcrypt@0.7.8_2
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
promise@0.5.0
raix:eventemitter@0.1.3
random@1.0.4
rate-limit@1.0.0
reactive-dict@1.1.2
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
routepolicy@1.0.6
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.1
templating@1.1.4
templating-tools@1.0.0
themeteorchef:jquery-validation@1.14.0
tracker@1.0.9
tsega:bootstrap3-datetimepicker@4.17.37_1
twbs:bootstrap@3.3.5
ui@1.0.8
underscore@1.0.4
urigo:angular@0.10.2
url@1.0.5
webapp@1.2.2
webapp-hashing@1.0.5
zimme:active-route@2.3.2
zimme:iron-router-auth@3.1.0

**Comment by MasterJames** [comment]
Try extending your wait for deploy time.

**Comment by fschaeffler** [comment]
@MasterJames I did set the following value in "deployCheckWaitTime": 600 in my mup.json file. Strange thing is that the deployment sometimes works and sometimes doesn't work. If it's not working, the logs look as follows. Any other ideas how to solve it?

[127.0.0.1] - Uploading bundle: SUCCESS
[127.0.0.1] - Sending environment variables
[127.0.0.1] - Sending environment variables: SUCCESS
[127.0.0.1] - Initializing start script
[127.0.0.1] - Initializing start script: SUCCESS
[127.0.0.1] - Invoking deployment process
[127.0.0.1] - Invoking deployment process: SUCCESS
[127.0.0.1] - Verifying deployment
[127.0.0.1] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80
-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

**Comment by fschaeffler** [comment]
@MasterJames the following issues seem to be duplicates, right?
https://github.com/arunoda/meteor-up/issues/854
https://github.com/arunoda/meteor-up/issues/853
https://github.com/arunoda/meteor-up/issues/850

By the way, we didn't change anything at our base systems and 4 days ago, everything was running as expected. For every deployment, we create a fresh and new instance on AWS from our company base image, which has lots of the environment already installed. The only thing, which is done on every new instance is the following
- meteor build /tmp/$app --server $rool_url --mobile-settings private/settings.development.json
- mupx setup --config=mup.json --settings=private/settings.development.json
- mupx deploy --config=mup.json --settings=private/settings.development.json

**Comment by fschaeffler** [comment]
The only weird thing in the logs looks like the following ones. Looks like docker is reloading every few seconds.

```
Jan 27 22:25:41 hikey-prod-874 kernel:  [ 3823.437132] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:25:41 hikey-prod-874 kernel:  [ 3823.437139] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:25:54 hikey-prod-874 kernel:  [ 3836.652239] docker0: port 1(vethc3f5a98) entered disabled state
Jan 27 22:25:54 hikey-prod-874 kernel:  [ 3836.678296] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:25:54 hikey-prod-874 kernel:  [ 3836.678303] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:07 hikey-prod-874 kernel:  [ 3849.760230] docker0: port 1(vethc3f5a98) entered disabled state
Jan 27 22:26:07 hikey-prod-874 kernel:  [ 3849.785147] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:07 hikey-prod-874 kernel:  [ 3849.785153] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:20 hikey-prod-874 kernel:  [ 3862.936234] docker0: port 1(vethc3f5a98) entered disabled state
Jan 27 22:26:20 hikey-prod-874 kernel:  [ 3862.961075] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:20 hikey-prod-874 kernel:  [ 3862.961082] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:34 hikey-prod-874 kernel:  [ 3876.124695] docker0: port 1(vethc3f5a98) entered disabled state
Jan 27 22:26:34 hikey-prod-874 kernel:  [ 3876.149488] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:34 hikey-prod-874 kernel:  [ 3876.149503] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:47 hikey-prod-874 kernel:  [ 3889.152238] docker0: port 1(vethc3f5a98) entered disabled state
Jan 27 22:26:47 hikey-prod-874 kernel:  [ 3889.177082] docker0: port 1(vethc3f5a98) entered forwarding state
Jan 27 22:26:47 hikey-prod-874 kernel:  [ 3889.177089] docker0: port 1(vethc3f5a98) entered forwarding state
```

**Comment by fschaeffler** [comment]
It seems like the meteor-process inside the docker-container is restarting every ~ 15 seconds. Found out about this by logging to the host-server and doing a **docker logs <app name>**.

```
=> Starting meteor app on port:80
info:  =====> logger initiated at Wed Jan 27 2016 20:59:52 GMT+0000 (UTC) <=====
info: *** startup
info: Meteor.settings:
info:  DEV_BUILD=false, BUILD_DISPLAY_NAME=#4, JOB_NAME=**APP NAME**-production, GIT_COMMIT=a99d166f2eafb802cfad7d6565498cfd22143a79, ***_PORTAL_VERSION=0.8.5, ***_PORTAL_NAME=*** Admin Portal, ***_TRACKER_VERSION=0.8.5, ***_TRACKER_NAME=*** Tracker
info: 
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80
info:  =====> logger initiated at Wed Jan 27 2016 21:00:06 GMT+0000 (UTC) <=====
info: *** startup
info: Meteor.settings:
info:  DEV_BUILD=false, BUILD_DISPLAY_NAME=#4, JOB_NAME=**APP NAME**-production, GIT_COMMIT=a99d166f2eafb802cfad7d6565498cfd22143a79, ***_PORTAL_VERSION=0.8.5, ***_PORTAL_NAME=*** Admin Portal, ***_TRACKER_VERSION=0.8.5, ***_TRACKER_NAME=*** Tracker
info: 
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80
info:  =====> logger initiated at Wed Jan 27 2016 21:00:20 GMT+0000 (UTC) <=====
info: *** startup
info: Meteor.settings:
info:  DEV_BUILD=false, BUILD_DISPLAY_NAME=#4, JOB_NAME=**APP NAME**-production, GIT_COMMIT=a99d166f2eafb802cfad7d6565498cfd22143a79, ***_PORTAL_VERSION=0.8.5, ***_PORTAL_NAME=*** Admin Portal, ***_TRACKER_VERSION=0.8.5, ***_TRACKER_NAME=*** Tracker
info: 
```

**Comment by fschaeffler** [comment]
Quite embarrassing, but it was our own app all the time. Logs for it where kinda hidden, so we didn't see anything.
