### ISSUE TITLE
[mupx] Where's nodejs?

### ISSUE THREAD

**Issue by katopz** [arunoda/meteor-up-legacy#863]
Everything is up and running except one thing I can't figure out. Where's node install (also npm)?
When I try

``` shell
# node
The program 'node' can be found in the following packages:
 * node
 * nodejs-legacy
Try: apt-get install <selected package>
# whereis node
node:
# npm
The program 'npm' is currently not installed. You can install it by typing:
apt-get install npm
```

BTW, I saw it running in process but I can't find it anywhere.(weird!)
Do I have to install it separately (which make no sense to me)?

Thanks

**Comment by katopz** [comment]
nvm, I've fun answer my own question this should be it 

https://www.digitalocean.com/community/questions/ubuntu-repo-nodejs-require-symlink-to-node-to-use-forever

**Comment by katopz** [comment]
Hmm, I was wrong that's not the case. It seem like `nodejs` is inside `docker`?
So the question is how do I access it? or maybe I have to install separately? 
also `npm`, `nginx` and else?

Any hint is welcome.

**Comment by MasterJames** [comment]
Reading this will explain it's bundled into the deployment also provided is a tool to answer that question.
https://meteorhacks.com/how-meteor-uses-node.html
You can SSH into the target machine and with docker commands like docker exec gain access to a bash shell or send and valid command too.

**Comment by katopz** [comment]
@MasterJames  I've no luck with that

```
root@foo:~# mnode
/usr/bin/env: node: No such file or directory
```

BTW for `docker` hint, I finally found the way to get in.

```
root@foo:~#docker exec -it todos /bin/bash
root@foo-todos:/# node -v
```

Now I've to find the wayout to `root@foo~#` lol

Thanks!
