### ISSUE TITLE
mupx setup - "usermod: group 'docker' does not exist"

### ISSUE THREAD

**Issue by jowilhnson** [arunoda/meteor-up-legacy#864]
Deploying to a remote (dreamhost dedicated) server running Ubuntu 12.04

I've followed all documents and other guides to get things set up. My user has sudo access and the suders file has been edited for NOPASSWD:ALL, but it doesn't seem to be adding the docker group during the docker install or whenever it does that. 

I gave it a shot after manually adding the docker group. Setup completed successfully, but now deployment failes while "Invoking deployment process" with:

```
    config/start.sh: line 11: docker: command not found
    config/start.sh: line 14: docker: command not found
    config/start.sh: line 18: docker: command not found
    config/start.sh: line 34: docker: command not found
```

So even though it is saying Docker is installing successfully, maybe it isn't? Or is something else going wrong here?

**Comment by MasterJames** [comment]
Only Ubuntu 14 is supported. Try a newer version. Maybe vwrsion 15 is okay that I'm not sure about but it's probably 14+ required.

**Comment by jowilhnson** [comment]
Thanks for the pointer. Looking into it, it seems it could run on 12, but requires kernel version of at least 3.8. 

I wonder why setup reports Docker being installed successfully when it clearly isn't. 

Our server is pretty stable, so not sure I want to fiddle with things just for the sake of mupx, as it's not like I NEED my meteor app to be in a docker container. I already spent a bunch of time rewriting an internal app to work right in a docker container. Probably should have spent the time researching other deployment methods instead. Mup used to be a godsend, but with it not working with meteor 1.2, and mupx forcing drastic changes to any app that interacts with the filesystem, it's become a bit of a nightmare for me.

**Comment by MasterJames** [comment]
Maybe there's an easier way. I'm not sure possibly if you just setup manually by installing meteor and then use scp to transfer the files over top and relaunch meteor from ssh she'll too. ?  I've not tested that idea but it's likely still dependent on your situation. Then agsain I don't thinking running docker will be as big a problem as you think. It's basically the way of the future. Micro Services Micro Kernels etc. Still docker is a good start.

**Comment by jowilhnson** [comment]
I ended up bundling and deploying with passenger, and all in all it was a pretty quick and painless deployment. 

I can see the benefits of docker or similar container platforms, and will definitely be factoring that into my app design moving forward, as it could be the best solution for a lot of situations. I'll certainly be checking in on the continued progress and changes to mup/mupx. If it gets to a point of working more reliably, and being more flexible with the container configuration, it could be a great tool.

**Comment by MasterJames** [comment]
Excellent the new port that's not ready and under development currently is moving over to kadirahq
