### ISSUE TITLE
`mup setup` hangs on "Installing Node.js"

### ISSUE THREAD

**Issue by pixelsage** [arunoda/meteor-up-legacy#866]
**EDIT: The solution to this issue is to make sure I'm setting up to a Ubuntu 14 server. I was attempting to setup on an Ubuntu 12 server.**

Tried to `mup setup`. It just hangs here:

```
Started TaskList: Setup (linux)
[moglets.com] - Installing Node.js
```

Anyone have any clue why it might be hanging here? Here is my mup.json file:

```
{
  // Server authentication info
  "servers": [
    {
      "host": "moglets.com",
      "username": "**********",
      "password": "**********"
      // or pem file (ssh based authentication)
      //"pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server.
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "Moglets",

  // Location of app (local directory)
  "app": ".",

  // Configure environment
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://moglets.com"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 15
}

```

Other random data:
1. Using DreamHost.com VPS
2. `mup.json` is in root folder of project folder
3. Also tried `sudo mup setup` to no avail
4. I'm super new to Meteor

**Comment by MasterJames** [comment]
You'll need version 0.10.40 for nodejs with Meteor 1.2+.
Maybe networking issues otherwise.

**Comment by pixelsage** [comment]
Thanks for the tip! Does that mean I simply change the one line in mup.json to:
`"nodeVersion": "0.10.40",`
…or is it more complicated than that? If so, just tried that, and it's still hanging.

As far as networking issues, I am generally able to connect fine via SFTP and moglets.com is working.

**Comment by MasterJames** [comment]
You got it. I was afraid it might not be the only possible issue.
You should try the this trick to see extra logging info.

```
DEBUG=* mupx deploy 
```

It doesn't work everywhere. 
Anyway posting your current logs may reveal something more.
I thought maybe the installation was having trouble accessing the nodejs binaries over the network.

Wait a minute I always say this first.
If mup is not working for you please try the development branch mupx first.
I'm assuming you'be only tried mup with this problem.
If not or trying mupx doesn't help please do post your logs as suggested prior.

**Comment by pixelsage** [comment]
I've actually tried mup and mupx a few times. I just re-uninstalled mup and re-reinstalled mupx to debug as you suggested. After typing `DEBUG=* mupx deploy`:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /Users/Pixel/Dropbox/My Files/Verse Jogger/VerseJogger
Using buildOptions : {}

/Users/Pixel/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:278
                        throw(ex);
                              ^
Error: EACCES, unlink '/Users/Pixel/Dropbox/My Files/Verse Jogger/VerseJogger/.meteor/local/cordova-build/resources/android_hdpi.icon.png'
    at Object.Future.wait (/Users/Pixel/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:398:15)
    at Object.rm_recursive (/tools/fs/files.js:270:9)
    at CordovaBuilder.writeConfigXmlAndCopyResources (/tools/cordova/builder.js:260:13)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:158:13)
    at /tools/cli/commands.js:966:24
    at /tools/utils/buildmessage.js:356:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:349:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:347:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.enterJob (/tools/utils/buildmessage.js:321:26)
    at /tools/cli/commands.js:958:20
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.main.captureAndExit (/tools/cli/main.js:270:29)
    at /tools/cli/commands.js:957:10
    at buildCommand (/tools/cli/commands.js:1012:8)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:791:12)
    at /tools/cli/main.js:1378:23
    - - - - -

=> Build Error. Check the logs printed above.
```
1. I'm a Terminal newbie as well. Hopefully I didn't post any sensitive info above!
2. Also tried uninstalling Node.js and reinstalling v5.5.0 Stable from nodejs.org. Does this affect anything?
3. Running `DEBUG=* mupx setup` gets me stuck on `[moglets.com] - Installing Docker`
4. Yes, I am trying to deploy an app named differently than the domain name

**Comment by MasterJames** [comment]
I notice the word Cordova and that suggest you should remove the mobile platforms. 

```
meteor remove-platform ios android
```

Here's a link about that.
https://github.com/meteor/meteor/wiki/Meteor-Cordova-integration

There a platforms file in .meteor that should not contain mobile targets. The deployment should stomp over them and does in various PRs.

I'm also wanting you to make sure you'received deploying to an Ubuntu 14 as its the only supported platform.

Let me know if any of that helps and I'll add more things to try if not.

**Comment by pixelsage** [comment]
@MasterJames, thanks for all your help so far. I really appreciate it!

I've typed in `meteor remove-platform ios android`, it said I had no android platform, so I only removed the ios platform. Just to make sure, I typed in `meteor list-platforms` and got

```
browser                                       
server
```

Regarding Ubuntu servers, I checked with Dreamhost support and their website. My VPS is **Ubuntu 12.04 LTS**. I'm guessing this is my blocker?

Just in case, I ran `DEBUG=* mupx deploy` again. Got this

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /Users/Pixel/Dropbox/My Files/Verse Jogger/VerseJogger
Using buildOptions : {}

Started TaskList: Deploy app 'VerseJogger' (linux)
[moglets.com] - Uploading bundle
  nodemiral:sess:moglets.com copy file - src: /tmp/8ac18bd3-c80f-41ce-bc13-2913352d94c0/bundle.tar.gz, dest: /opt/VerseJogger/tmp/bundle.tar.gz, vars: undefined +0ms
[moglets.com] x Uploading bundle: FAILED
    No such file
```

`DEBUG=* mupx setup` still gets stuck on `Installing Docker`

**Comment by MasterJames** [comment]
One step at a time no promises, but that seems to be not too difficult to change for most? One problem I know of is that sometimes you might need a new GPU graphics card to handle it (so if that's the issue?). Digital Ocean, and others are $5 bucks, or more if you need I suppose? Anyway food for thought, to solve the next step. Ubuntu 14 and I gather up from their are the only ones supported, which means maybe there's a way but it's not easier then a free upgrade (maybe ask the clients provider or suggest a switch, [if the GPU tip don't pane out]).
mupx is different then mup and is docker-centric, which solves many problems like this. Primarily you're launching your server almost instantly as an automated build with caching (micro services and micro kernels even?). Much better, look into it. Still, "Yes, sadly you do need a more modern server".
Sounds like if you follow the script you might manually get it done somehow, but it really can't be worth it.

**Comment by pixelsage** [comment]
My brother's going to see if he can find a way to get the VPS updated to Ubuntu 14. If that works, then we'll know what the problem was. All else fails, I'll look into other hosting options. Thanks!

**Comment by pixelsage** [comment]
Looks like we won't be able to update the VPS to Ubuntu 14. We've successfully deployed with other servers, so we're going to proceed that way. Thanks again, @MasterJames!
