### ISSUE TITLE
Working on localhost

### ISSUE THREAD

**Issue by ghost** [arunoda/meteor-up-legacy#869]
edittext: Methinks its stackoverflow question, but i'll be thankfull if i can get my answers. [my questions](https://github.com/arunoda/meteor-up/issues/869#issuecomment-180072679)

Searched my issue, but they didn't help.
Sorry for my bad english.
Trying to do like here: http://antobase.com/blog/meteor-and-subdomains-with-nginx

What did i do, step by step:

Followed the instructions on the link http://antobase.com/blog/meteor-and-subdomains-with-nginx

Setted up nginx, created files. After 3rd step:

// Created meteor app
sea@bey: ~/Meteor$ meteor create my-meteor-application

// Changed directory structure
sea@bey: ~/Meteor/my-meteor-application $ rm my-meteor-application.*; mkdir app mup; cd mup; mkdir alpha production

// Mup init for alpha
sea@bey: ~/Meteor/my-meteor-application/mup/alpha $ mup init

// Mup init for production
sea@bey: ~/Meteor/my-meteor-application/mup/production $ mup init

// .. /mup/alpha/mup.json

```
{
    "servers": [{
        "host": "bey", // -> Tried localhost, sea, bey, 0.0.0.0, 127.0.0.1 and they didnt work.
        "username": "sea", // -> Tried root, sea and didnt work.
        "password": "xxx" // -> My password at everywhere
    }],
    "setupMongo": false, // -> I installed it before
    "setupNode": false, // -> I installed it before
    "nodeVersion": "0.10.36",
    "setupPhantom": true,
    "enableUploadProgressBar": true,
    "appName": "alpha_example",
    "app": "~/Meteor/my-meteor-application/mup/alpha",
    "env": {
        "ROOT_URL": "http://alpha.example.com",
        "PORT": 8001
    },
    "deployCheckWaitTime": 15
}
```

And mup setup command isnt working.
Error message is:

```
Started TaskList: Setup (linux)
[bey] - Installing PhantomJS
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.1.1:22
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

```

I tried localhost, 127.0.0.1, 0.0.0.0, sea, bey and didnt work every single time. My /etc/hosts file is like that:

```
127.0.0.1   localhost
127.0.1.1   bey
```

And my nginx sites-\* files are exactly same at the link  http://antobase.com/blog/meteor-and-subdomains-with-nginx

// And my nginx service is working at background

What could i do?

**Comment by MasterJames** [comment]
For Meteor 1.2+ set your nodejs version to 0.10.40 instead of 36 and try again.

**Comment by ghost** [comment]
@MasterJames Getting same error, `mup setup` command isnt working, still.

I'll start over and I'll let you know if it works.

**Comment by MasterJames** [comment]
Your target machine needs to be Ubuntu 14+.
I'M not sure what's running at 127.0.1.1 ?
Usually you would use the networks network and not the/an internal local host route.

**Comment by ghost** [comment]
My machine is eosFreya which is Ubuntu14.04
Nginx was on the 127.0.0.1 -> I stopped nginx then tried. Then started then tried. Still `mup setup` command isnt working.

Actually i can try this on a DigitalOcean server but i want to be sure about file structure.

I want these:
- Top domain and several subdomains. (*.example.com)
- One account to all of top and subdomains.
- A user surfing on a.example.com -> clicked login -> example.com/login -> authenticated; and the user authenticated for all subdomains (b.example.com, c.example.com).
- Besides, users have profil pages 'example.com/u/userid' and users following each other, messaging.. Subdomain activities storing on users' profile pages.

I'll do these:

```
$ meteor create appmeteor; cd appmeteor
$ mkdir example.com mup; cd mup
$ mkdir a.example.com b.example.com c.example.com
```

Then will it work like this?

I'm very pleased for your attention. I'm kinda newbie on meteorjs and i want to build my dream app.

**Comment by MasterJames** [comment]
Try the development branch version mupx (if you'ré not already) it's better and solves lots of problems by using docker compared to mup which doesn't and uses stud instead of nginx etc.
It's a bit tricky if you have problems if you'received not familiar with docker. Then now is a good time to learn. Time well spent.

**Comment by ghost** [comment]
Thanks for advice, i'll try it.
