### ISSUE TITLE
Error during install bcrypt

### ISSUE THREAD

**Issue by rootedsoftware** [arunoda/meteor-up-legacy#87]
```
Invoking deployment process: FAILED

        -----------------------------------STDERR-----------------------------------
        e-gyp/bin/node-gyp.js" "rebuild"
        gyp ERR! cwd /opt/give/tmp/bundle/programs/server/node_modules/bcrypt
        gyp ERR! node -v v0.10.28
        gyp ERR! node-gyp -v v0.13.0
        gyp ERR! not ok
        npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the bcrypt@0.7.8 install script.
        npm ERR! This is most likely a problem with the bcrypt package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node-gyp rebuild
        npm ERR! You can get their info via:
        npm ERR!     npm owner ls bcrypt
        npm ERR! There is likely additional logging output above.

        npm ERR! System Linux 3.13.0-24-generic
        npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "bcrypt"
        npm ERR! cwd /opt/give/tmp/bundle/programs/server
        npm ERR! node -v v0.10.28
        npm ERR! npm -v 1.4.9
        npm ERR! code ELIFECYCLE
        npm ERR!
        npm ERR! Additional logging details can be found in:
        npm ERR!     /opt/give/tmp/bundle/programs/server/npm-debug.log
        npm ERR! not ok code 0
        -----------------------------------STDOUT-----------------------------------

        > fibers@1.0.1 install /opt/give/tmp/bundle/programs/server/node_modules/fibers
        > node ./build.js

        `linux-x64-v8-3.14` exists; testing
        Binary is fine; exiting
        fibers@1.0.1 node_modules/fibers

        > bcrypt@0.7.8 install /opt/give/tmp/bundle/programs/server/node_modules/bcrypt
        > node-gyp rebuild

        ----------------------------------------------------------------------------
```

**Comment by rootedsoftware** [comment]
I also ran a mup logs -n 300 and got this response.

```
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
error:   Cannot start forever
error:   script /opt/give/app/main.js does not exist.
```

**Comment by arunoda** [comment]
something like npm issue. send some log at here:
/opt/give/tmp/bundle/programs/server/npm-debug.log

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by jamesgibson14** [comment]
I don't know if this helps, but I had a similar problem as I was upgrading my app to Meteor 0.8.2, I finally found out that in my mup.json file I had node set to v0.10.26 and it needs to be v.0.10.28. Then I ran `mup setup` and after that `mup deploy` worked fine.

**Comment by hartwoolery** [comment]
I also noticed that issue when g++ was missing...

**Comment by rootedsoftware** [comment]
@hartwoolery I do have g++ installed, I checked the https://github.com/TooTallNate/node-gyp node-gyp requirements and made sure I had everything it needed. 

@jamesgibson14 My node version is set to 0.10.28. 

@arunoda it seems to be getting farther now since manually installing node using `sudo npm install n -g` `sudo n stable`. It still won't actually start, here is what I get when I run `mup logs -f` after I run the `mup deploy`

[trashmountainproject.org] Error: listen EADDRINUSE[trashmountainproject.org] 
[trashmountainproject.org]     at errnoException (net.js:904:11)[trashmountainproject.org] 
[trashmountainproject.org]     at Server._listen2 (net.js:1042:14)[trashmountainproject.org] 
[trashmountainproject.org]     at listen (net.js:1064:10)[trashmountainproject.org] 
[trashmountainproject.org]     at net.js:1146:9[trashmountainproject.org] 
[trashmountainproject.org]     at dns.js:72:18[trashmountainproject.org] 
[trashmountainproject.org]     at process._tickCallback (node.js:419:13)[trashmountainproject.org] 
[trashmountainproject.org] error: Forever detected script exited with code: 8[trashmountainproject.org] 
[trashmountainproject.org] error: Script restart attempt #12[trashmountainproject.org] 
[trashmountainproject.org] Kadira: completed instrumenting the app
[trashmountainproject.org] 
[trashmountainproject.org] events.js:72[trashmountainproject.org] 
[trashmountainproject.org]         throw er; // Unhandled 'error' event[trashmountainproject.org] 
[trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]  [trashmountainproject.org]   ^[trashmountainproject.org] 
[trashmountainproject.org] Error: listen EADDRINUSE[trashmountainproject.org] 
[trashmountainproject.org]     at errnoException (net.js:904:11)[trashmountainproject.org] 
[trashmountainproject.org]     at Server._listen2 (net.js:1042:14)[trashmountainproject.org] 
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
[trashmountainproject.org] error: Forever detected script exited with code: 8[trashmountainproject.org] 
[trashmountainproject.org] error: Script restart attempt #13[trashmountainproject.org] 
^Croot@trashmountainproject:~/mup/projects/give# tar -zxvf {/opt/give/tmp/bundle.tar.gz}  
tar (child): {/opt/give/tmp/bundle.tar.gz}: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by rootedsoftware** [comment]
I restored my server to an earlier state, reinstalled mup and set the install nodejs to false. I also installed node v0.10.29 using `sudo npm install n -g` `sudo n stable` and ran through `mup init`, `mup setup`, `mup deploy` works this time.
