### ISSUE TITLE
Support for pm2

### ISSUE THREAD

**Issue by yasinuslu** [arunoda/meteor-up-legacy#88]
I'm not sure if pm2 is better than forever but i see that it has better logging and some other features.

I think it deserves an investigation :)

EDIT: forgot to add a link

https://github.com/unitech/pm2

**Comment by arunoda** [comment]
Actually, we are using forever only to spawn the app after crashes. We can
use it with builtin upstart. But forever does it better.
Ubuntu upstart manages logs and log rotating.

I don't find how PM2 can help for our use case. If you can point out some
I'd happy to do it.

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by Kikobeats** [comment]
about this, I think that pm2 can be useful, for example, as load balancer and use all cpus availables:

`pm2 start app.js -i max  # Enable load-balancer and cluster features`

by default `pm2` restart the application too, but is more powerful, for example for things like this:

![](https://github.com/unitech/pm2/raw/master/pres/pm2-monit.png)

or web panel! https://www.npmjs.com/package/pm2-web

**Comment by Kikobeats** [comment]
another advantage:

`--max-memory-restart <memory>        specify max memory amount used to autorestart (in megaoctets)`

PM2 have too many configurables option. Maybe an easy way to implement is detecting that `pm2` object exist in `settings.json` and put here the configuration for lift the process.

**Comment by simakwm** [comment]
+1

**Comment by arunoda** [comment]
Sorry we are not going to support PM2. There is no reason to use PM2.
We will soon support docker as a runtime.
