### ISSUE TITLE
mupx: Use of two ssl certificates in one server

### ISSUE THREAD

**Issue by YosBD** [arunoda/meteor-up-legacy#890]
Hey,

We are routing two domains to the same meteor server, both domains have ssl.

Only the first certificate is in use, any idea why?

The mup.json file contains:
"ssl": {
    "certificate" : "bundle.crt",
    "key"         : "private.key",
    "pem"         : "staging.pem",
    "backendPort" : 80
  },

The "bundle.crt" contains:
-----BEGIN CERTIFICATE-----
<the first ssl certificate>
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
<the second ssl certificate>
-----END CERTIFICATE-----

Thanks,
Yossi

**Comment by MasterJames** [comment]
Don't you need two separate mupx settings files to do that? 
Oh wait you should first try to do this with the development branch called mupx if you've only tried mup (mupx is different as it is docker centric) but actually there is a port of it over at kadirahq and these are soon depreciated. At kadirahq they will be able to help with this kind of problem better. I think you need to run nginx to route to meteor apps running on separate ports. Also the meteor 1.3 will be adding SSL support with a node update and so it can be tried today too.

**Comment by YosBD** [comment]
Thanks @MasterJames.
More info that might make it clear:
I'm using mupx.
We are building a web app which will be directed from our clients DNS.
Meaning: "xyz.a.com" and "xyz.b.com" will both be directed to the same meteor app.
Therefore, we have to handle two different ssl certificates in one meteor app.
Our service is hosted on AWS. We Tried to:
1.Handle the SSL certificates in AWS ELB (load balancer)
2.ELB -> meteor app communication in http.
3.The only issue is that the user has to type "https://xyz.a.com" (using the force-ssl will cause an infinite routing loop)

Any suggestions?

**Comment by MasterJames** [comment]
I think you might be about to route ELB to two different ports with nginx forwarding back to meteor then you don't have to use force-ssl. 
But mupx won't do two nginx so you need to sort out the details maybe two mup.settings?
I thought maybe they were working on this in the new version a kadirahq? Anyway you'll get better help from them there about it.
Remember ddp can be eavesdropped on so login etc must use ssl.
Another thought is if you use Let'sEncrypt you might be able to build a more comprehensive certificate that accepts all your domains. Watch out for the limit by testing first.
