### ISSUE TITLE
Maintain database and filesystem data after deploy

### ISSUE THREAD

**Issue by g41n** [arunoda/meteor-up-legacy#891]
Hello guys,
mupx is great but my application manage files uploaded by users and after a deploy I've found my target directory empty on the docker container of the app.
How can I manage that?

And what about mongo docker container? May I find it empty too?

Thanks in advance for the support.

**Comment by MasterJames** [comment]
Basically one SSHs on to the deployment target.
Once there they can use 'docker exec' command to connect to a bash shell (or mongo etc) and then you can proceed from there.
Checking if mongo is running or restart looping because of a file lock etc.? If the http is running via curl (suggesting firewall problems) ? 

Maybe you have more questions or have found something to report with that??

Your problem sounds like permissions problem.

Next you have to step through the code checking each step manually in a sense. Does the file copy? or is it a permissions problem, etc.?

Mo Better logs can be obtained via DEBUG=\* mupx deploy. That could reveal extra error information like a file transfer problem, potentially.

Note: This version will be depreciated soon, because there is a port to kadirahq underway 
https://github.com/kadirahq/meteor-up
but it's still officially experimental, I believe it's ready for testing (soon?). If your into that sort of thing?

**Comment by g41n** [comment]
Sorry, I was not so clear. I've developed an app on my workstation and I need to install it on a custom server, so I found mupx. After the first deploy all works like a charm, files uploaded by users were in ~/uploads and to see them I have to SSH on my target machine and use docker exec as you said.

In the meantime the development of the app goes ahead and I've implemented new features on my workstation. I need to update on my custom server, so I've launched "mupx deploy" again (Is this the right way to update my server?). Sadly I've seen that, while the mongodb container seems untouched, the container of the app seems to be rebuilt entirely and my ~/uploads is now empty (files uploaded by users are lost).

How can I manage a situation like this? I think I have to store upload files on a "persistent" location and not on the app container. I've read something on how to mount a host directory on the app container, but I'm a noob with docker. Another solution could be use a dedicated container, but I don't know if worth it.

My concern is to set it up with mupx in order to deploy updates quickly without save, deploy and revert files (that's what I'm doing now).

Any hint would be appreciated.
Thanks in advance.

**Comment by MasterJames** [comment]
You would basically need a -volume entry in the correct 'docker run' command to mount the folder on the docker container. The Mongo one does a similar thing.

https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh

This file shows at the bottom for the front end where that would go.
I have not checked if the new port has added a feature in the settings to handle this but it should so try that one and ask them how-to or for a feature request. Otherwise you can manually hack the install folder of mupx or do a full PR fork but again it's the new version you want to look at either way.

It would be great if you could cross link to this issue and report back here your findings thanks.

**Comment by chip** [comment]
I'm interested in this as well, as I have my files currently being uploaded to `current/cfs/files`. I'm not experienced with docker and am unsure how to map a directory I create on the server to the `cfs` directory that is being written to by CollectionFS. Any pointers would be very much appreciated, though.

**Comment by MasterJames** [comment]
Docker users a --volume flag to 'mount' aka map a filesystem folder on the Docker image from the system it's being run on which can be already mounted from anywhere. I've not seen  CollectionFS but it looks useful. When the new feature of hooks lands in the kadirahq port of mupx you will find it easier to do such things in deployment phase directly from your development machine.

**Comment by g41n** [comment]
Where I can find news about the new feature of hooks?
I've tried to implement something on my own but without success...
Here the diff, can anyone help me with this?

```
diff --git a/lib/taskLists/linux.js b/lib/taskLists/linux.js
index 2bbbe0d..91c4dee 100644
--- a/lib/taskLists/linux.js
+++ b/lib/taskLists/linux.js
@@ -67,6 +67,12 @@ exports.deploy = function(bundlePath, env, config) {

   copyEnvVars(taskList, env, appName);

+  if (config.volumes.length) {
+    config.volumes = "-v " + config.volumes.join(" -v ");
+  } else {
+    config.volumes = "";
+  }
+
   taskList.copy('Initializing start script', {
     src: path.resolve(TEMPLATES_DIR, 'start.sh'),
     dest: '/opt/' + appName + '/config/start.sh',
@@ -74,7 +80,8 @@ exports.deploy = function(bundlePath, env, config) {
       appName: appName,
       useLocalMongo: config.setupMongo,
       port: env.PORT,
-      sslConfig: config.ssl
+      sslConfig: config.ssl,
+      volumes: config.volumes
     }
   });

@@ -189,4 +196,4 @@ function deployAndVerify(taskList, appName, port, deployCheckWaitTime) {
       port: port
     }
   });
-}
\ No newline at end of file
+}
diff --git a/templates/linux/start.sh b/templates/linux/start.sh
index b41556c..8528481 100644
--- a/templates/linux/start.sh
+++ b/templates/linux/start.sh
@@ -6,6 +6,7 @@ BUNDLE_PATH=$APP_PATH/current
 ENV_FILE=$APP_PATH/config/env.list
 PORT=<%= port %>
 USE_LOCAL_MONGO=<%= useLocalMongo? "1" : "0" %>
+VOLUMES=<%= volumes %>

 # Remove previous version of the app, if exists
 docker rm -f $APPNAME
@@ -23,6 +24,7 @@ if [ "$USE_LOCAL_MONGO" == "1" ]; then
     -d \
     --restart=always \
     --publish=$PORT:80 \
+    $VOLUMES \
     --volume=$BUNDLE_PATH:/bundle \
     --env-file=$ENV_FILE \
     --link=mongodb:mongodb \
@@ -35,6 +37,7 @@ else
     -d \
     --restart=always \
     --publish=$PORT:80 \
+    $VOLUMES \
     --volume=$BUNDLE_PATH:/bundle \
     --link=mongodb:mongodb \
     --hostname="$HOSTNAME-$APPNAME" \
@@ -57,4 +60,4 @@ fi
     --publish=<%= sslConfig.port %>:443 \
     --name=$APPNAME-frontend \
     meteorhacks/mup-frontend-server /start.sh
-<% } %>
\ No newline at end of file
+<% } %>
```

[volumes.diff.zip](https://github.com/arunoda/meteor-up/files/225740/volumes.diff.zip)

**Comment by chip** [comment]
As an update, I solved my issue using `cfs:gridfs`: https://atmospherejs.com/cfs/gridfs.

**Comment by g41n** [comment]
Thanks for the update but I'm not quite sure about gridfs because I can't see files and add something manually seems not so friendly. Than I'm scared about the db dimension, db is not the primary choiche to store files, imho... Moreover I've something that is already running, so I have to migrate in such a manner...

Anyway, I'll read something about to understand deeply if gridfs may suit my needs :D

**Comment by joncursi** [comment]
@chip I'm using `cfs:gridfs` as well, but running into `Error: Bad Gateway` issues on the server when trying to upload files in the Meteor app. I am deploying via mupx, which puts the app inside a docker container, which I'm thinking is causing some sort of communication/permissions problem on the server. How did you resolve this? Seems like something needs configuration, but I can't tell what. Thanks!

**Comment by joncursi** [comment]
@chip @MasterJames here is the error output:

<img width="761" alt="screen shot 2016-04-29 at 7 42 06 pm" src="https://cloud.githubusercontent.com/assets/4974609/14932346/aa3d01c0-0e42-11e6-8341-62ba5bdd840e.png">

Any ideas on why this file upload works in local development, but fails when deploying via mupx to a linux box?

**Comment by chip** [comment]
Hey @joncursi - I don't remember running into any Bad Gateway errors, but it has always been a common problem when working with nginx. Here are some suggestions on troubleshooting: https://www.keycdn.com/support/502-bad-gateway/. Try tailing the logs for clues if the DNS resolves properly. Let me know if any of these help you or not.

**Comment by joncursi** [comment]
Thanks @chip - I just managed to solve the issue by upgrading `cfs:gridfs` to the latest version: 0.0.33. The issue was with the MongoDB drivers, as my server is running Mongo 3.2.x.

**Comment by g41n** [comment]
I've upgraded to `cfs:gridfs` too, even if is deprecated, and also switched to [kadirahq/meteor-up](https://github.com/kadirahq/meteor-up) that is more updated even if not so stable yet.

There's still no way to add custom docker options in mupx config, but in the new version something seems moving on...
[kadirahq/meteor-up #160](https://github.com/kadirahq/meteor-up/issues/160)
[kadirahq/meteor-up #157](https://github.com/kadirahq/meteor-up/issues/157)
