### ISSUE TITLE
Unexpected error when trying deploy an app

### ISSUE THREAD

**Issue by teintinu** [arunoda/meteor-up-legacy#899]
mup deploy
## Meteor Up: Production Quality Meteor Deployments

Building Started: /home/hoda51/zscan/meteor
buffer.js:50
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:50:13)
    at Readable.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:86:20)
    at Readable.emit (events.js:180:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:406:13)
    at process._tickCallback (node.js:430:11)

**Comment by teintinu** [comment]
Sure! I was using with Node 6!  With v5.6 works well.
Thanks

**Comment by ThomsCass** [comment]
you made my day !

**Comment by sjmcdowall** [comment]
Yep that was it of rme too -- will mup get updated to handle V6 node??

**Comment by MasterJames** [comment]
I think it's a meteor error so deployment with mups unrelated.
Otherwise there's only the port at kadirahq for forward moving updates.

**Comment by yAnn1ck-B** [comment]
i have the same error but I don't know how to change the node version. Is this something I need to do in meteor or do i have to manually install node on the server?

I was using "mup setup" command to install it to a windows azure virtual machine running ubuntu

**Comment by sjmcdowall** [comment]
@yAnn1ck-B -- from the command line do a "node --version" to see which version you are on.  It's the version from the command line that is important here.  If it is not the right version I would suggest you use "nvm" (node version manager) by "npm -g install nvm"  and then follow the "nvm" --help options to install and select the node version you need on your development machine (i.e. the machine you are doing mup commands on)

**Comment by yAnn1ck-B** [comment]
Ok I'm still not there, but at least this is helping. Install command didn't work, i used the nvm windows installer instead. I also had to manually install to c: cuz it tries to install it in users and my name has a space which is unrecognized. this also requires the settings file to be moved and updated with the newly installed path. Modified the node version, then tried to deploy again and hurray! it worked! But now i get a new error, see the following post:

https://github.com/arunoda/meteor-up/issues/1039
