### ISSUE TITLE
Wrong node-fibers binary being called

### ISSUE THREAD

**Issue by Brianchat** [arunoda/meteor-up-legacy#900]
Deploying to Debian Wheezy box from Windows 10. 
Fails on verification.
Log shows:
`/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
        throw new Error('`'+ modPath+ '.node`is missing. Try reinstalling`node-fibe
              ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?`

Checking the npm fibers on the server:
` npm install fibers

> fibers@1.0.10 install /root/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-4.6` exists; testing
Binary is fine; exiting
/root
└── fibers@1.0.10
` 

Any ideas on how to make it use the v8-4.6 binary or install the v8-3.14 binary?

**Comment by MasterJames** [comment]
Only Ubuntu 14+ is supported.
Also note this version of nupx is depreciating to the new port over at kadirahq so besides maybe in some situations trying that might help it's the only version you'll likely get support for or that will accept PRs and suggestions with thanks in the near future.

**Comment by Brianchat** [comment]
Many thanks
