### ISSUE TITLE
Cannot deploy after switching from mup to mupx on Digital Ocean droplet

### ISSUE THREAD

**Issue by chrisco23** [arunoda/meteor-up-legacy#901]
I've been running an app at alpha stage on a Digital Ocean droplet for a long time, and deploying with mup.  I hadn't worked on it in some time and I read that mup is no longer maintained, so I tried to use mupx.

On this server I run several small sites, with nginx.  I had been using the nginx proxy method for my meteor app with mup to deploy.

I really do not want to purchase and maintain a whole new droplet just for this app.

Do I understand correctly that mupx is trying to install its own nginx in a docker container?  I'm new to docker.

I googled and found some similar problems but no solutions.  A lot of threads I read were discussing SSL, which I'm not even attempting for this app (yet).

In mup.json (with mup) I had port set to 3000.  with the mupx and the new mup.json, I tried both port 80 (as in the default file).  I'm trying 3000 now and I get this:

 -----------------------------------STDERR-----------------------------------
        Failed to remove container (myappname-frontend): Error response from daemon: No such container: myappname-frontend
        docker: Error response from daemon: failed to create endpoint myappname on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use.
        -----------------------------------STDOUT-----------------------------------
        m-staging-etfinvest-com
        base: Pulling from meteorhacks/meteord
        518dc1482465: Already exists
        a3ed95caeb02: Already exists
        a3ed95caeb02: Already exists
        a3ed95caeb02: Already exists
        537c534356b6: Already exists
        b65a0e1e554b: Already exists
        a3ed95caeb02: Already exists
        a3ed95caeb02: Already exists
        Digest: sha256:b5a4f6efa98e4070792ed36d33b14385a28e6ceda691a492ee5b9f2431b1515a
        Status: Image is up to date for meteorhacks/meteord:base
        3496c08ad6a7d90d480857882bd7f230643da4292133a901152641a063022172
        ----------------------------------------------------------------------------

**Comment by MasterJames** [comment]
Ya  it's pretty comprehensive so anything already running could cause conflicts.
Sounds like maybe that's what's happened there.
There is a migration guide (see bottom of mupx readme) to mupx from mup try following that with a fresh Ubuntu 14+ get a basic proof of function and then try adjusting to your existing proxy etc.
Some still have a need for mup but it's worth rebuilding things with a container way of thinking lIke mupx does.
Also note there's a new version of mupx being ported over to kadirahq so if you want support that's the route/version as that one will eventually depreciate mupx here.

**Comment by chrisco23** [comment]
Thanks for your response.  I may end up trying a fresh ubuntu droplet as a test case.  But actually I was posting in a rush yesterday and I really did mean to post on the mupx repo and not here, so maybe I'll give that a try first.

**Comment by chrisco23** [comment]
I just got things working, _I think_.  Verifying deployment is still FAILED, but the site is there.  

I believe these were all the things that were required (maybe not all):
1.  Blow away the old app deployed with mup
2.  Kill the upstart / node listening on port 3000
3.  rm -rf all /fibers everywhere I could find (hit the node-fibers is missing stuff)
4. mupx setup && mupx deploy

I won't close yet as the verification failure still seems to be a problem to me.  Here is what the last deployment gives:

x Verifying deployment: FAILED

```
    -----------------------------------STDERR-----------------------------------
    inished
      COPY Release/fibers.node
    make: Leaving directory `/bundle/bundle/programs/server/node_modules/fibers/build'
    Installed in `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
    ansi-regex@0.2.1 node_modules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    escape-string-regexp@1.0.4 node_modules/escape-string-regexp

    chalk@0.5.1 node_modules/chalk

    strip-ansi@0.3.0 node_modules/strip-ansi

    supports-color@0.2.0 node_modules/supports-color

    has-ansi@0.1.0 node_modules/has-ansi

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    underscore@1.5.2 node_modules/underscore

    meteor-promise@0.5.1 node_modules/meteor-promise

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.8 node_modules/fibers
    => Starting meteor app on port:80
```

**Comment by chip** [comment]
I followed the guide and ran into some issues, but suggestion by @chrisco23 to blow away the old app helped me get to this point (many thanks!). My staging instance is at least back up and running, but I'd like to see this error be resolved, so I'll continue to follow this.

**Comment by chip** [comment]
As an update, I was able to get it to Verify deployment successfully by updating **mup.json** with `"deployCheckWaitTime": 30`. Hope that helps.
