### ISSUE TITLE
Verifying deployment always failing with mupx with meteor 1.3 & DigitalOcean

### ISSUE THREAD

**Issue by ayhid** [arunoda/meteor-up-legacy#905]
I have constantly an error when trying to deploy an app with meteor 1.3-beta.12 on a Digital Ocean  Ubuntu 14.04.4 x64 droplet.

here is the log:

`[server-ip] - Initializing start script: SUCCESS
[server-ip] - Invoking deployment process
[server-ip] - Invoking deployment process: SUCCESS
[server-ip] - Verifying deployment
[server-ip] x Verifying deployment: FAILED

```
-----------------------------------STDERR-----------------------------------
modules/underscore

meteor-promise@0.5.1 node_modules/meteor-promise

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.8 node_modules/fibers
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:267
                        throw(ex);
                              ^
TypeError: Cannot call method 'setupGlobals' of undefined
    at __coffeescriptShare (packages/practicalmeteor_mocha/meteor/src/server/mocha.coffee:9:39)
    at packages/practicalmeteor_mocha/meteor/src/server/mocha.coffee:1:1
    at packages/practicalmeteor_mocha/meteor/src/lib/MochaRunner.coffee:1:1
    at /bundle/bundle/programs/server/boot.js:245:10
    at Array.forEach (native)
    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:140:5

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------`
```

**Comment by MasterJames** [comment]
I think for Meteor 1.3 the only best way forward will be with the new port of the dev branch mupx over at kadirahq. My guess is it won't be properly supported until the official release.
There are some other related posts. I'm not using it personally yet ;-(
https://github.com/arunoda/meteor-up/issues/841

**Comment by ayhid** [comment]
@MasterJames thank you for the quick reply, so do I have to stick with Meteor 1.2 if I want to deploy with mup/mupx ?

**Comment by MasterJames** [comment]
I'm not 100% on that. I think so., but try that newer version at kadirahq and ask there about it?

**Comment by thomasmery** [comment]
Hi there,

it would be great if mupx could handle deploying 1.3 beta xx until the new version is ready

for me it started breaking @ beta 12

any chance we can get help from kadira here ?

p.s. I could not get the 'being refactored' version to work 

thanks !

**Comment by thomasmery** [comment]
update:

I could actually deploy with beta 16 and current version of mupx

extended `deployCheckWaitTime` to 60 seconds (in `mup.json`)

have to admit I don't know if I had to take other steps since I kind of lost track of everything I tried

hope this helps

**Comment by patrickml** [comment]
@thomasmery i can verify updating to -16 fixed the issue.

**Comment by walleXD** [comment]
Verification still does not work for me, even on meteor 1.3 release. Also, are you guys having issue with 1.3 redeployment? [My meteor app fails to run on redeployment](https://github.com/arunoda/meteor-up/issues/929). Are these similar issue? #929

**Comment by ayhid** [comment]
@walleXD have your tried @thomasmery solution? worked well for me
