### ISSUE TITLE
dotenv doesn't work together with mupx ?

### ISSUE THREAD

**Issue by hems** [arunoda/meteor-up-legacy#911]
My project does use "dotenv" and used to load a .env file from my root directory.

once deployed using `mupx deploy` i found out the variables weren't being loaded and that the only ENV variables were the ones set on mup.json

**Comment by elie222** [comment]
From the README:

```
This version is no longer maintaining.
Mupx is the stable version. 
New development is moved to here: https://github.com/kadirahq/meteor-up.
```

Might be better to ask there.

**Comment by MasterJames** [comment]
The new version at kadirahq will have hooks where maybe you can integrate that dotenv somehow. Alternatively maybe there's a way to not use dotenv?

**Comment by hems** [comment]
moved issue to: https://github.com/kadirahq/meteor-up/issues/96
