### ISSUE TITLE
Deployment meteor 1.3-beta.16+ fails

### ISSUE THREAD

**Issue by pors** [arunoda/meteor-up-legacy#915]
I have my [app](https://app.pors.net/) running fine with meteor 1.3-beta.12 and node v0.10.41.

Since then I have tried 1.3-beta.16, 1.3-rc.1 and 1.3-rc.3 with node v0.10.43 (and earlier with v0.10.41), and all attempts (mup setup && mup deploy) result in the following error:

`Error: /opt/reactionic_kitchensink/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/opt/reactionic_kitchensink/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/opt/reactionic_kitchensink/app/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
error: Forever detected script exited with code: 8
error: Script restart attempt #6`

I'm not sure it is Meteor 1.3 related, but nothing much else has changed.

I also updated to the last version of mup: `npm install -g mup` => `mup@0.11.3`

**Comment by MasterJames** [comment]
There has been some varied reports of success posted here but I think this has a better chance of resolution with the mupx port at kadirahq.

**Comment by pors** [comment]
@MasterJames there is no mupx at kadirahq as far as I can see? https://github.com/kadirahq/meteor-up/branches

Is there anyone from Kadira who can comment on this? @arunoda?

**Comment by pors** [comment]
Tried again, now with mupx, resulting error is different now:

```
Using buildOptions : {}
Errors prevented bundling:
While linking the program:
error: this app is not compatible with architecture 'os.linux.x86_64'


=> Build Error. Check the logs printed above.`
```

**Comment by tmeasday** [comment]
I think the solution to this issue is ensuring you `meteor build --architecture <YOUR-SERVER_ARCH>`.

**Comment by MasterJames** [comment]
The new version is there.
https://github.com/kadirahq/meteor-up
I know it's confusion because mupx was an experimental version that could be used in tandem so when they ported it back fresh it's called mup and not mupx but it is docker centric like mupx.

**Comment by MasterJames** [comment]
This says node 0.10.43 is needed, but that's with the kadirahq version mupx is hard coded i think mainly because only the mup version readme shows the node version option.
Let us know if you can get it to work in either of the version here but again you probably should just try moving forward with the newer version at kadirahq.

https://github.com/kadirahq/meteor-up/issues/80

My personal opinion is to see an official release of 1.3 and then wait to see how the new mup adjusts. For instance I'm wondering if the included node update needs nginx anymore etc.

**Comment by pors** [comment]
@tmeasday I decided to deploy from a linux virtual box. That worked :)

**Comment by MasterJames** [comment]
Yes Ubuntu 14+ is the only officially supported platform.

**Comment by varunwyest** [comment]
Is there a way to specify the build options on mup? I am getting the bcrypt_lib.node: invalid ELF header
with 1.3.

**Comment by MasterJames** [comment]
Hi it would be great if you tried the new port over at kadirahq and cross link back if still having problem reported there. Thanks.

**Comment by pors** [comment]
@MasterJames are you saying that this issue is solved here: https://github.com/kadirahq/meteor-up?

Did you try it, or just assume it?

**Comment by piyushcoader** [comment]
same issue here updated
 node version to 0.10.43 and not deploying with mup...

**Comment by MasterJames** [comment]
I've not tried it just something to try. 
Obviously the hammer has finally dropped on 1.3 the way forward is with kadirahq. Any issues requiring changes to mupx/mup won't be resolved here as its depreciated by the new version.
All the 1.3 issues should settle out soon.
I'd say try 1.3 with the basic default demo and see if it deploys with mupx/mup and then drop your code into the new one, or maybe try remove all packages and reinstall them. The assumption is based more on observations and the logic of seeing when most people can switch to the new version now or not. Reporting problems here that need code fixes will unfortunately fall on essentially "deaf ears", but at kadirahq they are probably scrambling to help people by working on the needs of 1.3.
I think if you just start clean and drop you code and packages in a fresh 1.3 and use kadirahq mup version it should work.
It would be great if you could let us know how it goes for your situation. Thanks and good luck.

**Comment by MasterJames** [comment]
Doesn't 1.3 use a newer node internally finally 4. ?(maybe?) so it has encryption for SSL aka TLS ? Transport Layer Security and so no need for nginx as much etc. Very transformative.
Mupx is the dev branch and uses docker so the node version is obsolete in Mupx as the container has a pre built setup. The kadirahq port is a version of Mupx with the old name mup again so a bit confusing at first.
