### ISSUE TITLE
Mupx and small SSD

### ISSUE THREAD

**Issue by JWo1F** [arunoda/meteor-up-legacy#918]
Hi all! I have two physical disks: hard & ssd. I want to move current version of my project to the ssd and latest builds to the hard (because I have too small SSD disk). It's possible?

And, should I use kadira:mup or still arunoda:mupx?

Thanks.

**Comment by MasterJames** [comment]
I'm not sure in the new version if there's a solution for this so I'm partial to asking as well at kadirahq port as it might become a feature request better as well.
I would say you could SSH into the target machine and change a mount point between deploys there as well. I'll find something on desktop and post that too.

**Comment by MasterJames** [comment]
This is the file to look at I believe.
https://github.com/arunoda/meteor-up/blob/mupx/templates/linux/start.sh
The app path is /op/$APPNAME
But it's ENV_FILE=$APP_PATH/config/env.list
That might let you set override those as well  [I'm not certain about that.] as other means other then editing the files.
Anyway I'd say you make a mount point to /op/OtherDriveAppName etc.

Really you could make a bridge locally to whatever like, like this with SSHFS 
https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh
And just over right directly to the server.

**Comment by JWo1F** [comment]
@MasterJames can I use `mount -o bind` for it?

**Comment by MasterJames** [comment]
Yes it should be possible to use the --bind flag of the mount command to remount subfolders. Obviously avoid read-only options.
