### ISSUE TITLE
[mupx] Deploy fails on machines with SELinux

### ISSUE THREAD

**Issue by j6k4m8** [arunoda/meteor-up-legacy#922]
It seems like some issue with Docker not being installed or accessible. Is this something worth elaborating on, or is it out-of-scope for this repo?

**Comment by MasterJames** [comment]
Ubuntu 14+ is the only target supported.

**Comment by j6k4m8** [comment]
Does this exclude 14.04 running SELinux? (SE is a kernel security module)

On Thu, Mar 24, 2016 at 12:57 AM Master James notifications@github.com wrote:
Ubuntu 14+ is the only target supported.

**Comment by MasterJames** [comment]
Ya  I don't know about that.
Maybe try installing docker on it manually yourself and see how that goes first.

**Comment by j6k4m8** [comment]
Closing — installing Docker manually only leads to errors down the road using this code, but this is old enough that I don't think anyone cares anymore! :)
