### ISSUE TITLE
Setup Error Installing Docker

### ISSUE THREAD

**Issue by shwaydogg** [arunoda/meteor-up-legacy#923]
I'm not sure how to proceed investigating the following error.  (Ubuntu server on microsoft azure in case triggers any thoughts.)

```
mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json


Started TaskList: Setup (linux)
[skylight.cloudapp.net] - Installing Docker
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:22
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
```

**Comment by MasterJames** [comment]
Some connection problems. You can rest port access by SSHing into the target platform run a simple webserver and try accessing it and other ways to check for connecting problems.
At Amazon they call it "ingress" but anyway you need to check for a firewall or port access through their provided interfaces. 
Well at least that's the first thing to check.
Note: the new version porting over to kadirahq is the path forward.
Also you can use docket exec bash to gain access into the docker containers. Docker has volume mounts and other port mapping features etc.

**Comment by shwaydogg** [comment]
I was originally falsely assuming the connection was working because it the output first read: "Started TaskList: Setup (linux) [skylight.cloudapp.net] - Installing Docker" and that the connection error was with the docker container ... but that was a false assumption.  There was a now fixed ssh connection issue.
