### ISSUE TITLE
mupx deploys successfully but when accessing site displays "This site can’t be reached"

### ISSUE THREAD

**Issue by chackerian** [arunoda/meteor-up-legacy#924]
I recently created a new amazon instance and deployed with mupx which was successful. When I navigate to the root url however no content is shown and the page never loads. Eventually it display 

> This site can’t be reached

I have Kadira setup with it and kadira shows that it is up and running.

Also mupx logs show:

```
[52.38.62.167] => Starting meteor app on port:80
[52.38.62.167] Kadira: completed instrumenting the app
[52.38.62.167] Kadira: Successfully connected
```

.

**Comment by MasterJames** [comment]
Maybe the ports blocked. There should be some panel in their interface for ingress I think they call it.
If you SSH into the target and use curl to test its working, but it doesn't work from outside it's the port being blocked.

**Comment by chackerian** [comment]
I'm kind of confused about how to test with curl. Should I curl localhost or something to see if there is any code that is returned?

**Comment by chackerian** [comment]
Yeah that was it. I had to modify my inbound Security Group settings. Thanks for the quick response
