### ISSUE TITLE
Mupx can't deploy correctly after upgrading to Meteor 1.3

### ISSUE THREAD

**Issue by ChenLi0830** [arunoda/meteor-up-legacy#932]
My app can deploy successfully when I was using Meteor 1.3@beta.12. Since I upgrade to Meteor 1.3, I start to get the following error when trying to deploy on both of my servers. 

```
Using buildOptions : {}
Errors prevented bundling:
While linking the program:
error: this app is not compatible with architecture 'os.linux.x86_64'


=> Build Error. Check the logs printed above.
```

I am not sure what is causing the problem since mupx should build the app for os.linux.x86_64 automatically according to its documentation. It might be related to this issue [here](https://github.com/arunoda/meteor-up/issues/915).

**Comment by heberallred** [comment]
@ChenLi0830 I had similar issues.  I wish I could deploy directly from my Mac (and I was able to with 1.2.1), but now I can't with 1.3.  The work-around that I have done is to push my code to an Ubuntu computer, and then do "mupx" from there, and it worked.

**Comment by ChenLi0830** [comment]
Hey @heberallred, thanks! I'm going to give that a try.

**Comment by ChenLi0830** [comment]
@heberallred, thanks again for your reply. There is a solution which fixed the problem of deploying using Mac: Reinstall all the npm and meteor packages. 

More specifically, I removed the _node_modules_ and _.meteor/local_ directories, and then re-run npm install, meteor and mupx deploy. (The reason I have _node_modules_ in my project directory is because I've been using npm with Meteor 1.3@beta.12. If you upgraded meteor from 1.2.1, I think all you need to do is to remove **.meteor/local**, and re-deploy.)

This fixed the problem for me and hopefully it can fix the problem for you, too.

**Comment by heberallred** [comment]
@ChenLi0830 I was very hopeful it would work, but when I tried what you mentioned (cleared .meteor/local, node_modules, and then run npm install, meteor, mupx) I still get the same error:

error: this app is not compatible with architecture 'os.linux.x86_64'

I think it may be due to some package that I'm using which is not compatible or something.   I'm using a lot of packages so I'm not sure which one.  I'll keep testing.

**Comment by jakobloekke** [comment]
It's a meteor bug related to npm modules that use binary packages: https://github.com/meteor/meteor/issues/6537

**Comment by ChenLi0830** [comment]
Hey @heberallred, sorry to hear that. As @jakobloekke mentioned, there seems to be a good discussion in issue#6537. Hopefully you can find something useful there. I'm closing this issue for now since it is related to that one.
