### ISSUE TITLE
custom start.sh

### ISSUE THREAD

**Issue by mike623** [arunoda/meteor-up-legacy#936]
In order to add specific env while run the docker container. I modify start.sh on server. But it will be overide by start.sh template every time

**Comment by kayrules** [comment]
alter your local start.sh under `<meteor-up folder>/lib/modules/meteor/assets/start.sh`. and then run `mup setup` & `mup deploy` again.

**Comment by mike623** [comment]
Yes,  I know it is work. I am just think about easier way to depoly like docker-compose
