### ISSUE TITLE
Is meteor up compatible with nginx?

### ISSUE THREAD

**Issue by scottmcpherson** [arunoda/meteor-up-legacy#94]
Hello, 

I 'm trying to set up nginx with a previously deployed site that used meteor up for the deployment/build process. My nginx set up is going to point admin.sitename.com to the meteor app, and sitename.com to a static public facing website. Is it possible to continue using meteor up with this set up, or do I need to set this up manually? I'm kind of lost and any pointers would be greatly appreciated.

**Comment by arunoda** [comment]
Where do your trying to host nginx?
If that's on the same box. Yes you can do.
Simply use different ports for two mup apps.
Then configure nginx for that posts.
Deploy apps separately with two mup apps.

On Thursday, July 17, 2014, Scott McPherson notifications@github.com
wrote:

> Hello,
> 
> I 'm trying to set up nginx with a previously deployed site that used
> meteor up for the deployment/build process. My nginx set up is going to
> point admin.sitename.com to the meteor app, and sitename.com to a static
> public facing website. Is it possible to continue using meteor up with this
> set up, or do I need to set this up manually? I'm kind of lost and any
> pointers would be greatly appreciated.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/94.

## 

---

Arunoda Susiripala
I curate Meteor Weekly - Check it out!
http://meteorhacks.com/meteor-weekly/?utm_source=email-footer&utm_medium=email&utm_campaign=meteorweekly

**Comment by scottmcpherson** [comment]
@arunoda I'm hosting everthing on digital ocean and it's all under the same box (in this case droplet). So even though my static site is not a meteor app, I can still use meteor up to deploy it?

**Comment by arunoda** [comment]
No. You can only use mup for meteor apps.

On Thursday, July 17, 2014, Scott McPherson notifications@github.com
wrote:

> @arunoda https://github.com/arunoda I'm hosting everthing on digital
> ocean and it's all under the same box (in this case droplet). So even
> though my static site is not a meteor app, I can still use meteor up to
> deploy it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/94#issuecomment-49318475.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by scottmcpherson** [comment]
oh ok. But I can still use meteor up for the meteor app, and then just upload the static site via ssh or whatever, even though there both on the same droplet and nginx will be running in front of the meteor app and static site, right?

**Comment by arunoda** [comment]
Yes

On Thursday, July 17, 2014, Scott McPherson notifications@github.com
wrote:

> oh ok. But I can still use meteor up for the meteor app, and then just
> upload the static site via ssh or whatever, even though there both on the
> same droplet and nginx will be running in front of the meteor app and
> static site, right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/meteor-up/issues/94#issuecomment-49319041.

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
