### ISSUE TITLE
mupx - Uploading bundle: FAILED 	No such file

### ISSUE THREAD

**Issue by mrk-i** [arunoda/meteor-up-legacy#970]
$sudo DEBUG=\* mupx deploy

> started TaskList: Deploy app 'application_name' (linux)
> [xx.xx.xx.xx] - Uploading bundle
>   nodemiral:sess:xx.xx.xx.xx copy file - src: /tmp/7a48e3c4-2f8a-4ade-8f6a-3a01bc784869/bundle.tar.gz, dest: /opt/application_name/tmp/bundle.tar.gz, vars: undefined +0ms
> [52.38.202.158] x Uploading bundle: FAILED
>   No such file

Local /tmp directory is writable but  there is no 7a48e3c4-2f8a-4ade-8f6a-3a01bc784869/bundle.tar.gz inside of it? 
On ther remote server: /opt/application_name/tmp/
Doesn't even exist?? Isn't mupx supposed to create that directory?

> /opt/app/tmp/

Is the directory that exists.

**Comment by mrk-i** [comment]
I changed application name after server setup, the new directory was not created.

> $mupx setup

Fixed missing directory on remote server.
Is there any restart/update command once and if you decide to change app name?

**Comment by MasterJames** [comment]
Maybe reconf? 
https://github.com/arunoda/meteor-up/tree/mupx?files=1#other-utility-commands
