### ISSUE TITLE
cp: copyFileSync: could not write to dest file (code=ENOENT):platforms/android/assets/www/cordova.js

### ISSUE THREAD

**Issue by joncursi** [arunoda/meteor-up-legacy#982]
I am receiving the following error when trying to deploy:

```
$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/jcursi/meteor-app
Using buildOptions : {"debug":true,"executable":"meteor"}
cp: copyFileSync: could not write to dest file (code=ENOENT):platforms/android/assets/www/cordova.js

=> Build Error. Check the logs printed above.
```

Is this... some kind of permissions issue (local) or mupx issue?

I am using npm@3.8.7 and node@v5.11.0

**Comment by MasterJames** [comment]
I think you need to use meteor remove-platform ios android before deploying. 
Also the new official meteor update 1.3.2.2 is a better bet for handling cross build deployment issues.
Note: there is a new version at kadirahq/meteor-up that is depreciating mupx but still in flux/development so not as "stable".

**Comment by joncursi** [comment]
Removing ios and android before deploying did the trick, thanks!

The following script _should_ work, so long as your mupx deployment doesn't fail (causing platforms to not re-add themselves):

```
meteor remove-platform ios android && mupx deploy && meteor add-platform ios android
```

**Comment by vikash1993** [comment]
Error during untar for /home/singh/.cordova/lib/npm_cache/cordova-android/6.0.0/package.tgz: Error: EACCES: permission denied, open '/home/singh/.cordova/lib/npm_cache/cordova-android/6.0.0/package/package.json'
Error: Failed to fetch platform android
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: EACCES: permission denied, open '/home/singh/.cordova/lib/npm_cache/cordova-android/6.0.0/package/package.json'
