### ISSUE TITLE
Verifying Deployment Fail from Mac OS to Debian 8 (Jessie)

### ISSUE THREAD

**Issue by Taakn** [arunoda/meteor-up-legacy#988]
Hello,

I'm a bit at a loss here. I cannot deploy to production and I've been struggling for a couple of days already. I had to reinstall my production server. When I believe I fixed an issue, another one pops up. Plus deployment takes forever, so I'm losing 15 minutes every time I try. Everything works fine in DEV.

Here's my latest error if anyone could help me figure it out:

```
-----------------------------------STDERR-----------------------------------
 node_modules/chalk
strip-ansi@0.3.0 node_modules/strip-ansi
has-ansi@0.1.0 node_modules/has-ansi
supports-color@0.2.0 node_modules/supports-color
eachline@2.3.3 node_modules/eachline
type-of@2.0.1 node_modules/type-of
amdefine@1.0.0 node_modules/amdefine
asap@2.0.3 node_modules/asap
underscore@1.5.2 node_modules/underscore
meteor-promise@0.5.1 node_modules/meteor-promise
promise@7.0.4 node_modules/promise
source-map-support@0.3.2 node_modules/source-map-support
semver@4.1.0 node_modules/semver
source-map@0.1.32 node_modules/source-map

fibers@1.0.8 node_modules/fibers
=> Starting meteor app on port:80
WARNING: npm peer requirements (for react-meteor-data) not installed:
 - react@0.14.8 installed, react@15.x needed
 - react-addons-pure-render-mixin@0.14.8 installed, react-addons-pure-render-mixin@15.x needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies
=> Redeploying previous version of the app
-----------------------------------STDOUT-----------------------------------
```

I don't know why it says starting on port 80, when I specified port 8001 in mup.json. I am using nginx. My deployCheckWaitTime is 600. Meteor is 1.3.2.4

If I attempt to run mupx start, I get the following error:

```
-----------------------------------STDERR-----------------------------------
deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80
WARNING: npm peer requirements (for react-meteor-data) not installed:
 - react@0.14.8 installed, react@15.x needed
 - react-addons-pure-render-mixin@0.14.8 installed, react-addons-pure-render-mixin@15.x needed

Read more about installing npm peer dependencies:
 http://guide.meteor.com/using-packages.html#peer-npm-dependencies

-----------------------------------STDOUT-----------------------------------
```

I don't understand the Node error, I have on my production server:
npm -v: 3.8.7
node -v: 5.11.0
which npm: /usr/bin/npm
which node: /usr/bin/node

Thanks so much

**Comment by Taakn** [comment]
Closing the issue, I'm using meteor build instead.

**Comment by MasterJames** [comment]
Glad you found a way. 3 points.
Only Ubuntu 14+ is supported by mupx.
Latest official release of meteor version 1.3.2.2+ fixed all kinds of fiber problems and similar npm module build issues.
Know that the new version of mupx is porting to kadirahq/meteor-up

**Comment by Taakn** [comment]
It's now working in Production. Regardless I had to manually delete several packages, do a couple of npm installs and fix some other stuff. Going to production with Meteor is a little frustrating regardless of the method used haha. Thanks for the 3 points :+1:

**Comment by MasterJames** [comment]
It will get easier, don't forget about Galaxy too.
Then your dollars will go directly towards improvements.
Ya NodeJS 6 integration is in the pipeline. 4 (and fiv?) proven are not released. Then hopefully TLS will make nginx obsolete etc.
