### ISSUE TITLE
Can't stop app

### ISSUE THREAD

**Issue by rolivav** [arunoda/meteor-up-legacy#990]
I have several apps deployed on a server. I can start and stop every app except one. Whenever I try to stop it, it just says "Stopping app: SUCESS" but it doesn't actually stop. I think it might be bugged since the app has been listening for a long time.

How can you stop an app from the server itself?

**Comment by rolivav** [comment]
When I try to deploy the last version to it, I get this error.

```
   -----------------------------------STDERR-----------------------------------
        Failed to remove container (Meteor123): Error response from daemon: No such container: Meteor123
        Failed to remove container (Meteor123-frontend): Error response from daemon: No such container: Meteor123-frontend
        docker: Error response from daemon: failed to create endpoint Meteor123 on network bridge: Bind for 0.0.0.0:3002 failed: port is already allocated.
        -----------------------------------STDOUT-----------------------------------
        base: Pulling from meteorhacks/meteord
        4d690fa98655: Already exists
        a3ed95caeb02: Already exists
        0638f01c6191: Already exists
        086f3bb36259: Already exists
        Digest: sha256:684021facd5847f6a4ee2f0095fd26b4d7f5af2b776150531914d43fd0eb889b
        Status: Image is up to date for meteorhacks/meteord:base
        74e8d4df89fd1604149b1618d7a57930e4551093fc01ac582cac2c4d2523223d
        ----------------------------------------------------------------------------
```

**Comment by rolivav** [comment]
I was able to solve this by restarting the server and calling `mupx stop` again.
Then I was able to deploy it successfully.

**Comment by MasterJames** [comment]
Right, well don't forget and to answer your question...
You can SSH into the target machine and then call "docker exec" with bash or any available command to get into the docker containers and or execute a command.
